src/objects/ABB_Location__c.object
<CustomObject>
    <description>R4V1-This object refers to ABB Location.</description>
    <fields>
        <fullName>BU__c</fullName>
        <description>R4V1-This field refers to BU.</description>
        <label>BU</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <description>R4 Product Group</description>
        <label>Product Group MgmtOrg</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ABB Location</label>
    <nameField>
        <label>ABB Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ABB Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field is to e used to control access to the record, as part of the GIS Team Operations.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
   <fields>
        <fullName>Primary_Account_Manager__c</fullName>
        <description>The primary account manager requires a valid email address!</description>
        <inlineHelpText>This is the e-mail address for the Group or Strategic or Local Major Account Manager. The Group or Strategic Account is set by Group and the Local Major is a local selection.</inlineHelpText>
        <label>Group/Strategic/Local Major Acct Mgr.</label>
        <type>Email</type>
    </fields>

    <recordTypes>
        <fullName>Default</fullName>
        <active>true</active>
        <description>Before creating any new Account, search in SFDC. If the Account exists then use this Account.Initial record type to be selected to properly trigger the clearing and approval process for GIS/Masterdata.</description>
        <label>Default</label>
    </recordTypes>
 <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Capture_Team__c.object
<CustomObject>
    <description>R4V1-This object refers to data.</description>
    <fields>
        <fullName>End_User_Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>End User Project</label>
        <referenceTo>End_User_Project__c</referenceTo>
        <relationshipLabel>Capture Teams</relationshipLabel>
        <relationshipName>Capture_Teams</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Capture Team</label>
    <nameField>
        <label>Capture Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capture Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Capture_Team_Member__c.object
<CustomObject>
    <description>R4V1- This object refers to provide sharing model for Capture Team</description>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R4v1- Capturing user who needs to get share End User Project</description>
        <label>User</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Can not add System Administrator</errorMessage>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>notEqual</operation>
                <value>System Administrator</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Capture_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Core Capture Team Member</label>
    <nameField>
        <displayFormat>CTM-{0000000}</displayFormat>
        <label>Capture Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Core Capture Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Record Type for Active Contact (Default)</description>
        <label>Active</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/End_User_Project__c.object
<CustomObject>
    <description>Only the Project Owner and Account Manager should be able to change the status of the project (Not the opportunity owner)</description>
    <fields>
        <fullName>Account_End_User__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>- Account - End User (should be selected from account)</description>
        <label>Account - End User</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notEqual</operation>
                <value>&quot;ABB ICV&quot;, &quot;External non-buying Account&quot;</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>End User Projects</relationshipLabel>
        <relationshipName>End_User_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Capture_Team_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Capture Team Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_User_Project_Status__c</fullName>
        <description>End User Project Status</description>
        <label>End User Project Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>End User Project</label>
    <nameField>
        <label>End User Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>End User Projects</pluralLabel>
    <recordTypes>
        <fullName>Default</fullName>
        <active>true</active>
        <description>Default Record Type</description>
        <label>Default</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>

 
 

    <fields>
        <fullName>Account_End_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Account</description>
        <inlineHelpText>This Account lookup is used for End User Accounts.</inlineHelpText>
        <label>Account - End User</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities - End User</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BU__c</fullName>
        <description>R4.1 - New picklist field created to replace &quot;Application&quot;.
Picklist containing active Applications relating to specific Product Groups</description>
        <inlineHelpText>ABB classification of application based on the main process activity of the delivered product, service, solution. The selectable options are product group specific</inlineHelpText>
        <label>Application BU</label>
        <picklist>
            <picklistValues>
                <fullName>DMDR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMPC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMRO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PATU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGGA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGGI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGGS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All other BU&apos;s</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
	
    <fields>
        <fullName>Business_Unit__c</fullName>
        <formula>Product_Group__r.Business_Unit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
   
    <fields>
        <fullName>Division__c</fullName>
        <formula>Product_Group__r.Division__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Division</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_User_Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to active End User Projects only</description>
        <inlineHelpText>Please select a End User Project (mandatory for Regular Opportunities, optional for Fast Track Opportunities).
Make sure that you set the Project Site Country first as this will be a filter for the End User Projects.</inlineHelpText>
        <label>End User Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>End_User_Project__c.End_User_Project_Status__c</field>
                <operation>notEqual</operation>
                <value>Closed, Cancelled</value>
            </filterItems>
            <filterItems>
                <field>$Source.Account_End_User__c</field>
                <operation>equals</operation>
                <valueField>End_User_Project__c.Account_End_User__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.End_User_Project_Site_Country__c</field>
                <operation>equals</operation>
                <valueField>End_User_Project__c.End_User_Project_Site_Country__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>End_User_Project__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
<fields>
        <fullName>ABB_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Refers to the Sales, Project Execution or Manufacturing unit (Business Activity Location – BAL) that will lead the project in terms of final bid preparation towards the customer and that will book the order if we are awarded.</inlineHelpText>
        <label>ABB Location – Bidding unit</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND 3 AND 4 AND 5 AND 6</booleanFilter>
            <filterItems>
                <field>ABB_Location__c.Deleted__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>ABB_Location__c.Data_Load_Year__c</field>
                <operation>notEqual</operation>
                <value>2015</value>
            </filterItems>
            <filterItems>
                <field>ABB_Location__c.BU__c</field>
                <operation>notEqual</operation>
                <value>ZCCO, ZCRE, ZCVA</value>
            </filterItems>
            <filterItems>
                <field>ABB_Location__c.DIV__c</field>
                <operation>notEqual</operation>
                <value>ZC</value>
            </filterItems>
            <filterItems>
                <field>ABB_Location__c.Activity__c</field>
                <operation>notEqual</operation>
                <value>Admin/Corporate, Other, R&amp;D, Warehouse or Logistics, Training</value>
            </filterItems>
            <filterItems>
                <field>ABB_Location__c.Activity__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <infoMessage>Please use the filters to reduce the number of fields in the lookup window.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>ABB_Location__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
   <fields>
        <fullName>Product_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to PG / BU / Div, filtered on RecType &quot;Product Group&quot;</description>
        <inlineHelpText>This field will be auto populated by the offering flagged as Primary Product Group. If you haven’t selected an offering yet, please add it. If you don’t know which product/service will be offered, but you know the Product Group, you can enter it directly.</inlineHelpText>
        <label>Product Group</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product_Group__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Product Group</value>
            </filterItems>
            <filterItems>
                <field>Product_Group__c.Data_Load_Year__c</field>
                <operation>notEqual</operation>
                <value>2015</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product_Group__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Specific_Opportunity_Info__c</fullName>
        <description>Text field for additional, specific infos about the opportunity (will be added automatically to Opportunity name in the format of [Country Code]-[Account Name]-[Specific Opportunity Info].</description>
        <inlineHelpText>Text field for additional, specific infos about the opportunity (will be added automatically to Opportunity name in the format of [Country Code]-[Account Name]-[Specific Opportunity Info].</inlineHelpText>
        <label>Opportunity Name (free text)</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to determine whether a target has been set.</description>
        <label>Target</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Technical_Amount_USD__c</fullName>
        <description>This technical field holds the oppy amount in USD. The field is hidden for the end user.</description>
        <label>Opportunity Value USD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ClsTriggerCaptureTeamSharingControl_TEST.cls
/**
*   This test class for 1. ClsTriggerAccountHandler.
*                        2. ClsTriggerEndUserProjectHandler
*                        3. ClsTriggerCaptureTeamMemberHandler
*                        4. AddCaptureTeamMemberClass 
*                        5. NewCaptureTeamController 
*
@author Rajesh Kaliyaperumal
@created 2015-10-9
*
*/
@istest(seealldata=true)
public class ClsTriggerCaptureTeamSharingControl_TEST{
    public static Account createTestAccounts() {
        Account acc = new Account();    
        acc.Name = 'Test1';    
        acc.Primary_Account_Manager__c = 'mtester@company.com';   
        acc.BillingStreet = 'dajie';
        acc.BillingCity = 'berlin';
        acc.BillingState = 'Berlin';
        acc.BillingPostalCode = '20012';
        acc.BillingCountry = 'Germany';
        return acc;
    }
    public static User createTestUser1() {
        User u = new User();
        u.FirstName ='haobo';
        u.LastName = 'song';
        u.Username = 'test123ABB1237@test123ABB1237.com';
        u.Alias = 'mtst1';
        u.Email = 'mtester1@company.com';
        u.CommunityNickname = u.Alias;
        u.ProfileId = [Select Id from Profile Where Name = 'ABB Sales Standard Profile' limit 1].Id;
        u.TimeZoneSidKey = 'America/Chicago';
        u.LocaleSidKey = 'en_US';
        u.EmailEncodingKey = 'UTF-8';
        u.LanguageLocaleKey = 'en_US';
        u.ManagerId = UserInfo.getUserId();
        return u;
    }
    public static User createTestUser2() {
        User u = new User();
        u.FirstName ='haobo';
        u.LastName = 'song';
        u.Username = 'test1234awsedr@test1234.com';
        u.Alias = 'mtst2';
        u.Email = 'mtester2ABB1236@companyABB1236.com';
        u.CommunityNickname = u.Alias;
        u.ProfileId = [Select Id from Profile Where Name = 'ABB Sales Standard Profile' limit 1].Id;
        u.TimeZoneSidKey = 'America/Chicago';
        u.LocaleSidKey = 'en_US';
        u.EmailEncodingKey = 'UTF-8';
        u.LanguageLocaleKey = 'en_US';
        u.ManagerId = UserInfo.getUserId();
        return u;
    }
    public static User createTestUser3() {
        User u = new User();
        u.FirstName ='haobo';
        u.LastName = 'song';
        u.Username = 'test12345ABB1235@test12345ABB1235.com';
        u.Alias = 'mtst3';
        u.Email = 'mtester3@company.com';
        u.CommunityNickname = u.Alias;
        u.ProfileId = [Select Id from Profile Where Name = 'ABB Sales Standard Profile' limit 1].Id;
        u.TimeZoneSidKey = 'America/Chicago';
        u.LocaleSidKey = 'en_US';
        u.EmailEncodingKey = 'UTF-8';
        u.LanguageLocaleKey = 'en_US';
        u.ManagerId = UserInfo.getUserId();
        return u;
    }
    public static User createTestUser4() {
        User u = new User();
        u.FirstName ='haobo';
        u.LastName = 'song';
        u.Username = 'test12345ABB1234@test12345ABB1234.com';
        u.Alias = 'mtst3';
        u.Email = 'mtester3@company.com';
        u.CommunityNickname = u.Alias;
        u.ProfileId = [Select Id from Profile Where Name = 'Standard User' limit 1].Id;
        u.TimeZoneSidKey = 'America/Chicago';
        u.LocaleSidKey = 'en_US';
        u.EmailEncodingKey = 'UTF-8';
        u.LanguageLocaleKey = 'en_US';
        u.ManagerId = UserInfo.getUserId();
        return u;
    }
    public static Contact createTestContacts() {
        Contact contact = new Contact();
        contact.LastName = 'Test';
        contact.MailingStreet = 'dada';
        contact.MailingCity = 'berlin';
        contact.MailingState = 'Berlin';
        contact.MailingPostalCode = '1792';
        contact.MailingCountry = 'Germany'; 
        return contact;
    }
    public static End_User_Project__c createTestEndUserProject() {
        Account acc = createTestAccounts();
        insert acc;
        End_User_Project__c EUP = new End_User_Project__c();
        EUP.Account_End_User__c = acc.id;
        EUP.Name = 'TEST End User Project';
        EUP.End_User_Project_Status__c = 'Open';
        EUP.Capture_Team_Count__c=3;
        
        return EUP;
    }
   
    static testMethod void CaptureTeamsharingControlTEST1(){
        Test.StartTest();
        User u1 = createTestUser1();
        insert u1;
        User u2 = createTestUser2();
        insert u2; 
        User u3 = createTestUser3();
        insert u3;          
        Account acc = new Account();    
        acc.Name = 'TestAccount';    
        acc.Primary_Account_Manager__c = 'mtester@company.com';   
        acc.BillingStreet = 'dajie';
        acc.BillingCity = 'berlin';
        acc.BillingState = 'Berlin';
        acc.BillingPostalCode = '20012';
        acc.BillingCountry = 'Germany';
        insert acc;
        
        /*Account acc1 = new Account();    
        acc1.Name = 'TestAccount1';    
        acc1.Primary_Account_Manager__c = 'mtester1@company.com';   
        acc1.BillingStreet = 'dajie';
        acc1.BillingCity = 'berlin';
        acc1.BillingState = 'Berlin';
        acc1.BillingPostalCode = '20012';
        acc1.BillingCountry = 'Germany';
        acc1.Active__c=True;
        acc1.recordTypeId=[select id,Name from RecordType where SobjectType='Account' and Name='Default' Limit 1].Id;
        insert acc1;*/
        
        End_User_Project__c EUP = new End_User_Project__c();
        EUP.Account_End_User__c = acc.id;
        EUP.Name = 'TEST End User Project';
        EUP.End_User_Project_Status__c = 'Open';
        insert EUP;
        /*End_User_Project__c EUP1 = new End_User_Project__c();
        EUP1.Account_End_User__c = acc.id;
        EUP1.Name = 'TEST End User Project1';
        EUP1.End_User_Project_Status__c = 'Open';
        insert EUP1;
        End_User_Project__c EUP2 = new End_User_Project__c();
        EUP2.Account_End_User__c = acc1.id;
        EUP2.Name = 'TEST End User Project2';
        EUP2.End_User_Project_Status__c = 'Open';
        insert EUP2;*/
        
        ABB_Location__c loc=new ABB_Location__c();
        loc.Name='TLoc';
        loc.BU__c='PGHV - High Voltage Products';
        loc.DIV__c='PA-Process Automation';
        insert loc;       
        
        /*ABB_Location__c loc1=new ABB_Location__c();
        loc1.Name='testLoc';
        loc1.BU__c='PPHV-High Voltage Products';
        loc1.DIV__c='PP-Power Products';
        insert loc1;*/
        
        /*Product_Group__c pg1=new Product_Group__c();
        pg1.Name='testtt';
        pg1.Business_Unit__c='t01';
        pg1.Division__c='D01';
        insert pg1;*/
        
        Product_Group__c pg=new Product_Group__c();
        pg.Name='abbProd';
        pg.Business_Unit__c='t02';
        pg.Division__c='D02';
        insert pg;
        
        /*Opportunity op1=new Opportunity();
        op1.Technical_Amount_USD__c = 5000004;
        op1.Target__c = TRUE;
        op1.Account_End_User__c=acc1.id;
        op1.Accountid=acc1.id;
        op1.Specific_Opportunity_Info__c='testOppInfo';
        op1.Sales_Pursuit_Progress__c='Opportunity Is Captured';
        op1.Customer_Buying_Path__c='Awareness';
        op1.StageName='Prospecting';
        op1.ABB_Location__c=loc1.id;
        op1.CloseDate=date.today();
        op1.Product_Group__c=pg1.id;
        op1.Name='TestOpp';
        op1.Target__c=True;
        op1.Opportunity_Value__c=5000004;
        op1.End_User_Project__c=EUP1.id;       
        insert op1;
        
        Opportunity op2=new Opportunity();
        op2.Technical_Amount_USD__c = 15000004;
        op2.Target__c = TRUE;
        op2.Account_End_User__c=acc1.id;
        op2.Accountid=acc1.id;
        op2.Specific_Opportunity_Info__c='testOppInfo';
        op2.Sales_Pursuit_Progress__c='Opportunity Is Captured';
        op2.Customer_Buying_Path__c='Awareness';
        op2.StageName='Prospecting';
        op2.ABB_Location__c=loc1.id;
        op2.CloseDate=date.today();
        op2.Product_Group__c=pg.id;
        op2.Name='TestOpp1';
        op2.Opportunity_Value__c=15000004;
        op2.End_User_Project__c=EUP1.id;
        op2.Target__c=True;
        insert op2;*/
        
        Opportunity op3=new Opportunity();
        op3.Technical_Amount_USD__c = 15000004;
        op3.Target__c = TRUE;
        op3.Account_End_User__c=acc.id;
        op3.Accountid=acc.id;
        op3.Specific_Opportunity_Info__c='testOppInfo1';
        op3.Sales_Pursuit_Progress__c='Opportunity Is Captured';
        op3.Customer_Buying_Path__c='Awareness';
        op3.StageName='Prospecting';
        op3.ABB_Location__c=loc.id;
        op3.CloseDate=date.today();
        op3.Product_Group__c=pg.id;
        op3.Name='TestOpp21';
        op3.Opportunity_Value__c=15000004;
        op3.End_User_Project__c=EUP.id;
        op3.Target__c=True;
        insert op3;
        
        
        Capture_Team__c CT = new Capture_Team__c();
        CT.End_User_Project__c = EUP.id;        
        insert CT;
        
        Capture_Team__c CT1 = new Capture_Team__c();
        CT1.End_User_Project__c = EUP.id;        
        insert CT1;        
        
        delete CT1;
        
        Capture_Team__c CT2 = new Capture_Team__c();
        CT2.End_User_Project__c = EUP.id;        
        insert CT2;
        Test.StopTest();
        
        Capture_Team_Member__c CTM = new Capture_Team_Member__c();
        CTM.User__c = u1.id;
        CTM.Capture_Team__c = CT.id;
        insert CTM;
        
        Capture_Team_Member__c CTM2 = new Capture_Team_Member__c();
        CTM2.User__c = u2.id;
        CTM2.Capture_Team__c = CT.id;
        insert CTM2;
        
        Capture_Team_Member__c CTM3 = new Capture_Team_Member__c();
        CTM3.User__c = u3.id;
        CTM3.Capture_Team__c = CT.id;
        insert CTM3;
        
        acc.Primary_Account_Manager__c = 'mtester1@company.com';
        update acc;
        acc.Primary_Account_Manager__c = 'mtester2@company.com';
        update acc;
        
        CTM2.User__c = u3.id;
        CTM2.Access_Level__c = 'Read Only';
        update CTM2;
        CTM3.Access_Level__c = 'Read/Write';
        update CTM3;
        Delete CTM;        
       
        Account accn = new Account();    
        accn.Name = 'TestAccount1';    
        accn.Primary_Account_Manager__c = 'mtester1@company.com';   
        accn.BillingStreet = 'dajie';
        accn.BillingCity = 'berlin';
        accn.BillingState = 'Berlin';
        accn.BillingPostalCode = '20012';
        accn.BillingCountry = 'Germany';
        insert accn;
        
        End_User_Project__c EUPn = new End_User_Project__c();
        EUPn.Account_End_User__c = accn.id;
        EUPn.Name = 'TEST End User Project';
        EUPn.End_User_Project_Status__c = 'Open';
        insert EUPn;
        System.Runas(u1){     
            
            NewCaptureTeamController objCTController = new NewCaptureTeamController();
            Apexpages.Currentpage().getParameters().put('id',EUPn.id);
            objCTController.redirect();
          
        }    
        
       
        Capture_Team_Member__c stdCT = new Capture_Team_Member__c();
        ApexPages.StandardController sc = new ApexPages.StandardController(stdCT);
        AddCaptureTeamMemberClass objCT = new AddCaptureTeamMemberClass(sc);
        objCT.capTeamMember1.User__c = u1.id;
        objCT.capTeamMember2.User__c = u1.id;
        objCT.capTeamMember3.User__c = u1.id;
        objCT.capTeamMember4.User__c = u1.id;
        objCT.capTeamMember5.User__c = u1.id;
        objCT.saveRecord();
        objCT.saveMoreRecord();
        objCT.cancel();  
        
    }
    static testMethod void CaptureTeamsharingControlTEST2(){
        Account accn = new Account();    
        accn.Name = 'TestAccount1';    
        accn.Primary_Account_Manager__c = 'mtester1@company.com';   
        accn.BillingStreet = 'dajie';
        accn.BillingCity = 'berlin';
        accn.BillingState = 'Berlin';
        accn.BillingPostalCode = '20012';
        accn.BillingCountry = 'Germany';
        insert accn;
        
        End_User_Project__c EUPn = new End_User_Project__c();
        EUPn.Account_End_User__c = accn.id;
        EUPn.Name = 'TEST End User Project';
        EUPn.End_User_Project_Status__c = 'Open';
        insert EUPn;
        
        User u4 = createTestUser4();
        insert u4;
        System.Runas(u4){  
            Test.StartTest();   
            NewCaptureTeamController objCTController = new NewCaptureTeamController();
            Apexpages.Currentpage().getParameters().put('id',EUPn.id);
            objCTController.redirect();
            Test.StopTest();
        }
    }
    
}