src/objects/Account_Plan__c.object
<CustomObject>
    <description>R5 - Account Plan</description>
    <fields>
        <fullName>Account_Plan_Year__c</fullName>
        <description>R5 - Account Plan Year</description>
        <inlineHelpText>Enter the Account Plan Year</inlineHelpText>
        <label>Account Plan Year</label>
        <picklist>
            <picklistValues>
                <fullName>1991</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1992</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1993</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1994</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1995</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1996</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1997</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1998</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2001</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2002</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2003</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2004</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2005</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2006</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2007</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2008</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2009</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2011</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Budget__c.object
<CustomObject>
    <description>R5 - New Custom Object -Financial Target and Expectation Budgets</description>
    <fields>
        <fullName>Account_Plan__c</fullName>
        <description>R5 - Master Detail Relationship with Account Plan</description>
        <inlineHelpText>Description of the Account Plan  such that other users can understand the scope.</inlineHelpText>
        <label>Account Plan</label>
        <referenceTo>Account_Plan__c</referenceTo>
        <relationshipLabel>Sales Targets and Results</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Account_Plan_Status__c</fullName>
        <formula>TEXT(Account_Plan__r.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Plan Status</label>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>Business_Unit__c</fullName>
        <description>R5 - Business Unit</description>
        <inlineHelpText>Select ABB Business Unit from the picklist</inlineHelpText>
        <label>Business Unit</label>
        <picklist>
            <controllingField>Division__c</controllingField>
            <picklistValues>
                <fullName>DMDR - Drives and Controls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMMG - Motors &amp; Generators</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMPC - Power Conversion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMRO - Robotics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMSU - Sundry DM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPBP - Building Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPBS - Breakers &amp; Switches</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPCP - Control Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPCW - Protection, Connection &amp; Wire Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPLS - LV Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPMV - Medium Voltage Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPSU - Sundry LP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PACT - Control Technologies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAMA - Marine &amp; Ports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAMP - Measurement &amp; Analytics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAOG - Oil, Gas &amp; Chemicals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAPG - Power Generation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAPI - Process Industries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PASU - Sundry PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PATU - Turbocharging</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGGA - Grid Automation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGGI - Grid Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGGS - Grid Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGHV - High Voltage Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGSU - Sundry PGSU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGTR - Transformers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZCCO - Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZCRE - Real Estate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZCVA - Various</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <description>R5 - Division</description>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>DM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PG</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R5 - Lookup Relationship with Product Group</description>
        <inlineHelpText>The enter PG will automatically update both the assigned Division &amp; BU in the above fields for this particular PG</inlineHelpText>
        <label>Product Group</label>
        <referenceTo>Product_Group__c</referenceTo>
        <relationshipLabel>Sales Targets and Results</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R5 Product</description>
        <inlineHelpText>The enter Product Line will automatically update the assigned Division,  BU and PG in the above fields for this particular Product Line</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Sales Targets and Results</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Segment_Level__c</fullName>
        <inlineHelpText>Segmentation Level must always match to the values entered on the fields DIV,BU,Product Group,Product. For Example;Choose &quot;Division&quot; on segmentation level and populate up to DIV drop down list.</inlineHelpText>
        <label>Segment Level</label>
        <picklist>
            <picklistValues>
                <fullName>Division</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Line</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unique_Check__c</fullName>
        <description>R5 Unique Check</description>
        <label>Unique Check</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Sales Targets and Results</label>
    <nameField>
        <displayFormat>SalesTargets-Results{0000}</displayFormat>
        <label>Budget Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Targets and Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product_Lines__c.object
<CustomObject>
    <description>R5 - New Custom Object - Product Lines</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R5 - Lookup to product</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Product_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Focus</label>
    <nameField>
        <displayFormat>PROD-LINE-{0000}</displayFormat>
        <label>Product Lines Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Focus</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ClsTriggerBudget.cls
/**   
* TriggerClass on the Budget object to automatically populate BU and DIV based on PG
*       
* Release R5
*  
* @author  Indhu Selvi Ramalingam (Accenture)
* @created 2015-11-21
* @version 1.0
*
* - Created
*/
public without sharing class ClsTriggerBudget extends ClsTriggerVirtual {
     
     Set<Id> adminUserIdSet = new Set<Id>();
    
    /**
     * constructor
    */
    public ClsTriggerBudget() {
        
        Map<Id, User> adminUserMap = new Map<Id, User> ([ SELECT Id, Name FROM User WHERE Profile.Name =: Label.Sys_Admin_Profile_Name AND IsActive = TRUE LIMIT 50000]);
        adminUserIdSet.addAll(adminUserMap.KeySet());
    } 
        
   /**
* @see IntHelper.beforeTrigger
*/  
    public override void beforeTrigger(ClsWrappers.TriggerContext trgCtx) {        
        assignProductGroupValues(trgCtx);   
        if (trgCtx.IsDelete) {
            deleteValidation(trgCtx);
        }                 
    } 
    
      /**
* @see IntHelper.afterTrigger
*/   
    public override void afterTrigger(ClsWrappers.TriggerContext trgCtx) {        
        concatenateDIV(trgCtx);                
    }
    
        
        /**
    To prevent deletion when the account plan status is closed
    */
     Public void deleteValidation(ClsWrappers.TriggerContext trgCtx){
         
         for (Budget__c con : (List<Budget__c>) trgCtx.oldList) {             
             if (!adminUserIdSet.contains(UserInfo.getUSerId()) && con.Account_Plan_Status__c == Label.Closed ) {
                 con.addError(Label.Cannot_Save_Changes_Account_Plan_R5);
             }
         }        
     }

/**
* Assign the value to BU , DIV, Product Name / Product Group from the selected Product/Product Group
*/      
    @TestVisible 
    private void assignProductGroupValues(ClsWrappers.TriggerContext trgCtx) {    
        String productGroupId = null;
        String businessUnit = null;
        String division = null;
        String productName = null;
        Set<String> setProductId = new Set<String>(); 
        Set<String> setProductGroupId = new Set<String>(); 
        String productGroupValue = null;
        Map<Id, String> mapProductGroup = new Map<Id, String>(); 
        Map <ID, Product2> productMap = new Map<Id, Product2> ();
        Map <ID, Product_Group__c> productGroupMap = new Map<Id, Product_Group__c> ();
        Map <String, Product_Group__c> productGroupNameAndPGMap = new Map<String, Product_Group__c> ();
        Set<String> setProductName = new Set<String>();
        Integer remLimit =  limits.getLimitQueryRows() - limits.getQueryRows(); 
        if (trgCtx.isInsert || trgCtx.isUpdate) {

            for (sobject sObj : trgCtx.newList) {                   
                // Add the Record to the List - budget     && sobjBudget.Product__r.Product_Group__c != NULL 
                Budget__c sobjBudget = (Budget__c) sObj;   
                Budget__c oldBudget  = (trgCtx.isUpdate) ? (Budget__c)trgCtx.oldMap.get(sObj.ID) : NULL; 
                
                if (trgCtx.isUpdate) {
                
                    if (sobjBudget.Business_Unit__c != oldBudget.Business_Unit__c && sobjBudget.Business_Unit__c == NULL) {
                        sobjBudget.Segment_Level__c = 'Division';
                    }
                    
                    if (sobjBudget.Product_Group__c != oldBudget.Product_Group__c && sobjBudget.Product_Group__c == NULL) {
                    
                        sobjBudget.Segment_Level__c = (sobjBudget.Business_Unit__c != NULL) ? 'Business Unit' : 'Division';
                    }
                }
                
                if ((sobjBudget.Product__c != NULL || sobjBudget.Product_Group__c != Null) && (trgCtx.isInsert || ( trgCtx.isUpdate && (sobjBudget.Business_Unit__c != oldBudget.Business_Unit__c|| sobjBudget.Division__c != oldBudget.Division__c ||
                    sobjBudget.Product__c != oldBudget.Product__c || sobjBudget.Product_Group__c != oldBudget.Product_Group__c)))){                                    
                    if (sobjBudget.Product__c != NULL) setProductId.add(sobjBudget.Product__c); 
                    if (sobjBudget.Product_Group__c != NULL) setProductGroupId.add(sobjBudget.Product_Group__c);
                }
            }
            
            if (setProductId.size() > 0) {
                productMap = new Map<Id, Product2> ([SELECT Id, Name,Product_Group__c FROM Product2 WHERE ID IN: setProductId AND Product_Group__c != NULL LIMIT :remLimit]);
                for (Product2 prod: productMap.Values()) {
                    setProductName.add(String.ValueOf(prod.Product_Group__c));
                }
            }
            
            if (setProductGroupId.size() > 0 || setProductName.size() > 0) {
                productGroupMap = new Map<Id, Product_Group__c > ([ SELECT ID, Name, Business_Unit__c, Business_Unit_Name__c,Division__c
                            FROM Product_Group__c WHERE ID IN :setProductGroupId OR Name IN :setProductName LIMIT :remLimit]); 
                for (Product_Group__c prod: productGroupMap.Values()) {
                    productGroupNameAndPGMap.put(prod.Name, prod);
                }
                
            }
            
                       
            for (sobject sObj : trgCtx.newList) {    
                
                Budget__c sobjBudget = (Budget__c) sObj;
               
                if (sobjBudget.Product__c != NULL && productMap.containskey(sobjBudget.Product__c) && 
                            productGroupNameAndPGMap.containsKey(String.valueOf(productMap.get(sobjBudget.Product__c).Product_Group__c))) {
                    
                    Product_Group__c pg = productGroupNameAndPGMap.get(String.valueOf(productMap.get(sobjBudget.Product__c).Product_Group__c));               
                    sobjBudget.Business_Unit__c  = pg.Business_Unit__c;
                    
                    if (pg.Business_Unit_Name__c != '' && pg.Business_Unit_Name__c != NULL) {
                        sobjBudget.Business_Unit__c = (sobjBudget.Business_Unit__c == null) ? '': sobjBudget.Business_Unit__c;
                        sobjBudget.Business_Unit__c += ' - ' + pg.Business_Unit_Name__c;
                    }
                    
                    sobjBudget.Division__c  = pg.Division__c;
                    sobjBudget.Product_Group__c = pg.Id;
                    
                } else if (sobjBudget.Product__c == NULL && sobjBudget.Product_Group__c != NULL && productGroupMap.containskey(sobjBudget.Product_Group__c)) {
                    
                    sobjBudget.Business_Unit__c = productGroupMap.get(sobjBudget.Product_Group__c).Business_Unit__c;
                    if (productGroupMap.get(sobjBudget.Product_Group__c).Business_Unit_Name__c != '' && productGroupMap.get(sobjBudget.Product_Group__c).Business_Unit_Name__c != NULL) {
                        sobjBudget.Business_Unit__c = (sobjBudget.Business_Unit__c == null) ? '': sobjBudget.Business_Unit__c;
                        sobjBudget.Business_Unit__c += ' - ' + productGroupMap.get(sobjBudget.Product_Group__c).Business_Unit_Name__c;
                    }
                    sobjBudget.Division__c = productGroupMap.get(sobjBudget.Product_Group__c).Division__c;
                }else{}
                
                //system.debug('::::sobjBudget::'+sobjBudget);
                
                sobjBudget.Unique_Check__c = (sobjBudget.Division__c != NULL) ? sobjBudget.Division__c: '';
                sobjBudget.Unique_Check__c += (sobjBudget.Business_Unit__c != NULL) ? sobjBudget.Business_Unit__c: '';
                
                if (sobjBudget.Product_Group__c != NULL) {
                    sobjBudget.Unique_Check__c += sobjBudget.Product_Group__c ;
                }
                if (sobjBudget.Product__c != NULL) {
                    sobjBudget.Unique_Check__c += sobjBudget.Product__c;
                }
                sobjBudget.Unique_Check__c += (sobjBudget.Account_Plan__c != NULL) ? sobjBudget.Account_Plan__c: '';
                sobjBudget.Unique_Check__c += (sobjBudget.Account_Plan_Year__c != NULL) ? String.valueOf(sobjBudget.Account_Plan_Year__c): '';
                
                if ( sobjBudget.Segment_Level__c != NULL) sobjBudget.Unique_Check__c += sobjBudget.Segment_Level__c;
                //sobjBudget.Unique_Check__c += (sobjBudget.Start_Date__c != NULL) ? String.valueOf(sobjBudget.Start_Date__c): '';
               // sobjBudget.Unique_Check__c += (sobjBudget.End_Date__c != NULL) ? String.valueOf(sobjBudget.End_Date__c): '';
            }
        }
    }
        /*     
Method : Concatenate all the DIV and Update in Account Plan
@author  Indhu Selvi Ramalingam (Accenture)

*/ 
         @TestVisible 
        private void concatenateDIV(ClsWrappers.TriggerContext trgCtx) { 
            
            Set<String> setAccPlanId = new Set<String>();   
            MAP <ID,Account_Plan__c> mapAccPlanHeader = new Map <ID,Account_Plan__c>();
            List<Budget__c> budgetList = new List<Budget__c>();
            
            if (trgCtx.isInsert || trgCtx.isUpdate ) {           
                for (sobject sObj : trgCtx.newList) {                           
                    // Add the Record to the List   
                    Budget__c compBudget = (Budget__c)sObj;   
                    Budget__c oldBudget  = (trgCtx.isUpdate) ? (Budget__c)trgCtx.oldMap.get(sObj.ID) : NULL; 
                                  
                    if ((trgCtx.isInsert || ( trgCtx.isUpdate && (compBudget.Account_Plan__c != oldBudget.Account_Plan__c || compBudget.Product__c != oldBudget.Product__c ||
                     compBudget.Division__c != oldBudget.Division__c || compBudget.Product_Group__c != oldBudget.Product_Group__c || compBudget.Business_Unit__c != oldBudget.Business_Unit__c)) ) && compBudget.Account_Plan__c != NULL  ){
                        setAccPlanId.add(compBudget.Account_Plan__c);  
                    }
                } 
            }
            
            if (trigger.isDelete) { 
                for (sobject sObj : trgCtx.oldList) {
                    Budget__c compBudget = (Budget__c)sObj;    
                    if (compBudget.Account_Plan__c != NULL ){
                        setAccPlanId.add(compBudget.Account_Plan__c);
                    }
                }
            } 
           
            if (setAccPlanId.size() > 0) {
                
                Integer remLimit =  limits.getLimitQueryRows() - limits.getQueryRows();
                  
                for(Budget__c compProdQual : [Select Id, Product__r.Name, PRoduct_Group__r.NAme, Business_Unit__c, Account_Plan__r.DIV__c, Product__c, Account_Plan__c, Division__c 
                        FROM Budget__c WHERE Account_Plan__c IN : setAccPlanId AND (Division__c != null OR Business_Unit__c != NULL) LIMIT :remLimit ]) {
                                             
                         
                    if(!mapAccPlanHeader.containsKey(compProdQual.Account_Plan__c)) {
                        
                        Account_Plan__c acp = compProdQual.Account_Plan__r;
                        acp.DIV__c = (compProdQual.Division__c != NULL && compProdQual.Division__c != '') ? compProdQual.Division__c : '';
                        acp.PG__c = '';
                        acp.Product_Lines__c = '';
                        acp.BU__c = '';
                        
                        if (compProdQual.Business_Unit__c != NULL && compProdQual.Business_Unit__c != '') {
                            
                            acp.BU__c = compProdQual.Business_Unit__c;
                            if (compProdQual.Business_Unit__c.contains(Label.CL0003) ){
                                List<String> listBUShortName = compProdQual.Business_Unit__c.Split(Label.CL0003); //Label.CL0003 => -
                                acp.BU__c = listBUShortName[0].trim(); 
                            }
                        }
                        
                      
                        if (compProdQual.Product_Group__c != NULL) {
                            acp.PG__c = compProdQual.Product_Group__r.Name;
                        }
                        
                        if (compProdQual.Product__c != NULL) {
                            acp.Product_Lines__c= compProdQual.Product__r.Name;
                        }
                       
                        
                        mapAccPlanHeader.put(compProdQual.Account_Plan__c, acp);
                    } else {
                        
                        Account_Plan__c acp = mapAccPlanHeader.get(compProdQual.Account_Plan__c);
                        if (compProdQual.Division__c != NULL && compProdQual.Division__c != '') {
                            
                            String mapDivValues = (acp.DIV__c != NULL) ? acp.DIV__c : '';
                            
                            if(mapDivValues.contains(Label.System_CL00046)){
                                List<String> SplittedDivValues= mapDivValues.split(Label.System_CL00046); //Label.System_CL00046=>;
                                Set<String> setDivValues = new Set<String>();
                                
                                setDivValues.addAll(SplittedDivValues);
                                
                                if(!setDivValues.Contains(compProdQual.Division__c)){
                                    
                                     mapAccPlanHeader.get(compProdQual.Account_Plan__c).DIV__c += Label.System_CL00046 + compProdQual.Division__c;  
                                }
                            }else {
                                
                                if(!mapDivValues.contains(compProdQual.Division__c)){
                                
                                    if (acp.DIV__c != NULL && acp.DIV__c != '') {
                                        mapAccPlanHeader.get(compProdQual.Account_Plan__c).DIV__c += Label.System_CL00046;
                                    }
                                    mapAccPlanHeader.get(compProdQual.Account_Plan__c).DIV__c += compProdQual.Division__c;
                                }
                            }      
                        }
                        
                        if (compProdQual.Product_Group__c != NULL) {
                            
                            String mapDivValues = (acp.PG__c != NULL && acp.PG__c != '') ? acp.PG__c : '';
                            
                            if (mapDivValues == '') {
                                 mapAccPlanHeader.get(compProdQual.Account_Plan__c).PG__c = compProdQual.Product_Group__r.NAme;
                            } else {
                            
                                if(mapDivValues.contains(Label.System_CL00046)){
                                    List<String> splittedDivValues= mapDivValues.split(Label.System_CL00046); //Label.System_CL00046 => ;
                                    Set<String> setDivValues = new Set<String>();
                                    
                                    setDivValues.addAll(splittedDivValues);
                                    
                                    if(!setDivValues.Contains(compProdQual.Product_Group__r.NAme)){
                                         mapAccPlanHeader.get(compProdQual.Account_Plan__c).PG__c += Label.System_CL00046 + compProdQual.Product_Group__r.NAme;  
                                    }
                                }else{
                                    if(!mapDivValues.contains(compProdQual.Product_Group__r.NAme)){
                                        mapAccPlanHeader.get(compProdQual.Account_Plan__c).PG__c += Label.System_CL00046 + compProdQual.Product_Group__r.NAme;
                                    }
                                } 
                            }     
                        }
                            
                        if (compProdQual.Product__c != NULL) {
                        
                            String mapDivValues = (acp.Product_Lines__c != NULL && acp.Product_Lines__c != '') ? acp.Product_Lines__c: '';
                            if (mapDivValues == '') {
                                 mapAccPlanHeader.get(compProdQual.Account_Plan__c).Product_Lines__c = compProdQual.Product__r.NAme;
                            } else {
                                if(mapDivValues.contains(Label.System_CL00046)){
                                    List<String> splittedDivValues= mapDivValues.split(Label.System_CL00046);
                                    Set<String> setDivValues = new Set<String>();
                                    
                                    setDivValues.addAll(splittedDivValues);
                                    
                                    if(!setDivValues.Contains(compProdQual.Product__r.NAme)){
                                         mapAccPlanHeader.get(compProdQual.Account_Plan__c).Product_Lines__c += Label.System_CL00046 + compProdQual.Product__r.NAme;  
                                    }
                                }else{
                                    if(!mapDivValues.contains(compProdQual.Product__r.NAme)){
                                        mapAccPlanHeader.get(compProdQual.Account_Plan__c).Product_Lines__c += Label.System_CL00046 + compProdQual.Product__r.NAme;
                                    }
                                }
                            }     
                        }
                        
                        if (compProdQual.Business_Unit__c != NULL && compProdQual.Business_Unit__c != '') {
                            
                            String mapBUValues = (acp.BU__c != NULL) ? acp.BU__c : '';
                            
                            String bu = compProdQual.Business_Unit__c;
                            
                            if (compProdQual.Business_Unit__c.contains(Label.CL0003)) {
                                bu = compProdQual.Business_Unit__c.Split(Label.CL0003).get(0).trim(); //Label.CL0003 => -
                            }
                            
                            if(mapBUValues.contains(Label.System_CL00046)){
                                List<String> splittedBUValues= mapBUValues.split(Label.System_CL00046); //Label.System_CL00046 => ;
                                Set<String> setBUValues = new Set<String>();
                                
                                setBUValues.addAll(splittedBUValues);
                                
                                if(!setBUValues.Contains(bu)){
                                     mapAccPlanHeader.get(compProdQual.Account_Plan__c).BU__c += Label.System_CL00046 + bu;  
                                }
                            }else{
                            
                                if(!mapBUValues.contains(bu)){
                                    if (acp.BU__c != NULL && acp.BU__c != '') {
                                        mapAccPlanHeader.get(compProdQual.Account_Plan__c).BU__c += Label.System_CL00046;
                                    }
                                    mapAccPlanHeader.get(compProdQual.Account_Plan__c).BU__c += bu;
                                }
                            }      
                        }
                    }
                }
                        
                for (Id accPlanId : setAccPlanId) {
                    
                    if (!mapAccPlanHeader.containsKey(accPlanId)) {
                        mapAccPlanHeader.put(accPlanId, new Account_Plan__c ( Id = AccPlanId, BU__c = '', DIV__c = '', PG__c = '', Product_Lines__c = ''));
                    }
                }
                
                try {
                    
                   
                    if (mapAccPlanHeader.size() > 0) Database.Update(mapAccPlanHeader.values());    
                }  Catch (DMLException e) {   
                    
                    List<Sobject> objList = (trgCtx.isdelete) ? trgCtx.oldList : trgCtx.newList;
            
                    String error = '';
                    
                    for (Integer i=0; i < e.getNumDML(); i++) {
                        error += e.getDmlMessage(i) + Label.Line_Break;
                        //system.debug(':::'+e.getDmlFieldNames(i));
                    }
                    for (Sobject obj: objList) {                
                        Budget__c qtm = (Budget__c ) obj;
                        qtm.addError(error, false);            
                    }            
                }
            }         
       }        
               
}