src/objects/Account.object
<CustomObject>

    <recordTypes>
        <fullName>Default</fullName>
        <active>true</active>
        <description>Before creating any new Account, search in SFDC. If the Account exists then use this Account.Initial record type to be selected to properly trigger the clearing and approval process for GIS/Masterdata.</description>
        <label>Default</label>
    </recordTypes>
 <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/APTS_Common_Config_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>General single value custom setting used to store configurable constants in Apex Code</description>
    <fields>
        <fullName>APTS_Description__c</fullName>
        <label>Usage Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>APTS Common Config Settings</label>
</CustomObject>

src/objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>

 
 

    <fields>
        <fullName>Account_End_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Account</description>
        <inlineHelpText>This Account lookup is used for End User Accounts.</inlineHelpText>
        <label>Account - End User</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities - End User</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
	
   
    <fields>
        <fullName>Customer_Buying_Path__c</fullName>
        <description>Stages of the Customer Buying Path according definition</description>
        <inlineHelpText>Please select the Customer Buying Path.
Note: ABB Sales Process (Stage) should not be ahead of the Customer Buying Path</inlineHelpText>
        <label>Customer Buying Path</label>
        <picklist>
            <picklistValues>
                <fullName>Awareness</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Explore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tendering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buying</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sales_Pursuit_Progress__c</fullName>
        <description>Dependent picklist for Sales Pursuit Progress</description>
        <inlineHelpText>Please choose the Stage detail from picklist</inlineHelpText>
        <label>Sales Pursuit Progress</label>
        <picklist>
            <controllingField>StageName</controllingField>
            <picklistValues>
                <fullName>Opportunity Is Captured</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity Pursuit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold (Pursuit)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Budget Proposal Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFQ Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bidding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Preference To Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold (Bidding)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solution Presented To Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Budget Proposal Submitted (Bidding)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bid Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Is Neutral To Supplier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Preference To ABB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold (Negotiation)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LOI To Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Buying Preference To Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Position Is Neutral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clear Buying Signal To ABB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ABB Preferred &amp; Shows Clear Signals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LOI To ABB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSED Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSED Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSED Lost Without ABB Bid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSED Won</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Specific_Opportunity_Info__c</fullName>
        <description>Text field for additional, specific infos about the opportunity (will be added automatically to Opportunity name in the format of [Country Code]-[Account Name]-[Specific Opportunity Info].</description>
        <inlineHelpText>Text field for additional, specific infos about the opportunity (will be added automatically to Opportunity name in the format of [Country Code]-[Account Name]-[Specific Opportunity Info].</inlineHelpText>
        <label>Opportunity Name (free text)</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Quote_Team_Member__c.object
<CustomObject>
    <description>R5 - Object Created to add Quote team to Quotes as per Req#2503</description>
    <fields>
        <fullName>Access_Level__c</fullName>
        <description>R5 - Quote team member access level</description>
        <label>Access Level</label>
        <picklist>
            <picklistValues>
                <fullName>Read Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read/Write</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Quotation__c</fullName>
        <label>Quotation</label>
        <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
        <relationshipLabel>Quote Team Members</relationshipLabel>
        <relationshipName>Quote_Team_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team_Role__c</fullName>
        <description>R5 - Team Role of the Quote team member</description>
        <label>Member Role</label>
        <picklist>
            <picklistValues>
                <fullName>Account Engineer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Channel Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Service Responsible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive Sponsor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Qualifier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Sales Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GAM/SAM Account Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quote Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quote Support</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R5 - Look up to User</description>
        <label>Team Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quote_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote Team Member</label>
    <nameField>
        <displayFormat>QTM-{000000}</displayFormat>
        <label>Quote Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
<fields>
        <fullName>Default_BU__c</fullName>
        <description>R4 - Default BU</description>
        <label>Default LBU</label>
        <length>100</length>
        <type>Text</type>
    </fields>
<fields>
        <fullName>Default_LSO__c</fullName>
        <description>R4 - Default LSO</description>
        <label>Default LSO</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division_DIV__c</fullName>
        <description>The field Division is added to increase the ability to identify the area the user is related to / working in.</description>
        <label>Division (DIV)</label>
        <picklist>
            <picklistValues>
                <fullName>DM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PG</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/ClsTriggerQuoteTeamMemberHandler_Test.cls
/**
*  This test class used to test the method 
*  syncQTMWithOTM
*  in class ClsTriggerQuoteTeamMemberHandler
*
@author Shankaranarayanan V
@created 2015-10-06
@version 1.0

Code Coverage: 80%
**/

@isTest
public class ClsTriggerQuoteTeamMemberHandler_Test{

static testMethod void methodTest(){

//RecordType cqpRecordType = [SELECT Id, DeveloperName, SobjectType FROM RecordType WHERE SobjectType = 'Apttus_Proposal__Proposal__c' and DeveloperName = 'CQP']; 
RecordType defaultID = [SELECT Id, DeveloperName, SobjectType FROM RecordType WHERE SobjectType = 'Account' and DeveloperName = 'Default'];

Profile up = [Select Id, Name from Profile where profile.name = 'ABB Sales Standard Profile' Limit 1];
User u = new User();
u.firstname = '2503';
u.lastname = 'TestUser';
u.Username ='test2503@xyzdqg.com';
u.Alias = 'tester';
u.CommunityNickname = 'tester1';
u.TimeZoneSidKey ='Europe/London';
u.LocaleSidKey ='en_US';
u.EmailEncodingKey ='ISO-8859-1';
u.LanguageLocaleKey ='en_US';
u.email = 'abc@wxyz.com';
u.profileid = up.id;
u.isActive = true;
u.Division_DIV__c = 'DM';
u.Default_BU__c = 'LBUac1';
u.Default_LSO__c ='LSOac1';
insert u;

User u1 = new User();
u1.firstname = '25032';
u1.lastname = 'TestUser2';
u1.Username ='test25032@xyzdqg.com';
u1.Alias = 'tester2';
u1.CommunityNickname = 'tester';
u1.TimeZoneSidKey ='Europe/London';
u1.LocaleSidKey ='en_US';
u1.EmailEncodingKey ='ISO-8859-1';
u1.LanguageLocaleKey ='en_US';
u1.email = 'abc@vwxyz.com';
u1.profileid = up.id;
u1.isActive = true;
u1.Division_DIV__c = 'DM';
u1.Default_BU__c = 'LBUac1';
u1.Default_LSO__c ='LSOac1';
insert u1;

Account ac = new Account();
ac.Name = '2503Account1';
ac.BillingCountry = 'India';
ac.BillingStreet = 'TestStreet';
ac.BillingCity = 'TestCity';
ac.RecordtypeId = defaultID.id;   
insert ac;

Account ac1 = new Account();
ac1.Name = '2503Account2';
ac1.BillingCountry = 'Australia';
ac1.BillingStreet = 'TestStrt';
ac1.BillingCity = 'TestCy';
ac1.RecordtypeId = defaultID.id;   
insert ac1;


    APTS_Common_Config_Settings__c ap=new APTS_Common_Config_Settings__c();
    ap.Name='Global_Record_Type';
    ap.APTS_Value__c='Test';
    ap.APTS_Description__c='testdescr';
    insert ap;
    
    APTS_Common_Config_Settings__c ap1=new APTS_Common_Config_Settings__c();
    ap1.Name='LP_USER_DIVISION';
    ap1.APTS_Value__c='Test';
    ap1.APTS_Description__c='testdescr';
    insert ap1;
    
    APTS_Common_Config_Settings__c ap2=new APTS_Common_Config_Settings__c();
    ap2.Name='DEFAULT_SAP_DIVISION';
    ap2.APTS_Value__c='Test';
    ap2.APTS_Description__c='testdescr';
    insert ap2;
    
    APTS_Common_Config_Settings__c ap3=new APTS_Common_Config_Settings__c();
    ap3.Name='SPAIN_LOCALE';
    ap3.APTS_Value__c='Test';
    ap3.APTS_Description__c='testdescr';
    insert ap3;
    
    APTS_Common_Config_Settings__c ap4=new APTS_Common_Config_Settings__c();
    ap4.Name='DIVISION';
    ap4.APTS_Value__c='Test';
    ap4.APTS_Description__c='testdescr';
    insert ap4;
    
    APTS_Common_Config_Settings__c ap5=new APTS_Common_Config_Settings__c();
    ap5.Name='APPROVAL_COUNTRY';
    ap5.APTS_Value__c='Test';
    ap5.APTS_Description__c='testdescr';
    insert ap5;

Opportunity o1 = new Opportunity();
o1.ownerid = u.id;
o1.accountId = ac.id;
o1.Account_End_User__c = ac1.id; 
o1.Customer_Buying_Path__c = 'Awareness';
o1.name = '2503 Oppty1';
o1.Specific_Opportunity_Info__c = '2503TestAuto';
o1.StageName = 'Prospecting';
o1.Sales_Pursuit_Progress__c = 'Opportunity Is Captured';
o1.CloseDate = date.Today();
insert o1;

String oppId = o1.id;

System.runAs(u) {
Test.startTest();
Apttus_Proposal__Proposal__c apQuote= new Apttus_Proposal__Proposal__c();
apQuote.Apttus_Proposal__Proposal_Name__c = 'Test Quote';
apQuote.Apttus_Proposal__Opportunity__c = o1.id;
insert apQuote;

Quote_Team_Member__c qm = new Quote_Team_Member__c();
qm.Access_Level__c = 'Read/Write';
qm.Team_Role__c = 'Account Engineer';
qm.Quotation__c = apQuote.id;
qm.User__c = u1.id;
insert qm;

List<OpportunityTeamMember> oppTeamList = [SELECT Id, OpportunityId, OpportunityAccessLevel, TeamMemberRole, UserId FROM OpportunityTeamMember WHERE OpportunityId =: oppId];
                                            
    System.assertEquals(qm.User__c,oppTeamList[0].UserId);
    System.assertEquals(qm.Team_Role__c,oppTeamList[0].TeamMemberRole);

delete qm;

Test.stopTest();
List<OpportunityTeamMember> oppTeamDelList = [SELECT Id, OpportunityId, OpportunityAccessLevel, TeamMemberRole, UserId FROM OpportunityTeamMember WHERE OpportunityId =: oppId];
    
    System.assertEquals(oppTeamDelList.size(), 1);
}
}
}