src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ABACUS_code__c</fullName>
        <label>ABACUS code</label>
        <length>30</length>
        <type>Text</type>
    </fields>

 <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Email_Opt_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Updated for User Story R-2314 in ABB DOC:
https://abb--doc.cs18.my.salesforce.com/a0E1100000HuT09</description>
        <inlineHelpText>Do not send e-mail to this contact.</inlineHelpText>
        <label>Email Opt Out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Preferred_Contact_Method__c</fullName>
        <label>Preferred Contact Method</label>
        <picklist>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fax</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Do Not Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/LBU_Code__c.object
<CustomObject>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>

 
 

    <fields>
        <fullName>Actual_Bid_Submission_Date_Comm__c</fullName>
        <description>Contains the date when the Commercial bid was submitted.</description>
        <label>Actual Bid Submission Date (Comm.)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <description>R4.1 - New dependent picklist field created for &quot;BU&quot;.
Picklist containing active Applications relating to specific Product Groups</description>
        <inlineHelpText>ABB classification of application based on the main process activity of the delivered product, service, solution. The selectable options are product group specific</inlineHelpText>
        <label>Application</label>
        <picklist>
            <controllingField>BU__c</controllingField>
            <picklistValues>
                <fullName>AP.301</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.302</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.303</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.304</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.305</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.306</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.307</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.308</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.309</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.310</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.311</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.313</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.314</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.315</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.316</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.317</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.318</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.319</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.320</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.321</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.322</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.323</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.324</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.325</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.326</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.327</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.328</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.329</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.330</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.331</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BU__c</fullName>
        <description>R4.1 - New picklist field created to replace &quot;Application&quot;.
Picklist containing active Applications relating to specific Product Groups</description>
        <inlineHelpText>ABB classification of application based on the main process activity of the delivered product, service, solution. The selectable options are product group specific</inlineHelpText>
        <label>Application BU</label>
        <picklist>
            <picklistValues>
                <fullName>DMDR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMPC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMRO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PATU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGGA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGGI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGGS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All other BU&apos;s</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
	
    <fields>
        <fullName>Business_Unit__c</fullName>
        <formula>Product_Group__r.Business_Unit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
   
    <fields>
        <fullName>Division__c</fullName>
        <formula>Product_Group__r.Division__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Division</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Local_Business_Unit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Local Business Unit is the ABB management organisation responsible to market product, specific system or service mix either on division, BU or product group level. It is the local organisational unit, representing the BU&apos;s activities in a country.</inlineHelpText>
        <label>Leading LBU</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>LBU_Code__c.Data_Load_Year__c</field>
                <operation>notEqual</operation>
                <value>2015</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>LBU_Code__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Local_Product_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Product Group object</description>
        <label>Leading LPG</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product_Group__c.Data_Load_Year__c</field>
                <operation>notEqual</operation>
                <value>2015</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Product_Group__c</referenceTo>
        <relationshipLabel>Opportunities (Local Product Group)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Value__c</fullName>
        <description>Holds the overall Opportunity Value of an opportunity</description>
        <label>Opportunity Value</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
   <fields>
        <fullName>Product_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to PG / BU / Div, filtered on RecType &quot;Product Group&quot;</description>
        <inlineHelpText>This field will be auto populated by the offering flagged as Primary Product Group. If you haven’t selected an offering yet, please add it. If you don’t know which product/service will be offered, but you know the Product Group, you can enter it directly.</inlineHelpText>
        <label>Product Group</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product_Group__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Product Group</value>
            </filterItems>
            <filterItems>
                <field>Product_Group__c.Data_Load_Year__c</field>
                <operation>notEqual</operation>
                <value>2015</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product_Group__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requested_Bid_Submission_Date_Comm__c</fullName>
        <description>Requested date when a commercial bid should be submitted by.</description>
        <label>Requested Bid Submission Date (Comm.)</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Product_Group__c</fullName>
        <description>R3v1- Captures Product Group</description>
        <label>Product Group</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Product_Group__c.object
<CustomObject>
</CustomObject>

src/classes/PISOpportunityProductsExtension_Test.cls
@isTest(seeAllData=true) 
private class PISOpportunityProductsExtension_Test {

    static testMethod void myUnitTest() {
            Account acc = ClsTestHelp.createTestAccounts();
            acc.Name = 'sdjnbosetssss';
            insert acc;
            
            Contact con = ClsTestHelp.createTestContacts();
            con.LastName = 'tesddsssdd';
            con.AccountId = acc.Id;
            con.Email_Opt_Out__c = false;
            con.Preferred_Contact_Method__c = 'Email';
            insert con;
            
            Test.startTest();
            Product_Group__c pg = new Product_Group__c();
            pg.Business_Unit__c = 'tdsd';
            pg.Name = 'jinboetdspro';
            pg.Division__c = '10';
            insert pg;
            
            LBU_Code__c lc = new LBU_Code__c();
            lc.Abacus_Code__c = 'sd32';
            lc.BU__c = 'sswe';
            lc.Division__c = 'ssa';
            insert lc;
            
            Pricebook2 pb2 = new Pricebook2();
            pb2.Name = 'jinbotestd';
            pb2.CurrencyIsoCode = 'USD';
            insert pb2;
            
            Pricebook2 pb1 = new Pricebook2();
            pb1.Name = 'jinbotesddstd';
            pb1.CurrencyIsoCode = 'USD';
            insert pb1;
            
            Opportunity oppy = new Opportunity();
            oppy.AccountId = acc.Id;
            oppy.Primary_Contact__c = con.Id; 
            oppy.Name = 'Testpyssss';
            oppy.StageName = 'Negotiation';
            oppy.CloseDate = system.today();
            oppy.Actual_Bid_Submission_Date_Comm__c = system.today();
            oppy.Product_Group__c = pg.Id;
            oppy.Requested_Bid_Submission_Date_Comm__c = system.today();
            oppy.Application__c = 'AP.302 Cable Car - Ski Lift';
            oppy.Local_Business_Unit__c = lc.Id;
            oppy.Local_Product_Group__c = pg.Id;
            oppy.CurrencyIsoCode = 'USD';
            oppy.Opportunity_Value__c = 18646;
            insert oppy;
            
            Opportunity oppy1 = new Opportunity();
            oppy1.AccountId = acc.Id;
            oppy1.Primary_Contact__c = con.Id; 
            oppy1.Name = 'Tesyssss';
            oppy1.StageName = 'Negotiation';
            oppy1.CloseDate = system.today();
            oppy1.Actual_Bid_Submission_Date_Comm__c = system.today();
            oppy1.Product_Group__c = pg.Id;
            oppy1.Requested_Bid_Submission_Date_Comm__c = system.today();
            oppy1.Application__c = 'AP.302 Cable Car - Ski Lift';
            oppy1.Local_Business_Unit__c = lc.Id;
            oppy1.Local_Product_Group__c = pg.Id;
            oppy1.CurrencyIsoCode = 'USD';
            oppy1.Opportunity_Value__c = 18646;
            
            insert oppy1;
            
            Product2 p = new Product2();
            p.Name = 'jisksj';
            p.CID__c='876743h';
            p.isActive = true;
            insert p;
            p.CID__c='87673h';
            update p;
                       
            PricebookEntry pbe = new PricebookEntry();
            pbe.Pricebook2Id = Test.getStandardPricebookId();
            pbe.UnitPrice = 20;
            pbe.Product2Id = p.Id;
            pbe.IsActive = true;
            pbe.CurrencyIsoCode = 'USD';
            insert pbe;
            system.debug('**@@pbe' + pbe.CurrencyIsoCode);
            
            OpportunityLineitem oli = new OpportunityLineitem();
            oli.OpportunityId = oppy.Id;
            oli.PricebookEntryId = pbe.Id;
            oli.Quantity = 2.03;
            oli.TotalPrice = 221.1;
            insert oli;
            Test.stopTest();
            system.debug('**@@oli' + oli.CurrencyIsoCode);
            
            list<PISOpportunityProductsExtension.PISNode> products = new list<PISOpportunityProductsExtension.PISNode>();
            
            /*PISOpportunityProductsExtension.PISNode pisNode = new PISOpportunityProductsExtension.PISNode();
            pisNode.cid = 'tess';
            pisNode.englishDescription = 'testsddas';
            pisNode.languageSpecificDescription = 'tesssssss';
            products.add(pisNode);*/           
            ApexPages.StandardController ExtController = new ApexPages.StandardController(oli); 
            
            PISOpportunityProductsExtension cls = new PISOpportunityProductsExtension(ExtController);
            //PISOpportunityProductsExtension.ProductResult pr = PISOpportunityProductsExtension.replaceProduct(oli.Id, pisNode);
            //pisNode.cid = '87673h';
            //pr = PISOpportunityProductsExtension.replaceProduct(oli.Id, pisNode);
            PISOpportunityProductsExtension.ProductResult pr1 = PISOpportunityProductsExtension.addProducts(oppy1.Id, products);
            pr1 = PISOpportunityProductsExtension.addProducts(oppy.Id, products);
            //pisNode.cid = p.CID__c;
            //products.add(pisNode);
            PISOpportunityProductsExtension.ProductResult pr2 = PISOpportunityProductsExtension.addProducts(oppy.Id, products);
            
            
    }
}