src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>GUID__c</fullName>
        <externalId>true</externalId>
        <label>GUID</label>
        <length>9</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>

 <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/APTS_LP_Local_Customer_Reference_Data__c.object
<CustomObject>
    <description>Object to hold the reference data related to customer (account). (ABB-LP)</description>
    <fields>
        <fullName>APTS_Country__c</fullName>
        <description>Field to capture country for the LSO data.</description>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>ES</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>APTS_External_ID__c</fullName>
        <description>External Id to match the unique set. Value of this field will be SAP ID + Sales organisation + Distribution Channel.</description>
        <externalId>true</externalId>
        <label>APTS External ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_LP_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Local Operational Data</relationshipLabel>
        <relationshipName>Local_Customer_Reference_Data</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>APTS_LP_Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <picklist>
            <picklistValues>
                <fullName>BT</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>DT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>APTS_LP_Incoterms__c</fullName>
        <label>Incoterms</label>
        <picklist>
            <picklistValues>
                <fullName>CFR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DDP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DAF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DDU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DEQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FOB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZFE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EXW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZVR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>APTS_LP_Local_Channel__c</fullName>
        <label>Local Channel</label>
        <picklist>
            <picklistValues>
                <fullName>P1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P6</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>APTS_LP_SAP_Customer_ID__c</fullName>
        <description>Placeholder field to hold the value of customer ID fetched from SAP.</description>
        <label>SAP Customer ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_LP_Sales_Organisation__c</fullName>
        <label>Sales Organisation</label>
        <picklist>
            <picklistValues>
                <fullName>ABB</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>APTS_Payment_Terms__c</fullName>
        <description>Field to capture payment terms associated with Apttus LSO object record.</description>
        <label>Payment Terms</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Local Operational Data</label>
    <nameField>
        <displayFormat>LCRD-{00000}</displayFormat>
        <label>Local Operational Data Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Local Operational Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ERP_Reference_Data__c.object
<CustomObject>
    <description>R3v1 - This custom object holds LSO Reference Data for Accounts.</description>
    <fields>
        <fullName>Account_GUID__c</fullName>
        <description>R3 - Account GUID</description>
        <label>Account GUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R3v1 - Custom Lookup field to Account object to display the account reference in LSO Reference Data.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>LSO_Reference_Datas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LBU__c</fullName>
        <description>R3 -LBU</description>
        <label>LBU</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LSO__c</fullName>
        <description>R3 - LSO</description>
        <label>LSO</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Local_Customer_ID__c</fullName>
        <description>R3 - Local Customer ID</description>
        <inlineHelpText>Customer unique code identifier on the country local ERP.</inlineHelpText>
        <label>Local Customer ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Distribution_Channel__c</fullName>
        <description>R3 - Distribution Channel</description>
        <label>SAP Distribution Channel</label>
        <picklist>
            <controllingField>SAP_Sales_Organization__c</controllingField>
            <picklistValues>
                <fullName>01</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>K</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SAP_Sales_Organization__c</fullName>
        <description>R3v1 - Sales Organization values</description>
        <label>SAP Sales Organization</label>
        <picklist>
            <controllingField>Country__c</controllingField>
            <picklistValues>
                <fullName>0001</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ABB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ABB1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ABBP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YY01</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Local Reference Data</label>
    <nameField>
        <displayFormat>ERP-REF-DATA-{0000}</displayFormat>
        <label>LSO Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Local Reference Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
<fields>
        <fullName>Default_BU__c</fullName>
        <description>R4 - Default BU</description>
        <label>Default LBU</label>
        <length>100</length>
        <type>Text</type>
    </fields>
<fields>
        <fullName>Default_LSO__c</fullName>
        <description>R4 - Default LSO</description>
        <label>Default LSO</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/APTS_LRDLODUtilityTest.cls
@isTest
public class APTS_LRDLODUtilityTest {

    private static User user = null;
    public static testMethod void testGetLODForQuotationFromAccount(){
        
        user  = APTS_LP_TestUtility.getUser();
        System.runAs(user) { 
       		APTS_LP_TestUtility.getCommonConfigSetting();
            APTS_CaptureInputForLSODataController lsoController = new APTS_CaptureInputForLSODataController();
            Account acct = APTS_LP_TestUtility.getNewAccount('Test', 'Spain');
            test.startTest();
            insert acct;
            
            getERPReferenceData(acct);
            getLODReferenceData(acct);
            APTS_LRDLODUtility.findMatchingLODRecords(acct.id,lsoController,'Spain');
            
            test.stopTest();
        }
    }
    /*
    public static testMethod void testGetLODForAgreementFromAccount(){
        
         user  = APTS_LP_TestUtility.getUser();
         System.runAs(user) {         
             APTS_CaptureInputForLSODataController lsoController = new APTS_CaptureInputForLSODataController();
             Account acct = APTS_LP_TestUtility.getNewAccount('Test', 'Spain');
             test.startTest();
             insert acct;
             getERPReferenceData(acct);
             APTS_LRDLODUtility.GetLODForAgreementFromAccount(lsoController,acct.id,'Spain');
             test.stopTest();
         }
    }
    */
    /*
     public static testMethod void testGetLODForAgrrementFromOpportunity(){
        
         user  = APTS_LP_TestUtility.getUser();
         System.runAs(user) {
             APTS_CaptureInputForLSODataController lsoController = new APTS_CaptureInputForLSODataController();
             Account acct = APTS_LP_TestUtility.getNewAccount('Test', 'Spain');
             test.startTest();
             insert acct;
             ERP_Reference_Data__c erprefData = getERPReferenceData(acct);
             APTS_LRDLODUtility.GetLODForAgrrementFromOpportunity(lsoController,acct.id,'Spain',erpRefData);
             test.stopTest();
         }
        
     }
    
   */
   /* public static testMethod void testfindMatchingLODRecords(){
        
     user  = APTS_LP_TestUtility.getUser();
     System.runAs(user) {
     APTS_CaptureInputForLSODataController lsoController = new APTS_CaptureInputForLSODataController();
     Account acct = APTS_LP_TestUtility.getNewAccount('Test', 'Spain');
     test.startTest();
     insert acct;
     
     ERP_Reference_Data__c erprefData = getERPReferenceData(acct);
     List<ERP_Reference_Data__c> ref = new List<ERP_Reference_Data__c>();
     ref.add(erprefData);
     APTS_LRDLODUtility.findMatchingLODRecords(lsoController,ref);
     String refID = String.valueOf(erprefData.id);
     APTS_LRDLODUtility.GetLODForQuoteFromOpportunity(refID);
     test.stopTest();    
     } 
        
        
    }*/
    
    public static ERP_Reference_Data__c getERPReferenceData (Account acc){
    
        ERP_Reference_Data__c  refData1 = new ERP_Reference_Data__c();
        refData1.Local_Customer_ID__c = '12345678';
        refData1.SAP_Sales_Organization__c = 'ABB';
        refData1.SAP_Distribution_Channel__c = APTS_LP_TestUtility.getDistributionChannel().APTS_Code__c;
        refData1.LSO__c = user.Default_LSO__c;
        refData1.LBU__c = user.Default_BU__c;
        refData1.Account_GUID__c = acc.GUID__c;
        refData1.Account__c = acc.id;
        insert refData1;
        
        //String refID = String.valueOf(refData1.id);
        //APTS_LRDLODUtility.GetLODForQuoteFromOpportunity(refID);
        
        return refData1;
    }
    
        public static APTS_LP_Local_Customer_Reference_Data__c getLODReferenceData (Account acc){
    
        APTS_LP_Local_Customer_Reference_Data__c  refData1 = new APTS_LP_Local_Customer_Reference_Data__c();
        refData1.APTS_LP_SAP_Customer_ID__c = '12345678';
        refData1.APTS_LP_Sales_Organisation__c = 'ABB';
        refData1.APTS_LP_Distribution_Channel__c = APTS_LP_TestUtility.getDistributionChannel().APTS_Code__c;
        refData1.APTS_LP_Account__c = acc.id;
        refData1.APTS_Country__c = 'Spain';
        refData1.APTS_External_ID__c = '12345678';
        refData1.APTS_Payment_Terms__c = 'Z300';
        refData1.APTS_LP_Incoterms__c = 'CPT';
        refData1.APTS_LP_Local_Channel__c = 'P5';
        insert refData1;
        
        //String refID = String.valueOf(refData1.id);
        //APTS_LRDLODUtility.GetLODForQuoteFromOpportunity(refID);
        
        return refData1;
    }

}