src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field is to e used to control access to the record, as part of the GIS Team Operations.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>

 <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
<fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Applicable_for_NPS_Survey__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field captures, whether the record is applicable for a Transactual NPS Survey. Can be used to filter.</description>
        <inlineHelpText>This field captures, whether the record is applicable for a Transactual NPS Survey. Can be used to filter.</inlineHelpText>
        <label>Applicable for NPS Survey</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <controllingField>Division__c</controllingField>
            <picklistValues>
                <fullName>DMDR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMPC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMRO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPBP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPCP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPCW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPLS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPMV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PACT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAMP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAOG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAPG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAPI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PATU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGGA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGGI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGGS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGHV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGTR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZCCO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZCRE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZCVA</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>This field captures the description for the inquiry</description>
        <inlineHelpText>This field captures the description for the inquiry</inlineHelpText>
        <label>Description</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>DM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PG</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lead_Origin__c</fullName>
        <description>This field stores the origin of the lead generated in the system. If generated by sub processes(e.g: CCDv2), the values will be pre populated.</description>
        <inlineHelpText>Shows the origin of the Lead</inlineHelpText>
        <label>Lead Origin</label>
        <picklist>
            <picklistValues>
                <fullName>Phone</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Media</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NPS_ID__c</fullName>
        <description>Integration Workstream : R5 : R-2521</description>
        <label>NPS ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NPS_Survey_Reminder_Needed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NPS Survey Reminder Needed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NPS_Survey_Status__c</fullName>
        <description>Integration Workstream : R5 : R-2517</description>
        <label>NPS Survey Status</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Originating_Country__c</fullName>
        <label>Originating Country</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aland Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antarctica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua And Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia, Plurinational State Of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonaire, Sint Eustatius And Saba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia And Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Germany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Participant_reminder__c</fullName>
        <label>Participant reminder</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <label>Product Group</label>
        <picklist>
            <controllingField>Business_Unit__c</controllingField>
            <picklistValues>
                <fullName>1339 - Non-Core Various</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1342 - Various</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1722 - Thermal &amp; Water Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1723 - Power and Water Automation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1724 - Renewable Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1728 - Automation Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2106 - Gas Insulated Switchgear</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2108 - HV Breakers &amp; Modules</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2111 - Common Apparatus &amp; Devices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2115 - Generator Circuit Breakers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2127 - Other High Voltage Components</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2128 - Capacitors and Filters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2129 - Instrument Transformers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2132 - HV Testing Labs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2214 - Offshore Wind Connections</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2215 - HVDC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2217 - FACTS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2221 - OWC Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2222 - HVDC Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2223 - FACTS Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2224 - Power Cables Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2401 - Distribution Transformers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2404 - Small Power Transformers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2408 - Large and Medium Power Transformers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2409 - Dry Transformers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2413 - Transformer Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2425 - Insulation and Components</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2451 - Domestic Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2617 - Domestic Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2657 - High Voltage Service</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <description>This fields was also referred as &quot;Request Type CC Tier1&quot;</description>
        <inlineHelpText>CC Tier1</inlineHelpText>
        <label>Request Type</label>
        <picklist>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>(only for Contact Centre)</description>
        <label>Subject</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/MassUncheckforNPS_TEST.cls
/**
*  This test class used to test class MassUncheckforNPSController and MassUncheckforNPSClass
*    
@author : Saiprasad Telkapally
@Date : 23-03-2016
@version :  1.0 
* 
*/


@isTest
Public Class MassUncheckforNPS_TEST
{
static testmethod void MassUncheckforNPS1_TEST()
            {
            RecordType rt = [Select Id from RecordType where Name = 'Contact Center'];
            Account acc = new Account(); 
            acc.Name = 'Test1';
            acc.BillingStreet = 'dajie';
            acc.BillingCity = 'berlin';
            acc.BillingState = 'Berlin';
            acc.BillingPostalCode = '20012';
            acc.BillingCountry = 'Germany';
            acc.rating='Hot';
            acc.industry='Manufacturing';
            acc.Phone='+41 123 123456';
            acc.Type='Prospect';
            acc.Active__C= true;
            insert acc;
            Contact con = new Contact ();
            con.firstname ='Test'; 
            con.lastname='Contact1';
            con.email='test@test.com';
            con.phone='78545454';
            con.accountid=acc.id;
            insert con;
            Lead la =new Lead();
            la.LastName ='saipppp';
            la.Company = 'ABB';
            la.Status ='Contacted';
            la.Subject__c = 'fjkdnmkan';
            la.Description ='mfldsfkgj;lklhglklkgfkg';
            la.Originating_Country__c ='India';
            //la.Address ='jfdm,nagdf';
            la.Division__c= 'DM';
            la.Business_Unit__c= 'DMDR';
            la.Product_Group__c = '1339 - Non-Core Various';
            la.Request_Type__c = 'Sales';
            la.Applicable_for_NPS_Survey__c= true;
            la.NPS_Survey_Reminder_Needed__c = true;
            la.Participant_reminder__c= system.today()+1;
            la.Description__c ='fdkksnmfgl';
            //la.NPS_Survey_Status__c = '';
            la.Lead_Origin__c ='Web';
            la.Email ='abc@abc.com';
            la.Phone ='41 123 1234567';
            la.NPS_ID__c = '123';
            la.Related_existing_Contact__c= con.id;
            la.RecordTypeID =rt.ID;
            List<id> lids= new List<id>();
            test.startTest();
            insert la;
            lids.add(la.id);
            ApexPages.currentPage().getParameters().put('lrecs', la.id);
            MassUncheckforNPSclass.massUnchecker(lids);
            MassUncheckforNPSController mufnc = new MassUncheckforNPSController (new ApexPages.StandardController(new Lead()));
            ApexPages.currentPage().getParameters().put('id', la.id);
            PageReference pageRef2 = mufnc.validator();
            PageReference pageRef3 = mufnc.back();
            Test.StopTest();

            }
        static testmethod void MassUncheckforNPS_TEST2()
        {

        RecordType rt = [Select Id from RecordType where Name = 'Contact Center'];
        Account acc = new Account(); 
        acc.Name = 'Test1';
        acc.BillingStreet = 'dajie';
        acc.BillingCity = 'berlin';
        acc.BillingState = 'Berlin';
        acc.BillingPostalCode = '20012';
        acc.BillingCountry = 'Germany';
        acc.rating='Hot';
        acc.industry='Manufacturing';
        acc.Phone='+41 123 123456';
        acc.Type='Prospect';
        acc.Active__C= true;
        insert acc;

        Contact con = new Contact ();
        con.firstname ='Test'; 
        con.lastname='Contact1';
        con.email='test@test.com';
        con.phone='9988776600';
        con.accountid=acc.id;
        insert con;


        Lead la =new Lead();
        la.LastName ='saipppp';
        la.Company = 'ABB';
        la.Status ='Contacted';
        la.Subject__c = 'fjkdnmkan';
        la.Description ='mfldsfkgj;lklhglklkgfkg';
        //la.Originating_Country__c ='India';
        //la.Address ='jfdm,nagdf';
        la.Division__c= 'DM';
        la.Business_Unit__c= 'DMDR';
        la.Product_Group__c = '1339 - Non-Core Various';
        la.Request_Type__c = 'Sales';
        la.Applicable_for_NPS_Survey__c= true;
        la.NPS_Survey_Reminder_Needed__c = false;
        la.Participant_reminder__c= system.today()+1;
        la.Description__c ='fdkksnmfgl';
        //la.NPS_Survey_Status__c = '';
        la.Lead_Origin__c ='Email';
        la.Originating_Country__c = 'India';
        la.Email ='abc@abc.com';
        la.Phone ='122332332223';
        //la.NPS_ID__c ='';
        la.Related_existing_Contact__c= con.id;
        la.RecordTypeID =rt.ID;
        List<id> lids= new List<id>();

        test.startTest();
        insert la;
        lids.add(la.id);
        //string id =la.id;
        ApexPages.currentPage().getParameters().put('lrecs', la.id);
        MassUncheckforNPSController mufnc = new MassUncheckforNPSController (new ApexPages.StandardController(new Lead()));
        MassUncheckforNPSclass.massUnchecker(lids);
        ApexPages.currentPage().getParameters().put('id', la.id);
        PageReference pageRef2 = mufnc.validator();
        PageReference pageRef3 = mufnc.back();


        Test.StopTest();

        }

}