src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field is to e used to control access to the record, as part of the GIS Team Operations.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>

 <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <description>From Master Data Management Hierarchy</description>
        <inlineHelpText>Select the Business Unit that is responsible for resolving the case</inlineHelpText>
        <label>Business Unit</label>
        <picklist>
            <controllingField>Division__c</controllingField>
            <picklistValues>
                <fullName>DMDR - Drives and Controls</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>DMMG - Motors &amp; Generators</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>DMPC - Power Conversion</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>DMRO - Robotics</fullName>
                <color>#A845DC</color>
            </picklistValues>
            <picklistValues>
                <fullName>EPBP - Building Products</fullName>
                <color>#B6E32E</color>
            </picklistValues>
            <picklistValues>
                <fullName>EPBS - Breakers &amp; Switches</fullName>
                <color>#A53711</color>
            </picklistValues>
            <picklistValues>
                <fullName>EPCP - Control Products</fullName>
                <color>#66E9BD</color>
            </picklistValues>
            <picklistValues>
                <fullName>EPCW - Installation Products</fullName>
                <color>#641CCF</color>
            </picklistValues>
            <picklistValues>
                <fullName>EPLS - Electrification Solutions</fullName>
                <color>#419249</color>
            </picklistValues>
            <picklistValues>
                <fullName>EPMV - Medium Voltage Products</fullName>
                <color>#A845DC</color>
            </picklistValues>
            <picklistValues>
                <fullName>PACT - Control Technologies</fullName>
                <color>#2F5D85</color>
            </picklistValues>
            <picklistValues>
                <fullName>PAMA - Marine &amp; Ports</fullName>
                <color>#8F6429</color>
            </picklistValues>
            <picklistValues>
                <fullName>PAMP - Measurement &amp; Analytics</fullName>
                <color>#EFAE73</color>
            </picklistValues>
            <picklistValues>
                <fullName>PAOG - Oil, Gas &amp; Chemicals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAPG - Power Generation</fullName>
                <color>#B6E32E</color>
            </picklistValues>
            <picklistValues>
                <fullName>PAPI - Process Industries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PATU - Turbocharging</fullName>
                <color>#57F17C</color>
            </picklistValues>
            <picklistValues>
                <fullName>PGGA - Grid Automation</fullName>
                <color>#0B24BE</color>
            </picklistValues>
            <picklistValues>
                <fullName>PGGI - Grid Integration</fullName>
                <color>#641CCF</color>
            </picklistValues>
            <picklistValues>
                <fullName>PGGS - Grid Systems</fullName>
                <color>#66E9BD</color>
            </picklistValues>
            <picklistValues>
                <fullName>PGHV - High Voltage Products</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>PGTR - Transformers</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>ZCCO - Corporate</fullName>
                <color>#2F5D85</color>
            </picklistValues>
            <picklistValues>
                <fullName>ZCRE - Real Estate</fullName>
                <color>#AFCADF</color>
            </picklistValues>
            <picklistValues>
                <fullName>ZCVA - Various</fullName>
                <color>#8F6429</color>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CCRP_Status__c</fullName>
        <description>Integration Workstream : R5 : R-2190</description>
        <label>CCRP Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_2__c</fullName>
        <label>Case Type</label>
        <picklist>
            <controllingField>Category__c</controllingField>
            <picklistValues>
                <fullName>Homologation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Requirement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Factory Acceptance Test</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HelpDesk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complaints</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Details</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Originating_Country__c</fullName>
        <description>Use the related Account Country, if not sure.</description>
        <inlineHelpText>Select the country where the case was raised</inlineHelpText>
        <label>Originating Country</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aland Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antarctica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua And Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia, Plurinational State Of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonaire, Sint Eustatius And Saba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia And Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>France</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Germany</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Complaint</fullName>
        <active>true</active>
        <businessProcess>Services</businessProcess>
        <description>Please DO NOT directly create Case of this recordtype.Recordtype used to create Complaints to CCRP.</description>
        <label>Complaint</label>
    </recordTypes>
    <recordTypes>
        <fullName>Services</fullName>
        <active>true</active>
        <businessProcess>Services</businessProcess>
        <description>Record Type for Service Cases</description>
        <label>Services</label>
        
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SendCasetoCCRP_TEST.cls
/**
*  This test class used to test class SendCasetoCCRPClass and SendSubstitutesToCCRPclass
*    
@author Saiprasad Telkapally
@version 1.0 
* 
*/
@isTest
Public Class SendCasetoCCRP_TEST
{
    static testmethod void SendCasetoCCRP_TEST1()
    {
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        String uName = 'userIsTestinProd@testisUser.test';
        User u = new User();
        u.Alias = 'zdxzxz'; 
        u.Email='email@email.com';
        u.EmailEncodingKey='UTF-8';
        u.LastName='Testing'; 
        u.LanguageLocaleKey='en_US'; 
        u.LocaleSidKey='en_US';
        u.ProfileId = p.Id;
        u.TimeZoneSidKey='America/Los_Angeles';
        u.UserName='userIsTestinProd@testisUser.test';
        insert u;
        
     /*    User u1 = new User(alias = 'zdxzxz', email='kbrazi@salesforce.com',
                            emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='fr',
                            localesidkey='fr_FR_EURO', profileid = p.Id, country='France',
                            timezonesidkey='Europe/Paris', username='userIsTestinProd@testisUser.test',
                            IsActive = true);
    insert u1; */
        
        System.runAs(u){
        RecordType rt = [Select Id from RecordType where DeveloperName = 'Services'];
        Account acc = new Account(); 
        acc.Name = 'Test1';
        acc.BillingStreet = 'dajie';
        acc.BillingCity = 'berlin';
        acc.BillingState = 'Berlin';
        acc.BillingPostalCode = '20012';
        acc.BillingCountry = 'Germany';
        acc.rating='Hot';
        acc.industry='Manufacturing';
        acc.Phone='+41 123 123456';
        acc.Type='Prospect';
        acc.Active__C= true;
        Insert acc;
        Contact con = new Contact ();
        con.firstname ='Test';
        con.lastname='Contact1';
        con.email='test@test.com';
        con.phone='9988776600';
        con.accountid=acc.id;
        insert con;
        
    
        Case c2 = new Case();
        C2.subject = 'TestCase 1';
        C2.status ='Open';
        C2.type='Mechanical';
        C2.reason='Installation';
        C2.Business_unit__c ='EPCP - Control Products';
        C2.contactid=con.id;
        C2.RecordTypeId = rt.ID;
        C2.Originating_Country__c = 'Bangladesh';
        c2.Category_2__c ='Complaints';
       // c2.CCRP_Status__c =null;
       c2.Description = 'sai213';
        C2.SuppliedEmail='abc@abc.com';    
        C2.accountid=acc.id;
        c2.OwnerID =  u.id;
        
        System.assert(c2!=null);
         insert c2;

         
        
        system.debug('sai::accountid:::'+C2.accountid);
        system.debug('sai::::ContactId:::'+c2.ContactId);
        system.debug('sai::::Description::'+c2.Description);
        system.debug('sai::::RecordTypeId:'+ C2.RecordTypeId);
  
       CaseTeamRole CTR = new CaseTeamRole();
       CTR.AccessLevel='Edit';
       CTR.Name='Test Case Team Role';
       CTR.PreferencesVisibleInCSP=true;
        insert CTR;
        
      List<CaseTeamMember> CTMs = new List<CaseTeamMember>();
        CaseTeamMember CTM = new CaseTeamMember();
        CTM.MemberId=u.id;
        CTM.ParentId= c2.ID;
        CTM.TeamRoleId = CTR.Id;
        CTMs.add(CTM);

        Test.startTest();
      //  insert c2;
        insert CTMs;
      
        SendSubstitutesToCCRPclass.sendSubstitutes(c2.id);
        SendCaseToCCRPClass.sendtoCCRP(c2.id);    
        Test.StopTest();
    }
    }
    static testmethod void SendCasetoCCRP_TEST2()
    {
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User u = new User();
        u.Alias = 'zdxzyz'; 
        u.Email='email@email.com';
        u.EmailEncodingKey='UTF-8';
        u.LastName='Testing'; 
        u.LanguageLocaleKey='en_US'; 
        u.LocaleSidKey='en_US';
        u.ProfileId = p.Id;
        u.TimeZoneSidKey='America/Los_Angeles';
        u.UserName='userIsTestinProd@testisUser.test2';
        insert u;
        
     /*    User u1 = new User(alias = 'zdxzyz', email='kbrazi@salesforce.com',
                            emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='fr',
                            localesidkey='fr_FR_EURO', profileid = p.Id, country='France',
                            timezonesidkey='Europe/Paris', username='userIsTestinProd@testisUser.test2',
                            IsActive = true);
    insert u1; */
        
        System.runAs(u){
        RecordType rt = [Select Id from RecordType where DeveloperName = 'Complaint'];
        Account acc = new Account(); 
        acc.Name = 'Test1';
        acc.BillingStreet = 'dajie';
        acc.BillingCity = 'berlin';
        acc.BillingState = 'Berlin';
        acc.BillingPostalCode = '20012';
        acc.BillingCountry = 'Germany';
        acc.rating='Hot';
        acc.industry='Manufacturing';
        acc.Phone='+41 123 123456';
        acc.Type='Prospect';
        acc.Active__C= true;
        Insert acc;
        Contact con = new Contact ();
        con.firstname ='Test';
        con.lastname='Contact1';
        con.email='test@test.com';
        con.phone='9988776600';
        con.accountid=acc.id;
        insert con;
        
    
        Case c2 = new Case();
        C2.subject = 'TestCase 1';
        C2.status ='Open';
        C2.type='Mechanical';
        C2.reason='Installation';
        C2.Business_unit__c ='EPCP - Control Products';
        C2.contactid=con.id;
        C2.RecordTypeId = rt.ID;
        C2.Originating_Country__c = 'Bangladesh';
        c2.Category_2__c ='Complaints';
       // c2.CCRP_Status__c =null;
       c2.Description = 'sai213';
        C2.SuppliedEmail='abc@abc.com';    
        C2.accountid=acc.id;
        c2.OwnerID =  u.id;
        
        System.assert(c2!=null);
         insert c2;

       CaseTeamRole CTR = new CaseTeamRole();
       CTR.AccessLevel='Edit';
       CTR.Name='Test Case Team Role';
       CTR.PreferencesVisibleInCSP=true;
        insert CTR;
        
      List<CaseTeamMember> CTMs = new List<CaseTeamMember>();
        CaseTeamMember CTM = new CaseTeamMember();
        CTM.MemberId=u.id;
        CTM.ParentId= c2.ID;
        CTM.TeamRoleId = CTR.Id;
        CTMs.add(CTM);

        Test.startTest();
      //  insert c2;
      insert CTMs;
        Delete CTMs;
      
        SendSubstitutesToCCRPclass.sendSubstitutes(c2.id);
        SendCaseToCCRPClass.sendtoCCRP(c2.id);    
        Test.StopTest();
    }
    }
}