src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>GUID__c</fullName>
        <externalId>true</externalId>
        <label>GUID</label>
        <length>9</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Main_Local_City__c</fullName>
        <label>Primary Address (Local): City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Main_Local_Street__c</fullName>
        <label>Primary Address (Local): Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Address_Country__c</fullName>
        <description>This is hidden field to be used in the Account search filters and results!</description>
        <label>Primary Address: Country</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aland Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antarctica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia, Plurinational State of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia and Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spain</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>

 <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/APTS_Capture_LSO_Input_Config_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom object to configure settings like dropdown list values etc. for Capture LSO Input page while creating MSPA or Quotation from Account or Opportunity.</description>
    <fields>
        <fullName>APTS_Stage_MSPA__c</fullName>
        <description>Report link for Stage MSPA object</description>
        <label>Stage MSPA</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Capture LSO Input Config Settings</label>
</CustomObject>

src/objects/APTS_LP_Local_Customer_Reference_Data__c.object
<CustomObject>
    <description>Object to hold the reference data related to customer (account). (ABB-LP)</description>
    <fields>
        <fullName>APTS_External_ID__c</fullName>
        <description>External Id to match the unique set. Value of this field will be SAP ID + Sales organisation + Distribution Channel.</description>
        <externalId>true</externalId>
        <label>APTS External ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_LP_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Local Operational Data</relationshipLabel>
        <relationshipName>Local_Customer_Reference_Data</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>APTS_LP_SAP_Customer_ID__c</fullName>
        <description>Placeholder field to hold the value of customer ID fetched from SAP.</description>
        <label>SAP Customer ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Local Operational Data</label>
    <nameField>
        <displayFormat>LCRD-{00000}</displayFormat>
        <label>Local Operational Data Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Local Operational Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/APTS_Stage_Data_Validation_Rules_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>APTS_Validate_SFDC_User__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Flag to check if Assigned Approver and Actual Approver fields required validation against SFDC User Object</description>
        <label>Validate SFDC User</label>
        <type>Checkbox</type>
    </fields>
	<label>APTS Stage Data Validation Rules</label>
</CustomObject>

src/objects/APTS_Stage_Local_Operational_Data__c.object
<CustomObject>
    <description>Staging Object for Local Operational Data Object</description>
    <fields>
        <fullName>APTS_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>APTS External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>APTS_LP_SAP_Customer_ID__c</fullName>
        <description>Placeholder field to hold the value of customer ID fetched from SAP.</description>
        <label>SAP Customer ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Stage Local Operational Data</label>
    <nameField>
        <displayFormat>LCRD-{00000}</displayFormat>
        <label>Apttus Local Customer Reference Data Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stage Local Operational Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/APTS_Stage_MSPA__c.object
<CustomObject>
    <description>Staging Object for Agreement</description>
    <fields>
        <fullName>APTS_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>APTS_Incoterms_methods_Code__c</fullName>
        <label>Incoterms methods (Code)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Owner__c</fullName>
        <label>Owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Payment_Terms_SPA__c</fullName>
        <label>Payment Terms (SPA)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_SAP_Customer_ID__c</fullName>
        <label>SAP Customer ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Stage MSPA</label>
    <nameField>
        <label>MSPA Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stage MSPA</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/APTS_Stage_MSPA_LineItems__c.object
<CustomObject>
    <fields>
        <fullName>APTS_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>APTS_Owner__c</fullName>
        <label>Owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_SPA_Identifier__c</fullName>
        <label>SPA Identifier</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Stage MSPA LineItems</label>
    <nameField>
        <displayFormat>MLI{00000000}</displayFormat>
        <label>Stage MSPA Line Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stage MSPA Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/APTS_Stage_Product__c.object
<CustomObject>
    <description>Stage Product</description>
    <fields>
        <fullName>APTS_External_ID__c</fullName>
        <description>External ID</description>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>60</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Stage Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stage Product</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    
    <fields>
        <fullName>APTS_Locale__c</fullName>
        <description>This field has locale of user if available or gets the locale of Organization</description>
        <inlineHelpText>This field has locale of user if available or gets the locale of Organization</inlineHelpText>
        <label>Locale</label>
        <picklist>
            <picklistValues>
                <fullName>en_US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>es_ES</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
	<fullName>APTS_SAP_Customer_ID__c</fullName>
	<description>Field to hold the value of Sold To customer ID in SAP fetched from LRD.</description>
	<inlineHelpText>Matching Sold To ID in SAP</inlineHelpText>
	<label>SAP Customer ID</label>
	<length>255</length>
	<type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_SPA_Identifier__c</fullName>
        <description>SPA Identifier will be used as a reference to MSPA Line Item.</description>
        <label>SPA Identifier</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__PriceListId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated price list</description>
        <label>Price List</label>
        <referenceTo>Apttus_Config2__PriceList__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__LineItem__c.object
<CustomObject>
    <fields>
        <fullName>APTS_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Owner__c</fullName>
        <label>Original Owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Apttus_Config2__PriceList__c.object
<CustomObject>
    <fields>
        <fullName>APTS_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>APTS_External_ID__c</fullName>
        <description>External Id Field. This is used while copying records from staging to normal object</description>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>APTS_Locale__c</fullName>
        <label>Locale</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/APTS_DMMSPAHelperTest.cls
@isTest(seeAllData=False)
private class APTS_DMMSPAHelperTest {

	//private static APTS_Capture_LSO_Input_Config_Settings__c lodConfigSetting = APTS_LP_TestUtility.getLODConfigSetting();
	private static User user;
	public static testMethod void validateStageMSPA(){   
        Boolean isValidateOwner = False;
        APTS_LP_TestUtility.getCommonConfigSetting();
        List<APTS_Stage_Data_Validation_Rules_Setting__c> dataValCustomSetting = APTS_Stage_Data_Validation_Rules_Setting__c.getall().values();
        for(APTS_Stage_Data_Validation_Rules_Setting__c dvr: dataValCustomSetting) {
            if(dvr.name == 'DataMigration') isValidateOwner = true;
        }
        if (isValidateOwner != true) {
            APTS_Stage_Data_Validation_Rules_Setting__c validateUser = new APTS_Stage_Data_Validation_Rules_Setting__c(); 
            validateUser.name = 'DataMigration'; 
            validateUser.APTS_Validate_SFDC_User__c = FALSE ;        
            insert validateUser;
        }
        user  = APTS_LP_TestUtility.getUser();
        System.runAs(user) {
	       Account acct1 =  APTS_LP_TestUtility.getNewAccount('Acct-1','US');
	        insert acct1;
	       Account acct = [select ID, Primary_Address_Country__c,Main_Local_City__c,Main_Local_Street__c,BillingCity,BillingStreet,BillingCountry,GUID__c 
                         from Account where GUID__c = 'G01413815' limit 1];
            
	        List<APTS_Stage_MSPA__c> listStageMSPA =  APTS_LP_TestUtility.getStageMSPA(5);
	        for(APTS_Stage_MSPA__c stageMspa : listStageMSPA){
	        	stageMspa.APTS_Owner__c = 'Testing';
	        	stageMspa.APTS_SAP_Customer_ID__c = 'Testing';
	        }
	        APTS_LP_TestUtility.getSalesOffice();
	        APTS_LP_TestUtility.getDistributionChannel();
	        APTS_LP_Local_Customer_Reference_Data__c lcrd = new APTS_LP_Local_Customer_Reference_Data__c();
	        lcrd.APTS_LP_SAP_Customer_ID__c = 'Testing';
	        lcrd.APTS_LP_Account__c = acct.id;
	         lcrd.APTS_External_ID__c = 'Testing';
	        insert lcrd;

	        test.startTest();
	        
	        APTS_DMMSPAHelper.validateStageMSPA(listStageMSPA);
	        test.stopTest();  
       }
   }
	
	public static testMethod void copyMSPA(){
		Boolean isValidateOwner = False;
        APTS_LP_TestUtility.getCommonConfigSetting();
        List<APTS_Stage_Data_Validation_Rules_Setting__c> dataValCustomSetting = APTS_Stage_Data_Validation_Rules_Setting__c.getall().values();
        for(APTS_Stage_Data_Validation_Rules_Setting__c dvr: dataValCustomSetting) {
            if(dvr.name == 'DataMigration') isValidateOwner = true;
        }
        if (isValidateOwner != true) {
            APTS_Stage_Data_Validation_Rules_Setting__c validateUser = new APTS_Stage_Data_Validation_Rules_Setting__c(); 
            validateUser.name = 'DataMigration'; 
            validateUser.APTS_Validate_SFDC_User__c = FALSE ;        
            insert validateUser;
        }        
        user  = APTS_LP_TestUtility.getUser();
        System.runAs(user) {
	       Account acct1 =  APTS_LP_TestUtility.getNewAccount('Acct-1','US');
	       insert acct1;
	     Account acct = [select ID, Primary_Address_Country__c,Main_Local_City__c,Main_Local_Street__c,BillingCity,BillingStreet,BillingCountry,GUID__c 
                         from Account where GUID__c = 'G01413815' limit 1];

	        List<APTS_Stage_MSPA__c> listStageMSPA =  APTS_LP_TestUtility.getStageMSPA(5);
	        for(APTS_Stage_MSPA__c stageMspa : listStageMSPA){
	        	stageMspa.APTS_Owner__c = 'Testing';
	        	stageMspa.APTS_SAP_Customer_ID__c = 'Testing';
	        	stageMspa.APTS_Incoterms_methods_Code__c = 'Testing';
	        	stageMspa.APTS_Payment_Terms_SPA__c = 'Testing';
	        }
            
            insert listStageMSPA;
            
	        APTS_LP_TestUtility.getSalesOffice();
	        APTS_LP_TestUtility.getDistributionChannel();

	        APTS_LP_Local_Customer_Reference_Data__c lcrd = new APTS_LP_Local_Customer_Reference_Data__c();
	        lcrd.APTS_LP_SAP_Customer_ID__c = 'Testing';
	       // lcrd.Name = 'Testing';
	       lcrd.APTS_External_ID__c = 'Testing';
	        lcrd.APTS_LP_Account__c = acct.id;

	        insert lcrd;

	        Apttus_Config2__PriceList__c prcielst = APTS_LP_TestUtility.getPriceList(acct, 'Spain');
	        prcielst.Apttus_Config2__Active__c = true;
	        insert prcielst;

	        test.startTest();
	        
	       APTS_CopyDataWrapper oCopyWrapper= APTS_DMMSPAHelper.copyMSPA(listStageMSPA);
	        test.stopTest();  
       }
   }
	

	public static testMethod void copyStageMSPALineItemToLineItem(){
        user  = APTS_LP_TestUtility.getUser();
        
        System.runAs(user) {
        
            APTS_LP_TestUtility.getCommonConfigSetting();
            Account acct1 =  APTS_LP_TestUtility.getNewAccount('Acct-1','US');
	        insert acct1;

            Account acct = [select ID, Primary_Address_Country__c,Main_Local_City__c,Main_Local_Street__c,BillingCity,BillingStreet,BillingCountry,GUID__c 
                         from Account where GUID__c = 'G01413815' limit 1];
            
	         Apttus_Config2__PriceList__c prcielst = APTS_LP_TestUtility.getPriceList(acct, 'Spain');
	        prcielst.Apttus_Config2__Active__c = true;
	        insert prcielst;

			Apttus__APTS_Agreement__c agreement = APTS_LP_TestUtility.getAgreement('Testing');
			agreement.APTS_SPA_Identifier__c = 0;
			agreement.Apttus_CMConfig__PriceListId__c = prcielst.id;
			APTS_LP_TestUtility.getDiscountConfig();
			APTS_LP_TestUtility.getApproalRuleMatrix();
            agreement.APTS_Locale__c = 'es_ES';
			insert agreement;

	         APTS_LP_TestUtility.getSalesOffice();
	        APTS_LP_TestUtility.getDistributionChannel();
	        APTS_LP_TestUtility.getCustomSetting();

        	List<APTS_Stage_Product__c> listLocalProduct  = APTS_LP_TestUtility.getProductList(5,APTS_DMConstants.LOCAL_PRODUCTS); 
        	insert listLocalProduct;

        	List<APTS_Stage_MSPA_LineItems__c> listStageMSPALineItems =  APTS_LP_TestUtility.getStageMSPALineItems(5);
            for(APTS_Stage_MSPA_LineItems__c mspaLineItem: listStageMSPALineItems) {
                mspaLineItem.APTS_RowStatus__c = APTS_DMConstants.VALIDATION_STATUS;
            }
        	insert listStageMSPALineItems;
            
            
            List<Product2> productList =  APTS_LP_TestUtility.getProductList(6);
        	//insert productList1;
            
        	//List<Product2> productList = APTS_LP_TestUtility.getProductList(3);
          //List<Product2> productList = [Select ID, APTS_Product_ID__c from Product2 limit 6]; 
        	Integer i = 0;
        	for(Product2 prd: productList){
       		prd.APTS_Product_ID__c = 'Product-Code' + i;
        		i++;
        	//	APTS_LP_TestUtility.addPricebookAndEntries(prd);
        	}

        	insert productList;
        	

        	

 			Apttus_Config2__ProductConfiguration__c productConfig = APTS_LP_TestUtility.getProductConfiguration('TestProductConfiguration');
            productConfig.Apttus_CMConfig__AgreementId__c = agreement.id;
            insert productConfig;
            
            Apttus_Config2__ProductConfiguration__c hierarchyProductConfig = APTS_LP_TestUtility.getProductConfiguration('TestHierarchyProductConfiguration');
            hierarchyProductConfig.Apttus_CMConfig__AgreementId__c = agreement.id;
            insert hierarchyProductConfig;
            
            List<Apttus_Config2__LineItem__c> listLineItem = new List<Apttus_Config2__LineItem__c>();
            listLineItem.addAll(APTS_LP_TestUtility.getLineItemListWithDiscount(productConfig.ID, 2, productList[0],5));
            listLineItem.addAll(APTS_LP_TestUtility.getLineItemListWithDiscount(productConfig.ID, 5, productList[1],9));
            listLineItem.addAll(APTS_LP_TestUtility.getLineItemListWithPriceOveride(productConfig.ID, 5, productList[2],10));
            listLineItem.addAll(APTS_LP_TestUtility.getLineItemListWithDiscount(hierarchyProductConfig.ID, 2, productList[3],5));
            listLineItem.addAll(APTS_LP_TestUtility.getLineItemListWithDiscount(hierarchyProductConfig.ID, 5, productList[4],9));
            listLineItem.addAll(APTS_LP_TestUtility.getLineItemListWithPriceOveride(hierarchyProductConfig.ID, 5, productList[5],10));
            insert listLineItem;
            
            productConfig.Apttus_Config2__Status__c = 'Finalized';
            update productConfig;
            hierarchyProductConfig.Apttus_Config2__Status__c = 'Finalized';
            update hierarchyProductConfig;


	        List<APTS_Stage_MSPA__c> listStageMSPA =  APTS_LP_TestUtility.getStageMSPA(5);
	        for(APTS_Stage_MSPA__c stageMspa : listStageMSPA){
	        	stageMspa.APTS_Owner__c = 'Testing';
	        	stageMspa.APTS_SAP_Customer_ID__c = 'Testing';
	        	stageMspa.APTS_Incoterms_methods_Code__c = 'Testing';
	        	stageMspa.APTS_Payment_Terms_SPA__c = 'Testing';
	        }
	       
			insert listStageMSPA;
	        APTS_LP_Local_Customer_Reference_Data__c lcrd = new APTS_LP_Local_Customer_Reference_Data__c();
	        lcrd.APTS_LP_SAP_Customer_ID__c = 'Testing';
	         lcrd.APTS_External_ID__c = 'Testing';
	       // lcrd.Name = 'Testing';
	        lcrd.APTS_LP_Account__c = acct.id;

	        insert lcrd;

	       

	        test.startTest();
	       APTS_CopyDataWrapper oCopyWrapper= APTS_DMMSPAHelper.copyStageMSPALineItemToLineItem(listStageMSPALineItems);            
	        test.stopTest();  
            
            
       }
	}
       
       
       	public static testMethod void validateStageMSPANegative(){  
            Boolean isValidateOwner = False;
            List<APTS_Stage_Data_Validation_Rules_Setting__c> dataValCustomSetting = APTS_Stage_Data_Validation_Rules_Setting__c.getall().values();
            for(APTS_Stage_Data_Validation_Rules_Setting__c dvr: dataValCustomSetting) {
                if(dvr.name == 'DataMigration') isValidateOwner = true;
            }
            if (isValidateOwner != true) {
                APTS_Stage_Data_Validation_Rules_Setting__c validateUser = new APTS_Stage_Data_Validation_Rules_Setting__c(); 
                validateUser.name = 'DataMigration'; 
                validateUser.APTS_Validate_SFDC_User__c = FALSE ;        
                insert validateUser;
            }
       	 user  = APTS_LP_TestUtility.getUser();
   	     System.runAs(user) {
   	        //APTS_LP_TestUtility.getLODConfigSetting();
   	        
   	        List<APTS_Stage_MSPA__c> listStageMSPA =  APTS_LP_TestUtility.getStageMSPA(5);
   	        Account acct1 =  APTS_LP_TestUtility.getNewAccount('Acct-1','US');
	        insert acct1;
   	         Account acct = [select ID, Primary_Address_Country__c,Main_Local_City__c,Main_Local_Street__c,
	                            BillingCity,BillingStreet,BillingCountry,GUID__c 
                                from Account 
                                where GUID__c = 'G01413815' limit 1];

            
            for(APTS_Stage_MSPA__c stageMspa : listStageMSPA){
        	    stageMspa.APTS_Owner__c = '';
        	    stageMspa.APTS_SAP_Customer_ID__c = 'Testing';
        	    stageMspa.APTS_Incoterms_methods_Code__c = 'Testing';
        	    stageMspa.APTS_Payment_Terms_SPA__c = 'Testing';
        	    stageMspa.APTS_Max_Order_Amount_SPA__c = 0;
            }
            
            APTS_Stage_Local_Operational_Data__c stageLOD = new APTS_Stage_Local_Operational_Data__c();
	        stageLOD.APTS_LP_SAP_Customer_ID__c = 'Testing';
	        stageLOD.APTS_External_ID__c = 'Testing';
	        //stageLOD.APTS_LP_Account__c = acct.id;
	        Apttus_Config2__PriceList__c prcielst = APTS_LP_TestUtility.getPriceList(acct, 'Spain');
	        prcielst.Apttus_Config2__Active__c = true;
	        
	        APTS_LP_Local_Customer_Reference_Data__c lcrd = new APTS_LP_Local_Customer_Reference_Data__c();
	        lcrd.APTS_LP_SAP_Customer_ID__c = 'Testing';
	        lcrd.APTS_External_ID__c = 'Testing';
	        lcrd.APTS_LP_Account__c = acct.id;
	        
            test.startTest();
            insert stageLOD;
            insert listStageMSPA;
            insert lcrd;
            
            APTS_DMMSPAHelper.validateStageMSPA(listStageMSPA);
            test.stopTest();
   	    }
    }
    
    	public static testMethod void copyMSPANegative(){
	
		Boolean isValidateOwner = False;
       
        List<APTS_Stage_Data_Validation_Rules_Setting__c> dataValCustomSetting = APTS_Stage_Data_Validation_Rules_Setting__c.getall().values();
        
        for(APTS_Stage_Data_Validation_Rules_Setting__c dvr: dataValCustomSetting) {
            if(dvr.name == 'DataMigration') 
                isValidateOwner = true;
        }
        
        if (isValidateOwner != true) {
            APTS_Stage_Data_Validation_Rules_Setting__c validateUser = new APTS_Stage_Data_Validation_Rules_Setting__c(); 
            validateUser.name = 'DataMigration'; 
            validateUser.APTS_Validate_SFDC_User__c = FALSE ;        
            insert validateUser;
        }        
        user  = APTS_LP_TestUtility.getUser();
        System.runAs(user) {
	       Account acct1 =  APTS_LP_TestUtility.getNewAccount('Acct-1','US');
	       insert acct1;
	     Account acct = [select ID, Primary_Address_Country__c,Main_Local_City__c,Main_Local_Street__c,
	                            BillingCity,BillingStreet,BillingCountry,GUID__c 
                                from Account 
                                where GUID__c = 'G01413815' limit 1];

	    List<APTS_Stage_MSPA__c> listStageMSPA =  APTS_LP_TestUtility.getStageMSPA(5);
	        
	    for(APTS_Stage_MSPA__c stageMspa : listStageMSPA){
	        	stageMspa.APTS_Owner__c = 'Testing';
	        	stageMspa.APTS_SAP_Customer_ID__c = 'Testing';
	        	stageMspa.APTS_Incoterms_methods_Code__c = 'Testing';
	        	stageMspa.APTS_Payment_Terms_SPA__c = 'Testing';
	        	stageMSpa.APTS_Currency__c = null;
	        	stageMSpa.APTS_ChannelSetValue_Code__c = APTS_LP_TestUtility.getLocalChannel().APTS_Code__c;
	        	stageMSpa.APTS_Incoterms_methods_Code__c = APTS_LP_TestUtility.getIncoterm().APTS_Code__c;
	        	stageMSpa.APTS_Payment_Terms_SPA__c = APTS_LP_TestUtility.getPaymentTerm().APTS_Code__c;
	        	stageMSpa.APTS_Sales_Person_SPA__c = 'Testing';
	     }
	     
	        APTS_LP_Local_Customer_Reference_Data__c lcrd = new APTS_LP_Local_Customer_Reference_Data__c();
	        lcrd.APTS_LP_SAP_Customer_ID__c = 'Testing';
	        lcrd.APTS_External_ID__c = 'Testing';
	        lcrd.APTS_LP_Account__c = acct.id;
	        Apttus_Config2__PriceList__c prcielst = APTS_LP_TestUtility.getPriceList(acct, 'Spain');
	        prcielst.Apttus_Config2__Active__c = true;
            
            test.startTest();
            insert lcrd;
            insert listStageMSPA;
            insert prcielst;
	        APTS_CopyDataWrapper oCopyWrapper= APTS_DMMSPAHelper.copyMSPA(listStageMSPA);
	        test.stopTest();  
       }
   }
	



      /* public static testMethod void repriceAndFinalize(){
        user  = APTS_LP_TestUtility.getUser();
        System.runAs(user) {

        	List<APTS_Stage_Product__c> listLocalProduct  = APTS_LP_TestUtility.getProductList(5,APTS_DMConstants.LOCAL_PRODUCTS); 
        	insert listLocalProduct;

        	List<APTS_Stage_MSPA_LineItems__c> listStageMSPALineItems =  APTS_LP_TestUtility.getStageMSPALineItems(5);
        	insert listStageMSPALineItems;

        	List<Product2> prds = APTS_LP_TestUtility.getProductList(4);
        	Integer i = 0;
        	for(Product2 prd: prds){
        		prd.APTS_Product_ID__c = 'Product-Code' + i;
        		i++;
        	}

        	insert prds;

			Apttus__APTS_Agreement__c agreement = APTS_LP_TestUtility.getAgreement('Testing');
			agreement.APTS_SPA_Identifier__c = 0;
			APTS_LP_TestUtility.getDiscountConfig();
			insert agreement;

			APTS_LP_TestUtility.getCustomSetting();


	        Account acct =  APTS_LP_TestUtility.getNewAccount('Acct-1','US');
	        insert acct;

	        List<APTS_Stage_MSPA__c> listStageMSPA =  APTS_LP_TestUtility.getStageMSPA(5);
	        for(APTS_Stage_MSPA__c stageMspa : listStageMSPA){
	        	stageMspa.APTS_Owner__c = 'Testing';
	        	stageMspa.APTS_SAP_Customer_ID__c = 'Testing';
	        	stageMspa.APTS_Incoterms_methods_Code__c = 'Testing';
	        	stageMspa.APTS_Payment_Terms_SPA__c = 'Testing';
	        }
	        APTS_LP_TestUtility.getSalesOffice();
	        APTS_LP_TestUtility.getMasterPicklistTableData();
 
	        APTS_LP_Local_Customer_Reference_Data__c lcrd = new APTS_LP_Local_Customer_Reference_Data__c();
	        lcrd.APTS_LP_SAP_Customer_ID__c = 'Testing';
	        lcrd.Name = 'Testing';
	        lcrd.APTS_LP_Account__c = acct.id;

	        insert lcrd;

	        Apttus_Config2__PriceList__c prcielst = APTS_LP_TestUtility.getPriceList(acct, 'Spain');
	        prcielst.Apttus_Config2__Active__c = true;
	        insert prcielst;

	        test.startTest();
	        insert acct;
	       APTS_CopyDataWrapper oCopyWrapper= APTS_DMMSPAHelper.repriceAndFinalize(listStageMSPALineItems);
	        test.stopTest();  
       }*/
}