src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>GUID__c</fullName>
        <externalId>true</externalId>
        <label>GUID</label>
        <length>9</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Primary_Address_Country__c</fullName>
        <description>This is hidden field to be used in the Account search filters and results!</description>
        <label>Primary Address: Country</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aland Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antarctica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia, Plurinational State of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia and Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Germany</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>

    <fields>
        <fullName>Root_Account_GUID__c</fullName>
        <label>Root Account GUID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
 <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Channel_Business_Review__c.object
<CustomObject>
    <description>R5 Channel Business Review is a custom object to review the Channels, Partner, ABB Authorized value provider &amp; Strategic / Key Partner  who will be partnering with ABB to do business.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R5 - Channel review to have a look-up relationship with the Account Object.</description>
        <inlineHelpText>The partner and business plan this review covers. If the scope is several branch offices, that need to be indicated in general comments below.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Channel_Business_Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Joint_Business_Plan__c</fullName>
        <description>R5-Channel review to have a look-up relationship with the Joint Business Plan Object.</description>
        <inlineHelpText>The partner business plan this review covers. If the scope is several branch offices, that need to be indicated in general comments below.</inlineHelpText>
        <label>Business Plan</label>
        <referenceTo>Joint_Business_Plan__c</referenceTo>
        <relationshipLabel>Channel Partner Business Reviews</relationshipLabel>
        <relationshipName>Channel_Reviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Primary_Address_Country__c</fullName>
        <description>R5 - Copies Primary Address from Account</description>
        <formula>TEXT( Account__r.Primary_Address_Country__c )</formula>
        <label>Primary Address Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Channel_Class__c</fullName>
        <description>R5 - Primary Channel Class from Channel Partner Business Plan</description>
        <formula>Joint_Business_Plan__r.Primary_Channel_Class__c</formula>
        <label>Primary Channel Class</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>R5 - Status</description>
        <inlineHelpText>Change status or send to approval when completed. Note that fields indicated with ! (exclamation mark) must first be completed.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Channel Partner Business Review</label>
    <nameField>
        <label>Business Review Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partner Business Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <!--validationRules>
        <fullName>CBR_Validate_Required_Fields</fullName>
        <active>false</active>
        <description>R5 - Validation rule to check all the checkbox fields need to be filled out</description>
        <errorConditionFormula>OR(Sales_Answer_1__c = FALSE, Actions_Answer_1__c= FALSE, Partner_Answer_1__c=FALSE,ISBLANK(Sales_Answer_2__c),ISBLANK(Actions_Answer_2__c))</errorConditionFormula>
        <errorMessage>Cannot save the changes. Please fill the required fields.</errorMessage>
    </validationRules-->
</CustomObject>

src/objects/Channel_Market_Coverage__c.object
<CustomObject>
    <description>R5 - Custom Object to define Channel Market Coverage</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>R5 - Master Detail Relationship to Account Standard Object</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Channel_Market_Coverages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <description>R5 Division</description>
        <inlineHelpText>Pick division(s) focused in this market scope (and connected business plan/review)</inlineHelpText>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>DM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PG</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <!--fields>
        <fullName>Focussed_Industry1__c</fullName>
        <description>R5 - New Focussed Industry value -Combination of Industry usage level1, level2 and level3</description>
        <inlineHelpText>Pick all the industries currently served and targeted in the upcoming 3 years. Pick only industries with sales focus, not the ones that are served reactively.</inlineHelpText>
        <label>Focussed Industry</label>
        <picklist>
            <picklistValues>
                <fullName>BLD - BLD.8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BLD - BLD.9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BLD - BLD.10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.1 - IND.1.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.1 - IND.1.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.7 - IND.7.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.7 - IND.7.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.7 - IND.7.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.10 - IND.10.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.10 - IND.10.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.10 - IND.10.4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.10 - IND.10.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.11 - IND.11.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.11 - IND.11.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.12 - IND.12.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.12 - IND.12.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.12 - IND.12.3</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields-->
    <fields>
        <fullName>Primary_Address_Country__c</fullName>
        <description>R5 - Copies Primary Address Country from Account .</description>
        <formula>TEXT( Account__r.Primary_Address_Country__c )</formula>
        <label>Primary Address Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Channel_Class__c</fullName>
        <description>R5-Picklist contains Primary Channel Class values</description>
        <inlineHelpText>Select the primary channel class for this market scope</inlineHelpText>
        <label>Channel Class</label>
        <picklist>
            <picklistValues>
                <fullName>Engineering, Procurement and Construction (EPC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distributor (DIS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installer (INST)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Original Equipment Manufacturer (OEM)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panel Builder (PBL)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Provider (SPRO)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System Integrator (SYIN)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Distributor (TDIS)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Channel Partner Market Scope</label>
    <nameField>
        <label>Market Scope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partner Market Scope</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <!--webLinks>
        <fullName>Change_Product_Line</fullName>
        <availability>online</availability>
        <description>R5 - Change the Product through PIS Tree</description>
        <displayType>button</displayType>
        <height>600</height>
        <linkType>page</linkType>
        <masterLabel>Change Product Line</masterLabel>
        <openType>sidebar</openType>
        <page>EditChannelMarketPIS</page>
        <protected>false</protected>
    </webLinks-->
</CustomObject>

src/objects/Joint_Business_Plan__c.object
<CustomObject>
    <description>R5 Joint Business Plan</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R5 Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Joint_Business_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Channel_Market_Coverage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R5 - Lookup to Channel Market Coverage</description>
        <inlineHelpText>Channel &quot;Market scope&quot; this business plan is related to</inlineHelpText>
        <label>Market Scope</label>
        <referenceTo>Channel_Market_Coverage__c</referenceTo>
        <relationshipLabel>Channel Partner Business Plans</relationshipLabel>
        <relationshipName>Joint_Business_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>End Date Field</description>
        <inlineHelpText>The date the plan ends to be effective, typically Dec31st of the year</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Address_Country__c</fullName>
        <description>R5 - Copies Primary Address Country from Account.</description>
        <formula>TEXT( Account__r.Primary_Address_Country__c )</formula>
        <label>Primary Address Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Channel_Class__c</fullName>
        <description>R5 - Primary Channel Class</description>
        <formula>TEXT(Channel_Market_Coverage__r.Primary_Channel_Class__c )</formula>
        <inlineHelpText>Presents the channel class defined in &quot;Market scope&quot; where possible update must be done.</inlineHelpText>
        <label>Channel Class</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Start Date Field</description>
        <inlineHelpText>The date the plan starts to be effective, typically Jan1st of the year</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>R5 - Status</description>
        <inlineHelpText>Turn active when content agreed with partner and all mandatory fields are filled. Alternatively send for approval. Change back to draft for updating content that is locked for editing for active plan.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Channel Partner Business Plan</label>
    <nameField>
        <label>Business Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partner Business Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>

 
 

	
   
    <fields>
        <fullName>Division__c</fullName>
        <formula>Product_Group__r.Division__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Division</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Test_ClsTriggerOpportunityInformation.cls
/**
 * ApexClass -  Test_ClsTriggerOpportunityInformation  
 * Release R5
 * @author  Vasanthi (Accenture)
 * @created 2016-04-08
 * @version 1.0
 * Description: 
  This class will cover the ClsTriggerOpportunityInformation
 * Created
 
  */
@isTest
private class Test_ClsTriggerOpportunityInformation  {

    static testMethod void Test_ClsTriggerOpportunityInformation  () {
        
        Test.startTest();
       
        ClsAccountUtil.isUpdate = FALSE;
        
        Account a = new Account(
            Name = 'test',
            BillingStreet = 'street', 
            BillingCity = 'city', 
            BillingCountry = 'Germany', GUID__c = '1234', Primary_Address_Country__c = 'Germany', Root_Account_GUID__c = '1234');
        insert a;
        
       Channel_Market_Coverage__c[] cmcList = new Channel_Market_Coverage__c[]{
            new Channel_Market_Coverage__c(Account__c = a.Id, Primary_Channel_Class__c='Engineering, Procurement and Construction (EPC)', Division__c = 'EP;PA;')
        };
        
        insert cmcList;
        
        Joint_Business_Plan__c[] jbpList = new Joint_Business_Plan__c[] {
            new Joint_Business_Plan__c (Account__c = a.Id, Channel_Market_Coverage__c = cmcList[0].id, 
                Start_Date__c = Date.today(), End_Date__c = Date.today().addDays(3), Status__c = 'Draft')
        };
        insert jbpList;
        
        ID MP = Schema.SObjectType.Channel_Business_Review__c.getRecordTypeInfosByName().get('Mid-Period Business Review Detail').getRecordTypeId();
        Channel_Business_Review__c[] CBRList = new Channel_Business_Review__c[] { 
            new Channel_Business_Review__c (Account__c = a.Id, Joint_Business_Plan__c = jbpList[0].Id, RecordtypeId = MP, Status__c = 'Draft')
        };
        insert CBRList ;
        
        
        Opportunity[] oppList = new Opportunity[] {
            new Opportunity (  Name = 'ES-Acciona, S.A-Test', AccountId = a.id, Sales_Pursuit_Progress__c = 'Opportunity is Captured', 
                StageName = 'Prospecting',  Customer_Buying_Path__c='Awareness', CloseDate = date.today().addDays(3), Industry_Usage__c = 'BLD.10.1'),
            
            new Opportunity (  Name = 'ES-Acciona, S.A-Test', AccountId = a.id, Sales_Pursuit_Progress__c = 'Opportunity is Captured', 
                StageName = 'Prospecting',  Customer_Buying_Path__c='Awareness', CloseDate = date.today().addDays(3), Industry_Usage__c = 'BLD.10.1'),
                
           new Opportunity (  Name = 'ES-Acciona, S.A-Test', AccountId =a.id, Sales_Pursuit_Progress__c = 'Opportunity is Captured', 
                StageName = 'Prospecting',  Customer_Buying_Path__c='Awareness', CloseDate = date.today().addDays(3), Industry_Usage__c = 'BLD.10.1'),
                
           new Opportunity (  Name = 'ES-Acciona, S.A-Test', AccountId = a.id, Sales_Pursuit_Progress__c = 'Opportunity is Captured', 
                StageName = 'Prospecting',  Customer_Buying_Path__c='Awareness', CloseDate = date.today().addDays(3), Industry_Usage__c = 'BLD.10.1')
            
            
        };
        
        insert oppList;
        Test.stopTest();
    }
    
    public static User createTestUser(Id profileId, String LastNameVal) {
        User u = new User( FirstName ='haobo', LastName = LastNameVal, Username = 'test123ABB1237'+LastNameVal+'@test123ABB1237.com', Alias = LastNameVal,
            Email = 'mtester1'+LastNameVal+'@company.com', CommunityNickname = LastNameVal,
            ProfileId = profileId, TimeZoneSidKey = 'America/Chicago', LocaleSidKey = 'en_US', EmailEncodingKey = 'UTF-8',
             LanguageLocaleKey = 'en_US', ManagerId = UserInfo.getUserId());
        return u;
    }
}