src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field is to e used to control access to the record, as part of the GIS Team Operations.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>

 <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <description>From Master Data Management Hierarchy</description>
        <inlineHelpText>Select the Business Unit that is responsible for resolving the case</inlineHelpText>
        <label>Business Unit</label>
        <picklist>
            <controllingField>Division__c</controllingField>
            <picklistValues>
                <fullName>DMDR - Drives and Controls</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>DMMG - Motors &amp; Generators</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>DMPC - Power Conversion</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>DMRO - Robotics</fullName>
                <color>#A845DC</color>
            </picklistValues>
            <picklistValues>
                <fullName>EPBP - Building Products</fullName>
                <color>#B6E32E</color>
            </picklistValues>
            <picklistValues>
                <fullName>EPBS - Breakers &amp; Switches</fullName>
                <color>#A53711</color>
            </picklistValues>
            <picklistValues>
                <fullName>EPCP - Control Products</fullName>
                <color>#66E9BD</color>
            </picklistValues>
            <picklistValues>
                <fullName>EPCW - Installation Products</fullName>
                <color>#641CCF</color>
            </picklistValues>
            <picklistValues>
                <fullName>EPLS - Electrification Solutions</fullName>
                <color>#419249</color>
            </picklistValues>
            <picklistValues>
                <fullName>EPMV - Medium Voltage Products</fullName>
                <color>#A845DC</color>
            </picklistValues>
            <picklistValues>
                <fullName>PACT - Control Technologies</fullName>
                <color>#2F5D85</color>
            </picklistValues>
            <picklistValues>
                <fullName>PAMA - Marine &amp; Ports</fullName>
                <color>#8F6429</color>
            </picklistValues>
            <picklistValues>
                <fullName>PAMP - Measurement &amp; Analytics</fullName>
                <color>#EFAE73</color>
            </picklistValues>
            <picklistValues>
                <fullName>PAOG - Oil, Gas &amp; Chemicals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAPG - Power Generation</fullName>
                <color>#B6E32E</color>
            </picklistValues>
            <picklistValues>
                <fullName>PAPI - Process Industries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PATU - Turbocharging</fullName>
                <color>#57F17C</color>
            </picklistValues>
            <picklistValues>
                <fullName>PGGA - Grid Automation</fullName>
                <color>#0B24BE</color>
            </picklistValues>
            <picklistValues>
                <fullName>PGGI - Grid Integration</fullName>
                <color>#641CCF</color>
            </picklistValues>
            <picklistValues>
                <fullName>PGGS - Grid Systems</fullName>
                <color>#66E9BD</color>
            </picklistValues>
            <picklistValues>
                <fullName>PGHV - High Voltage Products</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>PGTR - Transformers</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>ZCCO - Corporate</fullName>
                <color>#2F5D85</color>
            </picklistValues>
            <picklistValues>
                <fullName>ZCRE - Real Estate</fullName>
                <color>#AFCADF</color>
            </picklistValues>
            <picklistValues>
                <fullName>ZCVA - Various</fullName>
                <color>#8F6429</color>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CCRP_Status__c</fullName>
        <description>Integration Workstream : R5 : R-2190</description>
        <label>CCRP Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_2__c</fullName>
        <label>Case Type</label>
        <picklist>
            <controllingField>Category__c</controllingField>
            <picklistValues>
                <fullName>Homologation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Requirement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Factory Acceptance Test</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HelpDesk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complaints</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Details</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Originating_Country__c</fullName>
        <description>Use the related Account Country, if not sure.</description>
        <inlineHelpText>Select the country where the case was raised</inlineHelpText>
        <label>Originating Country</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aland Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antarctica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua And Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia, Plurinational State Of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonaire, Sint Eustatius And Saba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia And Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Germany</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Owner_Type__c</fullName>
        <formula>IF(ISBLANK(Owner:User.Id),&quot;Queue&quot;,&quot;User&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Owner Type</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Complaint</fullName>
        <active>true</active>
        <businessProcess>Services</businessProcess>
        <description>Please DO NOT directly create Case of this recordtype.Recordtype used to create Complaints to CCRP.</description>
        <label>Complaint</label>
    </recordTypes>
    <recordTypes>
        <fullName>Services</fullName>
        <active>true</active>
        <businessProcess>Services</businessProcess>
        <description>Record Type for Service Cases</description>
        <label>Services</label>
        
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_BU__c.object
<CustomObject>
    <description>R5 - User who has read and edit access to a case will be able to create a Case Business Unit Detail record related to that Case using the related list &quot;Case Business Unit Details&quot; on the Case page. User will be able to create multiple Case Business Unit detail record per case only if all those records are created for a unique BU Specific recordtype. If a user tries to create a Case Business Unit detail record for the same recordtype the system will display an error message.</description>
    <fields>
        <fullName>Case__c</fullName>
        <description>Master-Detail Relationship to case object</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Case</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Case Business Unit Specifics</label>
    <nameField>
        <displayFormat>CBU-{0000}</displayFormat>
        <label>Case BU Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Business Unit Specifics</pluralLabel>
    <recordTypes>
        <fullName>DMDR</fullName>
        <active>true</active>
        <label>DMDR</label>
    </recordTypes>
    <recordTypes>
        <fullName>DMMG</fullName>
        <active>true</active>
        <label>DMMG</label>
    </recordTypes>
    <recordTypes>
        <fullName>DMPC</fullName>
        <active>true</active>
        <label>DMPC</label>
    </recordTypes>
    <recordTypes>
        <fullName>EPBP</fullName>
        <active>true</active>
        <label>EPBP</label>
    </recordTypes>
    <recordTypes>
        <fullName>EPCP</fullName>
        <active>true</active>
        <label>EPCP</label>
    </recordTypes>
    <recordTypes>
        <fullName>EPMV</fullName>
        <active>true</active>
        <label>EPMV</label>
    </recordTypes>
    <recordTypes>
        <fullName>PACT</fullName>
        <active>true</active>
        <label>PACT</label>
    </recordTypes>
    <recordTypes>
        <fullName>PAMP</fullName>
        <active>true</active>
        <label>PAMP</label>
    </recordTypes>
    <recordTypes>
        <fullName>PAOG</fullName>
        <active>true</active>
        <label>PAOG</label>
    </recordTypes>
    <recordTypes>
        <fullName>PAPG</fullName>
        <active>false</active>
        <label>PAPG</label>
    </recordTypes>
    <recordTypes>
        <fullName>PAPI</fullName>
        <active>true</active>
        <label>PAPI</label>
    </recordTypes>
    <recordTypes>
        <fullName>PGGA</fullName>
        <active>true</active>
        <label>PGGA</label>
       
    </recordTypes>
    <recordTypes>
        <fullName>PGGI</fullName>
        <active>true</active>
        <label>PGGI</label>
        
    </recordTypes>
    <recordTypes>
        <fullName>PGGS</fullName>
        <active>true</active>
        <label>PGGS</label>
       
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CaseBUController_TEST.cls
@isTest
Public Class CaseBUController_TEST
{
    static testmethod void TestCaseBUController()
    {
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        
        User u = new User();
        u.Alias = 'email'; 
        u.Email='email@email.com';
        u.EmailEncodingKey='UTF-8';
        u.LastName='Testing'; 
        u.LanguageLocaleKey='en_US'; 
        u.LocaleSidKey='en_US';
        u.ProfileId = p.Id;
        u.TimeZoneSidKey='America/Los_Angeles';
        u.UserName='email@testcoverage.com';
        insert u;

        RecordType rt = [Select Id from RecordType where DeveloperName = 'Services'];
        Account acc = new Account(); 
        acc.Name = 'Test1';
        acc.BillingStreet = 'dajie';
        acc.BillingCity = 'berlin';
        acc.BillingState = 'Berlin';
        acc.BillingPostalCode = '20012';
        acc.BillingCountry = 'Germany';
        acc.rating='Hot';
        acc.industry='Manufacturing';
        acc.Phone='+41 123 123456';
        acc.Type='Prospect';
        acc.Active__C= true;
        Insert acc;
        
        Contact con = new Contact ();
        con.firstname ='Test';
        con.lastname='Contact1';
        con.email='test@test.com';
        con.phone='9988776600';
        con.accountid=acc.id;
        insert con;
        
        Case c2 = new Case();
        C2.subject = 'TestCase 1';
        C2.status ='Open';
        C2.type='Mechanical';
        C2.reason='Installation';
        C2.Business_unit__c ='EPCP - Control Products';
        C2.contactid=con.id;
        C2.RecordTypeId = rt.ID;
        C2.Originating_Country__c = 'Bangladesh';
        c2.Category_2__c ='Homologation';
        c2.CCRP_Status__c ='qw1';
        c2.Description = 'fhshfks';
        C2.SuppliedEmail='abc@abc.com';    
        C2.accountid=acc.id;
        c2.OwnerID =  u.id;

      Test.startTest();
        
        System.runAs(u){
        insert c2;
        CaseBUController caseBU = new CaseBUController();
        CheckCaseBusinessUnitDetailClass.checkCaseBU(C2.id);
       // SendSubstitutesToCCRPclass.sendSubstitutes(c2.id);
       // SendCaseToCCRPClass.sendtoCCRP(c2.id);
        
        
        system.debug('SAI::AccountId'+ c2.AccountId);       
        system.debug('SAI::ContactId'+ c2.ContactId);
        system.debug('SAI::Description'+ c2.Description);
        system.debug('SAI::Category_2__c'+ c2.Category_2__c.equalsIgnoreCase('Complaints'));
        system.debug('SAI::CCRP_Status__c'+ c2.CCRP_Status__c);
        system.debug('SAI::RecordtypeId'+ c2.RecordtypeId); 
        //system.debug('SAI::complaintRecTypeId'+ c2.rt);         
        system.debug('SAI::Owner_Type__c'+ c2.Owner_Type__c);
        system.debug('SAI::OwnerUd'+ c2.OwnerId );
        
        
        ApexPages.currentPage().getParameters().put('id', c2.id);
        ApexPages.currentPage().getParameters().put('object', 'Case_BU__c');
        ApexPages.currentPage().getParameters().put('sfdc_created__c', '1');
        ApexPages.currentPage().getParameters().put('Case__c', c2.CaseNumber);
        ApexPages.currentPage().getParameters().put('ID_Case__c', c2.id);
        ApexPages.currentPage().getParameters().put('retURL', c2.id);           

        PageReference pageRef = Page.CaseBU;
        pageRef= caseBU.redirect();

        Schema.Sobjecttype oGenericObj = Schema.getGlobalDescribe().get('case');
        sObject oGeneric = oGenericObj.newSObject();
        StaticFunctions.createLabelParameters(pageRef,oGeneric);
        

        Test.StopTest();
    }
    }
 
    
    static testmethod void TestCaseBUController1()
    {
        RecordType rt = [Select Id from RecordType where DeveloperName = 'Complaint'];

        Account acc = new Account(); 
        acc.Name = 'Test1';
        acc.BillingStreet = 'dajie';
        acc.BillingCity = 'berlin';
        acc.BillingState = 'Berlin';
        acc.BillingPostalCode = '20012';
        acc.BillingCountry = 'Germany';
        acc.rating='Hot';
        acc.industry='Manufacturing';
        acc.Phone='+41 123 123456';
        acc.Type='Prospect';
        acc.Active__C= true;
        Insert acc;
        
        Contact con = new Contact ();
        con.firstname ='Test';
        con.lastname='Contact1';
        con.email='test@test.com';
        con.phone='9988776600';
        con.accountid=acc.id;
        insert con;
        
        Case c2 = new Case();
        C2.subject = 'TestCase 1';
        C2.status ='Open';
        C2.type='Mechanical';
        C2.reason='Installation';
        C2.Business_unit__c ='DMMG - Motors & Generators';
        C2.contactid=con.id;
        C2.RecordTypeId =rt.ID;
        C2.Originating_Country__c = 'Bangladesh';
        C2.SuppliedEmail='abc@abc.com';    
        C2.accountid=acc.id;
        Test.startTest();
        insert c2;
        CaseBUController caseBU = new CaseBUController();
        CheckCaseBusinessUnitDetailClass.checkCaseBU(C2.id);
        ApexPages.currentPage().getParameters().put('id', c2.id);
        ApexPages.currentPage().getParameters().put('object', 'Case_BU__c');
        ApexPages.currentPage().getParameters().put('sfdc_created__c', '1');
        ApexPages.currentPage().getParameters().put('Case__c', c2.CaseNumber);
        ApexPages.currentPage().getParameters().put('ID_Case__c', c2.id);
        ApexPages.currentPage().getParameters().put('retURL', c2.id);           

        PageReference pageRef = Page.CaseBU;
        pageRef= caseBU.redirect();

        Schema.Sobjecttype oGenericObj = Schema.getGlobalDescribe().get('case');
        sObject oGeneric = oGenericObj.newSObject();
        StaticFunctions.createLabelParameters(pageRef,oGeneric);
        Test.StopTest();
    }
    static testmethod void TestCaseBUController3()
    {
        RecordType rt = [Select Id from RecordType where DeveloperName = 'Complaint'];

        Account acc = new Account(); 
        acc.Name = 'Test1';
        acc.BillingStreet = 'dajie';
        acc.BillingCity = 'berlin';
        acc.BillingState = 'Berlin';
        acc.BillingPostalCode = '20012';
        acc.BillingCountry = 'Germany';
        acc.rating='Hot';
        acc.industry='Manufacturing';
        acc.Phone='+41 123 123456';
        acc.Type='Prospect';
        acc.Active__C= true;
        Insert acc;
        
        Contact con = new Contact ();
        con.firstname ='Test';
        con.lastname='Contact1';
        con.email='test@test.com';
        con.phone='9988776600';
        con.accountid=acc.id;
        insert con;
        
        Case c2 = new Case();
        C2.subject = 'TestCase 1';
        C2.status ='Open';
        C2.type='Mechanical';
        C2.reason='Installation';
        C2.Business_unit__c ='DMDR - Drives and Controls';
        C2.contactid=con.id;
        C2.RecordTypeId =rt.ID;
        C2.Originating_Country__c = 'Bangladesh';
        C2.SuppliedEmail='abc@abc.com';    
        C2.accountid=acc.id;
        Test.startTest();
        insert c2;
        CaseBUController caseBU = new CaseBUController();
        CheckCaseBusinessUnitDetailClass.checkCaseBU(C2.id);
        ApexPages.currentPage().getParameters().put('id', c2.id);
        ApexPages.currentPage().getParameters().put('object', 'Case_BU__c');
        ApexPages.currentPage().getParameters().put('sfdc_created__c', '1');
        ApexPages.currentPage().getParameters().put('Case__c', c2.CaseNumber);
        ApexPages.currentPage().getParameters().put('ID_Case__c', c2.id);
        ApexPages.currentPage().getParameters().put('retURL', c2.id);           

        PageReference pageRef = Page.CaseBU;
        pageRef= caseBU.redirect();

        Schema.Sobjecttype oGenericObj = Schema.getGlobalDescribe().get('case');
        sObject oGeneric = oGenericObj.newSObject();
        StaticFunctions.createLabelParameters(pageRef,oGeneric);
        Test.StopTest();
    }
    static testmethod void TestCaseBUController4()
    {
        RecordType rt = [Select Id from RecordType where DeveloperName = 'Complaint'];

        Account acc = new Account(); 
        acc.Name = 'Test1';
        acc.BillingStreet = 'dajie';
        acc.BillingCity = 'berlin';
        acc.BillingState = 'Berlin';
        acc.BillingPostalCode = '20012';
        acc.BillingCountry = 'Germany';
        acc.rating='Hot';
        acc.industry='Manufacturing';
        acc.Phone='+41 123 123456';
        acc.Type='Prospect';
        acc.Active__C= true;
        Insert acc;
        
        Contact con = new Contact ();
        con.firstname ='Test';
        con.lastname='Contact1';
        con.email='test@test.com';
        con.phone='9988776600';
        con.accountid=acc.id;
        insert con;
        
        Case c2 = new Case();
        C2.subject = 'TestCase 1';
        C2.status ='Open';
        C2.type='Mechanical';
        C2.reason='Installation';
        C2.Business_unit__c ='DMPC - Power Conversion';
        C2.contactid=con.id;
        C2.RecordTypeId =rt.ID;
        C2.Originating_Country__c = 'Bangladesh';
        C2.SuppliedEmail='abc@abc.com';    
        C2.accountid=acc.id;
        Test.startTest();
        insert c2;
        CaseBUController caseBU = new CaseBUController();
        CheckCaseBusinessUnitDetailClass.checkCaseBU(C2.id);
        ApexPages.currentPage().getParameters().put('id', c2.id);
        ApexPages.currentPage().getParameters().put('object', 'Case_BU__c');
        ApexPages.currentPage().getParameters().put('sfdc_created__c', '1');
        ApexPages.currentPage().getParameters().put('Case__c', c2.CaseNumber);
        ApexPages.currentPage().getParameters().put('ID_Case__c', c2.id);
        ApexPages.currentPage().getParameters().put('retURL', c2.id);           

        PageReference pageRef = Page.CaseBU;
        pageRef= caseBU.redirect();

        Schema.Sobjecttype oGenericObj = Schema.getGlobalDescribe().get('case');
        sObject oGeneric = oGenericObj.newSObject();
        StaticFunctions.createLabelParameters(pageRef,oGeneric);
        Test.StopTest();
    }
    static testmethod void TestCaseBUController5()
    {
        RecordType rt = [Select Id from RecordType where DeveloperName = 'Complaint'];

        Account acc = new Account(); 
        acc.Name = 'Test1';
        acc.BillingStreet = 'dajie';
        acc.BillingCity = 'berlin';
        acc.BillingState = 'Berlin';
        acc.BillingPostalCode = '20012';
        acc.BillingCountry = 'Germany';
        acc.rating='Hot';
        acc.industry='Manufacturing';
        acc.Phone='+41 123 123456';
        acc.Type='Prospect';
        acc.Active__C= true;
        Insert acc;
        
        Contact con = new Contact ();
        con.firstname ='Test';
        con.lastname='Contact1';
        con.email='test@test.com';
        con.phone='9988776600';
        con.accountid=acc.id;
        insert con;
        
        Case c2 = new Case();
        C2.subject = 'TestCase 1';
        C2.status ='Open';
        C2.type='Mechanical';
        C2.reason='Installation';
        C2.Business_unit__c ='EPBP - Building Products';
        C2.contactid=con.id;
        C2.RecordTypeId =rt.ID;
        C2.Originating_Country__c = 'Bangladesh';
        C2.SuppliedEmail='abc@abc.com';    
        C2.accountid=acc.id;
        Test.startTest();
        insert c2;
        CaseBUController caseBU = new CaseBUController();
        CheckCaseBusinessUnitDetailClass.checkCaseBU(C2.id);
        ApexPages.currentPage().getParameters().put('id', c2.id);
        ApexPages.currentPage().getParameters().put('object', 'Case_BU__c');
        ApexPages.currentPage().getParameters().put('sfdc_created__c', '1');
        ApexPages.currentPage().getParameters().put('Case__c', c2.CaseNumber);
        ApexPages.currentPage().getParameters().put('ID_Case__c', c2.id);
        ApexPages.currentPage().getParameters().put('retURL', c2.id);           

        PageReference pageRef = Page.CaseBU;
        pageRef= caseBU.redirect();

        Schema.Sobjecttype oGenericObj = Schema.getGlobalDescribe().get('case');
        sObject oGeneric = oGenericObj.newSObject();
        StaticFunctions.createLabelParameters(pageRef,oGeneric);
        Test.StopTest();
    }
    static testmethod void TestCaseBUController6()
    {
        RecordType rt = [Select Id from RecordType where DeveloperName = 'Complaint'];

        Account acc = new Account(); 
        acc.Name = 'Test1';
        acc.BillingStreet = 'dajie';
        acc.BillingCity = 'berlin';
        acc.BillingState = 'Berlin';
        acc.BillingPostalCode = '20012';
        acc.BillingCountry = 'Germany';
        acc.rating='Hot';
        acc.industry='Manufacturing';
        acc.Phone='+41 123 123456';
        acc.Type='Prospect';
        acc.Active__C= true;
        Insert acc;
        
        Contact con = new Contact ();
        con.firstname ='Test';
        con.lastname='Contact1';
        con.email='test@test.com';
        con.phone='9988776600';
        con.accountid=acc.id;
        insert con;
        
        Case c2 = new Case();
        C2.subject = 'TestCase 1';
        C2.status ='Open';
        C2.type='Mechanical';
        C2.reason='Installation';
        C2.Business_unit__c ='EPCP - Control Products';
        C2.contactid=con.id;
        C2.RecordTypeId =rt.ID;
        C2.Originating_Country__c = 'Bangladesh';
        C2.SuppliedEmail='abc@abc.com';    
        C2.accountid=acc.id;
        Test.startTest();
        insert c2;
        CaseBUController caseBU = new CaseBUController();
        CheckCaseBusinessUnitDetailClass.checkCaseBU(C2.id);
        ApexPages.currentPage().getParameters().put('id', c2.id);
        ApexPages.currentPage().getParameters().put('object', 'Case_BU__c');
        ApexPages.currentPage().getParameters().put('sfdc_created__c', '1');
        ApexPages.currentPage().getParameters().put('Case__c', c2.CaseNumber);
        ApexPages.currentPage().getParameters().put('ID_Case__c', c2.id);
        ApexPages.currentPage().getParameters().put('retURL', c2.id);           

        PageReference pageRef = Page.CaseBU;
        pageRef= caseBU.redirect();

        Schema.Sobjecttype oGenericObj = Schema.getGlobalDescribe().get('case');
        sObject oGeneric = oGenericObj.newSObject();
        StaticFunctions.createLabelParameters(pageRef,oGeneric);
        Test.StopTest();
    }
    static testmethod void TestCaseBUController7()
    {
        RecordType rt = [Select Id from RecordType where DeveloperName = 'Complaint'];

        Account acc = new Account(); 
        acc.Name = 'Test1';
        acc.BillingStreet = 'dajie';
        acc.BillingCity = 'berlin';
        acc.BillingState = 'Berlin';
        acc.BillingPostalCode = '20012';
        acc.BillingCountry = 'Germany';
        acc.rating='Hot';
        acc.industry='Manufacturing';
        acc.Phone='+41 123 123456';
        acc.Type='Prospect';
        acc.Active__C= true;
        Insert acc;
        
        Contact con = new Contact ();
        con.firstname ='Test';
        con.lastname='Contact1';
        con.email='test@test.com';
        con.phone='9988776600';
        con.accountid=acc.id;
        insert con;
        
        Case c2 = new Case();
        C2.subject = 'TestCase 1';
        C2.status ='Open';
        C2.type='Mechanical';
        C2.reason='Installation';
        C2.Business_unit__c ='EPMV - Medium Voltage Products';
        C2.contactid=con.id;
        C2.RecordTypeId =rt.ID;
        C2.Originating_Country__c = 'Bangladesh';
        C2.SuppliedEmail='abc@abc.com';    
        C2.accountid=acc.id;
        Test.startTest();
        insert c2;
        CaseBUController caseBU = new CaseBUController();
        CheckCaseBusinessUnitDetailClass.checkCaseBU(C2.id);
        ApexPages.currentPage().getParameters().put('id', c2.id);
        ApexPages.currentPage().getParameters().put('object', 'Case_BU__c');
        ApexPages.currentPage().getParameters().put('sfdc_created__c', '1');
        ApexPages.currentPage().getParameters().put('Case__c', c2.CaseNumber);
        ApexPages.currentPage().getParameters().put('ID_Case__c', c2.id);
        ApexPages.currentPage().getParameters().put('retURL', c2.id);           

        PageReference pageRef = Page.CaseBU;
        pageRef= caseBU.redirect();

        Schema.Sobjecttype oGenericObj = Schema.getGlobalDescribe().get('case');
        sObject oGeneric = oGenericObj.newSObject();
        StaticFunctions.createLabelParameters(pageRef,oGeneric);
        Test.StopTest();
    }
    static testmethod void TestCaseBUController8()
    {
        RecordType rt = [Select Id from RecordType where DeveloperName = 'Complaint'];

        Account acc = new Account(); 
        acc.Name = 'Test1';
        acc.BillingStreet = 'dajie';
        acc.BillingCity = 'berlin';
        acc.BillingState = 'Berlin';
        acc.BillingPostalCode = '20012';
        acc.BillingCountry = 'Germany';
        acc.rating='Hot';
        acc.industry='Manufacturing';
        acc.Phone='+41 123 123456';
        acc.Type='Prospect';
        acc.Active__C= true;
        Insert acc;
        
        Contact con = new Contact ();
        con.firstname ='Test';
        con.lastname='Contact1';
        con.email='test@test.com';
        con.phone='9988776600';
        con.accountid=acc.id;
        insert con;
        
        Case c2 = new Case();
        C2.subject = 'TestCase 1';
        C2.status ='Open';
        C2.type='Mechanical';
        C2.reason='Installation';
        C2.Business_unit__c ='PACT - Control Technologies';
        C2.contactid=con.id;
        C2.RecordTypeId =rt.ID;
        C2.Originating_Country__c = 'Bangladesh';
        C2.SuppliedEmail='abc@abc.com';    
        C2.accountid=acc.id;
        Test.startTest();
        insert c2;
        CaseBUController caseBU = new CaseBUController();
        CheckCaseBusinessUnitDetailClass.checkCaseBU(C2.id);
        ApexPages.currentPage().getParameters().put('id', c2.id);
        ApexPages.currentPage().getParameters().put('object', 'Case_BU__c');
        ApexPages.currentPage().getParameters().put('sfdc_created__c', '1');
        ApexPages.currentPage().getParameters().put('Case__c', c2.CaseNumber);
        ApexPages.currentPage().getParameters().put('ID_Case__c', c2.id);
        ApexPages.currentPage().getParameters().put('retURL', c2.id);           

        PageReference pageRef = Page.CaseBU;
        pageRef= caseBU.redirect();

        Schema.Sobjecttype oGenericObj = Schema.getGlobalDescribe().get('case');
        sObject oGeneric = oGenericObj.newSObject();
        StaticFunctions.createLabelParameters(pageRef,oGeneric);
        Test.StopTest();
    }
    static testmethod void TestCaseBUController9()
    {
        RecordType rt = [Select Id from RecordType where DeveloperName = 'Complaint'];

        Account acc = new Account(); 
        acc.Name = 'Test1';
        acc.BillingStreet = 'dajie';
        acc.BillingCity = 'berlin';
        acc.BillingState = 'Berlin';
        acc.BillingPostalCode = '20012';
        acc.BillingCountry = 'Germany';
        acc.rating='Hot';
        acc.industry='Manufacturing';
        acc.Phone='+41 123 123456';
        acc.Type='Prospect';
        acc.Active__C= true;
        Insert acc;
        
        Contact con = new Contact ();
        con.firstname ='Test';
        con.lastname='Contact1';
        con.email='test@test.com';
        con.phone='9988776600';
        con.accountid=acc.id;
        insert con;
        
        Case c2 = new Case();
        C2.subject = 'TestCase 1';
        C2.status ='Open';
        C2.type='Mechanical';
        C2.reason='Installation';
        C2.Business_unit__c ='PAMP - Measurement & Analytics';
        C2.contactid=con.id;
        C2.RecordTypeId =rt.ID;
        C2.Originating_Country__c = 'Bangladesh';
        C2.SuppliedEmail='abc@abc.com';    
        C2.accountid=acc.id;
        Test.startTest();
        insert c2;
        CaseBUController caseBU = new CaseBUController();
        CheckCaseBusinessUnitDetailClass.checkCaseBU(C2.id);
        ApexPages.currentPage().getParameters().put('id', c2.id);
        ApexPages.currentPage().getParameters().put('object', 'Case_BU__c');
        ApexPages.currentPage().getParameters().put('sfdc_created__c', '1');
        ApexPages.currentPage().getParameters().put('Case__c', c2.CaseNumber);
        ApexPages.currentPage().getParameters().put('ID_Case__c', c2.id);
        ApexPages.currentPage().getParameters().put('retURL', c2.id);           

        PageReference pageRef = Page.CaseBU;
        pageRef= caseBU.redirect();

        Schema.Sobjecttype oGenericObj = Schema.getGlobalDescribe().get('case');
        sObject oGeneric = oGenericObj.newSObject();
        StaticFunctions.createLabelParameters(pageRef,oGeneric);
        Test.StopTest();
    }
    static testmethod void TestCaseBUController10()
    {
        RecordType rt = [Select Id from RecordType where DeveloperName = 'Complaint'];
        Account acc = new Account(); 
        acc.Name = 'Test1';
        acc.BillingStreet = 'dajie';
        acc.BillingCity = 'berlin';
        acc.BillingState = 'Berlin';
        acc.BillingPostalCode = '20012';
        acc.BillingCountry = 'Germany';
        acc.rating='Hot';
        acc.industry='Manufacturing';
        acc.Phone='+41 123 123456';
        acc.Type='Prospect';
        acc.Active__C= true;
        Insert acc;
        
        Contact con = new Contact ();
        con.firstname ='Test';
        con.lastname='Contact1';
        con.email='test@test.com';
        con.phone='9988776600';
        con.accountid=acc.id;
        insert con;

        Case c2 = new Case();
        C2.subject = 'TestCase 1';
        C2.status ='Open';
        C2.type='Mechanical';
        C2.reason='Installation';
        C2.Business_unit__c ='PAOG - Oil, Gas & Chemicals';
        C2.contactid=con.id;
        C2.RecordTypeId =rt.ID;
        C2.Originating_Country__c = 'Bangladesh';
        C2.SuppliedEmail='abc@abc.com';    
        C2.accountid=acc.id;
        Test.startTest();
        insert c2;
        CaseBUController caseBU = new CaseBUController();
        CheckCaseBusinessUnitDetailClass.checkCaseBU(C2.id);
        ApexPages.currentPage().getParameters().put('id', c2.id);
        ApexPages.currentPage().getParameters().put('object', 'Case_BU__c');
        ApexPages.currentPage().getParameters().put('sfdc_created__c', '1');
        ApexPages.currentPage().getParameters().put('Case__c', c2.CaseNumber);
        ApexPages.currentPage().getParameters().put('ID_Case__c', c2.id);
        ApexPages.currentPage().getParameters().put('retURL', c2.id);           

        PageReference pageRef = Page.CaseBU;
        pageRef= caseBU.redirect();

        Schema.Sobjecttype oGenericObj = Schema.getGlobalDescribe().get('case');
        sObject oGeneric = oGenericObj.newSObject();
        StaticFunctions.createLabelParameters(pageRef,oGeneric);
        Test.StopTest();
    }
    static testmethod void TestCaseBUController11()
    {
        RecordType rt = [Select Id from RecordType where DeveloperName = 'Complaint'];
        Account acc = new Account(); 
        acc.Name = 'Test1';
        acc.BillingStreet = 'dajie';
        acc.BillingCity = 'berlin';
        acc.BillingState = 'Berlin';
        acc.BillingPostalCode = '20012';
        acc.BillingCountry = 'Germany';
        acc.rating='Hot';
        acc.industry='Manufacturing';
        acc.Phone='+41 123 123456';
        acc.Type='Prospect';
        acc.Active__C= true;
        Insert acc;
        
        Contact con = new Contact ();
        con.firstname ='Test';
        con.lastname='Contact1';
        con.email='test@test.com';
        con.phone='9988776600';
        con.accountid=acc.id;
        insert con;

        Case c2 = new Case();
        C2.subject = 'TestCase 1';
        C2.status ='Open';
        C2.type='Mechanical';
        C2.reason='Installation';
        C2.Business_unit__c ='PAPG - Power Generation';
        C2.contactid=con.id;
        C2.RecordTypeId =rt.ID;
        C2.Originating_Country__c = 'Bangladesh';
        C2.SuppliedEmail='abc@abc.com';    
        C2.accountid=acc.id;
        Test.startTest();
        insert c2;
        CaseBUController caseBU = new CaseBUController();
        CheckCaseBusinessUnitDetailClass.checkCaseBU(C2.id);
        ApexPages.currentPage().getParameters().put('id', c2.id);
        ApexPages.currentPage().getParameters().put('object', 'Case_BU__c');
        ApexPages.currentPage().getParameters().put('sfdc_created__c', '1');
        ApexPages.currentPage().getParameters().put('Case__c', c2.CaseNumber);
        ApexPages.currentPage().getParameters().put('ID_Case__c', c2.id);
        ApexPages.currentPage().getParameters().put('retURL', c2.id);           

        PageReference pageRef = Page.CaseBU;
        pageRef= caseBU.redirect();

        Schema.Sobjecttype oGenericObj = Schema.getGlobalDescribe().get('case');
        sObject oGeneric = oGenericObj.newSObject();
        StaticFunctions.createLabelParameters(pageRef,oGeneric);
        Test.StopTest();
    }
    static testmethod void TestCaseBUController12()
    {
        RecordType rt = [Select Id from RecordType where DeveloperName = 'Complaint'];
        Account acc = new Account(); 
        acc.Name = 'Test1';
        acc.BillingStreet = 'dajie';
        acc.BillingCity = 'berlin';
        acc.BillingState = 'Berlin';
        acc.BillingPostalCode = '20012';
        acc.BillingCountry = 'Germany';
        acc.rating='Hot';
        acc.industry='Manufacturing';
        acc.Phone='+41 123 123456';
        acc.Type='Prospect';
        acc.Active__C= true;
        Insert acc;
        
        Contact con = new Contact ();
        con.firstname ='Test';
        con.lastname='Contact1';
        con.email='test@test.com';
        con.phone='9988776600';
        con.accountid=acc.id;
        insert con;

        Case c2 = new Case();
        C2.subject = 'TestCase 1';
        C2.status ='Open';
        C2.type='Mechanical';
        C2.reason='Installation';
        C2.Business_unit__c ='PAPI - Process Industries';
        C2.contactid=con.id;
        C2.RecordTypeId =rt.ID;
        C2.Originating_Country__c = 'Bangladesh';
        C2.SuppliedEmail='abc@abc.com';    
        C2.accountid=acc.id;
        Test.startTest();
        insert c2;
        CaseBUController caseBU = new CaseBUController();
        CheckCaseBusinessUnitDetailClass.checkCaseBU(C2.id);
        ApexPages.currentPage().getParameters().put('id', c2.id);
        ApexPages.currentPage().getParameters().put('object', 'Case_BU__c');
        ApexPages.currentPage().getParameters().put('sfdc_created__c', '1');
        ApexPages.currentPage().getParameters().put('Case__c', c2.CaseNumber);
        ApexPages.currentPage().getParameters().put('ID_Case__c', c2.id);
        ApexPages.currentPage().getParameters().put('retURL', c2.id);           

        PageReference pageRef = Page.CaseBU;
        pageRef= caseBU.redirect();

        Schema.Sobjecttype oGenericObj = Schema.getGlobalDescribe().get('case');
        sObject oGeneric = oGenericObj.newSObject();
        StaticFunctions.createLabelParameters(pageRef,oGeneric);
        Test.StopTest();
    }
        static testmethod void TestCaseBUController13()
    {
        RecordType rt = [Select Id from RecordType where DeveloperName = 'Complaint'];
        Account acc = new Account(); 
        acc.Name = 'Test1';
        acc.BillingStreet = 'dajie';
        acc.BillingCity = 'berlin';
        acc.BillingState = 'Berlin';
        acc.BillingPostalCode = '20012';
        acc.BillingCountry = 'Germany';
        acc.rating='Hot';
        acc.industry='Manufacturing';
        acc.Phone='+41 123 123456';
        acc.Type='Prospect';
        acc.Active__C= true;
        Insert acc;
        
        Contact con = new Contact ();
        con.firstname ='Test';
        con.lastname='Contact1';
        con.email='test@test.com';
        con.phone='9988776600';
        con.accountid=acc.id;
        insert con;

        Case c2 = new Case();
        C2.subject = 'TestCase 1';
        C2.status ='Open';
        C2.type='Mechanical';
        C2.reason='Installation';
        C2.Business_unit__c ='PGGA - Grid Automation';
        C2.contactid=con.id;
        C2.RecordTypeId =rt.ID;
        C2.Originating_Country__c = 'Bangladesh';
        C2.SuppliedEmail='abc@abc.com';    
        C2.accountid=acc.id;
        Test.startTest();
        insert c2;
        CaseBUController caseBU = new CaseBUController();
        CheckCaseBusinessUnitDetailClass.checkCaseBU(C2.id);
        ApexPages.currentPage().getParameters().put('id', c2.id);
        ApexPages.currentPage().getParameters().put('object', 'Case_BU__c');
        ApexPages.currentPage().getParameters().put('sfdc_created__c', '1');
        ApexPages.currentPage().getParameters().put('Case__c', c2.CaseNumber);
        ApexPages.currentPage().getParameters().put('ID_Case__c', c2.id);
        ApexPages.currentPage().getParameters().put('retURL', c2.id);           

        PageReference pageRef = Page.CaseBU;
        pageRef= caseBU.redirect();

        Schema.Sobjecttype oGenericObj = Schema.getGlobalDescribe().get('case');
        sObject oGeneric = oGenericObj.newSObject();
        StaticFunctions.createLabelParameters(pageRef,oGeneric);
        Test.StopTest();
    }
    static testmethod void TestCaseBUController14()
    {
        RecordType rt = [Select Id from RecordType where DeveloperName = 'Complaint'];
        Account acc = new Account(); 
        acc.Name = 'Test1';
        acc.BillingStreet = 'dajie';
        acc.BillingCity = 'berlin';
        acc.BillingState = 'Berlin';
        acc.BillingPostalCode = '20012';
        acc.BillingCountry = 'Germany';
        acc.rating='Hot';
        acc.industry='Manufacturing';
        acc.Phone='+41 123 123456';
        acc.Type='Prospect';
        acc.Active__C= true;
        Insert acc;
        
        Contact con = new Contact ();
        con.firstname ='Test';
        con.lastname='Contact1';
        con.email='test@test.com';
        con.phone='9988776600';
        con.accountid=acc.id;
        insert con;

        Case c2 = new Case();
        C2.subject = 'TestCase 1';
        C2.status ='Open';
        C2.type='Mechanical';
        C2.reason='Installation';
        C2.Business_unit__c ='PGGI - Grid Integration';
        C2.contactid=con.id;
        C2.RecordTypeId =rt.ID;
        C2.Originating_Country__c = 'Bangladesh';
        C2.SuppliedEmail='abc@abc.com';    
        C2.accountid=acc.id;
        Test.startTest();
        insert c2;
        CaseBUController caseBU = new CaseBUController();
        CheckCaseBusinessUnitDetailClass.checkCaseBU(C2.id);
        ApexPages.currentPage().getParameters().put('id', c2.id);
        ApexPages.currentPage().getParameters().put('object', 'Case_BU__c');
        ApexPages.currentPage().getParameters().put('sfdc_created__c', '1');
        ApexPages.currentPage().getParameters().put('Case__c', c2.CaseNumber);
        ApexPages.currentPage().getParameters().put('ID_Case__c', c2.id);
        ApexPages.currentPage().getParameters().put('retURL', c2.id);           

        PageReference pageRef = Page.CaseBU;
        pageRef= caseBU.redirect();

        Schema.Sobjecttype oGenericObj = Schema.getGlobalDescribe().get('case');
        sObject oGeneric = oGenericObj.newSObject();
        StaticFunctions.createLabelParameters(pageRef,oGeneric);
        Test.StopTest();
    }
        static testmethod void TestCaseBUController15()
    {
        RecordType rt = [Select Id from RecordType where DeveloperName = 'Complaint'];
        Account acc = new Account(); 
        acc.Name = 'Test1';
        acc.BillingStreet = 'dajie';
        acc.BillingCity = 'berlin';
        acc.BillingState = 'Berlin';
        acc.BillingPostalCode = '20012';
        acc.BillingCountry = 'Germany';
        acc.rating='Hot';
        acc.industry='Manufacturing';
        acc.Phone='+41 123 123456';
        acc.Type='Prospect';
        acc.Active__C= true;
        Insert acc;
        
        Contact con = new Contact ();
        con.firstname ='Test';
        con.lastname='Contact1';
        con.email='test@test.com';
        con.phone='9988776600';
        con.accountid=acc.id;
        insert con;

        Case c2 = new Case();
        C2.subject = 'TestCase 1';
        C2.status ='Open';
        C2.type='Mechanical';
        C2.reason='Installation';
        C2.Business_unit__c ='PGGS - Grid Systems';
        C2.contactid=con.id;
        C2.RecordTypeId =rt.ID;
        C2.Originating_Country__c = 'Bangladesh';
        C2.SuppliedEmail='abc@abc.com';    
        C2.accountid=acc.id;
        Test.startTest();
        insert c2;
        CaseBUController caseBU = new CaseBUController();
        CheckCaseBusinessUnitDetailClass.checkCaseBU(C2.id);
        ApexPages.currentPage().getParameters().put('id', c2.id);
        ApexPages.currentPage().getParameters().put('object', 'Case_BU__c');
        ApexPages.currentPage().getParameters().put('sfdc_created__c', '1');
        ApexPages.currentPage().getParameters().put('Case__c', c2.CaseNumber);
        ApexPages.currentPage().getParameters().put('ID_Case__c', c2.id);
        ApexPages.currentPage().getParameters().put('retURL', c2.id);           

        PageReference pageRef = Page.CaseBU;
        pageRef= caseBU.redirect();

        Schema.Sobjecttype oGenericObj = Schema.getGlobalDescribe().get('case');
        sObject oGeneric = oGenericObj.newSObject();
        StaticFunctions.createLabelParameters(pageRef,oGeneric);
        Test.StopTest();
    }

}