src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Line__c</fullName>
        <description>R5 Business Line</description>
        <label>Business Line</label>
        <length>100</length>
        <type>Text</type>
    </fields>

 <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
<fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Email_Opt_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Updated for User Story R-2314 in ABB DOC:
https://abb--doc.cs18.my.salesforce.com/a0E1100000HuT09</description>
        <inlineHelpText>Do not send e-mail to this contact.</inlineHelpText>
        <label>Email Opt Out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Preferred_Contact_Method__c</fullName>
        <label>Preferred Contact Method</label>
        <picklist>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fax</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Do Not Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>

 
 <fields>
        <fullName>ABB_Domain__c</fullName>
        <description>R4.1 - New picklist field created for &quot;Business line&quot;.
Picklist containing ABB Domain values</description>
        <inlineHelpText>Business lines are intended for global reporting on a lower granularity than Business Units. They are stable data elements defining a certain offering scope with a product, system and service responsibility within a certain Business Unit.</inlineHelpText>
        <label>Business Line BU</label>
        <picklist>
            <picklistValues>
                <fullName>DMDR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMRO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PACT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAOG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAPG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGGA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
 

    <fields>
        <fullName>Actual_Bid_Submission_Date_Comm__c</fullName>
        <description>Contains the date when the Commercial bid was submitted.</description>
        <label>Actual Bid Submission Date (Comm.)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Actual_Bid_Submission_Date_Tech__c</fullName>
        <description>Contains the date when the technical bid was submitted.</description>
        <label>Actual Bid Submission Date (Tech.)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <description>R4.1 - New dependent picklist field created for &quot;BU&quot;.
Picklist containing active Applications relating to specific Product Groups</description>
        <inlineHelpText>ABB classification of application based on the main process activity of the delivered product, service, solution. The selectable options are product group specific</inlineHelpText>
        <label>Application</label>
        <picklist>
            <controllingField>BU__c</controllingField>
            <picklistValues>
                <fullName>AP.301</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.302</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.303</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.304</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.305</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.306</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.307</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.308</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.309</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.310</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.311</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.313</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.314</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.315</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.316</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.317</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.318</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.319</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.320</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.321</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.322</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.323</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.324</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.325</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.326</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.327</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.328</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.329</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.330</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP.331</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BU__c</fullName>
        <description>R4.1 - New picklist field created to replace &quot;Application&quot;.
Picklist containing active Applications relating to specific Product Groups</description>
        <inlineHelpText>ABB classification of application based on the main process activity of the delivered product, service, solution. The selectable options are product group specific</inlineHelpText>
        <label>Application BU</label>
        <picklist>
            <picklistValues>
                <fullName>DMDR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMPC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMRO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PATU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGGA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGGI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGGS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All other BU&apos;s</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
	
    <fields>
        <fullName>Business_Unit__c</fullName>
        <formula>Product_Group__r.Business_Unit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
   
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <formula>Product_Group__r.Division__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Division</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Value__c</fullName>
        <description>Holds the overall Opportunity Value of an opportunity</description>
        <label>Opportunity Value</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
   <fields>
        <fullName>Product_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to PG / BU / Div, filtered on RecType &quot;Product Group&quot;</description>
        <inlineHelpText>This field will be auto populated by the offering flagged as Primary Product Group. If you haven’t selected an offering yet, please add it. If you don’t know which product/service will be offered, but you know the Product Group, you can enter it directly.</inlineHelpText>
        <label>Product Group</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product_Group__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Product Group</value>
            </filterItems>
            <filterItems>
                <field>Product_Group__c.Data_Load_Year__c</field>
                <operation>notEqual</operation>
                <value>2015</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product_Group__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requested_Bid_Submission_Date_Comm__c</fullName>
        <description>Requested date when a commercial bid should be submitted by.</description>
        <label>Requested Bid Submission Date (Comm.)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Requested_Bid_Submission_Date_Tech__c</fullName>
        <description>Requested date when a technical bid should be submitted by.</description>
        <label>Requested Bid Submission Date (Tech.)</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Division_DIV__c</fullName>
        <description>The field Division is added to increase the ability to identify the area the user is related to / working in.</description>
        <label>Division (DIV)</label>
        <picklist>
            <picklistValues>
                <fullName>DM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PG</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/SetCreateQuoteRecordtypeController_TEST.cls
/**
*  This test class used to SetCreateQuoteRecordtypeController.
*
@author Rajesh Kaliyaperumal    
@created 2015-09-7
@version 1.0  
* 
*/
@isTest
private class SetCreateQuoteRecordtypeController_TEST {
    public static Account createTestAccount() {
        Account acc = new Account();    
        acc.Name = 'Test1';
        acc.BillingStreet = 'dajie';
        acc.BillingCity = 'berlin';
        acc.BillingState = 'Berlin';
        acc.BillingPostalCode = '20012';
        acc.BillingCountry = 'Germany';
        return acc;
    }
     public static User createTestUsers() {
        User u = new User();
        u.FirstName ='haobo';
        u.LastName = 'song';
        u.Username = 'tv@test123.com.prod';
        u.Alias = 'mtst';
        u.Email = 'mtester@company.com';
        u.CommunityNickname = u.Alias;
        u.ProfileId = [Select Id from Profile Where Name = 'Systemadministrator' OR Name = 'System Administrator' limit 1].Id;
        u.TimeZoneSidKey = 'America/Chicago';
        u.LocaleSidKey = 'en_US';
        u.EmailEncodingKey = 'UTF-8';
        u.LanguageLocaleKey = 'en_US';
        u.ManagerId = UserInfo.getUserId();
        u.Division_DIV__c = 'DM';
        return u;
    }
    public static User createTestUsers2() {
        User u = new User();
        u.FirstName ='haobo';
        u.LastName = 'song';
        u.Username = 'tv@test1234.com.prod';
        u.Alias = 'mtste';
        u.Email = 'mtester@company.com';
        u.CommunityNickname = u.Alias;
        u.ProfileId = [Select Id from Profile Where Name = 'Systemadministrator' OR Name = 'System Administrator' limit 1].Id;
        u.TimeZoneSidKey = 'America/Chicago';
        u.LocaleSidKey = 'en_US';
        u.EmailEncodingKey = 'UTF-8';
        u.LanguageLocaleKey = 'en_US';
        u.ManagerId = UserInfo.getUserId();
        u.Division_DIV__c = 'PL';
        return u;
    }
   
    public static Contact createTestContact() {
        account acc = createTestAccount();
        acc.Name='Test111';
        acc.BillingStreet = 'dajie123';
        acc.BillingCity = 'berlin123';
        acc.BillingState = 'Berlin';
        acc.BillingPostalCode = '200123';
        insert acc;
        Contact con = ClsTestHelp.createTestContacts();
        con.LastName = 'testContact';
        con.AccountId = acc.Id;
        con.Email_Opt_Out__c = false;
        con.Preferred_Contact_Method__c = 'Email';
        return con;
    }
    public static Product_Group__c createTestProductgroupFT() {
        Product_Group__c pg = new Product_Group__c();
        pg.Business_Unit__c = 'tdsd';
        pg.Name = '13333';
        pg.Opportunity_Default_Type__c = 'Fast Track';
        pg.Opportunity_Threshold__c = 100;
        pg.Division__c = 'DM';        
        return pg;
    }
    public static LBU_Code__c createTestLBUCode() {
        LBU_Code__c lbu = new LBU_Code__c();
        lbu.Name = 'test';
        lbu.BU__c = 'test';
        lbu.Division__c = 'DM';       
        return lbu;
    }
    static testMethod void SetCreateQuoteRecordtypeController1() {      
        Map<String, Schema.RecordTypeInfo> OPPORTUNITY_RECORD_TYPES = Schema.SObjectType.Opportunity.getRecordTypeInfosByName();
        String OPP_FASTTRACK_RECORD_TYPE_ID = OPPORTUNITY_RECORD_TYPES.get(System.label.Opportunity_RecordType_FastTrack).getRecordTypeId();
        
        Account acc = createTestAccount();
        acc.Name='Test11122';
        acc.BillingStreet = 'dajie23';
        acc.BillingCity = 'berlin23';
        acc.BillingState = 'Berlin';
        acc.BillingPostalCode = '2002312';
        insert acc;
        
        Account acc22 = createTestAccount();
        acc22.Name='Test11112';
        acc22.BillingStreet = 'dajie12312';
        acc22.BillingCity = 'berlin12312';
        acc22.BillingState = 'Berlin';
        acc22.BillingPostalCode = '20012312';
        insert acc22;
        Contact con1 = ClsTestHelp.createTestContacts();
        con1.LastName = 'testContact12';
        con1.AccountId = acc22.Id;
        con1.Email_Opt_Out__c = false;
        con1.Preferred_Contact_Method__c = 'Email';
        insert con1;
        
        Product_Group__c pg = createTestProductgroupFT();        
        insert pg;
        
        LBU_Code__c lbu = createTestLBUCode();       
        insert lbu;
        
        Opportunity oppy = new Opportunity();
        oppy.AccountId = acc.Id;
        oppy.Name = 'TestOpportunity';
        oppy.StageName = 'Negotiation';
        oppy.CloseDate = system.today();
        oppy.Product_Group__c = pg.Id;
        oppy.Opportunity_Value__c = 10000;
        oppy.Actual_Bid_Submission_Date_Comm__c = system.today();
        oppy.Actual_Bid_Submission_Date_Tech__c = system.today();
        oppy.Requested_Bid_Submission_Date_Comm__c = system.today();
        oppy.Requested_Bid_Submission_Date_Tech__c = system.today();
        oppy.BU__c ='DMDR';
        oppy.Application__c='AP.301 - Automatic Gate, Beam, Barrier or Door';
        oppy.Description__c='Test Description';
        oppy.ABB_Domain__c='DMDR';
        oppy.Business_Line__c='BL.401 - Packaging';
        oppy.Channel_Class_Level1__c='ABBINT - Internal ABB Sales';
        oppy.Channel_Class_Level2__c='ALCEN - ABB Logistic Centre';
        oppy.ABB_Industry_Usage_Level1__c='BLD - Building';
        oppy.ABB_Industry_Usage_Level2__c='BLD.9 - Commercial & institutional Buildings';
        oppy.ABB_Industry_Usage_Level3__c='BLD.9.1 - HVAC (Commercial Buildings)';
        oppy.Local_Business_Unit__c = lbu.id;
        oppy.Local_Product_Group__c = pg.id;
        oppy.Primary_Contact__c = con1.Id; 
        insert oppy;
        
        //ApexPages.StandardController sc = new ApexPages.StandardController(oppy);
        //OpportunitysetRecordtypeController  objopp = new OpportunitysetRecordtypeController(sc);
        //objopp.changeRecordtype(); 
        
        Apttus_Proposal__Proposal__c objproposal = new Apttus_Proposal__Proposal__c();
        ApexPages.StandardController sc1 = new ApexPages.StandardController(objproposal);      
       
        ApexPages.currentPage().getParameters().put('opportunityNumber','OPP-1233');
        CanvasController objcanvas = new CanvasController(sc1);
        objcanvas.getcParameters();
    }
    
    static testMethod void SetCreateQuoteRecordtypeController2() {      
        Map<String, Schema.RecordTypeInfo> OPPORTUNITY_RECORD_TYPES = Schema.SObjectType.Opportunity.getRecordTypeInfosByName();
        String OPP_FASTTRACK_RECORD_TYPE_ID = OPPORTUNITY_RECORD_TYPES.get(System.label.Opportunity_RecordType_FastTrack).getRecordTypeId();
        
        Account acc = createTestAccount();
        acc.Name='Test111234121';
        acc.BillingStreet = 'dajie2323';
        acc.BillingCity = 'berlin22343';
        acc.BillingState = 'Berlin';
        acc.BillingPostalCode = '200232341212';
        insert acc;
        
        Contact con = createTestContact();   
        con.LastName='Test11341';   
        insert con;
        
        Product_Group__c pg = createTestProductgroupFT();        
        insert pg;
        
        LBU_Code__c lbu = createTestLBUCode(); 
        lbu.Name='Test111';         
        insert lbu;
        
        User u = createTestUsers();
        insert u;
        User u2 = createTestUsers2();
        insert u2;
        
        Opportunity oppy = new Opportunity();
        oppy.AccountId = acc.Id;
        oppy.Name = 'TestOpportunity123';
        oppy.StageName = 'Negotiation';
        oppy.CloseDate = system.today();
        oppy.Product_Group__c = pg.Id;
        oppy.Opportunity_Value__c = 10000;
        oppy.Actual_Bid_Submission_Date_Comm__c = system.today();
        oppy.Actual_Bid_Submission_Date_Tech__c = system.today();
        oppy.Requested_Bid_Submission_Date_Comm__c = system.today();
        oppy.Requested_Bid_Submission_Date_Tech__c = system.today();
        oppy.BU__c ='DMDR';
        oppy.Application__c='AP.301 - Automatic Gate, Beam, Barrier or Door';
        oppy.Description__c='Test Description';
        oppy.ABB_Domain__c='DMDR';
        oppy.Business_Line__c='BL.401 - Packaging';
        oppy.Channel_Class_Level1__c='ABBINT - Internal ABB Sales';
        oppy.Channel_Class_Level2__c='ALCEN - ABB Logistic Centre';
        oppy.ABB_Industry_Usage_Level1__c='BLD - Building';
        oppy.ABB_Industry_Usage_Level2__c='BLD.9 - Commercial & institutional Buildings';
        oppy.ABB_Industry_Usage_Level3__c='BLD.9.1 - HVAC (Commercial Buildings)';
        oppy.Local_Business_Unit__c = lbu.id;
        oppy.Local_Product_Group__c = pg.id;
        oppy.Primary_Contact__c = con.Id; 
        insert oppy;
        
        Apttus_Proposal__Proposal__c objproposal = new Apttus_Proposal__Proposal__c();
        ApexPages.StandardController sc = new ApexPages.StandardController(objproposal);
        
        ApexPages.currentPage().getParameters().put('quotationNumber','234324');
        ApexPages.currentPage().getParameters().put('opportunityNumber','OPP-1233');
        CanvasController objcanvas = new CanvasController(sc);
        objcanvas.getcParameters();
        
        System.runAs(u) {
            ApexPages.currentPage().getParameters().put('id',acc.id);
            SetCreateQuoteRecordtypeController objQuote = new SetCreateQuoteRecordtypeController();
            objQuote.redirect();
        }
        System.runAs(u) {
            ApexPages.currentPage().getParameters().put('id',oppy.id);
            SetCreateQuoteRecordtypeController objQuote = new SetCreateQuoteRecordtypeController();
            objQuote.redirect();
        }
        System.runAs(u2) {
            ApexPages.currentPage().getParameters().put('id',acc.id);
            SetCreateQuoteRecordtypeController objQuote = new SetCreateQuoteRecordtypeController();
            objQuote.redirect();
        }
        System.runAs(u2) {
            ApexPages.currentPage().getParameters().put('id',oppy.id);
            SetCreateQuoteRecordtypeController objQuote = new SetCreateQuoteRecordtypeController();
            objQuote.redirect();
        }
        
    }
    static testMethod void canvascontroller() {      
        Apttus_Proposal__Proposal__c objproposal = new Apttus_Proposal__Proposal__c();
        ApexPages.StandardController sc = new ApexPages.StandardController(objproposal);
        CanvasController objcanvas = new CanvasController(sc);
        objcanvas.getcParameters();
    }
}