src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>GUID__c</fullName>
        <externalId>true</externalId>
        <label>GUID</label>
        <length>9</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>

 <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/APTS_LP_Local_Customer_Reference_Data__c.object
<CustomObject>
    <description>Object to hold the reference data related to customer (account). (ABB-LP)</description>
    <fields>
        <fullName>APTS_Country__c</fullName>
        <description>Field to capture country for the LSO data.</description>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>ES</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>APTS_External_ID__c</fullName>
        <description>External Id to match the unique set. Value of this field will be SAP ID + Sales organisation + Distribution Channel.</description>
        <externalId>true</externalId>
        <label>APTS External ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_LP_Account_GUID__c</fullName>
        <formula>HYPERLINK(&quot;/&quot;+ APTS_LP_Account__r.Id , APTS_LP_Account__r.GUID__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account GUID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_LP_Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <picklist>
            <picklistValues>
                <fullName>BT</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>DT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>APTS_LP_Incoterms__c</fullName>
        <label>Incoterms</label>
        <picklist>
            <picklistValues>
                <fullName>CFR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DDP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DAF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DDU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DEQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FOB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZFE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EXW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZVR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>APTS_LP_Local_Channel__c</fullName>
        <label>Local Channel</label>
        <picklist>
            <picklistValues>
                <fullName>P1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P6</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>APTS_LP_SAP_Customer_ID__c</fullName>
        <description>Placeholder field to hold the value of customer ID fetched from SAP.</description>
        <label>SAP Customer ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_LP_Sales_Organisation__c</fullName>
        <label>Sales Organisation</label>
        <picklist>
            <picklistValues>
                <fullName>ABB</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>APTS_Payment_Terms__c</fullName>
        <description>Field to capture payment terms associated with Apttus LSO object record.</description>
        <label>Payment Terms</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_SAP_Division__c</fullName>
        <description>Field to capture SAP Division.</description>
        <label>SAP Division</label>
        <picklist>
            <picklistValues>
                <fullName>ZZ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Local Operational Data</label>
    <nameField>
        <displayFormat>LCRD-{00000}</displayFormat>
        <label>Local Operational Data Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Local Operational Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/APTS_Master_Picklist_Table__c.object
<CustomObject>
    <description>Object to hold locale wise description for codes (used for incoterm, payment term etc.) used in SAP</description>
    <fields>
        <fullName>APTS_Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Code_Used_For__c</fullName>
        <description>Picklist field to determine that code in the record is being used for what.</description>
        <label>Code Used For</label>
        <picklist>
            <picklistValues>
                <fullName>Country</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incoterm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Channel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distribution Channel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SAP Division</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SAP Sales Organization</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>APTS_Code__c</fullName>
        <description>Code that is being used in SAP.</description>
        <label>Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Locale__c</fullName>
        <description>Field to hold value of Locale to determine that code and its description is for which locale.</description>
        <label>Locale</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Master Picklist Table</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Picklist Table</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/APTS_Stage_Local_Operational_Data__c.object
<CustomObject>
    <description>Staging Object for Local Operational Data Object</description>
    <fields>
        <fullName>APTS_Country__c</fullName>
        <description>Field to capture country for the LSO data.</description>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>ES</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>APTS_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>APTS External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>APTS_LP_Account_GUID__c</fullName>
        <label>Account GUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_LP_Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <picklist>
            <picklistValues>
                <fullName>BT</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>DT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>APTS_LP_Incoterms__c</fullName>
        <label>Incoterms</label>
        <picklist>
            <picklistValues>
                <fullName>CFR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DAF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DDP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DDU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DEQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EXW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FOB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZFE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZVR</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>APTS_LP_Local_Channel__c</fullName>
        <label>Local Channel</label>
        <picklist>
            <picklistValues>
                <fullName>P1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P6</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>APTS_LP_SAP_Customer_ID__c</fullName>
        <description>Placeholder field to hold the value of customer ID fetched from SAP.</description>
        <label>SAP Customer ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_LP_Sales_Organisation__c</fullName>
        <label>Sales Organisation</label>
        <picklist>
            <picklistValues>
                <fullName>ABB</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>APTS_Payment_Terms__c</fullName>
        <description>Field to capture payment terms associated with Apttus LSO object record.</description>
        <label>Payment Terms</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_SAP_Division__c</fullName>
        <label>APTS SAP Division</label>
        <picklist>
            <picklistValues>
                <fullName>ZZ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Stage Local Operational Data</label>
    <nameField>
        <displayFormat>LCRD-{00000}</displayFormat>
        <label>Apttus Local Customer Reference Data Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stage Local Operational Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/APTS_DMLODHelper.cls
public class APTS_DMLODHelper extends APTS_DMHelper{
    
      /**
   * This method contains Bussniess Validation Rule for Validating Local Operational Data
   *  Written-By : Sreekanth Pinnamaneni
   * 
   * */

  public static void validateLocalOperationalData(List < APTS_Stage_Local_Operational_Data__c > listStageLocalOperationalData) {
        boolean bisValidattionError = false;
    	String sErromMessage = '';
    	List < APTS_Stage_Local_Operational_Data__c > UpdatedLodList = new List < APTS_Stage_Local_Operational_Data__c >();
        Set < String > countrySet = new Set < String > ();
    	countrySet.add('ES'); countrySet.add('IT'); countrySet.add('FR');
        
        system.debug('HS -> Size of List' + listStageLocalOperationalData.size());
      // Set of fields to be validated against Master Picklist
        Set <String> setDistributionChannel = new Set <String> ();
        Set <String> setPaymentTerms = new Set <String> ();
        Set <String> setIncoterms = new Set <String> ();
        Set <String> setLocalChannel = new Set <String> ();
        Set <String> setSAPDivision = new Set <String> ();
        Set <String> guiIDSet = new Set <String> ();
        
        for(APTS_Stage_Local_Operational_Data__c localOpData: listStageLocalOperationalData){
        
            setLocalChannel.add(localOpData.APTS_LP_Local_Channel__c);
            setDistributionChannel.add(localOpData.APTS_LP_Distribution_Channel__c);
            setIncoterms.add(localOpData.APTS_LP_Incoterms__c);
            setPaymentTerms.add(localOpData.APTS_Payment_Terms__c);
            setSAPDivision.add(localOpData.APTS_SAP_Division__c);
            guiIDSet.add(localOpData.APTS_LP_Account_GUID__c);
        }
        
        List <Account> actList = [select GUID__c from Account where GUID__c in :guiIDSet];
        Set <String> accountGuiIDSet = new Set <String> ();
        for(Account act: actList) {
            accountGuiIDSet.add(act.GUID__c);
        }
        
        LIst<APTS_Master_Picklist_Table__c> masterPicklistSoLst =  [select id,APTS_Code__c,APTS_Code_Used_For__c 
                                                                      from APTS_Master_Picklist_Table__c 
                                                                     where (APTS_Locale__c = : APTS_DMConstants.SPAIN_LOCALE and(
                                                                            (APTS_Code__c in :setLocalChannel and APTS_Code_Used_For__c  = :APTS_DMConstants.MASTER_PICKLIST_LOCAL_CHANNEL)
                                                                               OR
                                                                               (APTS_Code__c in :setDistributionChannel and APTS_Code_Used_For__c  = :APTS_DMConstants.MASTER_PICKLIST_DISTRIBUTION_CHANNEL)
                                                                               OR
                                                                               (APTS_Code__c in :setIncoterms and APTS_Code_Used_For__c  = :APTS_DMConstants.MASTER_PICKLIST_INCOTERM)
                                                                               OR
                                                                               (APTS_Code__c in :setSAPDivision and APTS_Code_Used_For__c  = :APTS_DMConstants.MASTER_PICKLIST_SAP_DIVISION)
                                                                               OR
                                                                               (APTS_Code__c in :setPaymentTerms and APTS_Code_Used_For__c  = :APTS_DMConstants.MASTER_PICKLIST_PAYMENT_TERM)
                                                                              )) ];
        Set <String> masterDistributionChannel = new Set <String> ();
        Set <String> masterPaymentTerms = new Set <String> ();
        Set <String> masterIncoterms = new Set <String> ();
        Set <String> masterLocalChannel = new Set <String> ();
        Set <String> masterSAPDivision = new Set <String> ();
        
      //Prepare sets for Local Channel, Distribution Channel, Incoterm, Payment Term from Master Picklist                                                                       
        for(APTS_Master_Picklist_Table__c mpTable: masterPicklistSoLst) {
            if(mpTable.APTS_Code_Used_For__c == APTS_DMConstants.MASTER_PICKLIST_LOCAL_CHANNEL)        masterLocalChannel.add(mpTable.APTS_Code__c);
            if(mpTable.APTS_Code_Used_For__c == APTS_DMConstants.MASTER_PICKLIST_DISTRIBUTION_CHANNEL) masterDistributionChannel.add(mpTable.APTS_Code__c);
            if(mpTable.APTS_Code_Used_For__c == APTS_DMConstants.MASTER_PICKLIST_INCOTERM)             masterIncoterms.add(mpTable.APTS_Code__c);
            if(mpTable.APTS_Code_Used_For__c == APTS_DMConstants.MASTER_PICKLIST_PAYMENT_TERM)         masterPaymentTerms.add(mpTable.APTS_Code__c);
            if(mpTable.APTS_Code_Used_For__c == APTS_DMConstants.MASTER_PICKLIST_SAP_DIVISION)         masterSAPDivision.add(mpTable.APTS_Code__c);
        }                                                                   
        system.debug('HS -> Size of Local Channel set' + masterLocalChannel.size());
        system.debug('HS -> Size of Distribution Channel set' + masterDistributionChannel.size());
        system.debug('HS -> Size of Incoterm set' + masterIncoterms.size());
        system.debug('HS -> Size of Payment Term set' + masterPaymentTerms.size());
        system.debug('HS -> Size of SAP Division set' + masterSAPDivision.size());
        
        
      
    //Iterate thru the Local Operational Data List and Validate each record  
     for(APTS_Stage_Local_Operational_Data__c localOpData: listStageLocalOperationalData) {
     	
     	APTS_DMHelperUtility dmHelperUtility = New APTS_DMHelperUtility();
     	        
         bisValidattionError = false;
    	 //sErromMessage = '';
         // Validation of Local Channel
          if (string.isBlank(localOpData.APTS_LP_Local_Channel__c) ) {
            bisValidattionError = true;
            dmHelperUtility.appendErrorMessage('Local Channel cannot be Blank');
         }
     	 if (!string.isBlank(localOpData.APTS_LP_Local_Channel__c) && !masterLocalChannel.contains(localOpData.APTS_LP_Local_Channel__c)) {
            bisValidattionError = true;
            dmHelperUtility.appendErrorMessage('Local Channel not found in Master Picklist.');
         }
         
         // Validation of Distribution Channel
     	 if (!string.isBlank(localOpData.APTS_LP_Distribution_Channel__c) && !masterDistributionChannel.contains(localOpData.APTS_LP_Distribution_Channel__c)) {
            bisValidattionError = true;
            dmHelperUtility.appendErrorMessage('Distribution Channel not found in Master Picklist.');
         }
         
         // Validation of Incoterm
     	 if (!string.isBlank(localOpData.APTS_LP_Incoterms__c) && !masterIncoterms.contains(localOpData.APTS_LP_Incoterms__c)) {
            bisValidattionError = true;
            dmHelperUtility.appendErrorMessage('Incoterm not found in Master Picklist.');
         }
         
         // Validation of Payment Term
     	 if (!string.isBlank(localOpData.APTS_Payment_Terms__c) && !masterPaymentTerms.contains(localOpData.APTS_Payment_Terms__c)) {
            bisValidattionError = true;
            dmHelperUtility.appendErrorMessage('Payment Term not found in Master Picklist.');
         }
         
         // Validation of SAP Division code
     	 if (!string.isBlank(localOpData.APTS_SAP_Division__c) && !masterSAPDivision.contains(localOpData.APTS_SAP_Division__c)) {
            bisValidattionError = true;
            dmHelperUtility.appendErrorMessage('SAP Division not found in Master Picklist.');
         }
         
         // Validation of Country code
     	 if (!string.isBlank(localOpData.APTS_Country__c) && !countrySet.contains(localOpData.APTS_Country__c)) {
            bisValidattionError = true;
            dmHelperUtility.appendErrorMessage('Invalid Country code.');
         }
         
         // Validation of GUI ID
     	 if (!string.isBlank(localOpData.APTS_LP_Account_GUID__c) && !accountGuiIDSet.contains(localOpData.APTS_LP_Account_GUID__c)) {
            bisValidattionError = true;
            dmHelperUtility.appendErrorMessage('Account GUI ID not found in Account Object.');
         }
         
         dmHelperUtility.updateValidationStatus(localOpData,bIsValidattionError);
         UpdatedLodList.add(localOpData);
         //**end
      }// End of for Loop
     
     // update the records 
     if (UpdatedLodList.size() > 0) {
      system.debug('HS--> Size of LODs to be updated' + UpdatedLodList.size());
      try {
        Database.upsert(UpdatedLodList);
      } catch (Exception ex) {
        System.debug('Exception while upserting LOD stage Data.\nException : ' + ex.getMessage());
      }
    }
      

  }

  public static APTS_CopyDataWrapper copyLocalOperationalData(List < APTS_Stage_Local_Operational_Data__c > listStageLocalOperationalData) {

        APTS_CopyDataWrapper oCopyWrapper = new APTS_CopyDataWrapper();

        system.debug('Copying Data from Staging Object to Normal Object for LOD');

		Schema.SObjectField f = APTS_LP_Local_Customer_Reference_Data__c.Fields.APTS_External_Id__c;

        List < APTS_LP_Local_Customer_Reference_Data__c > listloadLocalOperationalData = new List < APTS_LP_Local_Customer_Reference_Data__c > ();
        List < APTS_Stage_Local_Operational_Data__c > listupdatestageLocalOperationalData = new List < APTS_Stage_Local_Operational_Data__c > ();
        
		Set<String> setAccountGUID = new Set<String>();
		Map<String,Account> mapAccountGUID = new Map<String,Account>();
		
		for(APTS_Stage_Local_Operational_Data__c oStageLOD : listStageLocalOperationalData) {
			setAccountGUID.add(oStageLOD.APTS_LP_Account_GUID__c);
		}
		
		List<Account> listAccount = [Select Id,Name,GUID__c from Account where GUID__c =:setAccountGUID];
		
		for(Account oAccount : listAccount) {
			mapAccountGUID.put(oAccount.GUID__c,oAccount);
		}

        // Creating Product Line Tree, assigning values and adding into List.
        for (APTS_Stage_Local_Operational_Data__c oStageLOD: listStageLocalOperationalData) {

            APTS_LP_Local_Customer_Reference_Data__c oLOD = new APTS_LP_Local_Customer_Reference_Data__c();
            
			oLOD.APTS_External_ID__c = oStageLOD.APTS_External_ID__c;
			oLOD.APTS_Country__c = oStageLOD.APTS_Country__c;
			oLOD.APTS_LP_Distribution_Channel__c = oStageLOD.APTS_LP_Distribution_Channel__c;
			oLOD.APTS_LP_Incoterms__c = oStageLOD.APTS_LP_Incoterms__c;
			oLOD.APTS_LP_Local_Channel__c = oStageLOD.APTS_LP_Local_Channel__c;
			oLOD.APTS_Payment_Terms__c = oStageLOD.APTS_Payment_Terms__c;
			oLOD.APTS_LP_Sales_Organisation__c = oStageLOD.APTS_LP_Sales_Organisation__c;
			oLOD.APTS_LP_SAP_Customer_ID__c = oStageLOD.APTS_LP_SAP_Customer_ID__c;
			oLOD.APTS_SAP_Division__c = oStageLOD.APTS_SAP_Division__c;
            
			if(mapAccountGUID.get(oStageLOD.APTS_LP_Account_GUID__c)!= NULL) {
				oLOD.APTS_LP_Account__c = mapAccountGUID.get(oStageLOD.APTS_LP_Account_GUID__c).Id;
			}
			
            listloadLocalOperationalData.add(oLOD);
            
            oStageLOD.APTS_RowStatus__c = APTS_DMConstants.LOAD_STATUS;
            listupdatestageLocalOperationalData.add(oStageLOD);
        }

        // Upserting the list
        try {
            if (listloadLocalOperationalData.size() > 0) {
                Database.UpsertResult[] results = Database.upsert(listloadLocalOperationalData, f, false);
                system.debug('HS--> Result while copying Local Operational Data ' + results);
                Set < Id > successIdSet = New Set < id > ();
				Set < Id > failedIdSet = New Set < id > ();

                for (Database.UpsertResult sr: results) {
                    if (sr.isSuccess()) {
                        System.debug('Successfully inserted LOD: ' + sr.getId());
                        successIdSet.add(sr.getId());
						system.debug('##SUCCESSresults.get(i)=' + sr);
                    } else {
                        // Operation failed, so get all errors 
                        oCopyWrapper.bIsUpsertFail = true;
                        for (Database.Error err: sr.getErrors()) {
                            System.debug('The following error has occurred.');
                            oCopyWrapper.sErrorMessage = oCopyWrapper.sErrorMessage + '<br/><br/>' + err.getStatusCode() + ': ' + err.getMessage();
                            System.debug(err.getStatusCode() + ': ' + err.getMessage());
                            System.debug('Following fields that affected this error: ' + err.getFields());
                        }
                    }
                }
                
                APTS_DMHelper.updateLoadingStatus(successIdSet, 'APTS_LP_Local_Customer_Reference_Data__c', 'APTS_External_Id__c', 'APTS_External_ID__c', listStageLocalOperationalData);
            }

                system.debug('HS1--> ' + oCopyWrapper);

        } catch (Exception e) {
            System.debug('Exception while upserting LOD records.\nException : ' + e.getMessage());
            oCopyWrapper.sErrorMessage = e.getMessage();
            oCopyWrapper.bIsUpsertFail = true;
        }

        return oCopyWrapper;
    }  
    
}