src/objects/Account_Plan__c.object
<CustomObject>
    <description>R5 - Account Plan</description>
    <fields>
        <fullName>Master_Account_Plan_Status__c</fullName>
        <formula>TEXT(Sub_Account_Plan_To__r.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Master Account Plan Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Plan_Year__c</fullName>
        <description>R5 - Account Plan Year</description>
        <inlineHelpText>Enter the Account Plan Year</inlineHelpText>
        <label>Account Plan Year</label>
        <picklist>
            <picklistValues>
                <fullName>1991</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1992</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1993</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1994</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1995</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1996</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1997</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1998</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2001</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2002</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2003</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2004</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2005</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2006</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2007</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2008</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2009</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2011</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R5 - Lookup Relationship with Account object</description>
        <inlineHelpText>Customer Name</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BU__c</fullName>
        <description>R5 - Business Unit field to concatenate all BU of Financial Target and Expectations.</description>
        <label>BU</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>DIV__c</fullName>
        <description>R5 - Division field to concatenate all the DIV of Financial Target and Expectations.</description>
        <label>DIV</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Freeze_Account_Plan_Budgets__c</fullName>
        <defaultValue>false</defaultValue>
        <description>R5 - Freeze Account Plan Budgets</description>
        <inlineHelpText>&quot;Freeze Account Plan Budgets&quot; check box to activate freezing the Opportunities associated with the Master Account Plan. Once the check box is activated then selected Opportunities cannot be removed/added to the &quot;Budgeted Opportunities&quot;</inlineHelpText>
        <label>Freeze Account Plan Budgets</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Old_Record_Type_Value__c</fullName>
        <description>R5 - To capture Old Record Type Value.</description>
        <label>Old Record Type Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PG__c</fullName>
        <label>PG</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Product_Lines__c</fullName>
        <label>Product Lines</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>R5 - Status</description>
        <inlineHelpText>Planning = &quot;This Account Plan is under Preparation&quot;. Approved = &quot;This Account Plan has been approved by Manager, and is operational&quot;. Closed = &quot;This Account Plan has expired&quot;</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Planning</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Plan_Information__c.object
<CustomObject>
    <description>R5 - Account Plan Information</description>
    <fields>
        <fullName>Account_Plan_End_Date__c</fullName>
        <description>R5 - Account Plan End Date</description>
        <label>Account Plan End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Account_Plan_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R5 - Lookup to User.</description>
        <label>Account Plan Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Plan_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Plan_Start_Date__c</fullName>
        <description>R5 - Account Plan Start Date</description>
        <label>Account Plan Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Account_Plan_Status__c</fullName>
        <label>Account Plan Status</label>
        <picklist>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Account_Plan_Type__c</fullName>
        <label>Account Plan Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Plan_Year__c</fullName>
        <description>R5 - Copies the Value from Account Plan Year.</description>
        <label>Account Plan Year</label>
        <picklist>
            <picklistValues>
                <fullName>1991</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1992</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1993</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1994</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1995</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1996</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1997</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1998</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2001</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2002</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2003</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2004</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2005</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2006</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2007</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2008</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2009</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2011</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Account_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R5 - Lookup to Account Plan.</description>
        <label>Account Plan</label>
        <referenceTo>Account_Plan__c</referenceTo>
        <relationshipLabel>Account Plan Informations</relationshipLabel>
        <relationshipName>Account_Plan_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R5 - Lookup to Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plan Informations</relationshipLabel>
        <relationshipName>Account_Plan_Informations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BU__c</fullName>
        <description>R5 - Business Unit field.</description>
        <label>BU</label>
        <length>100000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DIV__c</fullName>
        <description>R5 - Division field.</description>
        <label>DIV</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PG__c</fullName>
        <label>PG</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Product_Lines__c</fullName>
        <label>Product Lines</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Account Plan Information</label>
    <nameField>
        <displayFormat>API-{000000}</displayFormat>
        <label>Account Plan Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plan Informations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product_Lines__c.object
<CustomObject>
    <description>R5 - New Custom Object - Product Lines</description>
    <label>Product Focus</label>
    <nameField>
        <displayFormat>PROD-LINE-{0000}</displayFormat>
        <label>Product Lines Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Focus</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ClsTriggerAccountPlan.cls
/**   
* TriggerClass :  ClsTriggerAccountPlan
*    
* Release R5
*  
* @author  Indhu Selvi Ramalingam (Accenture)
* @created 2016-01-18
* @version 1.0
*
* - Created
*/
public without sharing class ClsTriggerAccountPlan extends ClsTriggerVirtual {
    
    public Map<Id, RecordType> rtMap = new Map<Id, RecordType>();
    public Static Set<Id> processedIdSet = new Set<Id>();
    public Id freezeBudgetRTId = null;
    public Id abbBasicAdminProfileId = NULL;
/**   
* Constructor ClsTriggerAccountPlan 
*    
* Release R5
*/
    public ClsTriggerAccountPlan () {
        Integer remLimit =  limits.getLimitQueryRows() - limits.getQueryRows();
        rtMap = new Map<Id, RecordType>([SELECT Id, Name FROM RecordType WHERE SobjectType =: Label.Account_Plan_Sobject AND IsActive = TRUE LIMIT :remLimit]); //'Account_Plan__c'
        
        Profile[] basicProf = [ SELECT ID, Name FROM Profile WHERE Name =: Label.Account_Plan_Profile LIMIT :remLimit];
        
        abbBasicAdminProfileId = (basicProf != NULL && basicProf.size() > 0) ? basicProf[0].Id : NULL;
        
        for(RecordType rt : rtMap.values()){
            if (rt.Name == Label.Account_Plan_Freeze_Budget) {
                freezeBudgetRTId = rt.Id;
            }
        } 
      
    }
 
/**   
* As per Req #2737
* When the user uncheckbox 'Freeze Budgets' then it will allow the user to Add any of the budgets by swapping the Record Type.         
* Release R5
*/   
    public override void bulkBefore(ClsWrappers.TriggerContext trgCtx) {
        
        if (trgCtx.isUpdate) {
        
            for (SObject sobj: trgCtx.newList) {
                
                if (!processedIdSet.contains(sobj.Id)) {
                
                    Account_Plan__c newAccountPlan = (Account_Plan__c) sobj;
                    Account_Plan__c oldAccountPlan = (Account_Plan__c) trgCtx.oldMap.get(sobj.Id);
                    
                   // system.debug('::new::'+newAccountPlan.Freeze_Account_Plan_Budgets__c  +':::'+oldAccountPlan.Freeze_Account_Plan_Budgets__c  +':::'+newAccountPlan.Old_Record_Type_Value__c);
                   // system.debug('::RTMap :::'+RTMap );  
                    
                    if (newAccountPlan.Freeze_Account_Plan_Budgets__c !=  oldAccountPlan.Freeze_Account_Plan_Budgets__c && newAccountPlan.Freeze_Account_Plan_Budgets__c == TRUE) {
                        
                        newAccountPlan.Old_Record_Type_Value__c = newAccountPlan.RecordTypeId; // Copy the previous record type
                        newAccountPlan.RecordTypeId = (freezeBudgetRTId != NULL) ? freezeBudgetRTId :  newAccountPlan.RecordTypeId;
                    } else if (newAccountPlan.Freeze_Account_Plan_Budgets__c != oldAccountPlan.Freeze_Account_Plan_Budgets__c && newAccountPlan.Freeze_Account_Plan_Budgets__c == FALSE && 
                        newAccountPlan.Old_Record_Type_Value__c != NULL && newAccountPlan.Old_Record_Type_Value__c != '' &&
                        rtMap.containsKey(newAccountPlan.Old_Record_Type_Value__c)){
                        
                        newAccountPlan.RecordTypeId = newAccountPlan.Old_Record_Type_Value__c;  // Update the previous record type
                    } 
                    
                    //system.debug('::after::newAccountPlan:::'+newAccountPlan.RecordTypeId+'::before::newAccountPlan:::'+newAccountPlan.Old_Record_Type_Value__c);
                    
                    processedIdSet.add(sobj.Id);
                } else{}              
            }
        }
    }
         
 
 
   /**
* @see IntHelper.beforeTrigger
*/  
    public override void beforeTrigger(ClsWrappers.TriggerContext trgCtx) {        
        
        accountPlanRecordSharing(trgCtx); 
        if(trgCtx.isDelete) {  
            accountPlanRecordDelete(trgCtx);
            deleteValidation(trgCtx);
        }           
    } 
    
    
    
       /**
    To prevent deletion when the account plan status is closed
    */
     Public void deleteValidation(ClsWrappers.TriggerContext trgCtx){
         ID sysAdminProfileId = Label.CL00075;
         for (Account_Plan__c con : (List<Account_Plan__c>) trgCtx.oldList) {             
             if (sysAdminProfileId  != Userinfo.getProfileid() && con.Master_Account_Plan_Status__c == Label.Closed ) {
                 con.addError(Label.Business_Account_Plan_delete_Err); //You cannot save the changes as Master Account Plan Status is Closed.
             }
         }        
     }
/**
* @see IntHelper.afterTrigger
* As part of Req - 2738; KAD-00823;
*/   
    public override void afterTrigger(ClsWrappers.TriggerContext trgCtx) {        
        updateAccPlanInfoRecords(trgCtx);              
    }
    
/**     
Method : accountPlanRecordSharing - Method to create/view the Account Plan record only by Account team member
@author  Indhu Selvi Ramalingam(Accenture)
*/
    @TestVisible   
    private void accountPlanRecordSharing(ClsWrappers.TriggerContext trgCtx) {
    
      if(trgCtx.isInsert && trgCtx.isBefore){
            Set<ID> setAccTeamUserIds = new Set<ID>(); //capture the Account team users ids
            Set<ID> setAccIds = new Set<ID>(); //capture the Account Ids
            Map<ID, Set<Id>> mapUsersId = new Map<ID, Set<Id>>();
            Id labelId = Label.CL00075;
            Id userProfileId = Userinfo.getProfileid();
            Id currUser = UserInfo.getUserId();
            Integer remLimit =  limits.getLimitQueryRows() - limits.getQueryRows();
            for(sobject so :trgCtx.newList){
                Account_Plan__c accPlan = (Account_Plan__c)so;
                setAccIds.add(accPlan.Account__c);
            }
            
            if (setAccIds.size() > 0) {
                for(AccountTeamMember atm : [SELECT id, UserId, AccountId FROM AccountTeamMember where AccountId IN:setAccIds LIMIT :remLimit]){
                    if(!mapUsersId.containsKey(atm.AccountId)){
                        mapUsersId.put(atm.AccountId, new Set<ID>());
                    }
                    mapUsersId.get(atm.AccountId).add(atm.UserId);
                } 
                
                Map<ID, Account> accMap = new Map <Id, Account> ([SELECT ID, OwnerID FROM Account WHERE ID IN :setAccIds LIMIT :remLimit]);
                
                for(sobject so : trgCtx.newList){
                    Account_Plan__c accPlan = (Account_Plan__c)so;
                    if(accPlan.Account__c != NULL && mapUsersId.containsKey(accPlan.Account__c)){
                        setAccTeamUserIds = mapUsersId.get(accPlan.Account__c);                  
                    }
                    
                    if(accPlan.Account__c != NULL && !setAccTeamUserIds.contains(currUser) && currUser != accMap.get(accPlan.Account__c).OwnerId && abbBasicAdminProfileId != userProfileId ){
                        so.addError(System.label.System_CL00102);
                    }
                }
            }
           
        } 
     }
     
/* 
* Method - Deleting Account Plan Records will delete Account Plan Information  - KAD-00823 (Req #2738)
*/    
    @TestVisible
    public void accountPlanRecordDelete(ClsWrappers.TriggerContext trgCtx) {
        
        Set<Id> setAccPlanId = new Set<Id>();
        Map<Id,Account_Plan__c> accPlanIdAndRecordMap = new Map<Id, Account_Plan__c>();
        Integer remLimit =  limits.getLimitQueryRows() - limits.getQueryRows();
    
        for(sobject so : trgCtx.oldList) {
            Account_Plan__c sobjAccPlan = (Account_Plan__c)so;
            setAccPlanId.add(sobjAccPlan.Id);
        } 
        
        if (setAccPlanId.size() > 0) {
        
            List<Account_Plan_Information__c> listAccPlanInfo = new List<Account_Plan_Information__c> ([SELECT Id, Name, Account_Plan__c, BU__c, DIV__c,
                                                                                                    Account_Plan_Status__c, Account_Plan_Year__c,
                                                                                                    Account_Plan_Owner__c FROM Account_Plan_Information__c WHERE Account_Plan__c =: setAccPlanId LIMIT :remLimit]);
           /* for(Account_Plan_Information__c  accPlanInfo : listAccPlanInfo) {
                
                if(trgCtx.isDelete) {
                    
                    accPlanInfo.Account_Plan_Owner__c = NULL;
                    accPlanInfo.BU__c = '';
                    accPlanInfo.DIV__c = '';
                    accPlanInfo.Account_Plan_Start_Date__c = NULL;
                    accPlanInfo.Account_Plan_End_Date__c = NULL;
                    accPlanInfo.Account_Plan_Status__c = '';
                }
            }*/
            
            if (listAccPlanInfo.size() > 0) {
                try {
                    Database.Delete(listAccPlanInfo);
                } Catch (DMLException e) {
                    
                    List<Sobject> objList = trgCtx.newList;
            
                    String error = '';
                    
                    for (Integer i=0; i < e.getNumDML(); i++) {
                        error += e.getDmlMessage(i) + Label.Line_Break;
                    }
                    for (Sobject obj: objList) {                
                        Account_Plan__c qtm = (Account_Plan__c ) obj;
                        qtm.addError(error, false);            
                    }            
                }       
            }
       }
    }
        
           
/* 
* Method - Update Account Plan Information Records based on Account Plan - KAD-00823 (Req #2738)
*/     
    @TestVisible
    public void updateAccPlanInfoRecords(ClsWrappers.TriggerContext trgCtx) {
    
        Set<Id> setAccPlanId = new Set<Id>();
        Map<Id,Account_Plan__c> accPlanIdAndRecordMap = new Map<Id, Account_Plan__c>();
        Integer remLimit =  limits.getLimitQueryRows() - limits.getQueryRows();
        List<Account_Plan_Information__c> listAccPlanInfo = new List<Account_Plan_Information__c>();
        
        //system.debug('::trgCtx::'+trgCtx);
        
        if(trgCtx.isUpdate) {
            for(sobject so : trgCtx.newList) {
                Account_Plan__c newAccPlan = (Account_Plan__c) so;
                Account_Plan__c oldAccPlan = (Account_Plan__c) trgCtx.oldMap.get(so.Id);
                
                if(newAccPlan.Status__c != oldAccPlan.Status__c || newAccPlan.Name != oldAccPlan.Name || newAccPlan.BU__c != oldAccPlan.BU__c ||
                   newAccPlan.DIV__c != oldAccPlan.DIV__c || newAccPlan.OwnerID != oldAccPlan.OwnerID || newAccPlan.Account__c != oldAccPlan.Account__c ||
                   newAccPlan.Product_Lines__c != oldAccPlan.Product_Lines__c|| newAccPlan.PG__c != oldAccPlan.PG__c || newAccPlan.RecordTypeId != oldAccPlan.RecordTypeId ||
                   newAccPlan.Account_Plan_Year__c != oldAccPlan.Account_Plan_Year__c) {
                    setAccPlanId.add(newAccPlan.Id);
                    accPlanIdAndRecordMap.put (newAccPlan.Id, newAccPlan);
                }
                
            }
        } 
           
        if(trgCtx.isInsert) {
            for(sobject so : trgCtx.newList) {
            
                Account_Plan__c accPlan = (Account_Plan__c) so;
                Account_Plan_Information__c sobjAccPlanInfo = new Account_Plan_Information__c();
                sobjAccPlanInfo.Account_Plan_Owner__c = accPlan.OwnerId;
                sobjAccPlanInfo.Account_Plan__c = accPlan.ID;
                sobjAccPlanInfo.Account__c = accPlan.Account__c;
                sobjAccPlanInfo.BU__c = accPlan.BU__c;
                sobjAccPlanInfo.DIV__c = accPlan.DIV__c;
               
                sobjAccPlanInfo.Account_Plan_Status__c = accPlan.Status__c;
                sobjAccPlanInfo.PG__c = accPlan.PG__C;    
                sobjAccPlanInfo.Product_Lines__c = accPlan.Product_Lines__c;
                sobjAccPlanInfo.Account_Plan_Year__c = accPlan.Account_Plan_Year__c;
                sobjAccPlanInfo.Account_Plan_Type__c= (rtMap.containsKey(accPlan.RecordTypeId)) ? rtMap.get(accPlan.RecordTypeId).Name : '';  
                listAccPlanInfo.add(sobjAccPlanInfo);
            }
        }
        
        
        if (setAccPlanId.size() > 0) {
        
            listAccPlanInfo = [SELECT Id, Account__c, Name, Account_Plan__c, BU__c, PG__C, Product_Lines__c, DIV__c, Account_Plan_Status__c,
                            Account_Plan_Year__c, Account_Plan_Owner__c FROM Account_Plan_Information__c WHERE Account_Plan__c =: setAccPlanId LIMIT :remLimit];
            
            //system.debug('::listAccPlanInfo :::'+listAccPlanInfo );
            
            for(Account_Plan_Information__c  accPlanInfo : listAccPlanInfo) {
                    
                Account_Plan__c accPlan = accPlanIdAndRecordMap.get(accPlanInfo.Account_Plan__c);
                
                accPlanInfo.Account_Plan_Owner__c = accPlan.OwnerId;
                accPlanInfo.BU__c = accPlan.BU__c;
                accPlanInfo.DIV__c = accPlan.DIV__c;              
                accPlanInfo.Account_Plan_Status__c = accPlan.Status__c;    
                accPlanInfo.Account__c = accPlan.Account__c;
                accPlanInfo.PG__c = accPlan.PG__C;    
                accPlanInfo.Product_Lines__c = accPlan.Product_Lines__c;
                accPlanInfo.Account_Plan_Year__c = accPlan.Account_Plan_Year__c; 
                accPlanInfo.Account_Plan_Type__c= (rtMap.containsKey(accPlan.RecordTypeId)) ? rtMap.get(accPlan.RecordTypeId).Name : ''; 
                  
                           
            }
        }
        
        if (listAccPlanInfo.size() > 0) {
            
            try {
                Database.Upsert(listAccPlanInfo);
            }  Catch (DMLException e) {   
                
                List<Sobject> objList = trgCtx.newList;
        
                String error = '';
                
                for (Integer i=0; i < e.getNumDML(); i++) {
                    error += e.getDmlMessage(i) + Label.Line_Break;
                }
                for (Sobject obj: objList) {                
                    Account_Plan__c qtm = (Account_Plan__c ) obj;
                    qtm.addError(error, false);            
                }            
            }         
        }
        
    }
}