src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>GUID__c</fullName>
        <externalId>true</externalId>
        <label>GUID</label>
        <length>9</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>

    <fields>
        <fullName>Relationship_Status__c</fullName>
        <description>R5 - Relationship Status</description>
        <inlineHelpText>Highest status of different ABB businesses. See market scope for details</inlineHelpText>
        <label>Relationship Status</label>
        <picklist>
            <picklistValues>
                <fullName>Channel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ABB authorized value provider</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
 <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Channel_Business_Review__c.object
<CustomObject>
    <description>R5 Channel Business Review is a custom object to review the Channels, Partner, ABB Authorized value provider &amp; Strategic / Key Partner  who will be partnering with ABB to do business.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R5 - Channel review to have a look-up relationship with the Account Object.</description>
        <inlineHelpText>The partner and business plan this review covers. If the scope is several branch offices, that need to be indicated in general comments below.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Channel_Business_Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Joint_Business_Plan__c</fullName>
        <description>R5-Channel review to have a look-up relationship with the Joint Business Plan Object.</description>
        <inlineHelpText>The partner business plan this review covers. If the scope is several branch offices, that need to be indicated in general comments below.</inlineHelpText>
        <label>Business Plan</label>
        <referenceTo>Joint_Business_Plan__c</referenceTo>
        <relationshipLabel>Channel Partner Business Reviews</relationshipLabel>
        <relationshipName>Channel_Reviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Primary_Channel_Class__c</fullName>
        <description>R5 - Primary Channel Class from Channel Partner Business Plan</description>
        <formula>Joint_Business_Plan__r.Primary_Channel_Class__c</formula>
        <label>Primary Channel Class</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>R5 - Status</description>
        <inlineHelpText>Change status or send to approval when completed. Note that fields indicated with ! (exclamation mark) must first be completed.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Channel Partner Business Review</label>
    <nameField>
        <label>Business Review Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partner Business Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <!--validationRules>
        <fullName>CBR_Validate_Required_Fields</fullName>
        <active>false</active>
        <description>R5 - Validation rule to check all the checkbox fields need to be filled out</description>
        <errorConditionFormula>OR(Sales_Answer_1__c = FALSE, Actions_Answer_1__c= FALSE, Partner_Answer_1__c=FALSE,ISBLANK(Sales_Answer_2__c),ISBLANK(Actions_Answer_2__c))</errorConditionFormula>
        <errorMessage>Cannot save the changes. Please fill the required fields.</errorMessage>
    </validationRules-->
</CustomObject>

src/objects/Channel_Market_Coverage__c.object
<CustomObject>
    <description>R5 - Custom Object to define Channel Market Coverage</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>R5 - Master Detail Relationship to Account Standard Object</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Channel_Market_Coverages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <description>R5 Division</description>
        <inlineHelpText>Pick division(s) focused in this market scope (and connected business plan/review)</inlineHelpText>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>DM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PG</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <!--fields>
        <fullName>Focussed_Industry1__c</fullName>
        <description>R5 - New Focussed Industry value -Combination of Industry usage level1, level2 and level3</description>
        <inlineHelpText>Pick all the industries currently served and targeted in the upcoming 3 years. Pick only industries with sales focus, not the ones that are served reactively.</inlineHelpText>
        <label>Focussed Industry</label>
        <picklist>
            <picklistValues>
                <fullName>BLD - BLD.8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BLD - BLD.9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BLD - BLD.10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.1 - IND.1.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.1 - IND.1.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.7 - IND.7.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.7 - IND.7.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.7 - IND.7.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.10 - IND.10.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.10 - IND.10.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.10 - IND.10.4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.10 - IND.10.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.11 - IND.11.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.11 - IND.11.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.12 - IND.12.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.12 - IND.12.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.12 - IND.12.3</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields-->
    <fields>
        <fullName>Primary_Channel_Class__c</fullName>
        <description>R5-Picklist contains Primary Channel Class values</description>
        <inlineHelpText>Select the primary channel class for this market scope</inlineHelpText>
        <label>Channel Class</label>
        <picklist>
            <picklistValues>
                <fullName>Engineering, Procurement and Construction (EPC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distributor (DIS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installer (INST)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Original Equipment Manufacturer (OEM)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panel Builder (PBL)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Provider (SPRO)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System Integrator (SYIN)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Distributor (TDIS)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Line1__c</fullName>
        <description>R5 - Long Text Area field to capture Product Line value</description>
        <inlineHelpText>List of PLs covered in the scope. Autofilled based on &quot;Channel Partner Product Mix&quot;</inlineHelpText>
        <label>Product Lines</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Relationship_Status__c</fullName>
        <description>R5-Picklist hold the Relationship Status  values</description>
        <inlineHelpText>&quot;Partner&quot; - if active business plan;  &quot;Strategic/Key&quot; - if locally identified as such; &quot;ABB AVP&quot; - if valid authorization; &quot;Channel&quot; - otherwise</inlineHelpText>
        <label>Relationship Status</label>
        <picklist>
            <picklistValues>
                <fullName>Channel</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic / Key Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ABB authorized value provider</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Targeted_Key_Strategic__c</fullName>
        <defaultValue>false</defaultValue>
        <description>R5-Checkbox for Targeted Key Strategic</description>
        <inlineHelpText>Mark if the partner is targeting to become key or strategic partner in the upcoming 0-2 years. Affects the templates and functionalities.</inlineHelpText>
        <label>Targeted Strategic / Key Partner</label>
        <type>Checkbox</type>
    </fields>
    <label>Channel Partner Market Scope</label>
    <nameField>
        <label>Market Scope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partner Market Scope</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <!--webLinks>
        <fullName>Change_Product_Line</fullName>
        <availability>online</availability>
        <description>R5 - Change the Product through PIS Tree</description>
        <displayType>button</displayType>
        <height>600</height>
        <linkType>page</linkType>
        <masterLabel>Change Product Line</masterLabel>
        <openType>sidebar</openType>
        <page>EditChannelMarketPIS</page>
        <protected>false</protected>
    </webLinks-->
</CustomObject>

src/objects/Channel_Market_Coverage_Product_Lines__c.object
<CustomObject>
    <description>R5 - Channel Market Coverage Product Lines</description>
    <fields>
        <fullName>Business_Unit_Name__c</fullName>
        <description>R5 - Business Unit Name</description>
        <label>Business Unit Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <description>R5 - Business Unit</description>
        <inlineHelpText>DIv, BU and PG are only editable if there are no pre-filled values. (Default values from Master Data)</inlineHelpText>
        <label>Business Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Channel_Market_Coverage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R5 - Lookup Relationship to Channel Market Coverage</description>
        <inlineHelpText>Channel Market Scope this product is connected to</inlineHelpText>
        <label>Channel Market Scope</label>
        <referenceTo>Channel_Market_Coverage__c</referenceTo>
        <relationshipName>Channel_Market_Coverage_Product_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Division_Name__c</fullName>
        <description>R5 - Division Name</description>
        <label>Division Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <description>R5 - Division</description>
        <inlineHelpText>DIv, BU and PG are only editable if there are no pre-filled values. (Default values from Master Data)</inlineHelpText>
        <label>Division</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <description>R5 - Product Group</description>
        <inlineHelpText>DIv, BU and PG are only editable if there are no pre-filled values. (Default values from Master Data)</inlineHelpText>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R5 - Lookup to Product</description>
        <inlineHelpText>Pick from the product tree. Use level practical for defining sales plans and targeted stock levels.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Channel Partner Product Mix</relationshipLabel>
        <relationshipName>Channel_Market_Coverage_Product_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Channel Partner Product Mix</label>
    <nameField>
        <displayFormat>CHAN-PROD-LINE-{0000}</displayFormat>
        <label>Product Mix</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channel Partner Product Mix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Joint_Business_Plan__c.object
<CustomObject>
    <description>R5 Joint Business Plan</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R5 Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Joint_Business_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Channel_Market_Coverage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R5 - Lookup to Channel Market Coverage</description>
        <inlineHelpText>Channel &quot;Market scope&quot; this business plan is related to</inlineHelpText>
        <label>Market Scope</label>
        <referenceTo>Channel_Market_Coverage__c</referenceTo>
        <relationshipLabel>Channel Partner Business Plans</relationshipLabel>
        <relationshipName>Joint_Business_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>End Date Field</description>
        <inlineHelpText>The date the plan ends to be effective, typically Dec31st of the year</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Channel_Class__c</fullName>
        <description>R5 - Primary Channel Class</description>
        <formula>TEXT(Channel_Market_Coverage__r.Primary_Channel_Class__c )</formula>
        <inlineHelpText>Presents the channel class defined in &quot;Market scope&quot; where possible update must be done.</inlineHelpText>
        <label>Channel Class</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship_Status__c</fullName>
        <description>R5 - Relationship Status</description>
        <formula>TEXT(Channel_Market_Coverage__r.Relationship_Status__c)</formula>
        <inlineHelpText>Presents the relationship status defined in &quot;Market scope&quot;, where any update must be done</inlineHelpText>
        <label>Relationship Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Start Date Field</description>
        <inlineHelpText>The date the plan starts to be effective, typically Jan1st of the year</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>R5 - Status</description>
        <inlineHelpText>Turn active when content agreed with partner and all mandatory fields are filled. Alternatively send for approval. Change back to draft for updating content that is locked for editing for active plan.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Channel Partner Business Plan</label>
    <nameField>
        <label>Business Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partner Business Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ChannelPartnerMarketScope_Test.cls
/*
 * ApexClass :  Test class - ChannelPartnerMarketScope_Test
 * Release R5
 * @author  Indhu Ramalingam (Accenture)
 * @created 2016-03-15
 * @version 1.0
 * Description: Test class 
 * Created
 * This is the Test class for 1.ClsPISChannelMarketCoverageProdLine
                              2.ClsTriggerChannelMarketCoverageHandler 
                              3.ClsChannelMarketCoverageEdit
                              4.ClsTriggerChannelPreQualProductLine
 
 */
    @isTest
    private class ChannelPartnerMarketScope_Test{

    public static User createTestUser1() {
        User u = new User();
        u.FirstName ='haobo';
        u.LastName = 'song';
        u.Username = 'test123ABB1237@test123ABB1237.com';
        u.Alias = 'mtst1';
        u.Email = 'mtester1@company.com';
        u.CommunityNickname = u.Alias;
        u.ProfileId = [Select Id from Profile Where Name = 'ABB Sales Standard Profile' limit 1].Id;
        u.TimeZoneSidKey = 'America/Chicago';
        u.LocaleSidKey = 'en_US';
        u.EmailEncodingKey = 'UTF-8';
        u.LanguageLocaleKey = 'en_US';
        u.ManagerId = UserInfo.getUserId();
        return u;
    }
    
    public static Account createAccount1() {
        Account a = new Account();
        a.Name = 'test';
        a.BillingStreet = 'street'; 
        a.BillingCity = 'city';
        a.BillingCountry = 'Germany';
        a.GUID__c = '1234sghf';
        return a;
    }    
    
    public static Account createAccount2() {
        Account a1 = new Account();
        a1.Name = 'test1';
        a1.BillingStreet = 'street1'; 
        a1.BillingCity = 'city1';
        a1.BillingCountry = 'France';
        a1.GUID__c = '12345sghf';
        return a1;
    }  
    
    public static Product2 createProduct() {
        Product2 prod = new Product2();   
        prod.Description = 'Aluminium Solutions';     
        prod.Name = 'Desc Aluminium Solutions';
        prod.Product_Group__c = 4104;
        prod.CID__c = 'ABCD1234';
        prod.IsActive = TRUE;
        return prod;
    }
    
    public static Product2 createProduct1() {
        Product2 prod1 = new Product2();   
        prod1.Description = 'Cooling Systems';     
        prod1.Name = 'Desc Cooling Systems';
        prod1.Product_Group__c = 4442;
        prod1.CID__c = 'ABCD0123';
        prod1.IsActive = TRUE;
        return prod1;
    }
    
    public static Product_Group__c createProductGroup() {
        Product_Group__c pg = new Product_Group__c();
        pg.Name = '4104';
        pg.Product_Group_Name__c = 'Metals';
        pg.Business_Unit__c = 'PAPI';
        pg.Business_Unit_Name__c = 'Process Industries';
        pg.Division__c = 'PA';
        pg.Division_Name__c ='Process Automation';
        return pg;
    }
    
    public static Product_Group__c createProductGroup1() {
        Product_Group__c pg1 = new Product_Group__c();
        pg1.Name = '4442';
        pg1.Product_Group_Name__c = 'Force Measurement';
        pg1.Business_Unit__c = 'PAMP';
        pg1.Business_Unit_Name__c = 'Measurement & Analytics';
        pg1.Division__c = 'PA';
        pg1.Division_Name__c ='Process Automation';
        return pg1;
    }
    
    public static Channel_Market_Coverage__c createChannelPartMarScope() {
        Channel_Market_Coverage__c cms = new Channel_Market_Coverage__c();
        cms.Name = 'Test Market Scope';
        cms.Primary_Channel_Class__c = 'Distributor (DIS)';
        cms.Division__c = 'DM';
        cms.Focussed_Industry1__c = 'Building - Residential Buildings';
        cms.Relationship_Status__c = 'Channel';
        cms.Targeted_Key_Strategic__c = TRUE;
        return cms;
    }
    
    public static Channel_Market_Coverage__c createChannelPartMarScope1() {
        Channel_Market_Coverage__c cms1 = new Channel_Market_Coverage__c();
        cms1.Name = 'Test Market Scope1';
        cms1.Primary_Channel_Class__c = 'Installer (INST)';
        cms1.Division__c = 'PG' + ';' + 'EP';
        cms1.Focussed_Industry1__c = 'Industry - Printing';
        cms1.Relationship_Status__c = 'ABB authorized value provider';
        cms1.Targeted_Key_Strategic__c = TRUE;
        return cms1;
    }
    
     public static Channel_Market_Coverage__c createChannelPartMarScope2() {
        Channel_Market_Coverage__c cms2 = new Channel_Market_Coverage__c();
        cms2.Name = 'Test Market Scope2';
        cms2.Primary_Channel_Class__c = 'Panel builder (PBL)';
        cms2.Division__c = 'PG' + ';' + 'EP' + ';' + 'DM' ;
        cms2.Focussed_Industry1__c = 'Industry - Printing' + ';' + 'Utilities - Gas Utilities';
        cms2.Relationship_Status__c = 'Strategic / Key Partner';
        cms2.Targeted_Key_Strategic__c = FALSE;
        return cms2;
    }
    
    public static Channel_Market_Coverage__c createChannelPartMarScope3() {
        Channel_Market_Coverage__c cms3 = new Channel_Market_Coverage__c();
        cms3.Name = 'Test Market Scope3';
        cms3.Primary_Channel_Class__c = 'Panel builder (PBL)';
        cms3.Division__c = 'PG';
        cms3.Focussed_Industry1__c = 'Utilities - Gas Utilities';
        cms3.Relationship_Status__c = 'Partner';
        cms3.Targeted_Key_Strategic__c = TRUE;
        return cms3;
    }
    
    public static Joint_Business_Plan__c createJBP() {
        Date sDate = Date.today();
        Date eDate = sDate.addDays(2);
        Joint_Business_Plan__c jbp = new Joint_Business_Plan__c();
        jbp.Name = 'JBP Test1';
        jbp.Start_Date__c = sDate;
        jbp.End_Date__c= eDate;
        jbp.CurrencyIsoCode= 'USD';      //'USD-U.S. Dollar';
        jbp.Status__c= 'Draft';
        return jbp;
    }
    
    public static Channel_Business_Review__c createCBR() {
        Channel_Business_Review__c CBR = new Channel_Business_Review__c();
        CBR.Name='TestReview1';
        return CBR;
    }
    
    public static Channel_Market_Coverage_Product_Lines__c createCMSProdLines() {
        Channel_Market_Coverage_Product_Lines__c cmsProdLines = new Channel_Market_Coverage_Product_Lines__c();
        return cmsProdLines;
    }
    
     public static Channel_Market_Coverage_Product_Lines__c createCMSProdLines1() {
        Channel_Market_Coverage_Product_Lines__c cmsProdLines1 = new Channel_Market_Coverage_Product_Lines__c();
        return cmsProdLines1;
    }
     
    static testMethod void channelMarketScopeMethod(){
        Test.StartTest();
        User u1 = createTestUser1();
            insert u1;
        Account a = createAccount1();
            insert a;          
        Product2 prod = createProduct();
            
        Product2 prod1 = createProduct1();
           
        List<Product2> pr = new List<Product2>();
        pr.add(prod);
        pr.add(prod1);
        insert pr;   
           
        Product_Group__c pg = createProductGroup();
            insert pg;    
        AccountTeamMember aTM = new AccountTeamMember(
            UserId = u1.id,
            TeamMemberRole = 'Manager', 
            AccountId = a.id);
           insert aTM;  
        Channel_Market_Coverage__c cms = createChannelPartMarScope();
            cms.Account__c = a.id;         
            insert cms;    
               
        Channel_Market_Coverage_Product_Lines__c cmsProdLines = createCMSProdLines();
            cmsProdLines.Channel_Market_Coverage__c = cms.id;
            cmsProdLines.Product_Group__c = pg.Name;
            cmsProdLines.Product__c = prod.Id;
            cmsProdLines.Division__c = pg.Division__c;
            cmsProdLines.Business_Unit__c = pg.Business_Unit__c;
            insert cmsProdLines;           
         
        
       // Code for Apex Class - ClsPISChannelMarketCoverageProdLine
        Channel_Market_Coverage_Product_Lines__c cmsPrLine = new Channel_Market_Coverage_Product_Lines__c ();
            apexpages.currentpage().getparameters().put('retURL', cmsProdLines.Id);
            ApexPages.StandardController cs = new ApexPages.StandardController(cmsProdLines);      
        ClsPISChannelMarketCoverageProdLine cmsPrLine1 = new ClsPISChannelMarketCoverageProdLine(cs);
            cmsPrLine1.GoBack();         
        List<ClsPISChannelMarketCoverageProdLine.PISNode> products = new List<ClsPISChannelMarketCoverageProdLine.PISNode>();
        ClsPISChannelMarketCoverageProdLine.PISNode objPIS = new ClsPISChannelMarketCoverageProdLine.PISNode();
            objPIS.cid = prod.Cid__c;
            objPIS.englishDescription = 'englishDescription';
            objPIS.languageSpecificDescription = 'languageSpecfDesption';
            products.add(objPIS);   
            ClsPISChannelMarketCoverageProdLine.ProductResult objProdResult = new ClsPISChannelMarketCoverageProdLine.ProductResult();    
            ClsPISChannelMarketCoverageProdLine.ProductResult objResult = ClsPISChannelMarketCoverageProdLine.addProducts(cmsProdLines.Id,products);
      
        Test.StopTest();       
     }
     
      static testMethod void channelMarketScopeMethod1(){
        
        User u1 = createTestUser1();
            insert u1;
        Account a = createAccount1();
            insert a;  
        Product2 prod = createProduct();
           
        Product2 prod1 = createProduct1();
           
        List<Product2> pr = new List<Product2>();
        pr.add(prod);
        pr.add(prod1);
        insert pr;
        
        Product_Group__c pg = createProductGroup();
           
        Product_Group__c pg1 = createProductGroup1();
           
        List<Product_Group__c> prodg = new List<Product_Group__c>();
        prodg.add(pg);
        prodg.add(pg1);
        insert prodg;
        
        Channel_Market_Coverage__c cms = createChannelPartMarScope();
            cms.Account__c = a.id; 
            cms.Product_Line1__c += prod.Name + ';' + prod1.Name;
            cms.BU_Covered__c += pg.Business_Unit__c + ';' + pg1.Business_Unit__c;    
            cms.PG_Covered__c += pg.Division__c + ';' + pg1.Division__c;   
            insert cms;       
        Channel_Market_Coverage_Product_Lines__c cmsProdLines1 = createCMSProdLines1();
            cmsProdLines1.Channel_Market_Coverage__c = cms.id;
            cmsProdLines1.Product_Group__c = pg1.Name;
            cmsProdLines1.Product__c = prod1.Id;
            cmsProdLines1.Division__c = pg1.Division__c;
            cmsProdLines1.Business_Unit__c = pg1.Business_Unit__c;
            insert cmsProdLines1;
          Test.StartTest();  
          // Code for Apex Class - ClsChannelMarketCoverageEdit     
            apexpages.currentpage().getparameters().put('id', cmsProdLines1.Id);
            ApexPages.StandardController cs1 = new ApexPages.StandardController(cmsProdLines1);      
        ClsChannelMarketCoverageEdit cmsPrLineEdit = new ClsChannelMarketCoverageEdit(cs1);
            cmsPrLineEdit.GoBack();         
        ClsChannelMarketCoverageEdit.PISNode editPIS = new ClsChannelMarketCoverageEdit.PISNode();
            editPIS.cid = prod.Cid__c;
            editPIS.englishDescription = 'englishDescription';
            editPIS.languageSpecificDescription = 'languageSpecfDesption';
             
            ClsChannelMarketCoverageEdit.ProductResult objProdResult1 = new ClsChannelMarketCoverageEdit.ProductResult();    
            ClsChannelMarketCoverageEdit.ProductResult objResult1 = ClsChannelMarketCoverageEdit.replaceProduct(cmsProdLines1.Id,editPIS);
       
           
        Test.stopTest();
       }
        
        static testMethod void channelMarketScopeMethod2(){
        Test.StartTest();
        
        User u1 = createTestUser1();
            insert u1;
        Account a1 = createAccount2();
            insert a1;
        Product2 prod = createProduct();
            insert prod;    
        Product2 prod1 = createProduct1();
            insert prod1;     
        Product_Group__c pg = createProductGroup();
            insert pg;   
        Product_Group__c pg1 = createProductGroup1();
            insert pg1;  
        Channel_Market_Coverage__c cms1 = createChannelPartMarScope1();
            cms1.Account__c = a1.id;          
            insert cms1;
        Channel_Market_Coverage_Product_Lines__c cmsProdLines1 = createCMSProdLines1();
            cmsProdLines1.Channel_Market_Coverage__c = cms1.id;
            cmsProdLines1.Product_Group__c = pg.Name;
            cmsProdLines1.Product__c = prod.Id;
            cmsProdLines1.Division__c = pg.Division__c;
            cmsProdLines1.Business_Unit__c = pg.Business_Unit__c;
            insert cmsProdLines1;     
            
        // Code for Apex Class - ClsChannelMarketCoverageEdit     
            apexpages.currentpage().getparameters().put('id', cmsProdLines1.Id);
            ApexPages.StandardController cs1 = new ApexPages.StandardController(cmsProdLines1);      
        ClsChannelMarketCoverageEdit cmsPrLineEdit = new ClsChannelMarketCoverageEdit(cs1);
            cmsPrLineEdit.GoBack();         
        ClsChannelMarketCoverageEdit.PISNode editPIS = new ClsChannelMarketCoverageEdit.PISNode();
            editPIS.cid = prod.Cid__c;
            editPIS.englishDescription = 'englishDescription';
            editPIS.languageSpecificDescription = 'languageSpecfDesption';
         
        ClsChannelMarketCoverageEdit.ProductResult objProdResult1 = new ClsChannelMarketCoverageEdit.ProductResult();    
        ClsChannelMarketCoverageEdit.ProductResult objResult1 = ClsChannelMarketCoverageEdit.replaceProduct(cmsProdLines1.Id,editPIS);
                  
        
        Test.stopTest();
        }
        
        static testMethod void channelMarketScopeMethod3(){
        Test.StartTest();
        
        User u1 = createTestUser1();
            insert u1;
        Account a1 = createAccount2();
            insert a1;
        Product2 prod = createProduct();
            insert prod;    
        Product2 prod1 = createProduct1();
            insert prod1;     
        Product_Group__c pg = createProductGroup();
            insert pg;   
        Product_Group__c pg1 = createProductGroup1();
            insert pg1;  
        Channel_Market_Coverage__c cms2 = createChannelPartMarScope2();
            cms2.Account__c = a1.id;    
            insert cms2;     
        ID DP = Schema.SObjectType.Joint_Business_Plan__c.getRecordTypeInfosByName().get('1. Distributor as Partner').getRecordTypeId();
        Joint_Business_Plan__c jbp = createJBP();
        jbp.RecordtypeId = DP;
        jbp.Channel_Market_Coverage__c = cms2.Id;
        insert jbp;
        
        ID EP = Schema.SObjectType.Channel_Business_Review__c.getRecordTypeInfosByName().get('End-Period Business Review Detail').getRecordTypeId();
        Channel_Business_Review__c CBR = createCBR();
        CBR.Account__c=a1.Id;
        CBR.Joint_Business_Plan__c=jbp.Id; 
        CBR.RecordtypeId =  EP;
        insert CBR;
        
        Channel_Market_Coverage_Product_Lines__c cmsProdLines = createCMSProdLines();
            cmsProdLines.Channel_Market_Coverage__c = cms2.id;
            cmsProdLines.Product__c = prod.Id;
            cmsProdLines.Product_Group__c = pg.Name;
            cmsProdLines.Division__c = pg.Division__c;
            cmsProdLines.Business_Unit__c = pg.Business_Unit__c;           
          //  insert cmsProdLines;           
        Channel_Market_Coverage_Product_Lines__c cmsProdLines1 = createCMSProdLines1();
            cmsProdLines1.Channel_Market_Coverage__c = cms2.id;
            cmsProdLines1.Product_Group__c = NULL;
            cmsProdLines1.Product__c = NULL; 
            cmsProdLines1.Division__c = NULL;
            cmsProdLines1.Business_Unit__c = NULL;         
    //        insert cmsProdLines1; 
    
        List<Channel_Market_Coverage_Product_Lines__c> cms = new List<Channel_Market_Coverage_Product_Lines__c>();
        cms.add(cmsProdLines);
        cms.add(cmsProdLines1);
        insert cms;
       
        Test.stopTest();
        }
        
        static testMethod void channelMarketScopeMethod4(){
        Test.StartTest();
        
        User u1 = createTestUser1();
            insert u1;
        Account a1 = createAccount2();
            insert a1;
        Product2 prod = createProduct();
            insert prod;    
        Product2 prod1 = createProduct1();
            insert prod1;     
        Product_Group__c pg = createProductGroup();
            insert pg;   
        Product_Group__c pg1 = createProductGroup1();
            insert pg1;  
        Channel_Market_Coverage__c cms3 = createChannelPartMarScope3();
            cms3.Account__c = a1.id;         
            cms3.Product_Line1__c += prod.Name + ';' + prod1.Name;
            cms3.BU_Covered__c += pg.Business_Unit__c + ';' + pg1.Business_Unit__c;    
            cms3.PG_Covered__c += pg.Division__c + ';' + pg1.Division__c;  
            insert cms3;
        Channel_Market_Coverage_Product_Lines__c cmsProdLines1 = createCMSProdLines1();
            cmsProdLines1.Channel_Market_Coverage__c = cms3.id;
            cmsProdLines1.Product_Group__c = pg1.Name;
            cmsProdLines1.Product__c = prod1.Id;
            cmsProdLines1.Division__c = pg1.Division__c;
            cmsProdLines1.Business_Unit__c = pg1.Business_Unit__c;
            insert cmsProdLines1;
        
        //Code for Apex Class - ClsCMSProductLinesList  
          apexpages.currentpage().getparameters().put('Id', cms3.Id);
          ApexPages.StandardController stdCtrllerCMSList = new ApexPages.StandardController(cms3);        
          ClsCMSProductLinesList cmsProdLineList = new ClsCMSProductLinesList(stdCtrllerCMSList);
          cmsProdLineList.save();
          cmsProdLineList.cancel();     
           
        Test.stopTest();
        }
     
}