src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>GUID__c</fullName>
        <externalId>true</externalId>
        <label>GUID</label>
        <length>9</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>

    <fields>
        <fullName>Strengths__c</fullName>
        <description>R5 - Strenghts</description>
        <inlineHelpText>Describe strengths related to this partner&apos;s overall business</inlineHelpText>
        <label>Strengths</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
 <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Channel_Market_Coverage__c.object
<CustomObject>
    <description>R5 - Custom Object to define Channel Market Coverage</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>R5 - Master Detail Relationship to Account Standard Object</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Channel_Market_Coverages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <description>R5 Division</description>
        <inlineHelpText>Pick division(s) focused in this market scope (and connected business plan/review)</inlineHelpText>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>DM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PG</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <!--fields>
        <fullName>Focussed_Industry1__c</fullName>
        <description>R5 - New Focussed Industry value -Combination of Industry usage level1, level2 and level3</description>
        <inlineHelpText>Pick all the industries currently served and targeted in the upcoming 3 years. Pick only industries with sales focus, not the ones that are served reactively.</inlineHelpText>
        <label>Focussed Industry</label>
        <picklist>
            <picklistValues>
                <fullName>BLD - BLD.8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BLD - BLD.9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BLD - BLD.10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.1 - IND.1.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.1 - IND.1.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.7 - IND.7.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.7 - IND.7.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.7 - IND.7.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.10 - IND.10.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.10 - IND.10.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.10 - IND.10.4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.10 - IND.10.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.11 - IND.11.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.11 - IND.11.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.12 - IND.12.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.12 - IND.12.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.12 - IND.12.3</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields-->
    <fields>
        <fullName>Primary_Channel_Class__c</fullName>
        <description>R5-Picklist contains Primary Channel Class values</description>
        <inlineHelpText>Select the primary channel class for this market scope</inlineHelpText>
        <label>Channel Class</label>
        <picklist>
            <picklistValues>
                <fullName>Engineering, Procurement and Construction (EPC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distributor (DIS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installer (INST)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Original Equipment Manufacturer (OEM)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panel Builder (PBL)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Provider (SPRO)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System Integrator (SYIN)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Distributor (TDIS)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Channel Partner Market Scope</label>
    <nameField>
        <label>Market Scope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partner Market Scope</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <!--webLinks>
        <fullName>Change_Product_Line</fullName>
        <availability>online</availability>
        <description>R5 - Change the Product through PIS Tree</description>
        <displayType>button</displayType>
        <height>600</height>
        <linkType>page</linkType>
        <masterLabel>Change Product Line</masterLabel>
        <openType>sidebar</openType>
        <page>EditChannelMarketPIS</page>
        <protected>false</protected>
    </webLinks-->
</CustomObject>

src/objects/Competitors__c.object
<CustomObject>
    <description>R5 - New Custom object Competitors</description>
    <!--fields>
        <fullName>Focused_Industry__c</fullName>
        <description>R5 - Focused Industry -Combination of Industry usage level1 ,level2 and level3</description>
        <label>Focused Industry</label>
        <picklist>
            <picklistValues>
                <fullName>Building - Residential Buildings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building - Commercial &amp; institutional Buildings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building - Industrial Buildings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Automotive - Automotive (Vehicles - OEM)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Automotive - Automotives (Parts - Tier1)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Chemical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Petrochemicals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Food and Beverage - Ingredients</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Food and Beverage - Sugar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Food and Beverage - Bakery &amp; Confectionery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Food and Beverage - Fruit &amp; Vegetables</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Food and Beverage - Dairy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Food and Beverage - Meat, Poultry, Seafood</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Food and Beverage - Beverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Food and Beverage - Other Food &amp; Beverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Printing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Textile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Metals - Aluminium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Metals - Steel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Metals - Other Metals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Electronics and Semiconductors (3C)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Mining and Minerals - Underground Mining including Hoisting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Mining and Minerals - Open Pit Mining</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Mining and Minerals - Grinding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Mining and Minerals - Mineral Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Cement and Glass - Cement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Cement and Glass - Glass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Oil and Gas Industry -Oil and Gas - Offshore Upstream</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Oil and Gas Industry -Oil and Gas - Onshore Upstream</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Oil and Gas Industry - Refining</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields-->
    <fields>
        <fullName>Joint_Business_Plan__c</fullName>
        <description>R5 - Joint Business Plan</description>
        <label>Business Plan</label>
        <referenceTo>Joint_Business_Plan__c</referenceTo>
        <relationshipLabel>Competitors</relationshipLabel>
        <relationshipName>Competitors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Strengths__c</fullName>
        <description>R5 - Strengths</description>
        <label>Competitor Strengths</label>
        <length>256</length>
        <type>LongTextArea</type>
    </fields>
    <label>Competitor</label>
    <nameField>
        <displayFormat>COMPET-NAME-{0000}</displayFormat>
        <label>Competitors  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Joint_Business_Plan__c.object
<CustomObject>
    <description>R5 Joint Business Plan</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R5 Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Joint_Business_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Channel_Market_Coverage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R5 - Lookup to Channel Market Coverage</description>
        <inlineHelpText>Channel &quot;Market scope&quot; this business plan is related to</inlineHelpText>
        <label>Market Scope</label>
        <referenceTo>Channel_Market_Coverage__c</referenceTo>
        <relationshipLabel>Channel Partner Business Plans</relationshipLabel>
        <relationshipName>Joint_Business_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>End Date Field</description>
        <inlineHelpText>The date the plan ends to be effective, typically Dec31st of the year</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Channel_Class__c</fullName>
        <description>R5 - Primary Channel Class</description>
        <formula>TEXT(Channel_Market_Coverage__r.Primary_Channel_Class__c )</formula>
        <inlineHelpText>Presents the channel class defined in &quot;Market scope&quot; where possible update must be done.</inlineHelpText>
        <label>Channel Class</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Start Date Field</description>
        <inlineHelpText>The date the plan starts to be effective, typically Jan1st of the year</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>R5 - Status</description>
        <inlineHelpText>Turn active when content agreed with partner and all mandatory fields are filled. Alternatively send for approval. Change back to draft for updating content that is locked for editing for active plan.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Strengths__c</fullName>
        <description>R5 - Strengths</description>
        <inlineHelpText>Describe the strengths when the partner and ABB are co-operating as described in this plan</inlineHelpText>
        <label>Strengths</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Channel Partner Business Plan</label>
    <nameField>
        <label>Business Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partner Business Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Joint_Business_Team__c.object
<CustomObject>
    <description>R5 Joint Business Team</description>
    <fields>
        <fullName>Access__c</fullName>
        <description>R5 Access</description>
        <label>Access</label>
        <picklist>
            <picklistValues>
                <fullName>Read/Write</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read-Only</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Joint_Business_Plan__c</fullName>
        <description>R5 Joint Business Plan</description>
        <label>Business Plan</label>
        <referenceTo>Joint_Business_Plan__c</referenceTo>
        <relationshipLabel>Channel Partner Business Plan Teams</relationshipLabel>
        <relationshipName>Joint_Business_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team_Role__c</fullName>
        <description>R5 Team Role</description>
        <label>Team Role</label>
        <picklist>
            <picklistValues>
                <fullName>Account Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Service Responsible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Channel Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GAM/SAM Account Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Sales Marketing Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Sales Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Support</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R5 User</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Joint_Business_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Channel Partner Business Plan Team</label>
    <nameField>
        <displayFormat>JBP-TEAMROLE-{0000}</displayFormat>
        <label>Business Plan Team</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channel Partner Business Plan Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ClsTriggerCompetitors_Test.cls
/**
 * ApexClass -  Test class Test_ClsTriggerCompetitors
 * Release R5
 * @author  Ayiravalli Arasu (Accenture)
 * @created 2016-03-22
 * @version 1.0
 * Description: Test class for - ClsTriggerCompetitors
 * Created 
 */
 
 @isTest
private class ClsTriggerCompetitors_Test{
      public static User createTestUser1() {
        User u = new User();
        u.FirstName ='haobo';
        u.LastName = 'song';
        u.Username = 'test123ABB1237@test123ABB1237.com';
        u.Alias = 'mtst4';
        u.Email = 'mtester1@company.com';
        u.CommunityNickname = u.Alias;
        u.ProfileId = [Select Id from Profile Where Name = 'ABB Sales Standard Profile' limit 1].Id;
        u.TimeZoneSidKey = 'America/Chicago';
        u.LocaleSidKey = 'en_US';
        u.EmailEncodingKey = 'UTF-8';
        u.LanguageLocaleKey = 'en_US';
        u.ManagerId = UserInfo.getUserId();
        return u;
      }
      
      public static Account createAccount1(){
        Account a = new Account();
        a.Name = 'test';
        a.BillingStreet = 'street'; 
        a.BillingCity = 'city';
        a.BillingCountry = 'Germany';
        a.GUID__c = '1234sghf';
        return a;
      }
      
      public static Channel_Market_Coverage__c createChannelMarkCov(){
        Channel_Market_Coverage__c mc = new Channel_Market_Coverage__c ();
        mc.Name = 'Test Market Coverage'; 
        mc.Division__c = 'PA';
        mc.Primary_Channel_Class__c ='Installer (INST)';
        mc.Focussed_Industry1__c = 'Building - Residential Buildings;Industry - Petrochemicals;Industry - Textile';  
        return mc;
      }   
    
      public static Joint_Business_Plan__c createJointBussPlan(){
        Joint_Business_Plan__c jbp = new Joint_Business_Plan__c();
        jbp.Name = 'Test Joint Business Plan'; 
        jbp.Start_Date__c = Date.valueOf(system.now());
        jbp.End_Date__c = Date.valueOf(system.now());
        jbp.Status__c='Active';
        return jbp;
      }
      
      public static Joint_Business_Team__c createJointBussPlanTeam1(){
        Joint_Business_Team__c jbpt1 = new Joint_Business_Team__c();
        jbpt1.Access__c= 'Read/Write';
        jbpt1.Team_Role__c='GAM/SAM Account Manager';
        return jbpt1;
      }
      
      public static Competitors__c createComp(){
          Competitors__c c = new Competitors__c();
          c.Strengths__c ='Test';
          return c;
      }
      
      public static AccountTeamMember createAccTeam1(){
         AccountTeamMember atm=new AccountTeamMember();
         atm.TeamMemberRole= 'Sales Support';
         return atm;
    } 
      
      static testMethod void Method1(){
          Test.StartTest();
          User u1 = createTestUser1();
            insert u1;
          Account a = createAccount1();
            insert a; 
            
           AccountTeamMember atm1 = createAccTeam1();
            atm1.UserId = u1.Id;
            atm1.AccountId = a.Id;
            insert atm1; 
          Channel_Market_Coverage__c cmc1 = createChannelMarkCov();
            cmc1.Account__c = a.id;
            insert cmc1;           
          Joint_Business_Plan__c jbp1 = createJointBussPlan();
            jbp1.Account__c = a.id;
            jbp1.Channel_Market_Coverage__c = cmc1.id;            
            insert jbp1; 
            jbp1.Start_Date__c = Date.valueOf(system.now());
            Update jbp1;
          Joint_Business_Team__c JBPT1 = createJointBussPlanTeam1();
            JBPT1.Joint_Business_Plan__c = jbp1.id;
            JBPT1.User__c = u1.id; 
            insert JBPT1;
          Competitors__c c1= createComp();
            c1.Joint_Business_Plan__c = jbp1.Id;
            insert c1;
            jbp1.Status__c ='Closed';
            system.runAs(u1){    
            try{
                update jbp1;
                delete c1;
            }Catch(exception e){}
            }
              
          Test.StopTest();
      }
         

}