src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field is to e used to control access to the record, as part of the GIS Team Operations.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Company_Status__c</fullName>
        <label>Account Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Clearing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Out of Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Changed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not a Legal Entity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

   <fields>
        <fullName>Reason_for_Deactivation__c</fullName>
        <label>Reason for Deactivation</label>
        <picklist>
            <picklistValues>
                <fullName>Out of Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Successor_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>In case the current Company has been merged to (has been acquired by) another Company. Updates are provided by the GIS Team.</inlineHelpText>
        <label>Successor Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Succesor Company)</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Default</fullName>
        <active>true</active>
        <description>Before creating any new Account, search in SFDC. If the Account exists then use this Account.Initial record type to be selected to properly trigger the clearing and approval process for GIS/Masterdata.</description>
        <label>Default</label>
    </recordTypes>
 <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Group__c.object
<CustomObject>
</CustomObject>

src/objects/Safe_Island_Assessments__c.object
<CustomObject>
    <description>R4-Safe Island Assessments</description>
    <fields>
        <fullName>AccountCustomer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>R4 - Safe Island</description>
        <label>Account Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Safe Island Assessments</relationshipLabel>
        <relationshipName>Safe_Island_Assessments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulgaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia, Plurinational State of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia and Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Czech Republic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Croatia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colombia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Congo, Democratic Republic of the</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cameroon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Costa Rica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cote d&apos;Ivoire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cyprus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denmark</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dominican Republic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ecuador</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>El Salvador</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sweden</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Credit_Assessment__c</fullName>
        <description>R4 - Safe Island</description>
        <label>Credit Assessment</label>
        <picklist>
            <picklistValues>
                <fullName>Weak (Credit rating 1 - 2)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Average (Credit rating 3)</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Strong (Credit rating 4)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PG__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>R4 - This field refers to PG.</description>
        <label>PG</label>
        <referenceTo>Product_Group__c</referenceTo>
        <relationshipLabel>Safe Island Assessments (PG)</relationshipLabel>
        <relationshipName>Product_Groups</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Safe Island Assessments</label>
    <nameField>
        <displayFormat>SIA-{00000000}</displayFormat>
        <label>Safe Island Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Safe Island Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Validation_Override__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This setting allows user to be excluded from validation rules and triggers</description>
    <fields>
        <fullName>Account_Merge_Override__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Account Merge Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Exclude__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If this field is set to true, the validation will not be applicable for the user</description>
        <inlineHelpText>If this field is set to true, the validation will not be applicable for the user</inlineHelpText>
        <label>Exclude</label>
        <type>Checkbox</type>
    </fields>
    <label>Validation Override</label>
</CustomObject>

src/classes/TrgAccount_AU_setSuccessorCompany_Test.cls
/**
*  This test class used to test class ExtRecalculateBudget.
*
@author MohanRaj
@created 2016-02-1
@version 1.0   
@since 28.0
*
@changelog
* coverage 85% 
* 
* 
2014-10-10 MohanRaj <Mohanraj.Kasinathan@accenture.com>
* - Created
*/
@isTest
private class TrgAccount_AU_setSuccessorCompany_Test {
    
    static Profile p = [SELECT Id FROM Profile WHERE Name= 'ABB Sales Standard Profile']; 
    static User u = new User(Alias = 'sysadmin', Email='SysAdmin@Accenture.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='admintest@accenture.com');    

    static Profile pi = [SELECT Id FROM Profile WHERE Name='ABB GIS Integration'];
    static User ui = new User(Alias = 'gistest', Email='gisInt@Accenture.com', 
    EmailEncodingKey='UTF-8', LastName='GIS Integration', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = pi.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='gis@Accenture.com');            

    
    static testMethod void myUnitTest_scenario1() {
               
        System.runAs(u) {

        Id GISApprovedID = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get('GIS Approved').getRecordTypeId();
        Id DefaultID = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get('Default').getRecordTypeId();
        Id EXtNonBuyingID = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get('External Non-Buying Account').getRecordTypeId();

        List<Account> lstAccount = new List<Account>();
        
        Account acc=new Account();
        acc.RecordTypeId=EXtNonBuyingID;
        acc.Active__c=true;
        acc.Name = 'AMP Foundries Inc';
        acc.BillingStreet = 'Teststr. 1';
        acc.BillingCountry = 'China';
        acc.BillingCity = 'Musterstadt';        
        acc.ShippingCountry = 'China';
        acc.ShippingStreet  = 'Teststr. 1';
        acc.ShippingCity = 'Musterstadt';
        acc.Company_Status__c='Open';        
        lstAccount.add(acc);
        
        Account acc2 =new Account();
        acc2.RecordTypeId=EXtNonBuyingID;
        acc2.Active__c=true;
        acc2.Name = 'AMP Foundries Inc';
        acc2.BillingStreet = 'Teststr. 1';
        acc2.BillingCountry = 'China';
        acc2.BillingCity = 'Musterstadt';        
        acc2.ShippingCountry = 'China';
        acc2.ShippingStreet  = 'Teststr. 1';
        acc2.ShippingCity = 'Musterstadt';
        acc2.Company_Status__c='Open';        
        lstAccount.add(acc2);
        
        insert lstAccount; 
        
        Product_Group__c pg = new Product_Group__c();
        pg.Business_Unit__c = 'Test';
        pg.Name = 'TestName';
        pg.Division__c = 'DZ';
        insert pg;
        
        List<Safe_Island_Assessments__c> lstSIA = new List<Safe_Island_Assessments__c>();   
        Safe_Island_Assessments__c sia = new Safe_Island_Assessments__c();
        sia.PG__c = pg.Id;
        sia.Country__c = 'Sweden';
        sia.Credit_Assessment__c ='Weak (Credit rating 1 - 2)';
        sia.AccountCustomer__c = lstAccount[0].Id;
        insert sia; 
    
        Safe_Island_Assessments__c sia1 = new Safe_Island_Assessments__c();
        sia1.PG__c = pg.Id;
        sia1.Country__c = 'Sweden';
        sia1.Credit_Assessment__c ='Strong (Credit rating 4)';
        sia1.AccountCustomer__c = lstAccount[1].Id;
        insert sia1; 
         
        test.startTest();        
        
        lstAccount[0].Successor_Company__c = acc2.Id; 
        lstAccount[0].Reason_for_Deactivation__c = 'Duplicate';
        lstAccount[0].Company_Status__c = 'Duplicate';
        lstAccount[0].Active__c=true;
        update lstAccount[0];         
        
        Test.stopTest();}
        
    }   
    
    static testMethod void myUnitTest_scenario2() {
               
        System.runAs(u) {

        Id GISApprovedID = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get('GIS Approved').getRecordTypeId();
        Id DefaultID = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get('Default').getRecordTypeId();
        Id EXtNonBuyingID = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get('External Non-Buying Account').getRecordTypeId();

        List<Account> lstAccount = new List<Account>();
        
        Account acc=new Account();
        acc.RecordTypeId=EXtNonBuyingID;
        acc.Active__c=true;
        acc.Name = 'AMP Foundries Inc';
        acc.BillingStreet = 'Teststr. 1';
        acc.BillingCountry = 'China';
        acc.BillingCity = 'Musterstadt';        
        acc.ShippingCountry = 'China';
        acc.ShippingStreet  = 'Teststr. 1';
        acc.ShippingCity = 'Musterstadt';
        acc.Company_Status__c='Open';        
        lstAccount.add(acc);
                
        Account acc5 =new Account();
        acc5.RecordTypeId=DefaultID;
        acc5.Active__c=true;
        acc5.Name = 'AMP Foundries Inc';
        acc5.BillingStreet = 'Teststr. 1';
        acc5.BillingCountry = 'China';
        acc5.BillingCity = 'Musterstadt';
        acc5.ShippingCountry = 'China';
        acc5.ShippingStreet  = 'Teststr. 1';
        acc5.ShippingCity = 'Musterstadt';
        acc5.Company_Status__c='Open';
        lstAccount.add(acc5);
                
        insert lstAccount; 
        
        Product_Group__c pg = new Product_Group__c();
        pg.Business_Unit__c = 'Test';
        pg.Name = 'TestName';
        pg.Division__c = 'DZ';
        insert pg;
        
        List<Safe_Island_Assessments__c> lstSIA = new List<Safe_Island_Assessments__c>();   
        Safe_Island_Assessments__c sia = new Safe_Island_Assessments__c();
        sia.PG__c = pg.Id;
        sia.Country__c = 'Sweden';
        sia.Credit_Assessment__c ='Weak (Credit rating 1 - 2)';
        sia.AccountCustomer__c = lstAccount[0].Id;
        insert sia; 
    
        Safe_Island_Assessments__c sia1 = new Safe_Island_Assessments__c();
        sia1.PG__c = pg.Id;
        sia1.Country__c = 'Sweden';
        sia1.Credit_Assessment__c ='Strong (Credit rating 4)';
        sia1.AccountCustomer__c = lstAccount[1].Id;
        insert sia1; 
         
        test.startTest();
        
        lstAccount[0].Successor_Company__c = acc5.Id; 
        lstAccount[0].Reason_for_Deactivation__c = 'Out of Business';
        lstAccount[0].Company_Status__c = 'Out of Business';
        lstAccount[0].Active__c=true;
        update lstAccount[0];     
        
        
        Test.stopTest();}
        
    }   
    
    static testMethod void myUnitTest_scenario3() {
               
        System.runAs(u) {

        Id GISApprovedID = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get('GIS Approved').getRecordTypeId();
        Id DefaultID = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get('Default').getRecordTypeId();
        Id EXtNonBuyingID = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get('External Non-Buying Account').getRecordTypeId();

        List<Account> lstAccount = new List<Account>();
        
        Account acc=new Account();
        acc.RecordTypeId=EXtNonBuyingID;
        acc.Active__c=true;
        acc.Name = 'AMP Foundries Inc';
        acc.BillingStreet = 'Teststr. 1';
        acc.BillingCountry = 'China';
        acc.BillingCity = 'Musterstadt';        
        acc.ShippingCountry = 'China';
        acc.ShippingStreet  = 'Teststr. 1';
        acc.ShippingCity = 'Musterstadt';
        acc.Company_Status__c='Open';        
        lstAccount.add(acc);
        
        Account acc6 =new Account();
        acc6.RecordTypeId=GISApprovedID;
        acc6.Active__c=true;
        acc6.Name = 'AMP Foundries Inc';
        acc6.BillingStreet = 'Teststr. 1';
        acc6.BillingCountry = 'China';
        acc6.BillingCity = 'Musterstadt';
        acc6.ShippingCountry = 'China';
        acc6.ShippingStreet  = 'Teststr. 1';
        acc6.ShippingCity = 'Musterstadt';
        acc6.Company_Status__c='Approved';
        lstAccount.add(acc6);
        
        insert lstAccount; 
        
        Product_Group__c pg = new Product_Group__c();
        pg.Business_Unit__c = 'Test';
        pg.Name = 'TestName';
        pg.Division__c = 'DZ';
        insert pg;
        
        List<Safe_Island_Assessments__c> lstSIA = new List<Safe_Island_Assessments__c>();   
        Safe_Island_Assessments__c sia = new Safe_Island_Assessments__c();
        sia.PG__c = pg.Id;
        sia.Country__c = 'Sweden';
        sia.Credit_Assessment__c ='Weak (Credit rating 1 - 2)';
        sia.AccountCustomer__c = lstAccount[0].Id;
        insert sia; 
    
        Safe_Island_Assessments__c sia1 = new Safe_Island_Assessments__c();
        sia1.PG__c = pg.Id;
        sia1.Country__c = 'Sweden';
        sia1.Credit_Assessment__c ='Strong (Credit rating 4)';
        sia1.AccountCustomer__c = lstAccount[1].Id;
        insert sia1; 
         
        test.startTest();
        
        lstAccount[0].Successor_Company__c = acc6.Id; 
        lstAccount[0].Reason_for_Deactivation__c = 'Out of Business';
        lstAccount[0].Company_Status__c = 'Out of Business';
        lstAccount[0].Active__c=true;
        update lstAccount[0];               
        
        Test.stopTest();}
        
    }   
    
    static testMethod void myUnitTest_GISapproved1() {
        
        Validation_Override__c vc = new Validation_Override__c();
        vc.Account_Merge_Override__c = true;
        vc.Exclude__c = true;
        insert vc;
                
        System.runAs(ui) {

        Id GISApprovedID = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get('GIS Approved').getRecordTypeId();
        Id DefaultID = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get('Default').getRecordTypeId();
        Id EXtNonBuyingID = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get('External Non-Buying Account').getRecordTypeId();

        List<Account> lstAccount = new List<Account>();     
        
        Account acc2 =new Account();
        acc2.RecordTypeId=GISApprovedID;
        acc2.Active__c=true;
        acc2.Name = 'AMP Foundries Inc';
        acc2.BillingStreet = 'Teststr. 1';
        acc2.BillingCountry = 'China';
        acc2.BillingCity = 'Musterstadt';        
        acc2.ShippingCountry = 'China';
        acc2.ShippingStreet  = 'Teststr. 1';
        acc2.ShippingCity = 'Musterstadt';
        acc2.Company_Status__c='Open';        
        lstAccount.add(acc2);
        
        Account acc3 =new Account();
        acc3.RecordTypeId=GISApprovedID;
        acc3.Active__c=true;
        acc3.Name = 'AMP Foundries Inc';
        acc3.BillingStreet = 'Teststr. 1';
        acc3.BillingCountry = 'China';
        acc3.BillingCity = 'Musterstadt';        
        acc3.ShippingCountry = 'China';
        acc3.ShippingStreet  = 'Teststr. 1';
        acc3.ShippingCity = 'Musterstadt';
        acc3.Company_Status__c='Open';        
        lstAccount.add(acc3);
        insert lstAccount; 
         
        test.startTest();

        lstAccount[0].Successor_Company__c = acc3.Id; 
        lstAccount[0].Reason_for_Deactivation__c = 'Duplicate';
        lstAccount[0].Company_Status__c = 'Duplicate';
        lstAccount[0].Active__c=true;
        update lstAccount[0];         
        
        Test.stopTest();}       
        
    }  
    
    static testMethod void myUnitTest_GISapproved2() {
        
        Validation_Override__c vc = new Validation_Override__c();
        vc.Account_Merge_Override__c = true;
        vc.Exclude__c = true;
        insert vc;
                
        System.runAs(ui) {

        Id GISApprovedID = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get('GIS Approved').getRecordTypeId();
        Id DefaultID = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get('Default').getRecordTypeId();
        Id EXtNonBuyingID = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get('External Non-Buying Account').getRecordTypeId();

        List<Account> lstAccount = new List<Account>();     
        
        Account acc2 =new Account();
        acc2.RecordTypeId=DefaultID;
        acc2.Active__c=true;
        acc2.Name = 'AMP Foundries Inc';
        acc2.BillingStreet = 'Teststr. 1';
        acc2.BillingCountry = 'China';
        acc2.BillingCity = 'Musterstadt';        
        acc2.ShippingCountry = 'China';
        acc2.ShippingStreet  = 'Teststr. 1';
        acc2.ShippingCity = 'Musterstadt';
        acc2.Company_Status__c='Open';        
        lstAccount.add(acc2);
        
        Account acc3 =new Account();
        acc3.RecordTypeId=GISApprovedID;
        acc3.Active__c=true;
        acc3.Name = 'AMP Foundries Inc';
        acc3.BillingStreet = 'Teststr. 1';
        acc3.BillingCountry = 'China';
        acc3.BillingCity = 'Musterstadt';        
        acc3.ShippingCountry = 'China';
        acc3.ShippingStreet  = 'Teststr. 1';
        acc3.ShippingCity = 'Musterstadt';
        acc3.Company_Status__c='Open';        
        lstAccount.add(acc3);
        insert lstAccount; 
         
        test.startTest();

        lstAccount[0].Successor_Company__c = acc3.Id; 
        lstAccount[0].Reason_for_Deactivation__c = 'Out of Business';
        lstAccount[0].Company_Status__c = 'Out of Business';
        lstAccount[0].Active__c=true;
        update lstAccount[0];         
        
        Test.stopTest();}       
        
    }  
    
 
}