src/objects/Account.object
<CustomObject>

    <recordTypes>
        <fullName>Default</fullName>
        <active>true</active>
        <description>Before creating any new Account, search in SFDC. If the Account exists then use this Account.Initial record type to be selected to properly trigger the clearing and approval process for GIS/Masterdata.</description>
        <label>Default</label>
    </recordTypes>
 <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/APTS_Capture_LSO_Input_Config_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom object to configure settings like dropdown list values etc. for Capture LSO Input page while creating MSPA or Quotation from Account or Opportunity.</description>
    <label>Capture LSO Input Config Settings</label>
</CustomObject>

src/objects/APTS_LP_Local_Customer_Reference_Data__c.object
<CustomObject>
    <description>Object to hold the reference data related to customer (account). (ABB-LP)</description>
    <fields>
        <fullName>APTS_Country__c</fullName>
        <description>Field to capture country for the LSO data.</description>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>ES</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>APTS_External_ID__c</fullName>
        <description>External Id to match the unique set. Value of this field will be SAP ID + Sales organisation + Distribution Channel.</description>
        <externalId>true</externalId>
        <label>APTS External ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_LP_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Local Operational Data</relationshipLabel>
        <relationshipName>Local_Customer_Reference_Data</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>APTS_LP_Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <picklist>
            <picklistValues>
                <fullName>BT</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>DT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>APTS_LP_Incoterms__c</fullName>
        <label>Incoterms</label>
        <picklist>
            <picklistValues>
                <fullName>CFR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DDP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DAF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DDU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DEQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FOB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZFE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EXW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZVR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>APTS_LP_Local_Channel__c</fullName>
        <label>Local Channel</label>
        <picklist>
            <picklistValues>
                <fullName>P1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P6</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>APTS_LP_SAP_Customer_ID__c</fullName>
        <description>Placeholder field to hold the value of customer ID fetched from SAP.</description>
        <label>SAP Customer ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_LP_Sales_Organisation__c</fullName>
        <label>Sales Organisation</label>
        <picklist>
            <picklistValues>
                <fullName>ABB</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>APTS_Payment_Terms__c</fullName>
        <description>Field to capture payment terms associated with Apttus LSO object record.</description>
        <label>Payment Terms</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_SAP_Division__c</fullName>
        <description>Field to capture SAP Division.</description>
        <label>SAP Division</label>
        <picklist>
            <picklistValues>
                <fullName>ZZ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Local Operational Data</label>
    <nameField>
        <displayFormat>LCRD-{00000}</displayFormat>
        <label>Local Operational Data Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Local Operational Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/APTS_LocalCustRefDataTriggerTest.cls
/*************************************************************
@Name: APTS_LocalCustRefDataTriggerTest
@Author: Shalin Shah
@CreateDate: 5th October, 2015
@Description: Test class for Trigger for records of Apttus Local Customer Reference Data.
@UsedBy: Test Class For Trigger - APTS_LocalCustRefDataTrigger
******************************************************************/

@isTest
public class APTS_LocalCustRefDataTriggerTest {
    
    private static String DEFAULT_SAP_DIVISION = 'ZZ';
    private static APTS_Capture_LSO_Input_Config_Settings__c oLODConfigSetting = APTS_LP_TestUtility.getLODConfigSetting();
    
	/**
	 * Method to test the setting of default values.
	 */
    public static testMethod void testSetDefaultValues() {
        
        Account acc = createNewAccount();
        
        List<APTS_LP_Local_Customer_Reference_Data__c> lsoDataList = new List<APTS_LP_Local_Customer_Reference_Data__c>();
        lsoDataList.add(getApttusLSOData(acc));
        lsoDataList.add(getApttusLSOData(acc));
        
        insert lsoDataList;
        
        List<ID> idList = new List<ID>();
        for(APTS_LP_Local_Customer_Reference_Data__c lsoData : lsoDataList) {
            idList.add(lsoData.id);
        }
        
        lsoDataList = [SELECT APTS_SAP_Division__c FROM APTS_LP_Local_Customer_Reference_Data__c WHERE ID in :idList];
        
        System.assertEquals(DEFAULT_SAP_DIVISION, lsoDataList.get(0).APTS_SAP_Division__c, 'Default SAP division is incorrect.');
        System.assertEquals(DEFAULT_SAP_DIVISION, lsoDataList.get(1).APTS_SAP_Division__c, 'Default SAP division is incorrect.');
    }
    
    /**
     * Method to create dummy Apttus LSO Data.
     */
    private static APTS_LP_Local_Customer_Reference_Data__c getApttusLSOData(Account acc) {
        
        APTS_LP_Local_Customer_Reference_Data__c apttusLSOData = new APTS_LP_Local_Customer_Reference_Data__c();
        
        apttusLSOData.APTS_LP_Account__c = acc.id;
        apttusLSOData.APTS_External_ID__c = 'ABBBT1234567';
        apttusLSOData.APTS_Country__c = 'ES';
        apttusLSOData.APTS_LP_Distribution_Channel__c = 'BT';
        apttusLSOData.APTS_LP_Incoterms__c = 'CPT';
        apttusLSOData.APTS_LP_Local_Channel__c = 'P4';
        apttusLSOData.APTS_Payment_Terms__c = 'Z100';
        apttusLSOData.APTS_LP_Sales_Organisation__c = 'ABB';
        apttusLSOData.APTS_LP_SAP_Customer_ID__c = '1234567';
        
        return apttusLSOData;
    }
    
    /**
     * Method to create New dummy Account.
     */
    private static Account createNewAccount() {
        Account acc = new Account();
        acc.Name = 'Test Account';
        acc.BillingCity = 'Barcelona';
        acc.BillingStreet = 'Some street in Barcelona';
        acc.BillingCountry = 'Spain';
        acc.BillingState = 'Barcelona';
        acc.BillingPostalCode = 'BRX12344';
        
        insert acc;
        
        return acc;
    }
}