src/objects/APTS_Master_Picklist_Table__c.object
<CustomObject>
    <description>Object to hold locale wise description for codes (used for incoterm, payment term etc.) used in SAP</description>
    <fields>
        <fullName>APTS_Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Code__c</fullName>
        <description>Code that is being used in SAP.</description>
        <label>Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Master Picklist Table</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Picklist Table</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus__AgreementLineItem__c.object
<CustomObject>
    <description>Represents a product or service line item associated with an agreement</description>
    <fields>
        <fullName>Apttus_CMConfig__PriceListId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the price list associated with the product or service</description>
        <label>Price List</label>
        <referenceTo>Apttus_Config2__PriceList__c</referenceTo>
        <relationshipLabel>Agreement Line Items</relationshipLabel>
        <relationshipName>AgreementLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agreement Line Item</label>
    <nameField>
        <displayFormat>AL-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreement Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>APTS_Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Spain</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>APTS_Integration_Status__c</fullName>
        <label>Integration Status</label>
        <picklist>
            <picklistValues>
                <fullName>Empty</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    
    <fields>
        <fullName>APTS_LP_MSPA_Type__c</fullName>
        <description>Type of the MSPA</description>
        <formula>RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MSPA Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_LP_Max_Order_Amount__c</fullName>
        <description>Total amount of the MSPA - Is a salesperson estimation about the total Amount of the opportunity. Sales person put this value.</description>
        <label>Max Order Amount (EUR)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>APTS_LP_Sales_Organization__c</fullName>
        <defaultValue>&quot;ABB&quot;</defaultValue>
        <description>Sales organization for which the MSPA is created; is the one of MSPA owner</description>
        <inlineHelpText>Auto populated from Account</inlineHelpText>
        <label>Sales Organization</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_LP_Sales_Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sales man on behalf of which the MSPA is created (by default = to the owner)</description>
        <inlineHelpText>Auto populated from User Profile</inlineHelpText>
        <label>Sales Person</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MSPAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>APTS_Local_Channel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Auto populated using information from the Quotation or from the Buying Account (LOD selected)</inlineHelpText>
        <label>Local Channel</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>APTS_Master_Picklist_Table__c.APTS_Code_Used_For__c</field>
                <operation>equals</operation>
                <value>Local Channel</value>
            </filterItems>
            <filterItems>
                <field>APTS_Master_Picklist_Table__c.APTS_Locale__c</field>
                <operation>equals</operation>
                <valueField>$Source.APTS_Locale__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>APTS_Master_Picklist_Table__c</referenceTo>
        <relationshipLabel>Agreements (Local Channel)</relationshipLabel>
        <relationshipName>Agreements1</relationshipName>
        <type>Lookup</type>
    </fields>
<fields>
        <fullName>APTS_Manually_Create_MSPA_in_SAP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Manually Create MSPA in SAP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
	<fullName>APTS_SAP_Customer_ID__c</fullName>
	<description>Field to hold the value of Sold To customer ID in SAP fetched from LRD.</description>
	<inlineHelpText>Matching Sold To ID in SAP</inlineHelpText>
	<label>SAP Customer ID</label>
	<length>255</length>
	<type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_SAP_Reference_No__c</fullName>
        <externalId>true</externalId>
        <label>MSPA Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Sales_Office_Code__c</fullName>
        <description>Field to hold value of Sales Office codes to be selected by user.</description>
        <inlineHelpText>Auto populated from User Profile</inlineHelpText>
        <label>Sales Office (Do not use picklist)</label>
        <picklist>
            <picklistValues>
                <fullName>Z111</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Z112</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Z113</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Z900</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZAPA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZAPB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZAPC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZAPE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZAPH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZAPM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZAPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZAPV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZAPY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZAPZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZBEX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZBN1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZBN2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZBN3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZBN4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZBN5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZBN6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZBN7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZBN8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZBN9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZBTN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZBTO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZBTS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZIAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZICA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZICE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
  <fields>
        <fullName>APTS_Sales_Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Auto populated from User Profile</inlineHelpText>
        <label>Sales Office</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.APTS_Country__c</field>
                <operation>equals</operation>
                <valueField>LSO_Field_Entries__c.Country__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>LSO_Field_Entries__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements_Sales_Office</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>APTS_Total_Agreement_Value__c</fullName>
        <label>Total Agreement Value</label>
        <summarizedField>Apttus__AgreementLineItem__c.APTS_Net_Price__c</summarizedField>
        <summaryForeignKey>Apttus__AgreementLineItem__c.Apttus__AgreementId__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Apttus__Contract_End_Date__c</fullName>
        <description>The end date for this agreement</description>
        <label>Agreement End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Apttus__Contract_Start_Date__c</fullName>
        <description>The effective date of the agreement</description>
        <label>Agreement Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Apttus__Status__c</fullName>
        <description>The sub stage of an agreement – the status underneath a given status category.  These are generally modifiable by the customer except for the following values which are Apttus reserved to manage agreement lifecycles:

Request, Submitted Request,
Cancelled Request, In Amendment, Being Amended, Superseded, Activated, Expired, Internal Signatures, Author Contract, Expired, Terminated,  Ready for Signatures, Fully Signed, Signature Declined</description>
        <label>Status</label>
        <picklist>
            <controllingField>Apttus__Status_Category__c</controllingField>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approval In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturated Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved but failed to load on SAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved but Action Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deactivated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Signatures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queued to create in SAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recalled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Generated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Presented</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>MSPA</fullName>
        <active>true</active>
        <label>MSPA</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__PriceList__c.object
<CustomObject>
    <fields>
        <fullName>APTS_Country__c</fullName>
        <description>Name of the country for which price list exists</description>
        <label>Country</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/LSO_Field_Entries__c.object
<CustomObject>
    <description>R3 -  LSO Field Entries</description>
    <fields>
        <fullName>PickList_Code__c</fullName>
        <description>R3 PickList Code</description>
        <label>PickList Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>LSO Field Entries</label>
    <nameField>
        <displayFormat>LSO Field Entry - {0000}</displayFormat>
        <label>LSO Field Entry</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LSO Field Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/APTS_ABB_SAPIntegrationServiceBaseImpl.cls
public with sharing class APTS_ABB_SAPIntegrationServiceBaseImpl implements APTS_ABB_LP_iIntegrationCallback {
    
    public class APTS_ABB_LP_IntegrationException extends Exception{}
    private List<Task> lstActivityInfo;
    
    public APTS_ABB_SAPIntegrationServiceBaseImpl(){
        this.lstActivityInfo = new List<Task>();
    }
    
    public Boolean invoke(String agreementId, String blockParam){
        
        Boolean isSuccess = false;
        if(blockParam == null || blockParam == ''){
            blockParam = 'false';
        }
        
        //Part- I - fetch the data
        List<Apttus__APTS_Agreement__c> lstAgreement =  [SELECT Id, Name, APTS_Integration_Status__c, CurrencyISOCode, APTS_Sales_Office_Code__c,
                                                        APTS_SAP_Customer_ID__c, APTS_SAP_Reference_No__c,APTS_Manually_Create_MSPA_in_SAP__c, 
                                                        Apttus__Status__c, APTS_LP_Sales_Organization__c, APTS_Total_Agreement_Value__c, APTS_Country__c,
                                                        APTS_LP_MSPA_Type__c, APTS_Local_Channel__r.APTS_Code__c, APTS_LP_Max_Order_Amount__c, 
                                                        Apttus__Contract_End_Date__c, APTS_LP_Sales_Person__r.Name, 
                                                        Apttus__Contract_Start_Date__c, APTS_Sales_Office__r.PickList_Code__c,
                                                        Apttus_CMConfig__PriceListId__r.currencyISOcode,
                                                        APTS_Distribution_Channel__r.APTS_Code__c, 
                                                        (SELECT Id, Name, currencyISOcode, Apttus_CMConfig__BasePrice__c, 
                                                        Apttus__NetPrice__c, Apttus_CMConfig__LineNumber__c, Apttus__Quantity__c, 
                                                        APTS_Discount_Type__c, APTS_LP_Unit_Of_Measure__c, Apttus__AgreementId__c, 
                                                        APTS_Net_Price_Override__c, APTS_Discount_Percentage__c,
                                                        Apttus__AgreementId__r.APTS_SAP_Reference_No__c, 
                                                        Apttus__ProductId__r.APTS_LP_Is_Hierarchy__c, 
                                                        Apttus__ProductId__r.APTS_LP_Product_Hierarchy__c,
                                                        Apttus__AgreementId__r.APTS_LP_Sales_Organization__c, APTS_Product_Code__c,
                                                        APTS_Line_Number_Custom__c
                                                        FROM Apttus__AgreementLineItems__r) 
                                                        FROM Apttus__APTS_Agreement__c WHERE Id = :agreementId];
        if(lstAgreement.size() != 1){
            notifyUser();
            return false;
        }
        
        Apttus__APTS_Agreement__c agrmt = lstAgreement[0];
        
        //Part- III - get Auth token
        isSuccess = APTS_ABB_LP_SAP_Integration_Util.GetSecureOauthTokenAzure();
        if(!isSuccess){
            
            if(!blockParam.toLowerCase().equals('true')){
                AgreementSO agreement = new AgreementSO(agrmt.Id);
                agreement.manualCreationInSAP = true;
                agreement.status = 'Approved but failed to load on SAP';
                agreement.integrationStatus = 'Failed';
                
                updateSObject(agreement);
            }
            
            
            createActivity(agrmt.Id, 'SAP Integration Error - Unable to get oAuth Token', APTS_ABB_LP_SAP_Integration_Util.errorMsg);
            insert lstActivityInfo;
            
            notifyUser();
            return false;
        }
        
        try{
            //Part- II - preapre data & Part- IV - prepare request
            
            String jsonRequest = APTS_ABB_LP_SAP_Integration_Util.getSAPRequestJSON(agrmt, blockParam.toLowerCase());
            System.debug('jsonRequest: '+jsonRequest);
            
            //Part- V - do callout
            //create http request to connect to SAP
            HttpRequest req = new HttpRequest();
            req.setEndpoint(APTS_ABB_LP_SAP_Integration_Util.sapEndPoint);//set end point here
            req.setMethod('POST');
            req.setHeader(APTS_ABB_LP_SAP_Integration_Util.sapHeaderKey, APTS_ABB_LP_SAP_Integration_Util.getSasToken());//pass sas token for authentication
            req.setHeader('X-HTTP-Method', 'POST');
            req.setHeader('Content-Type', 'application/json');
            req.setBody(jsonRequest);//pass json body with agreement and agreement line items
            req.setTimeout(APTS_ABB_LP_SAP_Integration_Util.callTimeout);
            
            Http http = new Http();
            
            createActivity(agrmt.Id, 'MSPA Request sent to SAP', req.getBody().length() < 32000 ? req.getBody() : req.getBody().left(29999));
            
            HttpResponse res = http.send(req);
            String responseJson = res.getBody();
            System.debug('responseJson: '+responseJson);
            APTS_ABB_LP_SAP_Tokens.MSPASAPResponseWrapper responses = (APTS_ABB_LP_SAP_Tokens.MSPASAPResponseWrapper)JSON.deserialize(responseJson, APTS_ABB_LP_SAP_Tokens.MSPASAPResponseWrapper.class);
            System.debug('responseWrapper: '+responses);
            
            createActivity(agrmt.Id, 'MSPA Response received from SAP', responseJson.length() < 32000 ? responseJson : res.getBody().left(29999));
            
            AgreementSO agreement = new AgreementSO(agrmt.Id);
            
            if(blockParam != null && blockParam.toLowerCase().equals('true')){
                agreement.blockStatus = true;
                agreement.status = 'Blocked';
            }
                
            if(res == null || res.getStatusCode() != 200 || responses.Errors.size() > 0){
                String descr = 'Erorr code: \n' + JSON.serialize(responses.Errors);
                if(descr.contains('502')){
                    descr = 'Error: MSPA('+agrmt.APTS_SAP_Reference_No__c+') already exist in SAP. \n' + descr;
                }
                
                agreement.manualCreationInSAP = true;
                agreement.status = 'Approved but failed to load on SAP';
                agreement.integrationStatus = 'Failed';
                createActivity(agrmt.Id, 'MSPA Failed to Load in SAP', descr);
            }
            
            updateSObject(agreement);
            
        }catch(Exception exp){
            
            AgreementSO agreement = new AgreementSO(agrmt.Id);
            agreement.manualCreationInSAP = true;
            agreement.status = 'Approved but failed to load on SAP';
            agreement.integrationStatus = 'Failed';
            String errorMsg = 'Error Type: '+ exp.getTypeName() + '\n Error: '+ exp.getMessage() + '\n'+ 'Cause: '+exp.getCause() + '\n' + 'Line Number: '+ exp.getLineNumber() + '\n StackTrace: '+ exp.getStackTraceString();
            APTS_ABB_LP_SAP_Integration_Util.errorMsg = errorMsg;
            createActivity(agrmt.Id, 'MSPA Failed to load in SAP', errorMsg);
            
            updateSObject(agreement);
            notifyUser();
            
            return false;
            
        }finally{
            
            if(lstActivityInfo.size() > 0){
                insert lstActivityInfo;
            }
        }
        
        return true;
    }
    
    private void updateSObject(AgreementSO agreement){
        
        Apttus__APTS_Agreement__c agreementObj = new Apttus__APTS_Agreement__c(Id = agreement.Id, Apttus__Status__c = agreement.status,
        APTS_Integration_Status__c = agreement.integrationStatus, 
        APTS_Manually_Create_MSPA_in_SAP__c = agreement.manualCreationInSAP);
        
        update agreementObj;
    }
    
    private void createActivity(String sObjectId, String subject, String description){
        
        Task activity = new Task();
        activity.ActivityDate = System.today();
        activity.OwnerId = UserInfo.getUserId();
        activity.Priority = 'Low';
        activity.Status = 'Completed';
        activity.Subject = subject;
        activity.Description = description;
        activity.WhatId = sObjectId;
        
        lstActivityInfo.add(activity);
    }
    
    private void notifyUser(){
         /*
         Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
         String[] toAddresses = new String[] {'avaru@apttus.com'};
         mail.setToAddresses(toAddresses);
         //mail.setReplyTo('developer@acme.com');
         mail.setSenderDisplayName('Apex error message');
         mail.setSubject('Error from Org : ' + UserInfo.getOrganizationName());
         mail.setPlainTextBody('error occurred integrating SAP.');
         Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
         */
    }
    
    public class AgreementSO{
        
        public String Id{get; set;}
        public String status{get; set;}
        public Boolean blockStatus{get; set;}
        public String integrationStatus{get; set;}
        public Boolean manualCreationInSAP{get; set;}
        
        public AgreementSO(){
            
            this.manualCreationInSAP = false;
            this.status = 'Approved';
            this.integrationStatus = 'Sent';
            this.blockStatus = false;
        }
        
        public AgreementSO(String agreementId){
            this();
            this.Id = agreementId;
        }
    }
}