src/objects/APTS_Agreement_SAP_Setting__c.object
<CustomObject>
    <description>Used to enable/disable auto creation of MSPA agreement in SAP, and Block MSPA agreement in SAP</description>
    <fields>
        <fullName>APTS_Auto_Create_MSPA_In_SAP_On_Approval__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If checked, system will create MSPA type agreement automatically in SAP upon approval</description>
        <inlineHelpText>If checked, system will create MSPA type agreement automatically in SAP, when approved in SFDC</inlineHelpText>
        <label>Auto Create MSPA In SAP On Approval ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_Block_MSPA_Creation_In_SAP__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If checked system will not allow user to create MSPA type agreement in SAP</description>
        <inlineHelpText>If checked system will see a button on MSPA - &apos;Block in SAP&apos; to manually trigger &apos;Block&apos; of MSPA in SAP.</inlineHelpText>
        <label>Block MSPA Creation In SAP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Spain</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Agreement SAP Setting</label>
    <nameField>
        <displayFormat>AS-{00000}</displayFormat>
        <label>Agreement SAP Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreement SAP Settings</pluralLabel>
    <recordTypes>
        <fullName>Spain</fullName>
        <active>true</active>
        <label>Spain</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/APTS_EditAgreementSAPSettingsCntrlrTest.cls
@isTest
private class APTS_EditAgreementSAPSettingsCntrlrTest {
	
	@isTest static void test_method_one() {

		APTS_Agreement_SAP_Setting__c agrementSapSettings = new APTS_Agreement_SAP_Setting__c();
		agrementSapSettings.APTS_Auto_Create_MSPA_In_SAP_On_Approval__c = true;
		agrementSapSettings.APTS_Block_MSPA_Creation_In_SAP__c = true;
		agrementSapSettings.APTS_Country__c = 'Spain';
		insert agrementSapSettings;

		Test.startTest();
		ApexPages.StandardController stdController = new ApexPages.StandardController(agrementSapSettings);
        Test.setCurrentPageReference(new PageReference('Page.APTS_EditAgreementSAPSettings')); 
		
        APTS_EditAgreementSAPSettingsController editAgrementSAPCntroler = new APTS_EditAgreementSAPSettingsController(stdController);
        PageReference ref = editAgrementSAPCntroler.init();

       System.assertEquals(ref,null);

       Test.stopTest();
	}
	
	@isTest static void test_method_two() {

		APTS_Agreement_SAP_Setting__c agrementSapSettings = new APTS_Agreement_SAP_Setting__c();
		agrementSapSettings.APTS_Auto_Create_MSPA_In_SAP_On_Approval__c = true;
		agrementSapSettings.APTS_Block_MSPA_Creation_In_SAP__c = true;
		agrementSapSettings.APTS_Country__c = 'Spain';
		insert agrementSapSettings;

		Test.startTest();
		ApexPages.StandardController stdController = new ApexPages.StandardController(agrementSapSettings);
        Test.setCurrentPageReference(new PageReference('Page.APTS_EditAgreementSAPSettings')); 
		
        APTS_EditAgreementSAPSettingsController editAgrementSAPCntroler = new APTS_EditAgreementSAPSettingsController(stdController);
        PageReference ref = editAgrementSAPCntroler.save();

       System.assertNotEquals(ref,null);

       Test.stopTest();
	}
	
}