src/objects/APTS_Approval_Rule_Matrix__c.object
<CustomObject>
    <description>Approval rule matrix stores routing rules that will be configured by country admin and it drives the Quotation &amp; Agreement approvals.</description>
    <fields>
        <fullName>APTS_Approval_Level__c</fullName>
        <label>Approval Level</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>APTS_Assigned_to__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned to</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approval_Rule_Matrix</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>APTS_Country__c</fullName>
        <inlineHelpText>Country name for which approval rule is created</inlineHelpText>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Spain</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>APTS_GTV_Level_Code__c</fullName>
        <inlineHelpText>Code used for product at level3</inlineHelpText>
        <label>GTV Level Code</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
		<fullName>APTS_LP_Local_Channel__c</fullName>
		<deleteConstraint>SetNull</deleteConstraint>
		<label>Local Channel</label>		
		<referenceTo>APTS_Master_Picklist_Table__c</referenceTo>
		<relationshipLabel>Approval Rule Matrix</relationshipLabel>
		<relationshipName>Approval_Rule_Matrix</relationshipName>
		<type>Lookup</type>
	</fields>
    <fields>
        <fullName>APTS_LP_Sales_Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Pick sales office code from master picklist table</inlineHelpText>
        <label>Sales Office</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>APTS_Master_Picklist_Table__c.APTS_Code_Used_For__c</field>
                <operation>equals</operation>
                <value>Sales Office</value>
            </filterItems>
            <filterItems>
                <field>APTS_Master_Picklist_Table__c.APTS_Country__c</field>
                <operation>equals</operation>
                <valueField>$User.Country</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>APTS_Master_Picklist_Table__c</referenceTo>
        <relationshipLabel>Approval Rule Matrix (Sales Office)</relationshipLabel>
        <relationshipName>Approval_Rule_Matrix1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>APTS_Max_Discount__c</fullName>
        <label>Max Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>APTS_Sales_Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Office</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>LSO_Field_Entries__c.Country__c</field>
                <operation>equals</operation>
                <valueField>$User.Country</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>LSO_Field_Entries__c</referenceTo>
        <relationshipLabel>Approval Rule Matrix</relationshipLabel>
        <relationshipName>Approval_Rule_Matrix</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>APTS_Sales_Organisation__c</fullName>
        <label>Sales Organisation</label>
        <picklist>
            <picklistValues>
                <fullName>ABB</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>APTS_Threshold_Discount__c</fullName>
        <label>Threshold Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Approval Rule Matrix</label>
    <nameField>
        <displayFormat>ARM-{00000000}</displayFormat>
        <label>Approval Rule Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Rule Matrix</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/APTS_EditApprovalRuleMatrixExtensionTest.cls
/*************************************************************
@Name: APTS_EditApprovalRuleMatrixExtensionTest
@Author: Chetan Patel
@CreateDate: 15th Oct 2015
@Description: test class for APTS_EditApprovalRuleMatrixExtension class
@UsedBy: Visualforce Page - APTS_EditApprovalRuleMatrix, Apex Class  - APTS_EditApprovalRuleMatrixExtension
******************************************************************/

@isTest
public class APTS_EditApprovalRuleMatrixExtensionTest {
    
    public static testMethod void methodWithOneRuleMatrix() {
        User usr = APTS_LP_TestUtility.getUser();
        System.runAs(usr) {
            
            Test.startTest();
            APTS_LP_TestUtility.getCommonConfigSetting();
            APTS_Approval_Rule_Matrix__c rule = APTS_LP_TestUtility.getApproalRuleMatrix()[0];
            
            APTS_Approval_Rule_Matrix__c dummyApproval = new APTS_Approval_Rule_Matrix__c();
            dummyApproval.APTS_Country__c = 'Spain';
            dummyApproval.APTS_Sales_Organisation__c = 'ABB';
            dummyApproval.APTS_GTV_Level_Code__c = '00996';
            dummyApproval.APTS_Threshold_Discount__c = APTS_EditApprovalRuleMatrixExtension.THRESHOLD_DISCOUNT_DUMMY_CUTOFF + 1;
            dummyApproval.APTS_Approval_Level__c = 3;
            dummyApproval.APTS_Max_Discount__c = APTS_EditApprovalRuleMatrixExtension.THRESHOLD_DISCOUNT_DUMMY_CUTOFF + 2;
            dummyApproval.APTS_LP_Local_Channel__c = APTS_LP_TestUtility.getLocalChannel().id;
            dummyApproval.APTS_Sales_Office__c = APTS_LP_TestUtility.getSalesOffice().id;
            dummyApproval.APTS_LP_Sales_Office__c = APTS_LP_TestUtility.getMasterPicklistSalesOffice().Id;
            dummyApproval.APTS_Assigned_to__c = UserInfo.getUserId();
            insert dummyApproval;
            
            /* Apttus__APTS_Admin__c admin = new Apttus__APTS_Admin__c();
            admin.Name = 'APTS_MaxApprovalRuleMatrixLevels';
            admin.Apttus__Value__c = '1';
            insert admin; */
            
            ApexPages.StandardController sc = new ApexPages.StandardController(rule);
            APTS_EditApprovalRuleMatrixExtension controller = new APTS_EditApprovalRuleMatrixExtension(sc);
            
            PageReference pageRef = Page.APTS_EditApprovalRuleMatrix;
            pageRef.getParameters().put('id', String.valueOf(rule.Id));
            Test.setCurrentPage(pageRef);
            
            APTS_EditApprovalRuleMatrixExtension.ApprovalRuleMatrixWrapperByDiscount discount = new APTS_EditApprovalRuleMatrixExtension.ApprovalRuleMatrixWrapperByDiscount(70, 100, rule);
                    
            controller.addRow();
            controller.addRow();
            controller.addRow();
            
            pageRef.getParameters().put('iRowNumber','1');
            controller.addRowInner();
            
            controller.Save();
            controller.Add();
            
            pageRef.getParameters().put('iRowNumber','1');
            controller.addRowInner();
            
            controller.Save();
            
            pageRef.getParameters().put('iRowNumber','1');
            pageRef.getParameters().put('innerRowNumber','2');
            controller.deleteRowInner();
            
            pageRef.getParameters().put('iRowNumber','1');
            controller.deleteRow();
            
            controller.Save();
            controller.Add();
            controller.getHistoryOnComplete();
            
            Test.stopTest();
        }
    }
    
    public static testMethod void methodWithNoRuleMatrix() {
        User usr = APTS_LP_TestUtility.getUser();
        System.runAs(usr) {
            
            Test.startTest();
            APTS_LP_TestUtility.getCommonConfigSetting();
            APTS_Approval_Rule_Matrix__c rule = new APTS_Approval_Rule_Matrix__c();
            rule.APTS_Country__c = 'Spain';
            rule.APTS_Sales_Organisation__c = 'ABB';
            rule.APTS_GTV_Level_Code__c = '00996';
            rule.APTS_Threshold_Discount__c = 71.13;
            rule.APTS_Approval_Level__c = 2;
            rule.APTS_Max_Discount__c = 100.00;
            rule.APTS_LP_Local_Channel__c = APTS_LP_TestUtility.getLocalChannel().id;
            rule.APTS_Sales_Office__c = APTS_LP_TestUtility.getSalesOffice().id;
            rule.APTS_LP_Sales_Office__c = APTS_LP_TestUtility.getMasterPicklistSalesOffice().Id;
            rule.APTS_Assigned_to__c = UserInfo.getUserId();
            
            Apttus__APTS_Admin__c admin = new Apttus__APTS_Admin__c();
            admin.Name = 'APTS_MaxApprovalRuleMatrixLevels';
            admin.Apttus__Value__c = '2';
            insert admin;
            
            ApexPages.StandardController sc = new ApexPages.StandardController(rule);
            APTS_EditApprovalRuleMatrixExtension controller = new APTS_EditApprovalRuleMatrixExtension(sc);
            
            PageReference pageRef = Page.APTS_EditApprovalRuleMatrix;
            Test.setCurrentPage(pageRef);
            
            controller.saveOrAdd();
            
            controller.addRow();
            controller.addRow();
            controller.addRow();
            
            pageRef.getParameters().put('iRowNumber','1');
            controller.addRowInner();
            
            pageRef.getParameters().put('iRowNumber','1');
            controller.addRowInner();
            
            controller.saveOrAdd();
            
            pageRef.getParameters().put('iRowNumber','1');
            pageRef.getParameters().put('innerRowNumber','2');
            controller.deleteRowInner();
            
            pageRef.getParameters().put('iRowNumber','1');
            controller.deleteRow();
            
            controller.getHistoryOnComplete();
            
            Test.stopTest();
        }
    }
    
    public static testMethod void testInValidThreshold() {
        User usr = APTS_LP_TestUtility.getUser();
        System.runAs(usr) {
            
            Test.startTest();
            APTS_LP_TestUtility.getCommonConfigSetting();
            APTS_Approval_Rule_Matrix__c rule = APTS_LP_TestUtility.getApproalRuleMatrix()[0];
            
            APTS_Approval_Rule_Matrix__c dummyApproval = new APTS_Approval_Rule_Matrix__c();
            dummyApproval.APTS_Country__c = 'Spain';
            dummyApproval.APTS_Sales_Organisation__c = 'ABB';
            dummyApproval.APTS_GTV_Level_Code__c = '00996';
            dummyApproval.APTS_Threshold_Discount__c = 101;
            dummyApproval.APTS_Approval_Level__c = 3;
            dummyApproval.APTS_Max_Discount__c = 102;
            dummyApproval.APTS_LP_Local_Channel__c = APTS_LP_TestUtility.getLocalChannel().id;
            dummyApproval.APTS_Sales_Office__c = APTS_LP_TestUtility.getSalesOffice().id;
            dummyApproval.APTS_LP_Sales_Office__c = APTS_LP_TestUtility.getMasterPicklistSalesOffice().Id;
            dummyApproval.APTS_Assigned_to__c = UserInfo.getUserId();
            insert dummyApproval;
            
            Apttus__APTS_Admin__c admin = new Apttus__APTS_Admin__c();
            admin.Name = 'APTS_MaxApprovalRuleMatrixLevels';
            admin.Apttus__Value__c = '1';
            insert admin;
            
            ApexPages.StandardController sc = new ApexPages.StandardController(rule);
            APTS_EditApprovalRuleMatrixExtension controller = new APTS_EditApprovalRuleMatrixExtension(sc);
            
            PageReference pageRef = Page.APTS_EditApprovalRuleMatrix;
            pageRef.getParameters().put('id', String.valueOf(rule.Id));
            Test.setCurrentPage(pageRef);
            
            APTS_EditApprovalRuleMatrixExtension.ApprovalRuleMatrixWrapperByDiscount discount = new APTS_EditApprovalRuleMatrixExtension.ApprovalRuleMatrixWrapperByDiscount(70, 100, rule);
                    
            controller.addRow();
            controller.addRow();
            controller.addRow();
            
            pageRef.getParameters().put('iRowNumber','1');
            controller.addRowInner();
            
            controller.Save();
            controller.Add();
            
            pageRef.getParameters().put('iRowNumber','1');
            controller.addRowInner();
            
            pageRef.getParameters().put('iRowNumber','1');
            pageRef.getParameters().put('innerRowNumber','2');
            controller.deleteRowInner();
            
            pageRef.getParameters().put('iRowNumber','1');
            controller.deleteRow();
            
            controller.Save();
            controller.Add();
            controller.getHistoryOnComplete();
            
            Test.stopTest();
        }
    }
}