src/objects/APTS_Master_Picklist_Table__c.object
<CustomObject>
    <description>Object to hold locale wise description for codes (used for incoterm, payment term etc.) used in SAP</description>
    <fields>
        <fullName>APTS_Code_Description__c</fullName>
        <description>Field to hold the description value for code.</description>
        <label>Code Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Code_Used_For__c</fullName>
        <description>Picklist field to determine that code in the record is being used for what.</description>
        <label>Code Used For</label>
        <picklist>
            <picklistValues>
                <fullName>Country</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incoterm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Channel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distribution Channel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SAP Division</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SAP Sales Organization</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>APTS_Code__c</fullName>
        <description>Code that is being used in SAP.</description>
        <label>Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Locale__c</fullName>
        <description>Field to hold value of Locale to determine that code and its description is for which locale.</description>
        <label>Locale</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Master Picklist Table</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Picklist Table</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/APTS_Stage_Master_Picklist__c.object
<CustomObject>
    <fields>
        <fullName>APTS_Code_Description__c</fullName>
        <label>Code Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Code_Used_For__c</fullName>
        <label>Code Used For</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Code__c</fullName>
        <label>Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Country__c</fullName>
        <description>Country in MPL</description>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>APTS_Locale__c</fullName>
        <label>Locale</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Stage Master Picklist</label>
    <nameField>
        <label>Master Picklist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stage Master Picklist</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/APTS_DMMasterPicklistTableHelper.cls
public class APTS_DMMasterPicklistTableHelper extends APTS_DMHelper {
	public static void validateStageMasterPickList(List < APTS_Stage_Master_Picklist__c > listStageMasterPick) {

		// Boolean Variable to indicate Validation Error
		Boolean bisValidattionError = false;
		// Variable for Error Message.
		//String sErrorMessage = ''; 

		// intialize the helper utility
		APTS_DMHelperUtility dmHelperUtility = New APTS_DMHelperUtility();

		List < APTS_Stage_Master_Picklist__c > listUpdatedMasterPick = new List < APTS_Stage_Master_Picklist__c > ();

		for (APTS_Stage_Master_Picklist__c stageMasterPickItem: listStageMasterPick) {
			bisValidattionError = false;
			// Variable for Error Message.
			// sErrorMessage = '';

			if (String.isBlank(stageMasterPickItem.APTS_Code_Used_For__c)) {
				bisValidattionError = true;
				// sErrorMessage = sErrorMessage + 'CodeUserFor field cannot be Blank \n';
				dmHelperUtility.appendErrorMessage('CodeUserFor field cannot be Blank.');
			}

			if (String.isBlank(stageMasterPickItem.APTS_Code__c)) {
				bisValidattionError = true;
				//sErrorMessage = sErrorMessage +'Code field cannot be Blank \n';
				dmHelperUtility.appendErrorMessage('Code field cannot be Blank.');
			}

			dmHelperUtility.updateValidationStatus(stageMasterPickItem, bIsValidattionError);
			listUpdatedMasterPick.add(stageMasterPickItem);

		} // End of for loop

		// List of MSPALineItems
		if (listUpdatedMasterPick.size() > 0) {
			system.debug('HS--> Size of MasterPickList to be updated' + listUpdatedMasterPick.size());
			try {
				Database.UpsertResult[] results = Database.upsert(listUpdatedMasterPick);
				system.debug('HS--Master PickList' + results);
			} catch (Exception ex) {
				System.debug('Exception while upserting MSPA-LineItem.\nException : ' + ex.getMessage());
			}
		}

	}

	public static APTS_CopyDataWrapper copyMasterPickList(List < APTS_Stage_Master_Picklist__c > listStageMasterPick) {

		APTS_CopyDataWrapper oCopyWrapper = new APTS_CopyDataWrapper();
		system.debug('HS--> Copying Data from Staging Object to Normal Object : MasterPickList');

		// List of MasterPick List Objects that needs to be updated
		List < APTS_Master_Picklist_Table__c > listMasterPick = new List < APTS_Master_Picklist_Table__c > ();

		Schema.SObjectField f = APTS_Master_Picklist_Table__c.Fields.APTS_External_Id__c;

		APTS_Master_Picklist_Table__c oMasterPickItem = null;

		// Creating Master PickList, assigning values and adding into List.
		for (APTS_Stage_Master_Picklist__c stageMasterPickItem: listStageMasterPick) {
			oMasterPickItem = new APTS_Master_Picklist_Table__c();
			oMasterPickItem.Name = stageMasterPickItem.Name;
			oMasterPickItem.APTS_Code__c = stageMasterPickItem.APTS_Code__c;
			oMasterPickItem.APTS_Code_Description__c = stageMasterPickItem.APTS_Code_Description__c;
			oMasterPickItem.APTS_Code_Used_For__c = stageMasterPickItem.APTS_Code_Used_For__c;
			oMasterPickItem.APTS_Locale__c = stageMasterPickItem.APTS_Locale__c;
			oMasterPickItem.APTS_External_Id__c = stageMasterPickItem.APTS_External_ID__c;
            oMasterPickItem.APTS_Country__c = stageMasterPickItem.APTS_Country__c;
			listMasterPick.add(oMasterPickItem);
		}

		try {
			if (listMasterPick.size() > 0) {
				Database.UpsertResult[] results = Database.upsert(listMasterPick, f, false);
				system.debug('HS--> Results While copying master-picklist ' + results);
				Set < Id > successIdSet = New Set < id > ();
				Set < Id > failedIdSet = New Set < id > ();

				// Iterate through each returned result
				for (Database.UpsertResult sr: results) {

					if (sr.isSuccess()) {
						System.debug('Successfully inserted master picklist: ' + sr.getId());
						successIdSet.add(sr.getId());
						system.debug('##SUCCESSresults.get(i)=' + sr);
					} else {
						// Operation failed, so get all errors 
						oCopyWrapper.bIsUpsertFail = true;
						for (Database.Error err: sr.getErrors()) {
							System.debug('The following error has occurred.');
							oCopyWrapper.sErrorMessage = oCopyWrapper.sErrorMessage + '<br/><br/>' + err.getStatusCode() + ': ' + err.getMessage();
							System.debug(err.getStatusCode() + ': ' + err.getMessage());
							System.debug('Master-PickList fields that affected this error: ' + err.getFields());

						}
					}
				}

				APTS_DMHelper.updateLoadingStatus(successIdSet, 'APTS_Master_Picklist_Table__c', 'APTS_External_Id__c', 'APTS_External_ID__c', listStageMasterPick);

			}
			system.debug('HS1--> ' + oCopyWrapper);

		} catch (Exception e) {
			System.debug('Exception while upserting Master-PickList  records.\nException : ' + e.getMessage());
			oCopyWrapper.sErrorMessage = e.getMessage();
			oCopyWrapper.bIsUpsertFail = true;
		}

		return oCopyWrapper;
	}

}