src/objects/APTS_Approval_Rule_Matrix__c.object
<CustomObject>
    <description>Approval rule matrix stores routing rules that will be configured by country admin and it drives the Quotation &amp; Agreement approvals.</description>
    <fields>
        <fullName>APTS_Approval_Level__c</fullName>
        <label>Approval Level</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>APTS_CHF__c</fullName>
        <formula>TEXT(APTS_Country__c ) + TEXT( APTS_Sales_Organisation__c ) + (  APTS_LP_Local_Channel__r.APTS_Code__c ) + (   APTS_Sales_Office__r.PickList_Code__c  ) + APTS_GTV_Level_Code__c</formula>
        <label>Combined Fields</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
		<fullName>APTS_LP_Local_Channel__c</fullName>
		<deleteConstraint>SetNull</deleteConstraint>
		<label>Local Channel</label>		
		<referenceTo>APTS_Master_Picklist_Table__c</referenceTo>
		<relationshipLabel>Approval Rule Matrix</relationshipLabel>
		<relationshipName>Approval_Rule_Matrix</relationshipName>
		<type>Lookup</type>
	</fields>
    <fields>
        <fullName>APTS_Local_Channel__c</fullName>
        <label>Local Channel</label>
        <picklist>
            <picklistValues>
                <fullName>P1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>APTS_Sales_Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Office</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>LSO_Field_Entries__c.Country__c</field>
                <operation>equals</operation>
                <valueField>$User.Country</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>LSO_Field_Entries__c</referenceTo>
        <relationshipLabel>Approval Rule Matrix</relationshipLabel>
        <relationshipName>Approval_Rule_Matrix</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Approval Rule Matrix</label>
    <nameField>
        <displayFormat>ARM-{00000000}</displayFormat>
        <label>Approval Rule Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Rule Matrix</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/APTS_Master_Picklist_Table__c.object
<CustomObject>
    <description>Object to hold locale wise description for codes (used for incoterm, payment term etc.) used in SAP</description>
    <fields>
        <fullName>APTS_Code__c</fullName>
        <description>Code that is being used in SAP.</description>
        <label>Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Master Picklist Table</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Picklist Table</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>APTS_Approval_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Chevron should appear if this checkbox is checked LP Spain</description>
        <label>Approval Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_CH_AQ__c</fullName>
        <formula>TEXT(APTS_Country__c) + APTS_LP_Sales_Organization__c + APTS_Local_Channel__r.APTS_Code__c +  APTS_Sales_Office__r.PickList_Code__c  + APTS_GTV_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Combined Fields Agreement Header</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_GTV_Code__c</fullName>
        <label>GTV Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    
    <fields>
        <fullName>APTS_LP_Local_Channel__c</fullName>
        <inlineHelpText>Auto populated from Account</inlineHelpText>
        <label>Local Channel</label>
        <picklist>
            <picklistValues>
                <fullName>OEMS CD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cuadristas CD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cuadristas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OEMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distribución General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integradores y EPC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>APTS_LP_No_Approval_Rule_Matched__c</fullName>
        <defaultValue>false</defaultValue>
        <label>No Approval Rule Matched</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_Local_Channel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Auto populated using information from the Quotation or from the Buying Account (LOD selected)</inlineHelpText>
        <label>Local Channel</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>APTS_Master_Picklist_Table__c.APTS_Code_Used_For__c</field>
                <operation>equals</operation>
                <value>Local Channel</value>
            </filterItems>
            <filterItems>
                <field>APTS_Master_Picklist_Table__c.APTS_Locale__c</field>
                <operation>equals</operation>
                <valueField>$Source.APTS_Locale__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>APTS_Master_Picklist_Table__c</referenceTo>
        <relationshipLabel>Agreements (Local Channel)</relationshipLabel>
        <relationshipName>Agreements1</relationshipName>
        <type>Lookup</type>
    </fields>
  <fields>
        <fullName>APTS_Sales_Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Auto populated from User Profile</inlineHelpText>
        <label>Sales Office</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.APTS_Country__c</field>
                <operation>equals</operation>
                <valueField>LSO_Field_Entries__c.Country__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>LSO_Field_Entries__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements_Sales_Office</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/APTS_ApprovalSubmitController.cls
/*************************************************************
@Name: APTS_ApprovalSubmitController
@Author: Hardik Shah
@CreateDate: 07 Sep 2015
@Description: This class fetches Group-Name for Corresponding Agreement 
@UsedBy: VF-Page : APTS_ApprovalSubmit
******************************************************************
@ModifiedBy: NA
@ModifiedDate: NA
@ChangeDescription: A brief description of what was modified.
**** PS: @ModifiedBy and @ChangeDescription can be repeated multiple time, based on number of changes made to the original process.
******************************************************************/

public with sharing class APTS_ApprovalSubmitController {
    // Apttus Agreemet 
    public Apttus__APTS_Agreement__c agreement {
        get;
        set;
    }
    // Boolean variable to show error message on  VF page
    public Boolean bHasErrors {
        get;
        set;
    }
    public boolean bIsARMActive;
    public boolean bIsARMApprovalLevelsCorrect;
    public static final String MAX_APPROVAL_LEVELS = 'APTS_MaxApprovalRuleMatrixLevels';
    
    // Constructor to initialize agreement
    public APTS_ApprovalSubmitController(ApexPages.StandardController controller) {
        agreement = (Apttus__APTS_Agreement__c) controller.getrecord();
        
        agreement = [Select id,APTS_CH_AQ__c,APTS_LP_No_Approval_Rule_Matched__c,APTS_Sales_Office__c, APTS_Local_Channel__r.APTs_Code__c, APTS_GTV_Code__c,APTS_Approval_Required__c from Apttus__APTS_Agreement__c where id=:agreement.id];
        bHasErrors = false;
        bIsARMActive = false;
        bIsARMApprovalLevelsCorrect = true;
    }


    public pagereference onload() {
        // Check for Validity of Agreement and Agreement Values
        if (isValidAgreement(agreement)) {
           
            PageReference pageRef = Page.Apttus_Approval__ApprovalContextPreview;
            pageRef.getParameters().put('sObjectType', 'Apttus__APTS_Agreement__c');
            pageRef.getParameters().put('sObjectId', agreement.id);
            pageRef.getParameters().put('CancelPendingProcess', 'false');
            pageRef.setredirect(true);
            return pageRef;            
        } else {
            // Show Error Message
            if(agreement.APTS_LP_No_Approval_Rule_Matched__c || bIsARMActive==false){
                Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.INFO, Label.APTS_NO_APPROVAL_RULE_MATRIX));
            }else if(bIsARMActive ==true && bIsARMApprovalLevelsCorrect==false){
                Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.INFO, Label.APTS_ARM_APPROVAL_LEVELS_NOT_CORRECT));
            }else
                Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.INFO, Label.APTS_APPROVAL_PROCESS_ENTRY_CRITERIA));
            bHasErrors = true;
        }

        return null;
    }

    // This Method checks for Validity of Agreement and Agreement Values
    private Boolean isValidAgreement(Apttus__APTS_Agreement__c agr) {

        Boolean bValid = false;
        // Check for Agreement validation
        system.debug('@@ agr.APTS_Sales_Office__c :'+ agr.APTS_Sales_Office__c);
      //  system.debug('@@ agr.APTS_LP_Local_Channel__c :'+ agr.APTS_LP_Local_Channel__c);
        system.debug('@@ agr.APTS_GTV_Code__c :'+ agr.APTS_GTV_Code__c);
        system.debug('@@ agr.id :'+ agr.id);
        if (agr != null && agr.id != null && String.isNotBlank(agr.id)) {
            // Check for Agreement field Validation   
            if (((agr.APTS_Sales_Office__c != null && String.isNotBlank(agr.APTS_Sales_Office__c))

          //  && (agr.APTS_LP_Local_Channel__c != null && String.isNotBlank(agr.APTS_LP_Local_Channel__c))

            && (agr.APTS_GTV_Code__c != null && String.isNotBlank(agr.APTS_GTV_Code__c)))) {

                // added by chetan 02-12-2015 ,to check ARM active flag before submit
                // Also check for Approval levels in ARM are in correct sequence or not.
                List<APTS_Approval_Rule_Matrix__c> lstApprovalRuleMatrix = new List<APTS_Approval_Rule_Matrix__c>(); 
                lstApprovalRuleMatrix = [select id,APTS_Approval_Level__c from APTS_Approval_Rule_Matrix__c where APTS_Is_Active__c =true and APTS_CHF__c = :agr.APTS_CH_AQ__c];
                
                if(lstApprovalRuleMatrix != null && lstApprovalRuleMatrix.size()>0){
                    
                    bIsARMActive = true;
                    set<Decimal> setApprovalLevels = new set<Decimal>();
                    
                    for(APTS_Approval_Rule_Matrix__c rule :lstApprovalRuleMatrix){
                            setApprovalLevels.add(rule.APTS_Approval_Level__c);
                    }
                    if(lstApprovalRuleMatrix.size()!=setApprovalLevels.size()){
                        bIsARMApprovalLevelsCorrect=false;
                    }
                    /* Removing this else part due to R3.1 change in Approval Rule Matrix - Removal of place holder records 
                       By Chetan Patel Date : 31/12/2015
                    else{
                        
                        List<Apttus__APTS_Admin__c> lstAdmin = new List<Apttus__APTS_Admin__c>();
                        Decimal MaxARMsAllowed=0;
                        lstAdmin = [select id,Apttus__Value__c from Apttus__APTS_Admin__c where name=:MAX_APPROVAL_LEVELS LIMIT :APTS_Constants.SELECT_SOQL_LIMIT];
                        if(lstAdmin != null && lstAdmin.size()>0){
                            
                            MaxARMsAllowed = Decimal.valueOf(lstAdmin[0].Apttus__Value__c);
                        }
                        for(Decimal d=1;d<=MaxARMsAllowed;d++){
                            
                            if(!setApprovalLevels.contains(d))
                                bIsARMApprovalLevelsCorrect =false;
                        }
                    }
                    */
                        
                    if(bIsARMApprovalLevelsCorrect)
                        bValid = true;
                    
                }

            }
            
            system.debug('@@ bValid :'+ bValid);

        }
        return bValid;
    }
}