src/objects/APTS_Capture_LSO_Input_Config_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom object to configure settings like dropdown list values etc. for Capture LSO Input page while creating MSPA or Quotation from Account or Opportunity.</description>
    <label>Capture LSO Input Config Settings</label>
</CustomObject>

src/objects/APTS_Master_Picklist_Table__c.object
<CustomObject>
    <description>Object to hold locale wise description for codes (used for incoterm, payment term etc.) used in SAP</description>
    <fields>
        <fullName>APTS_Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Code__c</fullName>
        <description>Code that is being used in SAP.</description>
        <label>Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Master Picklist Table</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Picklist Table</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/APTS_Stage_Master_Picklist__c.object
<CustomObject>
    <fields>
        <fullName>APTS_Code__c</fullName>
        <label>Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Country__c</fullName>
        <description>Country in MPL</description>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Stage Master Picklist</label>
    <nameField>
        <label>Master Picklist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stage Master Picklist</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/APTS_DMMasterPicklistTableHelperTest.cls
/*************************************************************
@Name: APTS_DMMasterPicklistTableHelper
@Author: Hardik Shah
@CreateDate: 16/11/2015
@Description: This class tests following Classes : APTS_DMMasterPicklistTableHelper
@UsedBy: NA
******************************************************************/


@isTest
public class APTS_DMMasterPicklistTableHelperTest {
    
    private static User user;
    private static APTS_Capture_LSO_Input_Config_Settings__c lodConfigSetting = APTS_LP_TestUtility.getLODConfigSetting();
    
    // Test Method to Copy Master-Pick List
    public static testMethod void validateMasterPickList(){
        
        user  = APTS_LP_TestUtility.getUser();
        System.runAs(user) { 
        List<APTS_Stage_Master_Picklist__c> listStageMasterPickList  = APTS_LP_TestUtility.getStageMasterPicklistTableData(5);
        test.startTest();
        APTS_DMMasterPicklistTableHelper.validateStageMasterPickList(listStageMasterPickList);
        test.stopTest();
        }
    }
    
     // Test Method to Copy Master-Pick List
     public static testMethod void copyMasterPickList(){
        Integer testSize = 5;
        String testCountry = 'testcountry';
        user  = APTS_LP_TestUtility.getUser();
        System.runAs(user) { 
        List<APTS_Stage_Master_Picklist__c> listStageMasterPickList  = APTS_LP_TestUtility.getStageMasterPicklistTableData(testSize);
        Integer i=1;
        for(APTS_Stage_Master_Picklist__c stg: listStageMasterPickList) {
            stg.name = 'P'+ i + ' - Local Channel';
            stg.APTS_Country__c = testCountry;
            stg.APTS_Code__c = 'P'+ i;
            stg.APTS_External_ID__c = 'P'+ i++;
        }
        test.startTest();
        APTS_DMMasterPicklistTableHelper.copyMasterPickList(listStageMasterPickList);
        List < APTS_Master_Picklist_Table__c > listCountry = [select id from APTS_Master_Picklist_Table__c where APTS_Country__c = :testCountry];
        system.assert(listCountry.size() == testSize*2);
        test.stopTest();
        }
    }


}