src/objects/APTS_Capture_LSO_Input_Config_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom object to configure settings like dropdown list values etc. for Capture LSO Input page while creating MSPA or Quotation from Account or Opportunity.</description>
    <label>Capture LSO Input Config Settings</label>
</CustomObject>

src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>APTS_LP_AccountCustomer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Customer name of the direct customer</description>
        <inlineHelpText>Direct customer to which the MSPA is related. Auto populated if MSPA created from Opportunity or Buying Account.</inlineHelpText>
        <label>Account Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>GIS Approved</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>MSPAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>APTS_LP_GTV_Level__c</fullName>
        <description>Product of GTV Level</description>
        <inlineHelpText>Product of GTV Level</inlineHelpText>
        <label>GTV Level</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    
    <fields>
        <fullName>APTS_LP_MaximumSubstituteDiscount__c</fullName>
        <label>Maximum Substitute Discount</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>APTS_MSPA_From_Quote__c</fullName>
        <description>Field to hold the action used for creating the MSPA from Quote by Sales Rep.</description>
        <inlineHelpText>Field to hold the action used for creating the MSPA from Quote by Sales Rep.</inlineHelpText>
        <label>APTS_MSPA_From_Quote</label>
        <picklist>
            <picklistValues>
                <fullName>Scratch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Changes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Without Changes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>APTS_isClone__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This Variable is used to determine whether agreement created is clone or from quote</description>
        <label>isClone</label>
        <type>Checkbox</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__LineItem__c.object
<CustomObject>
    <fields>
        <fullName>APTS_Discount_Percentage__c</fullName>
        <description>Field to specify the percentage of discount to be applied to the line item when selected discount type is either &quot;Substitute Discount&quot; or &quot;Additional Discount&quot;.</description>
        <label>Discount %</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>APTS_Hierarchy_Level_3_Code__c</fullName>
        <description>Field to capture Level 3 Hierarchy code entered by user.</description>
        <label>Hierarchy Level 3 Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__AdjustmentType__c</fullName>
        <description>The manual price adjustment type</description>
        <label>Adjustment Type</label>
        <picklist>
            <picklistValues>
                <fullName>% Discount Off List</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discount Amount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>% Uplift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>% Markup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Markup Amount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Price Override</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Base Price Override</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Price Factor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Additional Discounts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>% Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>--None--</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Apttus_Config2__ProductConfiguration__c.object
<CustomObject>
    <fields>
        <fullName>Apttus_Config2__Status__c</fullName>
        <description>The current status of the configuration</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Ready For Approvals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready For Finalization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalized</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Superseded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved but Action Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>APTS_Hierarchy_Level_3_Code__c</fullName>
        <description>Level 3 Hierarchy Code</description>
        <label>Hierarchy Level 3 Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/APTS_ProductConfigurationTriggerTest.cls
/*************************************************************
@Name: APTS_ProductConfigurationTriggerTest
@Author: Hardik Shah
@CreateDate: 01/09/2015
@Description: This class tests following Trigger : APTS_ProductConfigurationTrigger
@UsedBy: NA
**************************************************************/


@isTest
public class APTS_ProductConfigurationTriggerTest {
    
    private static User user;
    private static List<Apttus__APTS_Agreement__c> testAgreement;
    private static APTS_Capture_LSO_Input_Config_Settings__c lodConfigSetting = APTS_LP_TestUtility.getLODConfigSetting();
    
    // This method fetches those Product Configuration whose status is not finalized     
    public static testMethod void fetchProductConfiguration() {
        
        user = APTS_LP_TestUtility.getUser();
        System.runAs(user) {
            
            APTS_LP_TestUtility.getCommonConfigSetting();
            Apttus__APTS_Agreement__c agreement =  APTS_LP_TestUtility.getAgreement('Test Agreement');
            Apttus_Config2__ProductConfiguration__c productConfig = APTS_LP_TestUtility.getProductConfiguration('TestProductConfiguration');
            
            test.startTest();
            
            APTS_LP_TestUtility.getDiscountConfig();
            insert agreement;
            productConfig.Apttus_CMConfig__AgreementId__c = agreement.id;
            insert productConfig;
            productConfig.Apttus_Config2__Status__c = 'Saturated';
            update productConfig;
            
            test.stopTest();
            
            testAgreement = [SELECT APTS_LP_GTV_Level__c FROM Apttus__APTS_Agreement__c WHERE id =: agreement.id LIMIT 1];
            System.assertEquals(null, testAgreement[0].APTS_LP_GTV_Level__c);
        }
    }
    
    // This method fetches those Product Configuration whose status is finalized, but has no LineItem
    public static testMethod void fetchProductConfigurationwithNoLineItem() {
        
        user  = APTS_LP_TestUtility.getUser();
        System.runAs(user) {  
            
            APTS_LP_TestUtility.getCommonConfigSetting();
            Apttus__APTS_Agreement__c agreement =  APTS_LP_TestUtility.getAgreement('Test Agreement');
            Apttus_Config2__ProductConfiguration__c productConfig = APTS_LP_TestUtility.getProductConfiguration('TestProductConfiguration');
            
            test.startTest();
            
            APTS_LP_TestUtility.getDiscountConfig();
            insert agreement;
            productConfig.Apttus_CMConfig__AgreementId__c = agreement.id;
            insert productConfig;
            productConfig.Apttus_Config2__Status__c = 'Finalized';
            update productConfig;
            
            test.stopTest();
            
            testAgreement  =  [SELECT APTS_LP_GTV_Level__c FROM Apttus__APTS_Agreement__c WHERE id =: agreement.id LIMIT 1];
            System.assertEquals(null, testAgreement[0].APTS_LP_GTV_Level__c);
        }
    }
    
    // This method fetches those Product Configuration whose status is finalized, and has one LineItem
    public static testMethod void fetchProductConfigurationwithOneLineItem() {
        
        user  = APTS_LP_TestUtility.getUser();
        System.runAs(user) {  
            
            APTS_LP_TestUtility.getCommonConfigSetting();
            Apttus__APTS_Agreement__c agreement =  APTS_LP_TestUtility.getAgreement('Test Agreement');
            
            test.startTest();
            
            Product2 prod =  APTS_LP_TestUtility.getProduct();
            insert prod;
            Product2 hierachyProd =  APTS_LP_TestUtility.getHierarchyProduct();
            hierachyProd.APTS_Hierarchy_Level_3_Code__c = null;
            insert hierachyProd;
            
            APTS_LP_TestUtility.addPricebookAndEntries(prod);
            APTS_LP_TestUtility.getDiscountConfig();
            APTS_LP_TestUtility.getApproalRuleMatrix();
            insert agreement;
            
            Apttus_Config2__ProductConfiguration__c productConfig = APTS_LP_TestUtility.getProductConfiguration('TestProductConfiguration');
            productConfig.Apttus_CMConfig__AgreementId__c = agreement.id;
            insert productConfig;
            Apttus_Config2__ProductConfiguration__c hierarchyProductConfig = APTS_LP_TestUtility.getProductConfiguration('TestProductConfiguration');
            hierarchyProductConfig.Apttus_CMConfig__AgreementId__c = agreement.id;
            insert hierarchyProductConfig;
            
            List<Apttus_Config2__LineItem__c> lineItemList = APTS_LP_TestUtility.getLineItemListWithDiscount(productConfig.ID, 1, prod,5);
            lineItemList.addAll(APTS_LP_TestUtility.getLineItemListWithDiscount(hierarchyProductConfig.ID, 1, hierachyProd,5));
            insert lineItemList;
            
            agreement.APTS_MSPA_From_Quote__c = 'With Changes';
            agreement.APTS_isClone__c = TRUE;
            update agreement;
            productConfig.Apttus_Config2__Status__c = 'Finalized';
            update productConfig;
            
            agreement.APTS_MSPA_From_Quote__c = 'Without Changes';
            update agreement;
            hierarchyProductConfig.Apttus_Config2__Status__c = 'Finalized';
            update hierarchyProductConfig;
            
            test.stopTest();
            
            testAgreement  =  [SELECT APTS_LP_GTV_Level__c FROM Apttus__APTS_Agreement__c WHERE id =: agreement.id LIMIT 1];
        }
    }
    
    // This method fetches those Product Configuration whose status is finalized, and has multiple LineItem with Positive Adjustment-Amount,NetAdjustMentPercent
    public static testMethod void fetchProductConfigurationwithMulipleLineItem() {
        
        user  = APTS_LP_TestUtility.getUser();
        System.runAs(user) {  
            
            APTS_LP_TestUtility.getCommonConfigSetting();
            List<Product2> productList =  APTS_LP_TestUtility.getProductList(3);
            Apttus__APTS_Agreement__c agreement = APTS_LP_TestUtility.getAgreement('Test Agreement');
            
            test.startTest();
            
            insert productList;
            APTS_LP_TestUtility.getDiscountConfig();
            APTS_LP_TestUtility.getApproalRuleMatrix();
            insert agreement;
            Apttus_Config2__ProductConfiguration__c productConfig = APTS_LP_TestUtility.getProductConfiguration('TestProductConfiguration');
            productConfig.Apttus_CMConfig__AgreementId__c = agreement.id;
            insert productConfig;
            
            Apttus_Config2__ProductConfiguration__c hierarchyProductConfig = APTS_LP_TestUtility.getProductConfiguration('TestHierarchyProductConfiguration');
            hierarchyProductConfig.Apttus_CMConfig__AgreementId__c = agreement.id;
            insert hierarchyProductConfig;
            
            List<Apttus_Config2__LineItem__c> listLineItem = new List<Apttus_Config2__LineItem__c>();
            listLineItem.addAll(APTS_LP_TestUtility.getLineItemListWithDiscount(productConfig.ID, 2, productList[0],5));
            listLineItem.addAll(APTS_LP_TestUtility.getLineItemListWithDiscount(productConfig.ID, 5, productList[1],9));
            listLineItem.addAll(APTS_LP_TestUtility.getLineItemListWithPriceOveride(productConfig.ID, 5, productList[2],10));
            listLineItem.addAll(APTS_LP_TestUtility.getLineItemListWithPriceOveride(productConfig.ID, 5, productList[3],10));
            (listLineItem.get(listLineItem.size() - 1)).APTS_Discount_Percentage__c = 70.00;
            listLineItem.addAll(APTS_LP_TestUtility.getLineItemListWithDiscount(hierarchyProductConfig.ID, 2, productList[3],5));
            listLineItem.addAll(APTS_LP_TestUtility.getLineItemListWithDiscount(hierarchyProductConfig.ID, 5, productList[4],9));
            listLineItem.addAll(APTS_LP_TestUtility.getLineItemListWithPriceOveride(hierarchyProductConfig.ID, 5, productList[5],10));
            (listLineItem.get(listLineItem.size() - 1)).APTS_Discount_Percentage__c = 70.00;
            insert listLineItem;
            
            productConfig.Apttus_Config2__Status__c = 'Finalized';
            update productConfig;
            hierarchyProductConfig.Apttus_Config2__Status__c = 'Finalized';
            update hierarchyProductConfig;
            
            test.stopTest();
            
            testAgreement  =  [Select APTS_LP_GTV_Level__c,APTS_LP_MaximumSubstituteDiscount__c from Apttus__APTS_Agreement__c where id =: agreement.id limit 1];
        }
    }
    
    // This method fetches those Product Configuration whose status is finalized, and has multiple LineItem with Negative Adjustment-Amount,NetAdjustMentPercent
    public static testMethod void fetchProductConfigurationwithMulipleLineItemNegativeValues() {
        
        user  = APTS_LP_TestUtility.getUser();
        System.runAs(user) {  
            
            APTS_LP_TestUtility.getCustomSetting_QuoteNProposal();
            
            List<Product2> productList =  APTS_LP_TestUtility.getProductList(3);
            Apttus__APTS_Agreement__c agreement =  APTS_LP_TestUtility.getAgreement('Test Agreement');
            
            test.startTest();
            
            insert productList;
            APTS_LP_TestUtility.getDiscountConfig();
            
            APTS_LP_TestUtility.getApproalRuleMatrix();
            insert agreement;
            
            Apttus_Config2__ProductConfiguration__c productConfig = APTS_LP_TestUtility.getProductConfiguration('TestProductConfiguration');
            productConfig.Apttus_CMConfig__AgreementId__c = agreement.id;
            insert productConfig;
            Apttus_Config2__ProductConfiguration__c hierarchyProductConfig = APTS_LP_TestUtility.getProductConfiguration('TestHierarchyProductConfiguration');
            hierarchyProductConfig.Apttus_CMConfig__AgreementId__c = agreement.id;
            insert hierarchyProductConfig;
            
            List<Apttus_Config2__LineItem__c> listLineItem = new List<Apttus_Config2__LineItem__c>();
            // Get the LineItemList
            List<Apttus_Config2__LineItem__c> lineItemWithListPrice1 = APTS_LP_TestUtility.getLineItemListWithDiscount(productConfig.ID, 2, productList[0],5);
            lineItemWithListPrice1.addAll(APTS_LP_TestUtility.getLineItemListWithDiscount(hierarchyProductConfig.ID, 2, productList[3],5));
            for(Apttus_Config2__LineItem__c lineItemWithListPrice : lineItemWithListPrice1) {
                lineItemWithListPrice.Apttus_Config2__AdjustmentType__c = APTS_Constants.DISCOUNT;
                lineItemWithListPrice.Apttus_Config2__AdjustmentAmount__c = 1000;
            }
            listLineItem.addAll(lineItemWithListPrice1);
            
            // Get the LineItemList
            List<Apttus_Config2__LineItem__c> lineItemWithListPrice2 = APTS_LP_TestUtility.getLineItemListWithDiscount(productConfig.ID, 5, productList[1],9);
            lineItemWithListPrice2.addAll(APTS_LP_TestUtility.getLineItemListWithDiscount(hierarchyProductConfig.ID, 5, productList[4],9));
            for(Apttus_Config2__LineItem__c lineItemWithListPrice : lineItemWithListPrice2) {
                lineItemWithListPrice.Apttus_Config2__AdjustmentType__c = APTS_Constants.PRICEOVERIDE;
                lineItemWithListPrice.Apttus_Config2__NetAdjustmentPercent__c = 1000;
            }
            listLineItem.addAll(lineItemWithListPrice2);
            
            // Get the LineItemList
            listLineItem.addAll(APTS_LP_TestUtility.getLineItemListWithPriceOveride(productConfig.ID, 5, productList[2],-10));
            listLineItem.addAll(APTS_LP_TestUtility.getLineItemListWithPriceOveride(hierarchyProductConfig.ID, 5, productList[5],-10));
            insert listLineItem;
            
            productConfig.Apttus_Config2__Status__c = 'Finalized';
            update productConfig;
            hierarchyProductConfig.Apttus_Config2__Status__c = 'Finalized';
            update hierarchyProductConfig;
            
            test.stopTest();
            
            testAgreement  =  [SELECT APTS_LP_GTV_Level__c, APTS_LP_MaximumSubstituteDiscount__c FROM Apttus__APTS_Agreement__c WHERE id =: agreement.id LIMIT 1];
        }
    }

	// This method fetches those Product Configuration whose status is not finalized     
    public static testMethod void fetchProductConfigurationForProposal() {
        
        user = APTS_LP_TestUtility.getUser();
        System.runAs(user) {
            
            APTS_LP_TestUtility.getCustomSetting_QuoteNProposal();
            Apttus_Proposal__Proposal__c proposal= APTS_LP_TestUtility.getProposal('Test Proposal');
            Apttus_Config2__ProductConfiguration__c productConfig = APTS_LP_TestUtility.getProductConfiguration('TestProductConfiguration');
            Account acc = APTS_LP_TestUtility.getNewAccount('Test-Account', 'Spain');
            
            test.startTest();
            
            APTS_LP_TestUtility.getDiscountConfig();
            
            insert acc;
            proposal.APTS_LP_AccountCustomer__c = acc.id;
            insert proposal;
            
            productConfig.Apttus_QPConfig__Proposald__c = proposal.id;
            insert productConfig;
            productConfig.Apttus_Config2__Status__c = 'Saturated';
            update productConfig;
            
            test.stopTest();
        }
    }
    
    // This method fetches Product Configuration that has No LineItem for Proposal
    public static testMethod void fetchProductConfigurationwithNoLineItemForProposal() {
        
        user  = APTS_LP_TestUtility.getUser();
        System.runAs(user) {
            Test.startTest();
            
            APTS_LP_TestUtility.getCustomSetting_QuoteNProposal();
            Account acc = APTS_LP_TestUtility.getNewAccount('Test-Account', 'Spain');
            insert acc;
            
            APTS_LP_TestUtility.getDiscountConfig();
            
            Apttus_Proposal__Proposal__c proposal= APTS_LP_TestUtility.getProposal('Test Proposal');
            proposal.APTS_LP_AccountCustomer__c = acc.id;
            insert proposal;
            
            Apttus_Config2__ProductConfiguration__c productConfig = APTS_LP_TestUtility.getProductConfiguration('TestProductConfiguration');
            productConfig.Apttus_QPConfig__Proposald__c = proposal.id;
            insert productConfig;
            
            productConfig.Apttus_Config2__Status__c = 'Finalized';
            update productConfig;
            
            Test.stopTest();
            
            List<Apttus_Proposal__Proposal__c> proposalList = [SELECT APTS_LP_GTV_Level__c FROM Apttus_Proposal__Proposal__c WHERE id =: proposal.id LIMIT 1];
            System.assertEquals(null, proposalList[0].APTS_LP_GTV_Level__c);
        }
    }
    
    // This method fetches those Product Configuration that has lineitem for Proposal Object
    public static testMethod void fetchProductConfigurationwithOneLineItemForProposal() {
        
        user  = APTS_LP_TestUtility.getUser();
        System.runAs(user){
            
            APTS_LP_TestUtility.getCustomSetting_QuoteNProposal();
            Account acc = APTS_LP_TestUtility.getNewAccount('Test-Account', 'Spain');
            Apttus_Proposal__Proposal__c proposal= APTS_LP_TestUtility.getProposal('Test Proposal');
            
            test.startTest();
            
            insert acc;
            APTS_LP_TestUtility.getDiscountConfig();
            APTS_LP_TestUtility.getApproalRuleMatrix();
            proposal.APTS_LP_AccountCustomer__c = acc.id;
            insert proposal;
            
            Product2 prod =  APTS_LP_TestUtility.getProduct();
            insert prod;
            Product2 hierachyProd =  APTS_LP_TestUtility.getHierarchyProduct();
            hierachyProd.APTS_Hierarchy_Level_3_Code__c = null;
            insert hierachyProd;
            
            Apttus_Config2__ProductConfiguration__c productConfig = APTS_LP_TestUtility.getProductConfiguration('TestProductConfiguration');
            productConfig.Apttus_QPConfig__Proposald__c = proposal.id;
            insert productConfig;
            Apttus_Config2__ProductConfiguration__c hierarchyProductConfig = APTS_LP_TestUtility.getProductConfiguration('TestProductConfiguration');
            hierarchyProductConfig.Apttus_QPConfig__Proposald__c = proposal.id;
            insert hierarchyProductConfig;
            
            List<Apttus_Config2__LineItem__c> listLineItem = new List<Apttus_Config2__LineItem__c>();
            listLineItem.addAll(APTS_LP_TestUtility.getLineItemListWithDiscount(productConfig.ID, 1, prod, 5));
            listLineItem.addAll(APTS_LP_TestUtility.getLineItemListWithDiscount(hierarchyProductConfig.ID, 1, hierachyProd, 5));
            
            productConfig.Apttus_Config2__Status__c = 'Finalized';
            update productConfig;
            hierarchyProductConfig.Apttus_Config2__Status__c = 'Finalized';
            update hierarchyProductConfig;
            
            test.stopTest();
            
            List<Apttus_Proposal__Proposal__c> proposalList = [SELECT APTS_LP_GTV_Level__c FROM Apttus_Proposal__Proposal__c WHERE id =: proposal.id LIMIT 1];
        }
    }
    
    // This method fetches those Product Configuration whose status is finalized, and has multiple
    // LineItem with Positive Adjustment-Amount,NetAdjustMentPercent
    public static testMethod void fetchProductConfigurationwithMulipleLineItemForProposal() {
        
        user  = APTS_LP_TestUtility.getUser();
        System.runAs(user) {  
            
            APTS_LP_TestUtility.getCustomSetting_QuoteNProposal();
            List<Product2> productList =  APTS_LP_TestUtility.getProductList(3);
            Apttus_Proposal__Proposal__c proposal = APTS_LP_TestUtility.getProposal('Test Proposal');
            Account acc = APTS_LP_TestUtility.getNewAccount('Test-Account', 'Spain');
            
            test.startTest();
            
            insert productList;
            APTS_LP_TestUtility.getDiscountConfig();
            
            APTS_LP_TestUtility.getApproalRuleMatrix();
            insert acc;
            proposal.APTS_LP_AccountCustomer__c = acc.id;
            insert proposal;
            Apttus_Config2__ProductConfiguration__c productConfig = APTS_LP_TestUtility.getProductConfiguration('TestProductConfiguration');
            productConfig.Apttus_QPConfig__Proposald__c = proposal.id;
            insert productConfig;
            
            Apttus_Config2__ProductConfiguration__c hierarchyProductConfig = APTS_LP_TestUtility.getProductConfiguration('TestHierarchyProductConfiguration');
            hierarchyProductConfig.Apttus_QPConfig__Proposald__c = proposal.id;
            insert hierarchyProductConfig;
            
            List<Apttus_Config2__LineItem__c> listLineItem = new List<Apttus_Config2__LineItem__c>();
            listLineItem.addAll(APTS_LP_TestUtility.getLineItemListWithDiscount(productConfig.ID, 2, productList[0],5));
            listLineItem.addAll(APTS_LP_TestUtility.getLineItemListWithDiscount(productConfig.ID, 5, productList[1],9));
            listLineItem.addAll(APTS_LP_TestUtility.getLineItemListWithPriceOveride(productConfig.ID, 5, productList[2],10));
            listLineItem.addAll(APTS_LP_TestUtility.getLineItemListWithPriceOveride(productConfig.ID, 5, productList[3],10));
            (listLineItem.get(listLineItem.size() - 1)).APTS_Discount_Percentage__c = 70.00;
            listLineItem.addAll(APTS_LP_TestUtility.getLineItemListWithDiscount(hierarchyProductConfig.ID, 2, productList[3],5));
            listLineItem.addAll(APTS_LP_TestUtility.getLineItemListWithDiscount(hierarchyProductConfig.ID, 5, productList[4],9));
            listLineItem.addAll(APTS_LP_TestUtility.getLineItemListWithPriceOveride(hierarchyProductConfig.ID, 5, productList[5],10));
            (listLineItem.get(listLineItem.size() - 1)).APTS_Discount_Percentage__c = 70.00;
            insert listLineItem;
            
            productConfig.Apttus_Config2__Status__c = 'Finalized';
            update productConfig;
            hierarchyProductConfig.Apttus_Config2__Status__c = 'Finalized';
            update hierarchyProductConfig;
            
            test.stopTest();
        }
    }
    
    
    // This method fetches those Product Configuration whose status is finalized, and has multiple LineItem with Negative Adjustment-Amount,NetAdjustMentPercent
    public static testMethod void fetchProductConfigurationwithMulipleLineItemNegativeValuesForProposal() {
        
        user  = APTS_LP_TestUtility.getUser();
        System.runAs(user) {  
            
            APTS_LP_TestUtility.getCustomSetting_QuoteNProposal();
            List<Product2> productList =  APTS_LP_TestUtility.getProductList(3);
            Apttus_Proposal__Proposal__c proposal = APTS_LP_TestUtility.getProposal('Test Proposal');
            Account acc = APTS_LP_TestUtility.getNewAccount('Test-Account', 'Spain');
            
            test.startTest();
            
            insert productList;
            APTS_LP_TestUtility.getDiscountConfig();
            APTS_LP_TestUtility.getApproalRuleMatrix();
            
            insert acc;
            proposal.APTS_LP_AccountCustomer__c = acc.id;
            insert proposal;
            
            Apttus_Config2__ProductConfiguration__c productConfig = APTS_LP_TestUtility.getProductConfiguration('TestProductConfiguration');
            productConfig.Apttus_QPConfig__Proposald__c = proposal.id;
            insert productConfig;
            Apttus_Config2__ProductConfiguration__c hierarchyProductConfig = APTS_LP_TestUtility.getProductConfiguration('TestHierarchyProductConfiguration');
            hierarchyProductConfig.Apttus_QPConfig__Proposald__c = proposal.id;
            insert hierarchyProductConfig;
            
            List<Apttus_Config2__LineItem__c> listLineItem = new List<Apttus_Config2__LineItem__c>();
            // Get the LineItemList
            List<Apttus_Config2__LineItem__c> lineItemWithListPrice1 = APTS_LP_TestUtility.getLineItemListWithDiscount(productConfig.ID, 2, productList[0],5);
            lineItemWithListPrice1.addAll(APTS_LP_TestUtility.getLineItemListWithDiscount(hierarchyProductConfig.ID, 2, productList[3],5));
            for(Apttus_Config2__LineItem__c lineItemWithListPrice : lineItemWithListPrice1) {
                lineItemWithListPrice.Apttus_Config2__AdjustmentType__c = APTS_Constants.DISCOUNT;
                lineItemWithListPrice.Apttus_Config2__AdjustmentAmount__c = 1000;
            }
            listLineItem.addAll(lineItemWithListPrice1);
            
            // Get the LineItemList
            List<Apttus_Config2__LineItem__c> lineItemWithListPrice2 = APTS_LP_TestUtility.getLineItemListWithDiscount(productConfig.ID, 5, productList[1],9);
            lineItemWithListPrice2.addAll(APTS_LP_TestUtility.getLineItemListWithDiscount(hierarchyProductConfig.ID, 5, productList[4],9));
            for(Apttus_Config2__LineItem__c lineItemWithListPrice : lineItemWithListPrice2) {
                lineItemWithListPrice.Apttus_Config2__AdjustmentType__c = APTS_Constants.PRICEOVERIDE;
                lineItemWithListPrice.Apttus_Config2__NetAdjustmentPercent__c = 1000;
            }
            listLineItem.addAll(lineItemWithListPrice2);
            
            // Get the LineItemList
            listLineItem.addAll(APTS_LP_TestUtility.getLineItemListWithPriceOveride(productConfig.ID, 5, productList[2],-10));
            listLineItem.addAll(APTS_LP_TestUtility.getLineItemListWithPriceOveride(hierarchyProductConfig.ID, 5, productList[5],-10));
            insert listLineItem;
            
            productConfig.Apttus_Config2__Status__c = 'Finalized';
            update productConfig;
            hierarchyProductConfig.Apttus_Config2__Status__c = 'Finalized';
            update hierarchyProductConfig;
            
            test.stopTest();
        }
    }
}