src/objects/APTS_Capture_LSO_Input_Config_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom object to configure settings like dropdown list values etc. for Capture LSO Input page while creating MSPA or Quotation from Account or Opportunity.</description>
    <label>Capture LSO Input Config Settings</label>
</CustomObject>

src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>APTS_LP_AccountCustomer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Customer name of the direct customer</description>
        <inlineHelpText>Direct customer to which the MSPA is related. Auto populated if MSPA created from Opportunity or Buying Account.</inlineHelpText>
        <label>Account Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>GIS Approved</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>MSPAs</relationshipName>
        <type>Lookup</type>
    </fields>
    
    <fields>
        <fullName>Apttus__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The link to the account record to identify the external party to this agreement</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N50000001Xl0UEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
	<fullName>Apttus__Related_Opportunity__c</fullName>
	<deleteConstraint>SetNull</deleteConstraint>
	<inlineHelpText>Auto populated only if MSPA created from an opportunity</inlineHelpText>
	<label>Related Opportunity</label>
	<referenceTo>Opportunity</referenceTo>
	<relationshipName>R00N50000001Xl0FEAS</relationshipName>
	<type>Lookup</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__LineItem__c.object
<CustomObject>
</CustomObject>

src/objects/Apttus_Config2__ProductConfiguration__c.object
<CustomObject>
    <fields>
        <fullName>Apttus_Config2__Status__c</fullName>
        <description>The current status of the configuration</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Ready For Approvals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready For Finalization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalized</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Superseded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved but Action Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
</CustomObject>

src/classes/APTS_SaveAndExitCartControllerTest.cls
@isTest
private class APTS_SaveAndExitCartControllerTest {
	
 	private static User user;
    // Apttus Agreement Object
    private static Apttus__APTS_Agreement__c agreement;
    private static APTS_Capture_LSO_Input_Config_Settings__c lodConfigSetting = APTS_LP_TestUtility.getLODConfigSetting();
    

	@isTest static void test_method_one() {

		user  = APTS_LP_TestUtility.getUser();
        System.runAs(user) {
            APTS_LP_TestUtility.getCustomSetting_QuoteNProposal();
        	Account acc  = APTS_LP_TestUtility.getNewAccount('Test','Spain');
            acc.RecordTypeId= Schema.SObjectType.Account.getRecordTypeInfosByName().get('ABB ICV').getRecordTypeId();
        	insert acc;

        	Opportunity opp = APTS_LP_TestUtility.getOpportunity('Test Opp');
			opp.AccountId = acc.id;
        	insert opp;
        	
		    agreement = APTS_LP_TestUtility.getAgreement('TestAgreement');
            APTS_LP_TestUtility.getDiscountConfig();
            
            agreement.Apttus__Account__c = acc.id;
            agreement.Apttus__Related_Opportunity__c = opp.id;
            APTS_LP_TestUtility.getApproalRuleMatrix();
            insert agreement;
            
            
            List<Product2> productList =  APTS_LP_TestUtility.getProductList(3);
            Test.startTest();
            Apttus_Proposal__Proposal__c proposal = APTS_LP_TestUtility.getProposal('Test Proposal');
                        
            
            
            insert productList;
            //APTS_LP_TestUtility.getDiscountConfig();
            //APTS_LP_TestUtility.getApproalRuleMatrix();
            
            proposal.APTS_LP_AccountCustomer__c = acc.id;
            proposal.Apttus_Proposal__Opportunity__c = opp.id;
            insert proposal;
            Apttus_Config2__ProductConfiguration__c productConfig = APTS_LP_TestUtility.getProductConfiguration('TestProductConfiguration');
            productConfig.Apttus_QPConfig__Proposald__c = proposal.id;
            insert productConfig;

            System.debug('--> pc id :'+productConfig.id);
            
            Apttus_Config2__ProductConfiguration__c hierarchyProductConfig = APTS_LP_TestUtility.getProductConfiguration('TestHierarchyProductConfiguration');
            hierarchyProductConfig.Apttus_QPConfig__Proposald__c = proposal.id;
            insert hierarchyProductConfig;
            
            List<Apttus_Config2__LineItem__c> listLineItem = new List<Apttus_Config2__LineItem__c>();
            listLineItem.addAll(APTS_LP_TestUtility.getLineItemListWithDiscount(productConfig.ID, 2, productList[0],5));
            listLineItem.addAll(APTS_LP_TestUtility.getLineItemListWithDiscount(productConfig.ID, 5, productList[1],9));
            listLineItem.addAll(APTS_LP_TestUtility.getLineItemListWithPriceOveride(productConfig.ID, 5, productList[2],10));
            listLineItem.addAll(APTS_LP_TestUtility.getLineItemListWithDiscount(hierarchyProductConfig.ID, 2, productList[3],5));
            listLineItem.addAll(APTS_LP_TestUtility.getLineItemListWithDiscount(hierarchyProductConfig.ID, 5, productList[4],9));
            listLineItem.addAll(APTS_LP_TestUtility.getLineItemListWithPriceOveride(hierarchyProductConfig.ID, 5, productList[5],10));
            insert listLineItem;

            productConfig.Apttus_Config2__Status__c = 'Finalized';
            update productConfig;
            hierarchyProductConfig.Apttus_Config2__Status__c = 'Finalized';
            update hierarchyProductConfig;
         


            

            Test.setCurrentPageReference(new PageReference('Page.APTS_SaveAndExitCartPage')); 
			System.currentPageReference().getParameters().put('Id', productConfig.id);
			try{
				APTS_SaveAndExitCartController saveAndExitCntrlr = new APTS_SaveAndExitCartController();
				PageReference pgRef = saveAndExitCntrlr.syncwithOppportunity();

			}catch(Exception e){
				System.debug(e.getMessage());
				// giving error in method.
				/*
				System.NullPointerException: Attempt to de-reference a null object
				Class.APTS_SaveAndExitCartController.syncwithOppportunity: line 48, column 1
				*/
			}
			
			
			Test.stopTest();
          }
		
	}
	
	
	
}