src/objects/APTS_Capture_LSO_Input_Config_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom object to configure settings like dropdown list values etc. for Capture LSO Input page while creating MSPA or Quotation from Account or Opportunity.</description>
    <label>Capture LSO Input Config Settings</label>
</CustomObject>

src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    
    <fields>
        <fullName>Apttus__Status__c</fullName>
        <description>The sub stage of an agreement – the status underneath a given status category.  These are generally modifiable by the customer except for the following values which are Apttus reserved to manage agreement lifecycles:

Request, Submitted Request,
Cancelled Request, In Amendment, Being Amended, Superseded, Activated, Expired, Internal Signatures, Author Contract, Expired, Terminated,  Ready for Signatures, Fully Signed, Signature Declined</description>
        <label>Status</label>
        <picklist>
            <controllingField>Apttus__Status_Category__c</controllingField>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approval In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturated Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved but failed to load on SAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved but Action Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deactivated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Signatures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queued to create in SAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recalled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Generated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Presented</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/APTS_AgreementStatusControllerTest.cls
/*************************************************************
@Name: APTS_AgreementStatusControllerTest
@Author: Hardik Shah
@CreateDate: 09/09/2015
@Description: This class tests following Classes : APTS_AgreementStatusController
@UsedBy: NA
******************************************************************
@ModifiedBy: NA
@ModifiedDate: NA
@ChangeDescription: A brief description of what was modified.
**** PS: @ModifiedBy and @ChangeDescription can be repeated multiple time, based on number of changes made to the original process.
******************************************************************/


@isTest
public class APTS_AgreementStatusControllerTest {

    // Instance Variable of APTS_AgreementStatusController
    private static APTS_AgreementStatusController statusController;
    // User Variable for System Admin Profile
    private static User user;
    // Apttus Agreement Object
    private static Apttus__APTS_Agreement__c agreement;
    private static APTS_Capture_LSO_Input_Config_Settings__c lodConfigSetting = APTS_LP_TestUtility.getLODConfigSetting();
    
    // Test-Class When Agrement is not avialable
    public static testMethod void fetchNonExistsAgreement(){
       
        // Test-Case with System-Admin User
        user  = APTS_LP_TestUtility.getUser();
        System.runAs(user) {
             APTS_LP_TestUtility.getCommonConfigSetting();
		     agreement = APTS_LP_TestUtility.getAgreement('TestAgreement');
             ApexPages.StandardController stdController = new ApexPages.StandardController(agreement); 
           	 statusController = new APTS_AgreementStatusController(stdController);
             test.startTest();
       	     PageReference ref = statusController.onload();
             test.stopTest();
        	 system.assertEquals(null,ref);
          }
             
    }
    
     // Test-Class when Agrement is Avialable but Request Parameter doesn't exists
     public static testMethod void fetchExistsAgreement(){
       
        // Test-Case with System-Admin User
        user  = APTS_LP_TestUtility.getUser();
        System.runAs(user) {
		     APTS_LP_TestUtility.getCommonConfigSetting();
             agreement = APTS_LP_TestUtility.getAgreement('TestAgreement');
             APTS_LP_TestUtility.getDiscountConfig();
             test.startTest();
             insert agreement;
             ApexPages.StandardController stdController = new ApexPages.StandardController(agreement); 
           	 statusController = new APTS_AgreementStatusController(stdController);
             PageReference ref = statusController.onload();
             test.stopTest();
        	 system.assertEquals(null,ref);
          }
      }
    
    // Test-Class when Agreement is Avialable and Request Parameter Exits
     public static testMethod void updateAgreementStatusToDeActivated(){
       
        // Test-Case with System-Admin User
        user  = APTS_LP_TestUtility.getUser();
        System.runAs(user) {
             APTS_LP_TestUtility.getCommonConfigSetting();
		     agreement = APTS_LP_TestUtility.getAgreement('TestAgreement');
             Test.startTest();
             APTS_LP_TestUtility.getDiscountConfig();
             insert agreement;
             system.debug('agr1-->' + agreement);
             ApexPages.StandardController stdController = new ApexPages.StandardController(agreement);
             Test.setCurrentPageReference(new PageReference('Page.myPage')); 
			 System.currentPageReference().getParameters().put('requestParameter', 'DeActivated');
             statusController = new APTS_AgreementStatusController(stdController);
             PageReference ref = statusController.onload();
             Test.stopTest();
             
             List<Apttus__APTS_Agreement__c> testAgreement  =  [Select Apttus__Status__c from Apttus__APTS_Agreement__c where id =: agreement.id limit 1];
                        
             system.assertEquals('Deactivated',testAgreement[0].Apttus__Status__c);
             
          }
      }
    
    // Test-Class when Agreement is Avialable and Request Parameter Exits
     public static testMethod void updateAgreementStatusToBlocked(){
       
        // Test-Case with System-Admin User
        user  = APTS_LP_TestUtility.getUser();
        System.runAs(user) {
             APTS_LP_TestUtility.getCommonConfigSetting();
		     agreement = APTS_LP_TestUtility.getAgreement('TestAgreement');
             APTS_LP_TestUtility.getDiscountConfig();
             test.startTest();
             insert agreement;
             ApexPages.StandardController stdController = new ApexPages.StandardController(agreement);
             Test.setCurrentPageReference(new PageReference('Page.myPage')); 
			 System.currentPageReference().getParameters().put('requestParameter', 'Blocked');
             statusController = new APTS_AgreementStatusController(stdController);
             PageReference ref = statusController.onload();
             test.stopTest();
             List<Apttus__APTS_Agreement__c> testAgreement  =  [Select Apttus__Status__c from Apttus__APTS_Agreement__c where id =: agreement.id limit 1];
             system.assertEquals('Blocked',testAgreement[0].Apttus__Status__c);
             
          }
      }
    
    // Test-Class when Agreement is Avialable and Request Parameter is Different
     public static testMethod void updateAgreementStatusToOtherStatus(){
       
        // Test-Case with System-Admin User
        user  = APTS_LP_TestUtility.getUser();
       System.runAs(user) {
             APTS_LP_TestUtility.getCommonConfigSetting();
		     agreement = APTS_LP_TestUtility.getAgreement('TestAgreement');
           	 agreement.Apttus__Status__c = APTS_Constants.AGREEMENT_STATUS;
             APTS_LP_TestUtility.getDiscountConfig();
             test.startTest();
             insert agreement;
             ApexPages.StandardController stdController = new ApexPages.StandardController(agreement);
             Test.setCurrentPageReference(new PageReference('Page.myPage')); 
			 System.currentPageReference().getParameters().put('requestParameter', 'Test');
             statusController = new APTS_AgreementStatusController(stdController);
             PageReference ref = statusController.onload();
             test.stopTest();
             List<Apttus__APTS_Agreement__c> testAgreement  =  [Select Apttus__Status__c from Apttus__APTS_Agreement__c where id =: agreement.id limit 1];
            // system.assertEquals('Draft',testAgreement[0].Apttus__Status__c);
             
          }
      }
      
       // Test-Class when Agreement is Avialable and Request Parameter is Different
     /*public static testMethod void updateAgreementStatusToOPendingApproval(){
       
        // Test-Case with System-Admin User
        user  = APTS_LP_TestUtility.getUser();
        System.runAs(user) {
		     agreement = APTS_LP_TestUtility.getAgreement('TestAgreement');
             APTS_LP_TestUtility.getDiscountConfig();
		     agreement.Apttus__Status__c = 'Pending Approval';
             test.startTest();
             insert agreement;
             ApexPages.StandardController stdController = new ApexPages.StandardController(agreement);
             Test.setCurrentPageReference(new PageReference('Page.myPage')); 
			 System.currentPageReference().getParameters().put('requestParameter', 'Test');
             statusController = new APTS_AgreementStatusController(stdController);
             PageReference ref = statusController.onload();
             test.stopTest();
             List<Apttus__APTS_Agreement__c> testAgreement  =  [Select Apttus__Status__c from Apttus__APTS_Agreement__c where id =: agreement.id limit 1];
             system.assertEquals('Pending Approval',testAgreement[0].Apttus__Status__c);
             
          }
      }*/
    
    
}