src/objects/APTS_Agreement_SAP_Setting__c.object
<CustomObject>
    <description>Used to enable/disable auto creation of MSPA agreement in SAP, and Block MSPA agreement in SAP</description>
    <fields>
        <fullName>APTS_Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Spain</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Agreement SAP Setting</label>
    <nameField>
        <displayFormat>AS-{00000}</displayFormat>
        <label>Agreement SAP Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreement SAP Settings</pluralLabel>
    <recordTypes>
        <fullName>Spain</fullName>
        <active>true</active>
        <label>Spain</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/APTS_Discounts_Config__c.object
<CustomObject>
    <fields>
        <fullName>APTS_Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Spain</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Discount Config</label>
    <nameField>
        <displayFormat>DC-{00000}</displayFormat>
        <label>Discounts Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discounts Config</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus__AgreementLineItem__c.object
<CustomObject>
    <description>Represents a product or service line item associated with an agreement</description>
    <fields>
        <fullName>APTS_Discount_Type__c</fullName>
        <description>Field used by user to select appropriate type of discount in line item.</description>
        <label>Discount Type</label>
        <picklist>
            <picklistValues>
                <fullName>--None--</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net Price Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Additional Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Substitute Discount</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__BasePrice__c</fullName>
        <description>The base price is List price + Automatic Adjustments for individual products and options</description>
        <label>Base Price</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Apttus__ProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the selected product or service</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Agreement Line Items</relationshipLabel>
        <relationshipName>AgreementLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus__Quantity__c</fullName>
        <description>The product or service quantity</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <label>Agreement Line Item</label>
    <nameField>
        <displayFormat>AL-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreement Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>APTS_Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Spain</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    
    <fields>
	<fullName>Apttus__Related_Opportunity__c</fullName>
	<deleteConstraint>SetNull</deleteConstraint>
	<inlineHelpText>Auto populated only if MSPA created from an opportunity</inlineHelpText>
	<label>Related Opportunity</label>
	<referenceTo>Opportunity</referenceTo>
	<relationshipName>R00N50000001Xl0FEAS</relationshipName>
	<type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus__Status__c</fullName>
        <description>The sub stage of an agreement – the status underneath a given status category.  These are generally modifiable by the customer except for the following values which are Apttus reserved to manage agreement lifecycles:

Request, Submitted Request,
Cancelled Request, In Amendment, Being Amended, Superseded, Activated, Expired, Internal Signatures, Author Contract, Expired, Terminated,  Ready for Signatures, Fully Signed, Signature Declined</description>
        <label>Status</label>
        <picklist>
            <controllingField>Apttus__Status_Category__c</controllingField>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approval In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturated Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved but failed to load on SAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved but Action Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deactivated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Signatures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queued to create in SAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recalled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Generated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Presented</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__PriceList__c.object
<CustomObject>
    <fields>
        <fullName>APTS_Country__c</fullName>
        <description>Name of the country for which price list exists</description>
        <label>Country</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>APTS_LP_Is_Hierarchy__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check only if Product Hierarchy is created.</description>
        <label>Is Hierarchy</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/classes/APTS_MSPACreatorInSAPControllerTest.cls
@isTest
public class APTS_MSPACreatorInSAPControllerTest {

    private static Apttus_Config2__PriceList__c testPriceList;
    private static User user;
    private static Account acc ;
    private static Apttus__APTS_Agreement__c agr;
    private static final String QUOTE_RECORD_TYPE = 'LP'; 

    public static testMethod void APTS_MSPACreatorInSAPControllerTest1() {
    
        Test.startTest();
            
        List < APTS_Discounts_Config__c > listDisConfig = APTS_LP_TestUtility.getDiscountConfig();
        APTS_LP_TestUtility.getCommonConfigSetting();
        acc =  APTS_LP_TestUtility.getNewAccount('Test-Account', 'Spain');
        insert acc;
        
        Product2 product2 = APTS_LP_TestUtility.getProduct();
        product2.APTS_LP_Is_Hierarchy__c = false;
        insert product2;
        
        Opportunity opp = APTS_LP_TestUtility.getOpportunity('Test Oppty');
        insert opp;
        
        Partner part = APTS_LP_TestUtility.getPartner(opp.Id, acc.Id);
        insert part;
        
        Apttus_Config2__PriceList__c priceList = new Apttus_Config2__PriceList__c();
        priceList.APTS_Country__c = 'Spain';
        insert priceList;
        
        agr = APTS_LP_TestUtility.getAgreement('TestAgreement');
        agr.Apttus__Related_Opportunity__c = opp.Id;
        insert agr;
        
        Apttus__AgreementLineItem__c objAgreementLineItem = APTS_LP_TestUtility.getAgreementLineItem(agr.ID);
        objAgreementLineItem.Apttus_CMConfig__BasePrice__c = 10;
        objAgreementLineItem.Apttus__ProductId__r = product2;
        objAgreementLineItem.Apttus__Quantity__c = 5;
        objAgreementLineItem.APTS_Discount_Type__c = 'Substitute Discount' ;
        insert objAgreementLineItem;
        
        Set<Id> AggrementIds = new Set<Id>();
        AggrementIds.add(agr.ID);
        
        APTS_Agreement_SAP_Setting__c sapSetting = new APTS_Agreement_SAP_Setting__c();
        sapSetting.APTS_Country__c = agr.APTS_Country__c;
        insert sapSetting;
        
        APTS_LP_TestUtility.getIntegrationParameters();
        
        agr.Apttus__Status__c = 'Approved but Action Required';
        update agr;
        
        Boolean BlockParam = True;
    
        Apexpages.currentpage().getparameters().put('BlockParam','BlockParam');
 
        ApexPages.StandardController sc = new ApexPages.StandardController(agr);
        APTS_MSPACreatorInSAPController objAPTS_MSPACreatorInSAPController = new APTS_MSPACreatorInSAPController(sc);
        objAPTS_MSPACreatorInSAPController.backToMSPA();
        objAPTS_MSPACreatorInSAPController.createMSPAviaButton();
       // APTS_MSPACreatorInSAPController.createOrBlockMSPA(AggrementIds,'True');
        APTS_MSPACreatorInSAPController.createMSPA(AggrementIds,'True');
        
        Test.stopTest();
    
    }
    
    public static testMethod void APTS_MSPACreatorInSAPControllerTestBlockMSPA() {
    
        Test.startTest();
            
        List < APTS_Discounts_Config__c > listDisConfig = APTS_LP_TestUtility.getDiscountConfig();
        APTS_LP_TestUtility.getCommonConfigSetting();
        acc =  APTS_LP_TestUtility.getNewAccount('Test-Account', 'Spain');
        insert acc;
        
        Product2 product2 = APTS_LP_TestUtility.getProduct();
        product2.APTS_LP_Is_Hierarchy__c = false;
        insert product2;
        
        Opportunity opp = APTS_LP_TestUtility.getOpportunity('Test Oppty');
        insert opp;
        
        Partner part = APTS_LP_TestUtility.getPartner(opp.Id, acc.Id);
        insert part;
        
        Apttus_Config2__PriceList__c priceList = new Apttus_Config2__PriceList__c();
        priceList.APTS_Country__c = 'Spain';
        insert priceList;
        
        agr = APTS_LP_TestUtility.getAgreement('TestAgreement');
        agr.Apttus__Related_Opportunity__c = opp.Id;
        insert agr;
        
        Apttus__AgreementLineItem__c objAgreementLineItem = APTS_LP_TestUtility.getAgreementLineItem(agr.ID);
        objAgreementLineItem.Apttus_CMConfig__BasePrice__c = 10;
        objAgreementLineItem.Apttus__ProductId__r = product2;
        objAgreementLineItem.Apttus__Quantity__c = 5;
        objAgreementLineItem.APTS_Discount_Type__c = 'Substitute Discount' ;
        insert objAgreementLineItem;
        
        Set<Id> AggrementIds = new Set<Id>();
        AggrementIds.add(agr.ID);
        
        APTS_Agreement_SAP_Setting__c sapSetting = new APTS_Agreement_SAP_Setting__c();
        sapSetting.APTS_Country__c = agr.APTS_Country__c;
        insert sapSetting;
        
        APTS_LP_TestUtility.getIntegrationParameters();
        
        agr.Apttus__Status__c = 'Approved but Action Required';
        update agr;
        
        Boolean BlockParam = True;
    
        Apexpages.currentpage().getparameters().put('BlockParam','BlockParam');
 
        ApexPages.StandardController sc = new ApexPages.StandardController(agr);
        APTS_MSPACreatorInSAPController objAPTS_MSPACreatorInSAPController = new APTS_MSPACreatorInSAPController(sc);
        APTS_MSPACreatorInSAPController.createOrBlockMSPA(AggrementIds,'True');
        
        Test.stopTest();
    
    }
    
    
    public static testMethod void APTS_MSPACreatorInSAPControllerTest3() {
            
        APTS_LP_TestUtility.getDiscountConfig();
        APTS_LP_TestUtility.getCommonConfigSetting();
        acc =  APTS_LP_TestUtility.getNewAccount('Test-Account', 'Spain');
        insert acc;
        
        testPriceList = APTS_LP_TestUtility.getPriceList(acc,'Spain');
        insert testPriceList;
        
        Opportunity opp = APTS_LP_TestUtility.getOpportunity('Test Oppty');
        insert opp;
        
        APTS_Agreement_SAP_Setting__c sapSetting = new APTS_Agreement_SAP_Setting__c();
        sapSetting.APTS_Country__c = 'Spain';
        insert sapSetting;
        
        APTS_ProcessorControl.inFutureContext = false;
        
        APTS_LP_TestUtility.getIntegrationParameters();
        
        agr = APTS_LP_TestUtility.getAgreement('TestAgreement');
        agr.Apttus__Related_Opportunity__c = opp.Id;
        insert agr;
        
        Set<Id> AggrementIds = new Set<Id>();
        AggrementIds.add(agr.ID);
        
        APTS_LP_TestUtility.getIntegrationParameters();
        APTS_LP_TestUtility.getSAPIntegrationTokens();
        
        Product2 product2 = APTS_LP_TestUtility.getProduct();
        product2.APTS_LP_Is_Hierarchy__c = false;
        insert product2;
        
        List<Apttus__AgreementLineItem__c> listAgreementLineItem = APTS_LP_TestUtility.getAgreementLineItemList(agr.id,2);
        
        for(Apttus__AgreementLineItem__c agrLineItem: listAgreementLineItem){
            
            agrLineItem.Apttus_CMConfig__BasePrice__c = 10;
            agrLineItem.Apttus__ProductId__r = product2;
            agrLineItem.Apttus__Quantity__c = 5;
            agrLineItem.APTS_Discount_Type__c = 'Substitute Discount' ;
            
        }
        insert listAgreementLineItem;
        
        agr.Apttus__Status__c = 'Approved but Action Required';
        
        update agr;
        
        Test.setMock(HttpCalloutMock.class, new APTPS_SAPCalloutMockTest());
        
        test.startTest();
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(agr); 
        APTS_MSPACreatorInSAPController obj = new APTS_MSPACreatorInSAPController(stdController);        
        APTS_MSPACreatorInSAPController.createOrBlockMSPA(AggrementIds,'True');
        
        test.stopTest();
           
    }
    
    public static testMethod void APTS_MSPACreatorInSAPControllerTest2() {
    
        Test.startTest();
            
        List < APTS_Discounts_Config__c > listDisConfig = APTS_LP_TestUtility.getDiscountConfig();
        APTS_LP_TestUtility.getCommonConfigSetting();
        acc =  APTS_LP_TestUtility.getNewAccount('Test-Account', 'Spain');
        insert acc;
        
        Product2 product2 = APTS_LP_TestUtility.getProduct();
        product2.APTS_LP_Is_Hierarchy__c = false;
        insert product2;
        
        Opportunity opp = APTS_LP_TestUtility.getOpportunity('Test Oppty');
        insert opp;
        
        Partner part = APTS_LP_TestUtility.getPartner(opp.Id, acc.Id);
        insert part;
        
        Apttus_Config2__PriceList__c priceList = new Apttus_Config2__PriceList__c();
        priceList.APTS_Country__c = 'Spain';
        insert priceList;
        
        agr = APTS_LP_TestUtility.getAgreement('TestAgreement');
        agr.Apttus__Related_Opportunity__c = opp.Id;
        insert agr;
        
        Apttus__AgreementLineItem__c objAgreementLineItem = APTS_LP_TestUtility.getAgreementLineItem(agr.ID);
        objAgreementLineItem.Apttus_CMConfig__BasePrice__c = 10;
        objAgreementLineItem.Apttus__ProductId__r = product2;
        objAgreementLineItem.Apttus__Quantity__c = 5;
        objAgreementLineItem.APTS_Discount_Type__c = 'Substitute Discount' ;
        insert objAgreementLineItem;
        
        Set<Id> AggrementIds = new Set<Id>();
        AggrementIds.add(agr.ID);
        
        APTS_Agreement_SAP_Setting__c sapSetting = new APTS_Agreement_SAP_Setting__c();
        sapSetting.APTS_Country__c = agr.APTS_Country__c;
        insert sapSetting;
        
        APTS_LP_TestUtility.getIntegrationParameters();
        
        Boolean BlockParam = True;
    
        Apexpages.currentpage().getparameters().put('BlockParam','BlockParam');

        ApexPages.StandardController sc = new ApexPages.StandardController(agr);
        APTS_MSPACreatorInSAPController objAPTS_MSPACreatorInSAPController = new APTS_MSPACreatorInSAPController(sc);
        APTS_MSPACreatorInSAPController.createMSPA(AggrementIds,'True');
        
        Test.stopTest();
    
    }
    

}