src/objects/APTS_Capture_LSO_Input_Config_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom object to configure settings like dropdown list values etc. for Capture LSO Input page while creating MSPA or Quotation from Account or Opportunity.</description>
    <label>Capture LSO Input Config Settings</label>
</CustomObject>

src/objects/APTS_Stage_Data_Validation_Rules_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>APTS_Category_Sequence__c</fullName>
        <description>Determines the sequence of Category</description>
        <inlineHelpText>Values should be Semicolon Seperated</inlineHelpText>
        <label>Category Sequence</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>APTS_Validate_SFDC_User__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Flag to check if Assigned Approver and Actual Approver fields required validation against SFDC User Object</description>
        <label>Validate SFDC User</label>
        <type>Checkbox</type>
    </fields>
	<label>APTS Stage Data Validation Rules</label>
</CustomObject>

src/objects/APTS_Stage_Local_Hierarchy__c.object
<CustomObject>
    <description>Stage Local Hierarchy</description>
    <fields>
        <fullName>APTS_Active__c</fullName>
        <label>Active</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_External_ID__c</fullName>
        <description>External ID</description>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>60</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>APTS_Level2_Code__c</fullName>
        <description>Level 2 Code</description>
        <label>Level 2 Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Level2_Name__c</fullName>
        <description>Level 2 Name</description>
        <inlineHelpText>Level 2 Name</inlineHelpText>
        <label>Level 2 Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Level3_Code__c</fullName>
        <description>Level 3 Code</description>
        <label>Level 3 Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Level3_Name__c</fullName>
        <description>Level 3 Name</description>
        <inlineHelpText>Level 3 Name</inlineHelpText>
        <label>Level 3 Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Level4_Name__c</fullName>
        <description>Level 4 Name</description>
        <inlineHelpText>Level 4 Name</inlineHelpText>
        <label>Level 4 Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Stage Local Hierarchy</label>
    <nameField>
        <displayFormat>LH-{00000}</displayFormat>
        <label>Local Hierarchy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stage Local Hierarchy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__ClassificationHierarchy__c.object
<CustomObject>
    <fields>
        <fullName>APTS_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_LP_Code__c</fullName>
        <inlineHelpText>Category Level 4 Name</inlineHelpText>
        <label>Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Apttus_Config2__ClassificationName__c.object
<CustomObject>
    <fields>
        <fullName>APTS_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Apttus_Config2__PriceList__c.object
<CustomObject>
    <fields>
        <fullName>APTS_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>APTS_External_ID__c</fullName>
        <description>External Id Field. This is used while copying records from staging to normal object</description>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/APTS_DMLocalHierarchyHelperTest.cls
@isTest
private class APTS_DMLocalHierarchyHelperTest {
    
    private static User user;
    private static Apttus__APTS_Agreement__c agreement;
    private static APTS_Capture_LSO_Input_Config_Settings__c lodConfigSetting = APTS_LP_TestUtility.getLODConfigSetting();
    

     public static testMethod void validateLocalHierachyNegative(){
            user  = APTS_LP_TestUtility.getUser();
            System.runAs(user) { 
            List<APTS_Stage_Local_Hierarchy__c> listStageLocalHierachy = APTS_LP_TestUtility.getLocalHierachyList(2);
            test.startTest();
            APTS_DMLocalHierarchyHelper.validateLocalHierachy(listStageLocalHierachy);
            test.stopTest();
            }
        }  
    
    public static testMethod void validateLocalHierachyPositive(){
            user  = APTS_LP_TestUtility.getUser();
            System.runAs(user) { 
            List<APTS_Stage_Local_Hierarchy__c> listStageLocalHierachy = new List<APTS_Stage_Local_Hierarchy__c>();
            APTS_Stage_Local_Hierarchy__c stgLclHrchy = new APTS_Stage_Local_Hierarchy__c();
            listStageLocalHierachy.add(stgLclHrchy);

            test.startTest();
           APTS_DMLocalHierarchyHelper.validateLocalHierachy(listStageLocalHierachy);
            test.stopTest();
            }
        }


        public static testMethod void copyLocalHierarchyLevelFourInProduct(){
            APTS_Stage_Data_Validation_Rules_Setting__c validateUser = new APTS_Stage_Data_Validation_Rules_Setting__c();
            validateUser.name = 'DataMigration';
            validateUser.APTS_Validate_SFDC_User__c = FALSE ;        
            insert validateUser; 
            
            user  = APTS_LP_TestUtility.getUser();
            System.runAs(user) { 
            List<APTS_Stage_Local_Hierarchy__c> listStageLocalHierachy=APTS_LP_TestUtility.getLocalHierachyList(2);
            for(APTS_Stage_Local_Hierarchy__c aslh : listStageLocalHierachy){
                            aslh.APTS_Active__c = 'TRUE';
                        }

            test.startTest();
             APTS_CopyDataWrapper cpyDtaWrpr =APTS_DMLocalHierarchyHelper.copyLocalHierarchyLevelFourInProduct(listStageLocalHierachy);
            test.stopTest();
            }
        }
        
        
         public static testMethod void copyLocalHierarchyLevelThreeInProduct(){
             APTS_Stage_Data_Validation_Rules_Setting__c validateUser = new APTS_Stage_Data_Validation_Rules_Setting__c();
            validateUser.name = 'DataMigration';
            validateUser.APTS_Validate_SFDC_User__c = FALSE ;        
            insert validateUser; 
            
            user  = APTS_LP_TestUtility.getUser();
            System.runAs(user) { 
            List<APTS_Stage_Local_Hierarchy__c> listStageLocalHierachy=APTS_LP_TestUtility.getLocalHierachyList(2);
            for(APTS_Stage_Local_Hierarchy__c aslh : listStageLocalHierachy){
                aslh.APTS_Active__c = 'TRUE';
            }

            test.startTest();
             APTS_CopyDataWrapper cpyDtaWrpr =APTS_DMLocalHierarchyHelper.copyLocalHierarchyLevelThreeInProduct(listStageLocalHierachy);
            test.stopTest();
            }
        }


        public static testMethod void copyLocalHierarchyLevelTwoInProduct(){
            APTS_Stage_Data_Validation_Rules_Setting__c validateUser = new APTS_Stage_Data_Validation_Rules_Setting__c();
            validateUser.name = 'DataMigration';
            validateUser.APTS_Validate_SFDC_User__c = FALSE ;        
            insert validateUser; 
            
            user  = APTS_LP_TestUtility.getUser();
            System.runAs(user) { 
            List<APTS_Stage_Local_Hierarchy__c> listStageLocalHierachy=APTS_LP_TestUtility.getLocalHierachyList(2);
            for(APTS_Stage_Local_Hierarchy__c aslh : listStageLocalHierachy){
                aslh.APTS_Active__c = 'TRUE';
            }

            test.startTest();
             APTS_CopyDataWrapper cpyDtaWrpr =APTS_DMLocalHierarchyHelper.copyLocalHierarchyLevelTwoInProduct(listStageLocalHierachy);
            test.stopTest();
            }
        }


        public static testMethod void createCategory(){
            APTS_Stage_Data_Validation_Rules_Setting__c validateUser = new APTS_Stage_Data_Validation_Rules_Setting__c();
            validateUser.name = 'DataMigration';
            validateUser.APTS_Validate_SFDC_User__c = FALSE ;        
            insert validateUser; 
            
            user  = APTS_LP_TestUtility.getUser();
            System.runAs(user) { 
            
            test.startTest();
            APTS_CopyDataWrapper cpyDtaWrpr = APTS_DMLocalHierarchyHelper.createCategory();

            System.assertNotEquals(cpyDtaWrpr,null);
            test.stopTest();
            }
        }


        public static testMethod void createPriceList(){
            APTS_Stage_Data_Validation_Rules_Setting__c validateUser = new APTS_Stage_Data_Validation_Rules_Setting__c();
            validateUser.name = 'DataMigration';
            validateUser.APTS_Validate_SFDC_User__c = FALSE ;        
            insert validateUser; 
            
            user  = APTS_LP_TestUtility.getUser();
            System.runAs(user) { 
            
            test.startTest();
            APTS_CopyDataWrapper cpyDtaWrpr = APTS_DMLocalHierarchyHelper.createPriceList();

            System.assertNotEquals(cpyDtaWrpr,null);
            test.stopTest();
            }
        }

    public static testMethod void associatePriceListWithCategory(){
            APTS_Stage_Data_Validation_Rules_Setting__c validateUser = new APTS_Stage_Data_Validation_Rules_Setting__c();
            validateUser.name = 'DataMigration';
            validateUser.APTS_Validate_SFDC_User__c = FALSE ;        
            insert validateUser; 
            
            user  = APTS_LP_TestUtility.getUser();
            System.runAs(user) { 
            Account acc  = APTS_LP_TestUtility.getNewAccount('Test','Spain');
            insert acc;

            Apttus_Config2__PriceList__c pricelist = APTS_LP_TestUtility.getPriceList(acc, 'Spain');
            pricelist.Name = APTS_DMConstants.CATEGORY_NAME;
            insert pricelist;

            Apttus_Config2__ClassificationName__c clsfcName = new Apttus_Config2__ClassificationName__c();
            clsfcName.Name = 'LP Spain';
            clsfcName.Apttus_Config2__Active__c = true;
            clsfcName.Apttus_Config2__HierarchyLabel__c = 'Test';
            clsfcName.Apttus_Config2__Type__c = 'Offering';
            insert clsfcName;

            Apttus_Config2__PriceListCategory__c prclistCat = new Apttus_Config2__PriceListCategory__c();
            prclistCat.Apttus_Config2__HierarchyId__c = clsfcName.id;
            prclistCat.Apttus_Config2__PriceListId__c = pricelist.id;
            insert prclistCat;

            test.startTest();
            APTS_CopyDataWrapper cpyDtaWrpr = APTS_DMLocalHierarchyHelper.associatePriceListWithCategory();


            

            System.assertNotEquals(cpyDtaWrpr,null);
            test.stopTest();
            }
        }



        public static testMethod void copyLocalHierarchyLevelTwoInCategoryHierarchy(){
            APTS_Stage_Data_Validation_Rules_Setting__c validateUser = new APTS_Stage_Data_Validation_Rules_Setting__c();
            validateUser.name = 'DataMigration';
            validateUser.APTS_Validate_SFDC_User__c = FALSE ;        
            insert validateUser; 
            
            user  = APTS_LP_TestUtility.getUser();
            System.runAs(user) { 

            Apttus_Config2__ClassificationName__c clsfcName = new Apttus_Config2__ClassificationName__c();
            clsfcName.Name = 'LP Spain';
            clsfcName.Apttus_Config2__Active__c = true;
            clsfcName.Apttus_Config2__HierarchyLabel__c = 'Test';
            clsfcName.Apttus_Config2__Type__c = 'Offering';
            insert clsfcName;


            Apttus_Config2__ClassificationHierarchy__c clsfHrchy = new Apttus_Config2__ClassificationHierarchy__c();
            clsfHrchy.Name = 'LP Spain';
            clsfHrchy.Apttus_Config2__HierarchyId__c =clsfcName.id;
            clsfHrchy.Apttus_Config2__Label__c = 'Test';
            insert clsfHrchy;

            List<APTS_Stage_Local_Hierarchy__c> listStageLocalHierachy=APTS_LP_TestUtility.getLocalHierachyList(2);
   
            APTS_Stage_Data_Validation_Rules_Setting__c oTemp1 = new APTS_Stage_Data_Validation_Rules_Setting__c();
            oTemp1.name = 'DataMigration';
            oTemp1.APTS_Category_Sequence__c = 'L20;L21';    
            insert oTemp1;   
        
            test.startTest();
            APTS_CopyDataWrapper cpyDtaWrpr = APTS_DMLocalHierarchyHelper.copyLocalHierarchyLevelTwoInCategoryHierarchy(listStageLocalHierachy);
            
           
            test.stopTest();
            }
        }


         public static testMethod void copyLocalHierarchyLevelThreeInCategoryHierarchy(){
             APTS_Stage_Data_Validation_Rules_Setting__c validateUser = new APTS_Stage_Data_Validation_Rules_Setting__c();
            validateUser.name = 'DataMigration';
            validateUser.APTS_Validate_SFDC_User__c = FALSE ;        
            insert validateUser; 
            
            user  = APTS_LP_TestUtility.getUser();
            System.runAs(user) { 
            Apttus_Config2__ClassificationName__c clsfcName = new Apttus_Config2__ClassificationName__c();
            clsfcName.Name = 'LP Spain';
            clsfcName.Apttus_Config2__Active__c = true;
            clsfcName.Apttus_Config2__HierarchyLabel__c = 'Test';
            clsfcName.Apttus_Config2__Type__c = 'Offering';
            insert clsfcName;


            Apttus_Config2__ClassificationHierarchy__c clsfHrchy = new Apttus_Config2__ClassificationHierarchy__c();
            clsfHrchy.Name = 'LP Spain';
            clsfHrchy.Apttus_Config2__Level__c = 1;
            clsfHrchy.Apttus_Config2__HierarchyId__c =clsfcName.id;
            clsfHrchy.Apttus_Config2__Label__c = 'Test';
            clsfHrchy.APTS_LP_Code__c = '2';
            insert clsfHrchy;

            Apttus_Config2__ClassificationHierarchy__c clsfHrchy1 = new Apttus_Config2__ClassificationHierarchy__c();
            clsfHrchy1.Name = '2';
            clsfHrchy1.Apttus_Config2__Level__c = 1;
            clsfHrchy1.Apttus_Config2__HierarchyId__c =clsfcName.id;
            clsfHrchy1.Apttus_Config2__Label__c = 'Test';
            clsfHrchy1.APTS_LP_Code__c = '2';
            insert clsfHrchy1;



            List<APTS_Stage_Local_Hierarchy__c> listStageLocalHierachy=APTS_LP_TestUtility.getLocalHierachyList(2);
            for(APTS_Stage_Local_Hierarchy__c aslh : listStageLocalHierachy){
                aslh.APTS_Level2_Code__c = '2';
                aslh.APTS_Level2_Name__c = '2';
                aslh.APTS_Level3_Name__c = '3';
            }

            test.startTest();
            APTS_CopyDataWrapper cpyDtaWrpr =APTS_DMLocalHierarchyHelper.copyLocalHierarchyLevelThreeInCategoryHierarchy(listStageLocalHierachy);
            test.stopTest();
            }
        }


          public static testMethod void copyLocalHierarchyLevelFourInCategoryHierarchy(){
            user  = APTS_LP_TestUtility.getUser();
            System.runAs(user) { 
            Apttus_Config2__ClassificationName__c clsfcName = new Apttus_Config2__ClassificationName__c();
            clsfcName.Name = 'LP Spain';
            clsfcName.Apttus_Config2__Active__c = true;
            clsfcName.Apttus_Config2__HierarchyLabel__c = 'Test';
            clsfcName.Apttus_Config2__Type__c = 'Offering';
            insert clsfcName;


            Apttus_Config2__ClassificationHierarchy__c clsfHrchy = new Apttus_Config2__ClassificationHierarchy__c();
            clsfHrchy.Name = 'LP Spain';
            clsfHrchy.Apttus_Config2__Level__c = 2;
            clsfHrchy.Apttus_Config2__HierarchyId__c =clsfcName.id;
            clsfHrchy.Apttus_Config2__Label__c = 'Test';
            insert clsfHrchy;

            Apttus_Config2__ClassificationHierarchy__c clsfHrchy1 = new Apttus_Config2__ClassificationHierarchy__c();
            clsfHrchy1.Name = '2';
            clsfHrchy1.Apttus_Config2__Level__c = 2;
            clsfHrchy1.Apttus_Config2__HierarchyId__c =clsfcName.id;
            clsfHrchy1.Apttus_Config2__Label__c = 'Test1';
            clsfHrchy1.APTS_LP_Code__c = '2';
            insert clsfHrchy1;

            List<APTS_Stage_Local_Hierarchy__c> listStageLocalHierachy=APTS_LP_TestUtility.getLocalHierachyList(2);

            for(APTS_Stage_Local_Hierarchy__c aslh : listStageLocalHierachy){
                aslh.APTS_Level4_Name__c = '4';
                aslh.APTS_Level3_Code__c = '2';
                aslh.APTS_Level3_Name__c = '2';

            }

            

            test.startTest();
            APTS_CopyDataWrapper cpyDtaWrpr =APTS_DMLocalHierarchyHelper.copyLocalHierarchyLevelFourInCategoryHierarchy(listStageLocalHierachy);
            test.stopTest();
            }
        }


        public static testMethod void copyLocalHierarchyInProductClassification(){
            user  = APTS_LP_TestUtility.getUser();
            System.runAs(user) { 

          
     
            Product2  prd2 = APTS_LP_TestUtility.getHierarchyProduct();
            prd2.APTS_External_ID__c = 'Test';

            insert prd2;
         
                
            Apttus_Config2__ClassificationName__c clsfcName = new Apttus_Config2__ClassificationName__c();
            clsfcName.Name = 'LP Spain';
            clsfcName.Apttus_Config2__Active__c = true;
            clsfcName.Apttus_Config2__HierarchyLabel__c = 'Test';
            clsfcName.Apttus_Config2__Type__c = 'Offering';
            insert clsfcName;

            Apttus_Config2__ClassificationHierarchy__c clsfHrchy = new Apttus_Config2__ClassificationHierarchy__c();
            clsfHrchy.Name = 'ES - Hierarchy';
            clsfHrchy.Apttus_Config2__HierarchyId__c =clsfcName.id;
            clsfHrchy.Apttus_Config2__Label__c = 'Test';
            insert clsfHrchy;


            List<APTS_Stage_Local_Hierarchy__c> listStageLocalHierachy=APTS_LP_TestUtility.getLocalHierachyList(2);
            test.startTest();
            APTS_CopyDataWrapper cpyDtaWrpr =APTS_DMLocalHierarchyHelper.copyLocalHierarchyInProductClassification();
            test.stopTest();
            }
        }


        public static testMethod void rebuildCategoryHierachies(){
            user  = APTS_LP_TestUtility.getUser();
            System.runAs(user) { 
            List<APTS_Stage_Local_Hierarchy__c> listStageLocalHierachy=APTS_LP_TestUtility.getLocalHierachyList(2);
            
            Apttus_Config2__ClassificationName__c clsfcName = new Apttus_Config2__ClassificationName__c();
            clsfcName.Name = 'LP Spain';
            clsfcName.Apttus_Config2__Active__c = true;
            clsfcName.Apttus_Config2__HierarchyLabel__c = 'Test';
            clsfcName.Apttus_Config2__Type__c = 'Offering';
            insert clsfcName;
            
             Apttus_Config2__ClassificationHierarchy__c clsfHrchy = new Apttus_Config2__ClassificationHierarchy__c();
            clsfHrchy.Name = 'LP Spain';
            clsfHrchy.Apttus_Config2__Level__c = 1;
            clsfHrchy.Apttus_Config2__HierarchyId__c =clsfcName.id;
            clsfHrchy.Apttus_Config2__Label__c = 'Test';
            clsfHrchy.APTS_LP_Code__c = '2';
            clsfHrchy.Apttus_Config2__Left__c=1;
            clsfHrchy.Apttus_Config2__Right__c=2;
            insert clsfHrchy;

            Apttus_Config2__ClassificationHierarchy__c clsfHrchy1 = new Apttus_Config2__ClassificationHierarchy__c();
            clsfHrchy1.Name = '2';
            clsfHrchy1.Apttus_Config2__Level__c = 1;
            clsfHrchy1.Apttus_Config2__HierarchyId__c =clsfcName.id;
            clsfHrchy1.Apttus_Config2__Label__c = 'Test';
            clsfHrchy1.APTS_LP_Code__c = '1';
            clsfHrchy1.Apttus_Config2__Left__c=1;
            clsfHrchy1.Apttus_Config2__Right__c=2;
            insert clsfHrchy1;
            
            test.startTest();
            APTS_CopyDataWrapper cpyDtaWrpr =APTS_DMLocalHierarchyHelper.rebuildCategoryHierachies();
            test.stopTest();
            }
        }
        
         public static testMethod void copyLocalHierarchyLevelFourInProductNegative(){
            try{
                user  = APTS_LP_TestUtility.getUser();
                System.runAs(user) { 
                test.startTest();
                List<APTS_Stage_Local_Hierarchy__c> listStageLocalHierachy=APTS_LP_TestUtility.getLocalHierachyList(2);
                for(APTS_Stage_Local_Hierarchy__c aslh : listStageLocalHierachy){
                            aslh.APTS_External_ID__c = '1234';
                 }
                APTS_CopyDataWrapper cpyDtaWrpr = APTS_DMLocalHierarchyHelper.copyLocalHierarchyLevelFourInProduct(null);
                 test.stopTest();
                }
            }catch(Exception ex){
                
            }
        }
        
        public static testMethod void copyLocalHierarchyLevelFourInProductNegative2(){
            try{
                user  = APTS_LP_TestUtility.getUser();
                System.runAs(user) { 
                test.startTest();
                List<APTS_Stage_Local_Hierarchy__c> listStageLocalHierachy= new List<APTS_Stage_Local_Hierarchy__c>();
                APTS_CopyDataWrapper cpyDtaWrpr = APTS_DMLocalHierarchyHelper.copyLocalHierarchyLevelFourInProduct(listStageLocalHierachy);
                test.stopTest();
                }
            }catch(Exception ex){
                
            }
        }
       
       
        public static testMethod void copyLocalHierarchyLevelThreeInCategoryHierarchyNegative(){
            user  = APTS_LP_TestUtility.getUser();
            System.runAs(user) { 
            Apttus_Config2__ClassificationName__c clsfcName = new Apttus_Config2__ClassificationName__c();
            clsfcName.Name = 'LP Spain';
            clsfcName.Apttus_Config2__Active__c = true;
            clsfcName.Apttus_Config2__HierarchyLabel__c = 'Test';
            clsfcName.Apttus_Config2__Type__c = 'Offering';
            insert clsfcName;


            Apttus_Config2__ClassificationHierarchy__c clsfHrchy = new Apttus_Config2__ClassificationHierarchy__c();
            clsfHrchy.Name = 'LP Spain';
            clsfHrchy.Apttus_Config2__Level__c = 1;
            clsfHrchy.Apttus_Config2__HierarchyId__c =clsfcName.id;
            clsfHrchy.Apttus_Config2__Label__c = 'Test';
            clsfHrchy.APTS_LP_Code__c = '2';
            insert clsfHrchy;

            Apttus_Config2__ClassificationHierarchy__c clsfHrchy1 = new Apttus_Config2__ClassificationHierarchy__c();
            clsfHrchy1.Name = '2';
            clsfHrchy1.Apttus_Config2__Level__c = 1;
            clsfHrchy1.Apttus_Config2__HierarchyId__c =clsfcName.id;
            clsfHrchy1.Apttus_Config2__Label__c = 'Test';
            clsfHrchy1.APTS_LP_Code__c = '2';
            insert clsfHrchy1;

            List<APTS_Stage_Local_Hierarchy__c> listStageLocalHierachy=APTS_LP_TestUtility.getLocalHierachyList(2);
            for(APTS_Stage_Local_Hierarchy__c aslh : listStageLocalHierachy){
                aslh.APTS_Level2_Code__c = '2';
                aslh.APTS_Level2_Name__c = '2';
                aslh.APTS_Level3_Name__c = '3';
                aslh.APTS_External_ID__c = '1234';
            }
            test.startTest();
            APTS_CopyDataWrapper cpyDtaWrpr =APTS_DMLocalHierarchyHelper.copyLocalHierarchyLevelThreeInCategoryHierarchy(listStageLocalHierachy);
            test.stopTest();
            }
        }
        
       public static testMethod void copyESCategoryHierarchy(){
            user  = APTS_LP_TestUtility.getUser();
            System.runAs(user) { 

            Apttus_Config2__ClassificationName__c clsfcName = new Apttus_Config2__ClassificationName__c();
            clsfcName.Name = 'LP Spain';
            clsfcName.Apttus_Config2__Active__c = true;
            clsfcName.Apttus_Config2__HierarchyLabel__c = 'Test';
            clsfcName.Apttus_Config2__Type__c = 'Offering';
            insert clsfcName;


            Apttus_Config2__ClassificationHierarchy__c clsfHrchy = new Apttus_Config2__ClassificationHierarchy__c();
            clsfHrchy.Name = 'LP Spain';
            clsfHrchy.Apttus_Config2__HierarchyId__c =clsfcName.id;
            clsfHrchy.Apttus_Config2__Label__c = 'Test';
            insert clsfHrchy;

            List<APTS_Stage_Local_Hierarchy__c> listStageLocalHierachy=APTS_LP_TestUtility.getLocalHierachyList(2);
             
            for(APTS_Stage_Local_Hierarchy__c aslh : listStageLocalHierachy){
                aslh.APTS_Level2_Name__c = '2';
            
            }
   
            APTS_Stage_Data_Validation_Rules_Setting__c oTemp1 = new APTS_Stage_Data_Validation_Rules_Setting__c();
            oTemp1.name = 'DataMigration';
            oTemp1.APTS_Category_Sequence__c = 'Series de empotrar;Envolventes;Service BT;Interruptores de Potencia B.T;Thomas and Betts;KNX-EIB;Aparamenta Modular;Entrelec;Control y Automatizacion';        
            insert oTemp1;   
         
            test.startTest();
            APTS_CopyDataWrapper cpyDtaWrpr = APTS_DMLocalHierarchyHelper.copyESCategoryHierarchy();
            test.stopTest();
            }
        }  
    
    
     

    
}