src/objects/APTS_Approval_Rule_Matrix__c.object
<CustomObject>
    <description>Approval rule matrix stores routing rules that will be configured by country admin and it drives the Quotation &amp; Agreement approvals.</description>
    <fields>
        <fullName>APTS_Approval_Level__c</fullName>
        <label>Approval Level</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>APTS_CHF__c</fullName>
        <formula>TEXT(APTS_Country__c ) + TEXT( APTS_Sales_Organisation__c ) + (  APTS_LP_Local_Channel__r.APTS_Code__c ) + (   APTS_Sales_Office__r.PickList_Code__c  ) + APTS_GTV_Level_Code__c</formula>
        <label>Combined Fields</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Country__c</fullName>
        <inlineHelpText>Country name for which approval rule is created</inlineHelpText>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Spain</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>APTS_Local_Channel__c</fullName>
        <label>Local Channel</label>
        <picklist>
            <picklistValues>
                <fullName>P1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>APTS_Sales_Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Office</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>LSO_Field_Entries__c.Country__c</field>
                <operation>equals</operation>
                <valueField>$User.Country</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>LSO_Field_Entries__c</referenceTo>
        <relationshipLabel>Approval Rule Matrix</relationshipLabel>
        <relationshipName>Approval_Rule_Matrix</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>APTS_Threshold_Discount__c</fullName>
        <label>Threshold Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Approval Rule Matrix</label>
    <nameField>
        <displayFormat>ARM-{00000000}</displayFormat>
        <label>Approval Rule Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Rule Matrix</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/APTS_Master_Picklist_Table__c.object
<CustomObject>
    <description>Object to hold locale wise description for codes (used for incoterm, payment term etc.) used in SAP</description>
    <fields>
        <fullName>APTS_Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Code__c</fullName>
        <description>Code that is being used in SAP.</description>
        <label>Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Master Picklist Table</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Picklist Table</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>APTS_Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Spain</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>APTS_GTV_Code__c</fullName>
        <label>GTV Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    
    <fields>
        <fullName>APTS_LP_MSPA_Type__c</fullName>
        <description>Type of the MSPA</description>
        <formula>RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MSPA Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_LP_MaximumSubstituteDiscount__c</fullName>
        <label>Maximum Substitute Discount</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>APTS_Legacy_MSPA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Legacy MSPA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_LP_Sales_Organization__c</fullName>
        <defaultValue>&quot;ABB&quot;</defaultValue>
        <description>Sales organization for which the MSPA is created; is the one of MSPA owner</description>
        <inlineHelpText>Auto populated from Account</inlineHelpText>
        <label>Sales Organization</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Local_Channel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Auto populated using information from the Quotation or from the Buying Account (LOD selected)</inlineHelpText>
        <label>Local Channel</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>APTS_Master_Picklist_Table__c.APTS_Code_Used_For__c</field>
                <operation>equals</operation>
                <value>Local Channel</value>
            </filterItems>
            <filterItems>
                <field>APTS_Master_Picklist_Table__c.APTS_Locale__c</field>
                <operation>equals</operation>
                <valueField>$Source.APTS_Locale__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>APTS_Master_Picklist_Table__c</referenceTo>
        <relationshipLabel>Agreements (Local Channel)</relationshipLabel>
        <relationshipName>Agreements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>APTS_MSPA_without_Changes__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If the value it checked and if Related Quotation Status = &quot;Approved&quot; then the Status of MSPA will also be approved LP Spain</description>
        <label>Create MSPA without Changes</label>
        <type>Checkbox</type>
    </fields>
  <fields>
        <fullName>APTS_Sales_Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Auto populated from User Profile</inlineHelpText>
        <label>Sales Office</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.APTS_Country__c</field>
                <operation>equals</operation>
                <valueField>LSO_Field_Entries__c.Country__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>LSO_Field_Entries__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements_Sales_Office</relationshipName>
        <type>Lookup</type>
    </fields>
 <fields>
        <fullName>Apttus_Approval__Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Submitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved but Action Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deactivated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Apttus_QPComply__RelatedProposalId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated quote/proposal</description>
        <label>Related Quote/Proposal</label>
        <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus__Status__c</fullName>
        <description>The sub stage of an agreement – the status underneath a given status category.  These are generally modifiable by the customer except for the following values which are Apttus reserved to manage agreement lifecycles:

Request, Submitted Request,
Cancelled Request, In Amendment, Being Amended, Superseded, Activated, Expired, Internal Signatures, Author Contract, Expired, Terminated,  Ready for Signatures, Fully Signed, Signature Declined</description>
        <label>Status</label>
        <picklist>
            <controllingField>Apttus__Status_Category__c</controllingField>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approval In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturated Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved but failed to load on SAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved but Action Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deactivated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Signatures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queued to create in SAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recalled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Generated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Presented</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__LineItem__c.object
<CustomObject>
    <fields>
        <fullName>APTS_Hierarchy_Level_3_Code__c</fullName>
        <description>Field to capture Level 3 Hierarchy code entered by user.</description>
        <label>Hierarchy Level 3 Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Apttus_Config2__ProductConfiguration__c.object
<CustomObject>
    <fields>
        <fullName>APTS_LP_Sales_Organization__c</fullName>
        <description>This field will pick the value of Sales Organization from Agreement or Quote/Proposal object based on its Business Object Type value.</description>
        <formula>IF( TEXT( Apttus_Config2__BusinessObjectType__c )  = &quot;Agreement&quot;,  Apttus_CMConfig__AgreementId__r.APTS_LP_Sales_Organization__c ,  IF( TEXT( Apttus_Config2__BusinessObjectType__c ) = &quot;Proposal&quot;,  Apttus_QPConfig__Proposald__r.APTS_LP_Sales_Organization__c , &quot;&quot;) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Organization</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/LSO_Field_Entries__c.object
<CustomObject>
    <description>R3 -  LSO Field Entries</description>
    <fields>
        <fullName>PickList_Code__c</fullName>
        <description>R3 PickList Code</description>
        <label>PickList Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>LSO Field Entries</label>
    <nameField>
        <displayFormat>LSO Field Entry - {0000}</displayFormat>
        <label>LSO Field Entry</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LSO Field Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/APTS_ProductConfigurationTriggerHelper.cls
/*
@Name: APTS_ProductConfigurationTriggerHelper
@Author: Hardik Shah
@CreateDate: 05/09/2015
@Description: Helper Class to Perform operations on ProductConfiguration Object
@UsedBy: APTS_ProductConfigurationHandler
******************************************************************
@ModifiedBy: Nishi and Hardik to include changes to Show Chevron for Approval Required. (Issue 135 in Element Tool)
@ModifiedDate: 27 Sep 2015
@ModifiedBy: Hardik- To Round of Digits to two decimal places.
@ModifiedDate: 28 Sep 2015
@ChangeDescription: 
**** PS: @ModifiedBy and @ChangeDescription can be repeated multiple time, based on number of changes made to the original process.
*/

public class APTS_ProductConfigurationTriggerHelper {
    public static map<String,Decimal> mapProdConfigWithMaxDiscount = new map<String,Decimal>();
    public static map<String,String> mapProdConfigWithGTVCode = new map<String,String>();
    public static List<Apttus_Config2__LineItem__c> listCriticalDiscLineItem = new List<Apttus_Config2__LineItem__c>();
    public static final Integer THRESHOLD_DISCOUNT_DUMMY_CUTOFF = 101;
    /*
    @Addedby:Chetan Patel
    @Method to update Agreement/Proposal header fields GTV-level and MaxDiscount to Maximum discount among LineItems.
    @param:ProductConfiguration
    */
    
    public static void getMaxLineItemDiscount(Map < Id, Apttus_Config2__ProductConfiguration__c > records, Map < Id, Apttus_Config2__ProductConfiguration__c > oldRecordsMap){
        String sLocalChannelCode='';
        // Set of ProductConfigurationId
        Set < String > setProductConfig = new Set < String > ();
        // Boolean variable that marks all those product configuration whose status has changed to Finalized
        Boolean bStatusChanged = false;
        Boolean isProposal = false;
        Boolean isAgreement = false;
        Boolean isMSPAwithoutChanges = false;
        List<Apttus_Proposal__Proposal__c> lstProposal = new List<Apttus_Proposal__Proposal__c>();
        List<Apttus__APTS_Agreement__c> lstAgreement = new List<Apttus__APTS_Agreement__c>();
        list<Apttus_Config2__LineItem__c> LineswithLineNumberSequence=new list<Apttus_Config2__LineItem__c>();
                
        setProductConfig = getFilteredProductConfig(records,oldRecordsMap );
        
        // Clear Critical discount line item before we start finding critical line Item.
        listCriticalDiscLineItem.clear();

        system.debug('<<<< Product Config >>>>' + setProductConfig.size());
        if (setProductConfig.size() > 0) {

            // Fetch all the information required from Product Configuration
            List < Apttus_Config2__ProductConfiguration__c > listConfig = APTS_LP_QueryUtility.getProductConfiguration(setProductConfig);
            
            boolean isAnyLineItemWithNoRule = false;
            boolean isCartEmpty = false;
            
            
            system.debug('<<<< List Of configuration >>>>: ' + listConfig);
            for (Apttus_Config2__ProductConfiguration__c productConfig: listConfig) {
                
                if(productConfig.Apttus_Config2__LineItems__r.size()==0)
                    isCartEmpty=true;
                
                lstProposal = [select id,Apttus_Proposal__Approval_Stage__c,APTS_Local_Channel__c,APTS_GTV_Code__c,APTS_LP_MaximumSubstituteDiscount__c 
                from Apttus_Proposal__Proposal__c where id =:productConfig.Apttus_QPConfig__Proposald__c limit 1];
                 
                
                lstAgreement = [select id,Apttus_Approval__Approval_Status__c,APTS_GTV_Code__c, APTS_Local_Channel__c, Apttus__Status__c,
                                APTS_LP_MaximumSubstituteDiscount__c, APTS_MSPA_without_Changes__c, Apttus_QPComply__RelatedProposalId__c, APTS_Legacy_MSPA__c 
                                from Apttus__APTS_Agreement__c where id  =:productConfig.Apttus_CMConfig__AgreementId__c
                                 LIMIT :APTS_Constants.SELECT_SOQL_LIMIT];
                
                String LocalChannel = '';
                String SalesOffice = '';
                String Country = '';
                String SalesOrganization = '';
            
                if(productConfig.Apttus_QPConfig__Proposald__c !=null){
              
                    if(productConfig.Apttus_QPConfig__Proposald__r.APTS_QuotationType__c == APTS_Constants.PROPOSAL_TYPE){      
                        
                        isProposal          =   true;
                        LocalChannel        =   productConfig.Apttus_QPConfig__Proposald__r.APTS_Local_Channel__c;
                        SalesOffice         =   productConfig.Apttus_QPConfig__Proposald__r.APTS_Sales_Office__r.PickList_Code__c;
                        Country             =   productConfig.Apttus_QPConfig__Proposald__r.APTS_Country__c;
                        SalesOrganization   =   productConfig.Apttus_QPConfig__Proposald__r.APTS_LP_Sales_Organization__c;
                        sLocalChannelCode   =   productConfig.Apttus_QPConfig__Proposald__r.APTS_Local_Channel__r.APTS_Code__c; 
                    }
                    
                }
                if(productConfig.Apttus_CMConfig__AgreementId__c != null){
             
                    if(productConfig.Apttus_CMConfig__AgreementId__r.APTS_LP_MSPA_Type__c == APTS_Constants.MSPA_TYPE){
                        system.debug('@@ LocalChannel agreement : ' + LocalChannel + SalesOffice);
                        
                        isAgreement = true;
                        LocalChannel = productConfig.Apttus_CMConfig__AgreementId__r.APTS_Local_Channel__c;
                        SalesOffice = productConfig.Apttus_CMConfig__AgreementId__r.APTS_Sales_Office__r.PickList_Code__c;
                        Country             =   productConfig.Apttus_CMConfig__AgreementId__r.APTS_Country__c;
                        SalesOrganization   =   productConfig.Apttus_CMConfig__AgreementId__r.APTS_LP_Sales_Organization__c;
                        sLocalChannelCode   =   productConfig.Apttus_CMConfig__AgreementId__r.APTS_Local_Channel__r.APTS_Code__c;
                    }
                }
                set<String> setGTVCode = new set<String>();
               
                
                // fetch the lineItem from ProductConfiguration
                for(Apttus_Config2__LineItem__c item: productConfig.Apttus_Config2__LineItems__r){
                    
                    setGTVCode.add(item.Apttus_Config2__ProductId__r.APTS_Hierarchy_Level_3_Code__c);
                  
                }
                
                system.debug('@@ line item setGTVCode : ' + setGTVCode );
                map<String,List<APTS_Approval_Rule_Matrix__c>> mapApprovalRuleMatrix = new map<String,List<APTS_Approval_Rule_Matrix__c>>();
                List<APTS_Approval_Rule_Matrix__c> lstApprovalRuleMatrix = [select id,APTS_Threshold_Discount__c,APTS_Approval_Level__c,APTS_CHF__c
                                                                            from APTS_Approval_Rule_Matrix__c
                                                                            where APTS_LP_Local_Channel__c=:LocalChannel
                                                                            and APTS_Sales_Office__r.PickList_Code__c =:SalesOffice
                                                                            and APTS_GTV_Level_Code__c IN :setGTVCode
                                                                            and APTS_Threshold_Discount__c < :THRESHOLD_DISCOUNT_DUMMY_CUTOFF
                                                                            and APTS_Is_Active__c=true LIMIT :APTS_Constants.SELECT_SOQL_LIMIT];
                                                                            
                system.debug('@@ lstApprovalRuleMatrix after : ' + JSON.serialize(lstApprovalRuleMatrix));
                
                if(lstApprovalRuleMatrix != null && lstApprovalRuleMatrix.size() > 0) {
                    
                    for(APTS_Approval_Rule_Matrix__c rule : lstApprovalRuleMatrix){
                        
                        if(!mapApprovalRuleMatrix.keyset().contains(rule.APTS_CHF__c)){
                            
                            List<APTS_Approval_Rule_Matrix__c> tmplstApprovalRuleMatrix = new List<APTS_Approval_Rule_Matrix__c>();
                            tmplstApprovalRuleMatrix.add(rule);
                            mapApprovalRuleMatrix.put(rule.APTS_CHF__c,tmplstApprovalRuleMatrix);
                        }else{
                            
                            List<APTS_Approval_Rule_Matrix__c> tmplstApprovalRuleMatrix = new List<APTS_Approval_Rule_Matrix__c>();
                            tmplstApprovalRuleMatrix = mapApprovalRuleMatrix.get(rule.APTS_CHF__c);
                            tmplstApprovalRuleMatrix.add(rule);
                            mapApprovalRuleMatrix.put(rule.APTS_CHF__c,tmplstApprovalRuleMatrix);
                        }
                    }
                }else{
                    
                    if(lstProposal != null && lstProposal.size() > 0){
                        lstProposal[0].APTS_LP_No_Approval_Rule_Matched__c = true;
                        lstProposal[0].APTS_LP_MaximumSubstituteDiscount__c = null;
                        lstProposal[0].APTS_GTV_Code__c  = null;
                        
                    }
                    
                    if(lstAgreement != null && lstAgreement.size() > 0){
                        System.debug(': update agreement');
                        lstAgreement[0].APTS_LP_No_Approval_Rule_Matched__c = true;
                        lstAgreement[0].APTS_LP_MaximumSubstituteDiscount__c = null;
                        lstAgreement[0].APTS_GTV_Code__c  = null;
                        
                    }
                }
                
                system.debug('@@ mapApprovalRuleMatrix : ' + JSON.serialize(mapApprovalRuleMatrix));
                
                if(mapApprovalRuleMatrix != null && mapApprovalRuleMatrix.size() > 0){
                    system.debug('<<<< Local Channel Code >>>>' + sLocalChannelCode);
                    Decimal previousDiscount = 0;
                    Decimal maxDiscount = 0;
                    map<String,Integer> maplineItemWiseRulesCount = new map <String,Integer>();
                    map<String,Apttus_Config2__LineItem__c> maplineItemWithId = new map <String,Apttus_Config2__LineItem__c>();
                    set<string> lineItemsWithNoRule = new set<String>();
                    
                    for(Apttus_Config2__LineItem__c item: productConfig.Apttus_Config2__LineItems__r){
                        
                        String combinedHeaderFields       = Country + SalesOrganization + sLocalChannelCode + SalesOffice + item.Apttus_Config2__ProductId__r.APTS_Hierarchy_Level_3_Code__c;
                        String combinedHeaderFieldsDetail = 'Country : '            + Country + ' | ' + 
                                                            'Sales Organization : ' + SalesOrganization + ' | ' + 
                                                            'Local Channel : '      + sLocalChannelCode + ' | ' + 
                                                            'Sales Office : '       + SalesOffice + ' | ' + 
                                                            'Product GTV Code : '   + item.Apttus_Config2__ProductId__r.APTS_Hierarchy_Level_3_Code__c;
                        system.debug('@@ combinedHeaderFields :'+ combinedHeaderFields);
                        if(mapApprovalRuleMatrix.keyset().contains(combinedHeaderFields)){
                            
                            List<APTS_Approval_Rule_Matrix__c> tmplstApprovalRuleMatrix  = new List<APTS_Approval_Rule_Matrix__c>();
                            tmplstApprovalRuleMatrix= mapApprovalRuleMatrix.get(combinedHeaderFields);
                            
                            if(tmplstApprovalRuleMatrix != null){
                                Integer ruleCount = 0;
                                for(APTS_Approval_Rule_Matrix__c rule :tmplstApprovalRuleMatrix){
                                    
                                    if(item.APTS_Line_Item_Discount__c >=rule.APTS_Threshold_Discount__c)
                                        ruleCount++;
                                    
                                }
                                maplineItemWiseRulesCount.put(item.id,ruleCount);
                                maplineItemWithId.put(item.id,item);
                                
                            }
                        }else{
                            
                            lineItemsWithNoRule.add(combinedHeaderFieldsDetail);
                            
                        }
                        
                    }
                    system.debug('<<<< Line Items with No Rules >>>> '+ lineItemsWithNoRule.size());
                    system.debug('<<<< Line Items with No Rules >>>> '+ JSON.serialize(lineItemsWithNoRule));
                    if(lineItemsWithNoRule.size()>0){
                        System.debug('<<<< In Side No Rules >>>>');
                        
                        String WhatId = '';
                        if(lstProposal != null && !lstProposal.isEmpty())
                            whatId = lstProposal[0].id;
                        if( lstAgreement != null && !lstAgreement.isEmpty())
                            whatId = lstAgreement[0].id;
                        String summary = 'List of line items not having approval rule matrix.';
                        for(String s : lineItemsWithNoRule)
                               summary += '\r\n' + s;
                        
                        system.debug('<<<< Before Insert Task >>>> ');
                        
                        createTask(Label.APTS_NO_APPROVAL_RULE_FOR_ONE_OF_LINE_ITEM, summary, whatId);
                        
                        isAnyLineItemWithNoRule = true;
                        system.debug('<<<< Before Values Set >>>> '+ lstProposal);
                        if(lstProposal != null && !lstProposal.isEmpty()){
                            system.debug('<<<< Set No Rule Match >>>> ');
                            lstProposal[0].APTS_LP_No_Approval_Rule_Matched__c = true;
                            lstProposal[0].APTS_LP_MaximumSubstituteDiscount__c = null;
                            lstProposal[0].APTS_GTV_Code__c  = null;
                            
                        }
                        
                        if(lstAgreement != null && !lstAgreement.isEmpty()){
                            lstAgreement[0].APTS_LP_No_Approval_Rule_Matched__c = true;
                            lstAgreement[0].APTS_LP_MaximumSubstituteDiscount__c = null;
                            lstAgreement[0].APTS_GTV_Code__c  = null;
                            
                        }
                        
                    }else{
                        system.debug('@@ maplineItemWiseRulesCount : '+ JSON.serialize(maplineItemWiseRulesCount));
                        Integer maxCount=0;
                        if(maplineItemWiseRulesCount != null && maplineItemWiseRulesCount.size() > 0){                            
                            set<Integer> setItemDiscounts = new set<Integer>();                            
                            setItemDiscounts.addAll(maplineItemWiseRulesCount.values());
                            List<Integer> lstItemDiscounts = new List<Integer>();
                            lstItemDiscounts.addAll(setItemDiscounts);
                            lstItemDiscounts.sort();
                            system.debug('<<<< lstItemDiscounts >>>>: '+ lstItemDiscounts);
                            maxCount = lstItemDiscounts[lstItemDiscounts.size()-1];
                            system.debug('@@@ maxCount : '+ maxCount);
                            Decimal maxDiscountFromAllItems = 99999;
                            String itemGTVCodeHavingMaxDisc = '';
                            system.debug('@@ maplineItemWiseRulesCount 1 : '+ JSON.serialize(maplineItemWiseRulesCount));
                            if(maxCount>0){
                                // Set max discount details and GTV Code
                                setDiscountAndGTVCode(productConfig, isProposal, maplineItemWiseRulesCount, maplineItemWithId,maxCount);
                            }else{
                                system.debug('<<<< Auto Approval Entry >>>>');
                                // Set max discount details and GTV Code
                                setDiscountAndGTVCode(productConfig, isProposal, maplineItemWiseRulesCount, maplineItemWithId,maxCount);
                                
                                // Commented by JS - there is design change inAuto Approval.                                                               
                                if(lstAgreement != null && lstAgreement.size() > 0){
                                    //markAgreementAutoApproved(lstAgreement);
                                    lstAgreement[0].APTS_Approval_Required__c = true;
                                }
                                if(lstProposal != null && lstProposal.size() > 0){
                                    //markProposalAutoApproved(lstProposal);
                                    lstProposal[0].APTS_Approval_Required__c = true;    
                                }                              
                                
                            }
                            system.debug('@@ lstProposal :'+ lstProposal);
                            if(lstProposal !=null && lstProposal.size()>0){                                
                                lstProposal[0].APTS_LP_No_Approval_Rule_Matched__c = false;
                                lstProposal[0].APTS_Max_Approval_Levels__c = maxCount;
                            }
                            if(lstAgreement !=null && lstAgreement.size()>0){
                                lstAgreement[0].APTS_LP_No_Approval_Rule_Matched__c = false;
                                lstAgreement[0].APTS_Max_Approval_Levels__c = maxCount;
                            }
                                    
                        }else{
                        
                            if(lstProposal !=null){
                                lstProposal[0].APTS_LP_No_Approval_Rule_Matched__c = true;
                                lstProposal[0].APTS_LP_MaximumSubstituteDiscount__c = null;
                                lstProposal[0].APTS_GTV_Code__c  = null;
                                
                            }
                            if(lstAgreement !=null){
                                lstAgreement[0].APTS_LP_No_Approval_Rule_Matched__c = true;
                                lstAgreement[0].APTS_LP_MaximumSubstituteDiscount__c = null;
                                lstAgreement[0].APTS_GTV_Code__c  = null;                                
                            }                    
                        }
                        
                        //system.debug('@@ mapProdConfigWithMaxDiscount : ' + JSON.serialize(mapProdConfigWithMaxDiscount));
                        
                        // Set Approval related fieds on Proposal - JS - 14-Nov-2015
                        if(lstProposal !=null){
                            for(Apttus_Proposal__Proposal__c proposal :lstProposal){
                                proposal.APTS_LP_MaximumSubstituteDiscount__c = mapProdConfigWithMaxDiscount.get(proposal.id).setScale(2);
                                proposal.APTS_GTV_Code__c = mapProdConfigWithGTVCode.get(proposal.id);
                                if(lstProposal[0].Apttus_Proposal__Approval_Stage__c != 'Approved'){
                                    proposal.APTS_Approval_Required__c= true;
                                    proposal.Apttus_Proposal__Approval_Stage__c = 'Draft';
                                    proposal.APTS_LP_No_Approval_Rule_Matched__c = false;
                                }else{
                                    // Commented by JS on 18-Nov-2015
                                    //proposal.APTS_Approval_Required__c= false;
                                }
                            }
                        }
                        
                        // Set Approval related fields on Agreement - JS - 14-Nov-2015
                        if(lstAgreement !=null){
                            
                            for(Apttus__APTS_Agreement__c agreement :lstAgreement){
                                agreement.APTS_LP_MaximumSubstituteDiscount__c = mapProdConfigWithMaxDiscount.get(agreement.id).setScale(2);
                                agreement.APTS_GTV_Code__c = mapProdConfigWithGTVCode.get(agreement.id);
                                system.debug('<<<< Set Final Status >>>>');
                                if(lstAgreement[0].Apttus_Approval__Approval_Status__c != 'Approved'){
                                    agreement.APTS_Approval_Required__c= true;
                                    if(!agreement.APTS_Legacy_MSPA__c){
                                        agreement.Apttus__Status__c = 'Draft';
                                    }
                                    agreement.APTS_LP_No_Approval_Rule_Matched__c = false;

                                }else{
                                    // Commented by JS on 18-Nov-2015
                                    //agreement.APTS_Approval_Required__c= false; 
                                }
                            }
                           // update lstAgreement;
                        }
                    
                    }
                    
                }else{
                    
                    if(lstProposal != null && lstProposal.size() > 0){
                        lstProposal[0].APTS_LP_No_Approval_Rule_Matched__c = true;
                        lstProposal[0].APTS_LP_MaximumSubstituteDiscount__c = null;
                        lstProposal[0].APTS_GTV_Code__c  = null;
                    }
                    if(lstAgreement != null && lstAgreement.size() > 0){
                        lstAgreement[0].APTS_LP_No_Approval_Rule_Matched__c = true;
                        lstAgreement[0].APTS_LP_MaximumSubstituteDiscount__c = null;
                        lstAgreement[0].APTS_GTV_Code__c  = null;
                    }
                    
                    
                }
                
                if(lstProposal != null &&  lstProposal.size() > 0 && lstProposal[0].APTS_LP_No_Approval_Rule_Matched__c && isAnyLineItemWithNoRule==FALSE){
                    
                    if(isCartEmpty)
                        createTask(Label.APTS_EMPTY_CART, Label.APTS_EMPTY_CART, lstProposal[0].id);
                    else
                        createTask(Label.APTS_NO_APPROVAL_RULE_MATRIX, Label.APTS_NO_APPROVAL_RULE_MATRIX_DESCRIPTION, lstProposal[0].id);
                }
                
                if(lstAgreement != null &&  lstAgreement.size() > 0 && lstAgreement[0].APTS_LP_No_Approval_Rule_Matched__c && isAnyLineItemWithNoRule==FALSE){
                    
                    if(isCartEmpty)
                        createTask(Label.APTS_EMPTY_CART, Label.APTS_EMPTY_CART, lstAgreement[0].id);
                    else
                        createTask(Label.APTS_NO_APPROVAL_RULE_MATRIX, Label.APTS_NO_APPROVAL_RULE_MATRIX_DESCRIPTION, lstAgreement[0].id);
                }

            }
            
        }
        
        // Set Critical Discount flag = True on line Item + JS - 27-Nov-2015
        if(listCriticalDiscLineItem.size() > 0){
            update listCriticalDiscLineItem;
        }

        if(lstProposal != null && lstProposal.size() > 0){
            update lstProposal;
        }
        
        if(lstAgreement != null && lstAgreement.size() > 0){
            update lstAgreement;
        }
        
    }
    
   /**
       @ Method to re arrange the line numbers on shopping cart
       @ param: list of product configurations  
       @ Assumption: There will be only stand alone products on cart.
   **/
    public static void populateLineNumber(list<Apttus_Config2__ProductConfiguration__c > prodConfigs){
        
         integer i=0;
         list<Apttus_Config2__LineItem__c> linesWithLineNumberSequence=new list<Apttus_Config2__LineItem__c>();
         system.debug('#####lines3'+prodConfigs.size());
         
         list<Apttus_Config2__LineItem__c> configLines=[select Id,APTS_Line_Number_Custom__c,Apttus_Config2__ConfigurationId__c  from Apttus_Config2__LineItem__c where Apttus_Config2__ConfigurationId__c IN: prodConfigs LIMIT :APTS_Constants.SELECT_SOQL_LIMIT];
         system.debug('#####lines5'+configLines.size());
         
         // loop through each configuration
         for (Apttus_Config2__ProductConfiguration__c productConfig: prodConfigs) {  
            
                 system.debug('#####lines2');
            for(Apttus_Config2__LineItem__c item: configLines){
            
              if(item.Apttus_Config2__ConfigurationId__c==productConfig.Id){
                 //assign proper line number for each line item
                 item.APTS_Line_Number_Custom__c=i+1;
                 i++;
                 system.debug('#####lines'+item.Id);
                 linesWithLineNumberSequence.add(item);
              }
              
            }
         }
         
         if(!LineswithLineNumberSequence.isEmpty()){
             update linesWithLineNumberSequence;  
         }
     
  }       
    
     /*
    
    @Method to skip finalisation logic for Product Config records which belong to MSPAs created with changes from an Approved Quote.
    @param:ProductConfiguration
    */
    
    private static Set < String > getFilteredProductConfig(Map < Id, Apttus_Config2__ProductConfiguration__c > records, Map < Id, Apttus_Config2__ProductConfiguration__c > oldRecordsMap){
        Set < String > setProductConfig = new Set < String > ();
        Map <String, String> objToProductconfigMap = new Map<String,String>();
        List <Apttus__APTS_Agreement__c> toBeReset = new List<Apttus__APTS_Agreement__c>();
        Apttus__APTS_Agreement__c tmpagrmt ;
        Boolean bStatusChanged = false;
        
         
        for (Apttus_Config2__ProductConfiguration__c productConfig: records.values()) {
            
            Apttus_Config2__ProductConfiguration__c newConfig = records.get(productConfig.ID);
            Apttus_Config2__ProductConfiguration__c oldConfig = oldRecordsMap.get(productConfig.ID);
            //recalculate the approvals and set approved status only for non cloned items
         /*    string flag= ApexPages.currentPage().getParameters().get('flag');
           
            for(string param: ApexPages.currentPage().getParameters().values()){
               system.debug('param is '+param);        
            }
        */
            if((oldConfig != null && newConfig.Apttus_Config2__Status__c.equals('Finalized') && newConfig.Apttus_Config2__Status__c != oldConfig.Apttus_Config2__Status__c ))
                bStatusChanged = newConfig.Apttus_Config2__Status__c.equals('Finalized');
            //RG added exclusion rule to exclude MSPAs created from Quote with change
            
            if (bStatusChanged ){
                System.debug('change in the status of the - prod config to finalize');
                objToProductconfigMap.put((productConfig.Apttus_QPConfig__Proposald__c!=null?productConfig.Apttus_QPConfig__Proposald__c: productConfig.Apttus_CMConfig__AgreementId__c), productConfig.Id);
            }
            
        }
        
        List<Apttus_Proposal__Proposal__c> proposals = [select id,Apttus_Proposal__Approval_Stage__c,APTS_Local_Channel__c,APTS_GTV_Code__c,APTS_LP_MaximumSubstituteDiscount__c 
                from Apttus_Proposal__Proposal__c where id IN :objToProductconfigMap.keySet() LIMIT :APTS_Constants.SELECT_SOQL_LIMIT];
        
        List<Apttus__APTS_Agreement__c> agrmts = [select id,Apttus_Approval__Approval_Status__c,APTS_GTV_Code__c, APTS_Local_Channel__c, APTS_isClone__c,
                                APTS_LP_MaximumSubstituteDiscount__c, APTS_MSPA_From_Quote__c, Apttus__Status__c, Apttus_QPComply__RelatedProposalId__c 
                                from Apttus__APTS_Agreement__c where id  IN :objToProductconfigMap.keySet() LIMIT :APTS_Constants.SELECT_SOQL_LIMIT];
                               
        system.debug('<<<< Proposal Size >>>>: ' + proposals.size());                       
        if(proposals!=null && proposals.size()>0){
            for (Apttus_Proposal__Proposal__c proposal: proposals){
                setProductConfig.add(objToProductconfigMap.get(proposal.Id));
            }
        }
        
        system.debug('<<<< Agreement Size >>>>: ' + agrmts.size());                       
        if(agrmts!=null && agrmts.size()>0) {
            for(Apttus__APTS_Agreement__c agrmt: agrmts){
                setProductConfig.add(objToProductconfigMap.get(agrmt.Id));
                
                system.debug('### is it included ?###'+agrmt.APTS_MSPA_From_Quote__c);
                /*
                if(agrmt.APTS_MSPA_From_Quote__c == null && !agrmt.APTS_isClone__c){
                    setProductConfig.add(objToProductconfigMap.get(agrmt.Id));
                }
                */
                if(agrmt.APTS_MSPA_From_Quote__c!=null){
                   
                    if(agrmt.APTS_MSPA_From_Quote__c.equals('Without Changes')){
                     system.debug('### inside if condition'+agrmt.APTS_MSPA_From_Quote__c);
                        tmpagrmt = new Apttus__APTS_Agreement__c (Id = agrmt.Id, Apttus__Status__c=APTS_Constants.STATUS_APPROVED_ACTION_REQ);
                    }else if(agrmt.APTS_MSPA_From_Quote__c.equals('With Changes')){
                        tmpagrmt = new Apttus__APTS_Agreement__c (Id = agrmt.Id, APTS_MSPA_From_Quote__c='');
                    system.debug('### is it included ?###'+agrmt.APTS_MSPA_From_Quote__c+';;'+agrmt.Apttus__Status__c);
                    toBeReset.add(tmpagrmt);
                   }
                }
                
                if(agrmt.APTS_isClone__c){
                    tmpagrmt = new Apttus__APTS_Agreement__c (Id = agrmt.Id, APTS_isClone__c=FALSE);
                    toBeReset.add(tmpagrmt);
                }
            }
        }
        
        if(toBeReset!=null && toBeReset.size()>0){
            update toBeReset;
        }
        
        return setProductConfig;
        
    }
    
    private static void setDiscountAndGTVCode(Apttus_Config2__ProductConfiguration__c productConfig, Boolean bProposal, map<String,Integer> maplineItemWiseRulesCount, map<String,Apttus_Config2__LineItem__c> maplineItemWithId,Decimal maxCount){
        
        Decimal maxDiscountFromAllItems = 99999;
        String itemGTVCodeHavingMaxDisc = '';
        String sCriticalLineItemId = '';
        Apttus_Config2__LineItem__c oCriticalDiscLineItem = new Apttus_Config2__LineItem__c();
        for(String key : maplineItemWiseRulesCount.keyset()){
            if(key != null){
                system.debug(' @@ key @@  : '+ key);
                Integer keyCount = (Integer)maplineItemWiseRulesCount.get(key);
                Apttus_Config2__LineItem__c keyItem = maplineItemWithId.get(key);
                system.debug(' @@ key : '+ keyItem);
                system.debug(' @@ keyCount : '+ keyCount);
                if(keyCount ==maxCount){
                    
                    
                    if(maxDiscountFromAllItems == 99999){
                        maxDiscountFromAllItems = keyItem.APTS_Line_Item_Discount__c;
                        itemGTVCodeHavingMaxDisc = keyItem.Apttus_Config2__ProductId__r.APTS_Hierarchy_Level_3_Code__c;
                        sCriticalLineItemId = keyItem.Id;
                    }
                    if(keyItem.APTS_Line_Item_Discount__c > maxDiscountFromAllItems){
                        maxDiscountFromAllItems = keyItem.APTS_Line_Item_Discount__c;
                        itemGTVCodeHavingMaxDisc = keyItem.Apttus_Config2__ProductId__r.APTS_Hierarchy_Level_3_Code__c;
                        sCriticalLineItemId = keyItem.Id;
                    }
                    system.debug('@@@ maxDiscountFromAllItems : '+ maxDiscountFromAllItems);
                    
                }
            }
        }
        if(bProposal){
            mapProdConfigWithMaxDiscount.put(productConfig.Apttus_QPConfig__Proposald__c,maxDiscountFromAllItems);
            mapProdConfigWithGTVCode.put(productConfig.Apttus_QPConfig__Proposald__c,itemGTVCodeHavingMaxDisc);
        }
        else{
            mapProdConfigWithMaxDiscount.put(productConfig.Apttus_CMConfig__AgreementId__c,maxDiscountFromAllItems);
            mapProdConfigWithGTVCode.put(productConfig.Apttus_CMConfig__AgreementId__c,itemGTVCodeHavingMaxDisc);
        }
        
        // Set Critical Discount LineItem flag to true
        if(!String.isEmpty(sCriticalLineItemId)){
            oCriticalDiscLineItem = maplineItemWithId.get(sCriticalLineItemId);
            oCriticalDiscLineItem.APTS_Is_Critical_Discount__c = True;
            listCriticalDiscLineItem.add(oCriticalDiscLineItem);
        }
        system.debug('<<<< Critical Line Item >>>> :'+ listCriticalDiscLineItem);
        
    }
    

    
    private static void createTask(String subject, String description, String whatId){
        
        Task t = new Task();
        t.Subject = subject;
        t.WhatId = whatId;
        t.Description = description;
        t.Status = 'Completed';
        t.Priority = 'Normal';
        t.ActivityDate = system.today();
        insert t;

    }
}