src/objects/APTS_Capture_LSO_Input_Config_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom object to configure settings like dropdown list values etc. for Capture LSO Input page while creating MSPA or Quotation from Account or Opportunity.</description>
    <label>Capture LSO Input Config Settings</label>
</CustomObject>

src/objects/APTS_Stage_Approval_Rule_Matrix__c.object
<CustomObject>
    <description>Stage Approval rule matrix stores routing rules that will be configured by country admin and it drives the Quotation &amp; Agreement approvals.</description>
    <fields>
        <fullName>APTS_Approval_Level__c</fullName>
        <label>Approval Level</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>APTS_Owner__c</fullName>
        <label>Owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Sales_Office__c</fullName>
        <label>Sales Office</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Stage Approval Rule Matrix</label>
    <nameField>
        <displayFormat>ARM-{00000000}</displayFormat>
        <label>Stage Approval Rule Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stage Approval Rule Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/APTS_Stage_Data_Validation_Rules_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>APTS_Validate_SFDC_User__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Flag to check if Assigned Approver and Actual Approver fields required validation against SFDC User Object</description>
        <label>Validate SFDC User</label>
        <type>Checkbox</type>
    </fields>
	<label>APTS Stage Data Validation Rules</label>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>APTS_Country_Code__c</fullName>
        <description>Country Code for Local Products.</description>
        <label>Country Code</label>
        <picklist>
            <picklistValues>
                <fullName>ES</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>APTS_Hierarchy_Level_3_Code__c</fullName>
        <description>Level 3 Hierarchy Code</description>
        <label>Hierarchy Level 3 Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Hierarchy_Level__c</fullName>
        <label>Hierarchy Level</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>APTS_LP_Is_Hierarchy__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check only if Product Hierarchy is created.</description>
        <label>Is Hierarchy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_Product_ID__c</fullName>
        <description>Local Product ID for Local Products Record Type and Product ID for Global Products Record Type.</description>
        <label>Product ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/APTS_DMApprovalRuleMatrixHelperTest.cls
@isTest
public class APTS_DMApprovalRuleMatrixHelperTest {
    
    private static User user;
    private static APTS_Capture_LSO_Input_Config_Settings__c lodConfigSetting = APTS_LP_TestUtility.getLODConfigSetting();
    
    // Test method to validate Stage Approval-Rule-Matrix Object
    public static testMethod void validateStageApprovalRuleMatrix(){
        APTS_Stage_Data_Validation_Rules_Setting__c validateUser = new APTS_Stage_Data_Validation_Rules_Setting__c();
        validateUser.name = 'DataMigration';
        validateUser.APTS_Validate_SFDC_User__c = FALSE ;        
        insert validateUser; 
            
        user  = APTS_LP_TestUtility.getUser();
        System.runAs(user) {
            List<APTS_Stage_Approval_Rule_Matrix__c> listApprovalRuleMatrix  = APTS_LP_TestUtility.getStageApprovalRuleMatrix(3);
            APTS_LP_TestUtility.getCommonConfigSetting();
            for(APTS_Stage_Approval_Rule_Matrix__c stageApproval :listApprovalRuleMatrix ){
                stageApproval.APTS_Sales_Office__c = APTS_LP_TestUtility.getSalesOffice().id;
            }
            listApprovalRuleMatrix.get(0).APTS_Owner__c = '';
            
            Product2 prod = new Product2();
            prod.APTS_Hierarchy_Level__c = 3;
            prod.name = 'Test Prod';
            prod.APTS_Country_Code__c = 'ES';
            prod.APTS_LP_Is_Hierarchy__c = TRUE;
            prod.APTS_Hierarchy_Level__c = 3;
            prod.APTS_Hierarchy_Level_3_Code__c = '00996';
            prod.Description = 'Test Desc';
            prod.RecordTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByName().get(APTS_DMConstants.LOCAL_HIERACHY).getRecordTypeId();
            prod.IsActive = true;
            prod.APTS_Product_ID__c = 'P123';
            
            Test.startTest();
            insert prod;
            APTS_DMApprovalRuleMatrixHelper.validateApprovalMatrix(listApprovalRuleMatrix); 
            Test.stopTest();
        }
    }
    
    // Test method to validate Stage Approval-Rule-Matrix Object
    public static testMethod void copyStageApprovalRuleMatrix(){
        APTS_Stage_Data_Validation_Rules_Setting__c validateUser = new APTS_Stage_Data_Validation_Rules_Setting__c();
        validateUser.name = 'DataMigration';
        validateUser.APTS_Validate_SFDC_User__c = FALSE ;        
        insert validateUser; 
            
        user  = APTS_LP_TestUtility.getUser();
        System.runAs(user) {
            List<APTS_Stage_Approval_Rule_Matrix__c> listApprovalRuleMatrix  = APTS_LP_TestUtility.getStageApprovalRuleMatrix(3);
            APTS_LP_TestUtility.getCommonConfigSetting();
            for(APTS_Stage_Approval_Rule_Matrix__c stageApproval :listApprovalRuleMatrix ){
                stageApproval.APTS_Sales_Office__c = APTS_LP_TestUtility.getSalesOffice().id;
                stageApproval.APTS_Approval_Level__c = 2;
            }
            listApprovalRuleMatrix.get(0).APTS_Owner__c = '';
            
            Test.startTest();
            APTS_LP_TestUtility.getDiscountConfig();
            APTS_DMApprovalRuleMatrixHelper.copyApprovalMatrix(listApprovalRuleMatrix); 
            Test.stopTest();
        }
    }
}