src/objects/APTS_SAP_Integration_Tokens__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This setting holds all SAP static strings, passwords, tokens etc.</description>
<fields>
        <fullName>APTS_Base_Address__c</fullName>
        <label>Base Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Bau_Code__c</fullName>
        <label>Bau Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_ERP_Response_Culture__c</fullName>
        <label>ERP Response Culture</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_End_Point__c</fullName>
        <label>End Point</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Http_Header_Key__c</fullName>
        <label>Http Header Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Key_Name__c</fullName>
        <label>Key Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Key__c</fullName>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_oAuth_Token__c</fullName>
        <description>It holds oAuth Token URL</description>
        <label>oAuth Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SAP Integration Tokens</label>
</CustomObject>

src/objects/Apttus__AgreementLineItem__c.object
<CustomObject>
    <description>Represents a product or service line item associated with an agreement</description>
    <fields>
        <fullName>APTS_Discount_Type__c</fullName>
        <description>Field used by user to select appropriate type of discount in line item.</description>
        <label>Discount Type</label>
        <picklist>
            <picklistValues>
                <fullName>--None--</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net Price Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Additional Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Substitute Discount</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__BasePrice__c</fullName>
        <description>The base price is List price + Automatic Adjustments for individual products and options</description>
        <label>Base Price</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__DerivedFromId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The ID of the line item this was derived from</description>
        <label>Derived From</label>
        <referenceTo>Apttus_Config2__LineItem__c</referenceTo>
        <relationshipLabel>Derived Agreement Line Items</relationshipLabel>
        <relationshipName>DerivedAgreementLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__PriceListId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the price list associated with the product or service</description>
        <label>Price List</label>
        <referenceTo>Apttus_Config2__PriceList__c</referenceTo>
        <relationshipLabel>Agreement Line Items</relationshipLabel>
        <relationshipName>AgreementLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus__AgreementId__c</fullName>
        <description>ID of the associated agreement</description>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Agreement Line Items</relationshipLabel>
        <relationshipName>AgreementLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Apttus__Quantity__c</fullName>
        <description>The product or service quantity</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <label>Agreement Line Item</label>
    <nameField>
        <displayFormat>AL-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreement Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>APTS_Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Spain</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>APTS_Integration_Status__c</fullName>
        <label>Integration Status</label>
        <picklist>
            <picklistValues>
                <fullName>Empty</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>APTS_LP_AccountCustomer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Customer name of the direct customer</description>
        <inlineHelpText>Direct customer to which the MSPA is related. Auto populated if MSPA created from Opportunity or Buying Account.</inlineHelpText>
        <label>Account Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>GIS Approved</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>MSPAs</relationshipName>
        <type>Lookup</type>
    </fields>
    
    <fields>
        <fullName>Apttus_CMConfig__PriceListId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated price list</description>
        <label>Price List</label>
        <referenceTo>Apttus_Config2__PriceList__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus__Contract_End_Date__c</fullName>
        <description>The end date for this agreement</description>
        <label>Agreement End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Apttus__Contract_Start_Date__c</fullName>
        <description>The effective date of the agreement</description>
        <label>Agreement Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Apttus__Status__c</fullName>
        <description>The sub stage of an agreement – the status underneath a given status category.  These are generally modifiable by the customer except for the following values which are Apttus reserved to manage agreement lifecycles:

Request, Submitted Request,
Cancelled Request, In Amendment, Being Amended, Superseded, Activated, Expired, Internal Signatures, Author Contract, Expired, Terminated,  Ready for Signatures, Fully Signed, Signature Declined</description>
        <label>Status</label>
        <picklist>
            <controllingField>Apttus__Status_Category__c</controllingField>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approval In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturated Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved but failed to load on SAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved but Action Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deactivated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Signatures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queued to create in SAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recalled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Generated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Presented</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Apttus__Workflow_Trigger_Created_From_Clone__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates a transient agreement that may get deleted by the user. A new agreement is in transient state until the agreement is explicitly saved by the user. A new agreement is created by new, clone, amend, renew, create offline or create from opportunity methods. Workflow rules should check this field to test for false before firing so that rules are not incorrectly fired when transient agreements are created .</description>
        <inlineHelpText>Indicates a transient agreement that may get deleted by the user. A new agreement is in transient state until the agreement is explicitly saved by the user.</inlineHelpText>
        <label>Is Transient</label>
        <type>Checkbox</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>MSPA</fullName>
        <active>true</active>
        <label>MSPA</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__LineItem__c.object
<CustomObject>
    <fields>
        <fullName>Apttus_Config2__Quantity__c</fullName>
        <description>The product or service quantity</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>APTS_GTV_Level__c</fullName>
        <formula>Apttus_Config2__ProductId__r.APTS_GTV_Level__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GTV Level</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Apttus_Config2__PriceList__c.object
<CustomObject>
    <fields>
        <fullName>APTS_Country__c</fullName>
        <description>Name of the country for which price list exists</description>
        <label>Country</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>APTS_Country_Code__c</fullName>
        <description>Country Code for Local Products.</description>
        <label>Country Code</label>
        <picklist>
            <picklistValues>
                <fullName>ES</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>APTS_GTV_Level__c</fullName>
        <label>GTV Level</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_LP_Is_Hierarchy__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check only if Product Hierarchy is created.</description>
        <label>Is Hierarchy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_Product_ID__c</fullName>
        <description>Local Product ID for Local Products Record Type and Product ID for Global Products Record Type.</description>
        <label>Product ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/APTS_SAPConnectorForMSPACreationTest.cls
@isTest
public class APTS_SAPConnectorForMSPACreationTest {
    private static User user;
    public static Apttus__APTS_Agreement__c agreement;
    static APTS_Capture_LSO_Input_Config_Settings__c oLODConfigSetting = APTS_LP_TestUtility.getLODConfigSetting();
    
    public static void createTestData()
    {        
        
        APTS_LP_TestUtility.getDiscountConfig();
        APTS_LP_TestUtility.getCommonConfigSetting();
        List<APTS_SAP_Integration_Tokens__c> tokenList = new List<APTS_SAP_Integration_Tokens__c>();
        
        APTS_SAP_Integration_Tokens__c SAPMSPACreationTokens = new APTS_SAP_Integration_Tokens__c();
        SAPMSPACreationTokens.Name = 'SAP MSPA Creation Tokens';
        SAPMSPACreationTokens.APTS_Base_Address__c = 'https://abberpgatewaydev.servicebus.windows.net/';
        SAPMSPACreationTokens.APTS_Bau_Code__c = 'ES1';
        SAPMSPACreationTokens.APTS_Key__c = 'Sd6tRl5wj9ieNgE6q7Q9Y/wkYoD24aqERudvHvB9Ow8=';
        SAPMSPACreationTokens.APTS_Key_Name__c = 'FaceServiceBusServices';
        SAPMSPACreationTokens.APTS_End_Point__c = 'https://abberpgatewaydev.servicebus.windows.net/api/products/quotationpricelistsearch';
        SAPMSPACreationTokens.APTS_ERP_Response_Culture__c = 'es-ES';
        SAPMSPACreationTokens.APTS_Http_Header_Key__c = 'Authorization';
        tokenList.add(SAPMSPACreationTokens);
        
        APTS_SAP_Integration_Tokens__c OAuthToken = new APTS_SAP_Integration_Tokens__c();
        OAuthToken.Name = 'SAP oAuth Tokens';
        OauthToken.APTS_Base_Address__c = 'https://abberpgatewaydev.servicebus.windows.net/';
        OauthToken.APTS_Key__c = 'hj7nmmYxSZbtVsyeyqAJ';
        OauthToken.APTS_Http_Header_Key__c = 'Authorization';
        OauthToken.APTS_oAuth_Token__c = 'ErpGateway:nU2+tOVFCK81+/wuuSx61QgOyySMcS9z//go4Lpej6k=';
        OauthToken.APTS_Key_Name__c = 'FaceErpGateway_ServiceBus';
        OauthToken.APTS_End_Point__c = 'https://applications.it.abb.com/abbaccountstest/issue/oauth2/token';
        tokenList.add(OauthToken);
        
        APTS_SAP_Integration_Tokens__c PricingToken = new APTS_SAP_Integration_Tokens__c();
        PricingToken.Name = 'PricingToken';
        PricingToken.APTS_Base_Address__c = 'https://abberpgatewaydev.servicebus.windows.net/';
        PricingToken.APTS_Bau_Code__c = 'ES1';
        PricingToken.APTS_Key__c = 'Sd6tRl5wj9ieNgE6q7Q9Y/wkYoD24aqERudvHvB9Ow8=';
        PricingToken.APTS_Key_Name__c = 'FaceServiceBusServices';
        PricingToken.APTS_End_Point__c = 'https://abberpgatewaydev.servicebus.windows.net/api/products/quotationpricelistsearch';
        PricingToken.APTS_ERP_Response_Culture__c = 'es-ES';
        PricingToken.APTS_Http_Header_Key__c = 'Authorization';
        tokenList.add(PricingToken);
        
        insert tokenList;
        
        Account acc = new Account();
        acc = APTS_LP_TestUtility.getNewAccount('Test Account', 'Spain');
        insert acc;
        
        Apttus_Config2__PriceList__c priceList = new Apttus_Config2__PriceList__c(Apttus_Config2__AccountId__c = acc.id, Name='Test - Price List');
        priceList.APTS_Country__c = 'Spain';
        insert priceList;
        
        List<Apttus__APTS_Agreement__c> agreementList = new List<Apttus__APTS_Agreement__c>();
        
        Apttus__APTS_Agreement__c  agr1 = new Apttus__APTS_Agreement__c();
        agr1 = APTS_LP_TestUtility.getAgreement('TestAgreement');
        agr1.APTS_LP_AccountCustomer__c = acc.id;       
        agr1.APTS_Country__c = 'Spain';          
        agr1.APTS_Integration_Status__c = 'Empty';
        agr1.Apttus__Workflow_Trigger_Created_From_Clone__c = false;
        agr1.Apttus__Status__c = 'Draft';
        agr1.Apttus_CMConfig__PriceListId__c = priceList.Id;
        agreementList.add(agr1);  
        
        agreement = APTS_LP_TestUtility.getAgreement('Test Agreement');
        agreement.Apttus_CMConfig__PriceListId__c = priceList.Id;
        agreement.Apttus__Contract_Start_Date__c = date.today();
        agreement.Apttus__Contract_End_Date__c = date.today()+30;
        agreementList.add(agreement);
        
        insert agreementList;
        
        agr1.Apttus__Status__c = 'Approved but Action Required';
        update agr1;
        
        Product2 testPrd = new Product2();
        testPrd.name = 'Test Prod';
        testPrd.APTS_Country_Code__c = 'EN';
        testPrd.APTS_GTV_Level__c = 'TestGTV';
        testPrd.Description = 'Test Desc';
        testPrd.RecordTypeId = APTS_LP_TestUtility.getRecordId();
        testPrd.IsActive = true;                
        testPrd.APTS_Product_ID__c = '1SAJ230000R1005';
        testPrd.APTS_LP_Is_Hierarchy__c = true;
        insert testPrd;
        
        Apttus_Config2__PriceListItem__c PLI = new Apttus_Config2__PriceListItem__c();
        PLI.Apttus_Config2__PriceListId__c = priceList.Id;
        PLI.Apttus_Config2__Active__c =true;
        PLI.Apttus_Config2__ProductId__c = testPrd.Id;
        insert PLI;
        
        Apttus_Config2__ProductConfiguration__c productConfig = new Apttus_Config2__ProductConfiguration__c();
        productConfig = APTS_LP_TestUtility.getProductConfiguration('TestProductConfiguration');
        productConfig.Apttus_CMConfig__AgreementId__c = agreement.Id;
        Insert productConfig;
        
        List<Apttus_Config2__LineItem__c> listLineItem = new List<Apttus_Config2__LineItem__c>(); 
        
        Apttus_Config2__LineItem__c lineItem = new Apttus_Config2__LineItem__c(); 
        lineItem.Apttus_Config2__Quantity__c = 2;
        lineitem.CurrencyIsoCode = 'EUR';
        lineItem.Apttus_Config2__LineNumber__c = 1;
        lineItem.Apttus_Config2__PrimaryLineNumber__c =1;
        lineItem.Apttus_Config2__ListPrice__c = 0;
        lineItem.Apttus_Config2__ItemSequence__c = 1;
        lineItem.Apttus_Config2__ProductId__c = testprd.id;
        lineitem.Apttus_Config2__PriceListId__c = priceList.Id;
        lineitem.Apttus_Config2__PriceListItemId__c = PLI.Id;
        lineitem.Apttus_Config2__ConfigurationId__c = productConfig.Id;
        listLineItem.add(lineItem);
        
        Apttus_Config2__LineItem__c lineItem2 = new Apttus_Config2__LineItem__c(); 
        lineItem2.Apttus_Config2__Quantity__c = 2;
        lineitem2.CurrencyIsoCode = 'EUR';
        lineItem2.Apttus_Config2__LineNumber__c = 1;
        lineItem2.Apttus_Config2__PrimaryLineNumber__c =1;
        lineItem2.Apttus_Config2__ListPrice__c = 0;
        lineItem2.Apttus_Config2__ItemSequence__c = 2;
        lineItem2.Apttus_Config2__ProductId__c = testprd.id;
        lineitem2.Apttus_Config2__PriceListId__c = priceList.Id;
        lineitem2.Apttus_Config2__PriceListItemId__c = PLI.Id;
        lineitem2.Apttus_Config2__ConfigurationId__c = productConfig.Id;
        listLineItem.add(lineItem2);
        
        insert listLineItem;
        listLineItem = APTS_LP_TestUtility.getLineItemListWithDiscount(productConfig.Id, 2, testPrd, 0);
        
        List<Apttus__AgreementLineItem__c> agrLineItemList = new List<Apttus__AgreementLineItem__c>();
        
        Apttus__AgreementLineItem__c AgreeLineItem = new Apttus__AgreementLineItem__c();
        AgreeLineItem.Apttus__AgreementId__c = agreement.Id;
        AgreeLineItem.Apttus_CMConfig__DerivedFromId__c = lineItem.Id;
        AgreeLineItem.Apttus__Quantity__c = 2;
        AgreeLineItem.Apttus_CMConfig__BasePrice__c=200;     
        AgreeLineItem.APTS_Discount_Type__c = 'Additional Discount';              
        AgreeLineItem.APTS_Discount_Percentage__c = 10;        
        agrLineItemList.add(AgreeLineItem);
        
        Apttus__AgreementLineItem__c AgreeLineItem2 = new Apttus__AgreementLineItem__c();
        AgreeLineItem2.Apttus__AgreementId__c = agreement.Id;
        AgreeLineItem2.Apttus_CMConfig__DerivedFromId__c = lineItem2.Id;
        AgreeLineItem2.Apttus__Quantity__c = 2;
        AgreeLineItem2.Apttus_CMConfig__BasePrice__c=200;
        AgreeLineItem2.APTS_Discount_Type__c = 'Substitute Discount';              
        AgreeLineItem2.APTS_Discount_Percentage__c = 10;        
        agrLineItemList.add(AgreeLineItem2);
        
        Apttus__AgreementLineItem__c AgreeLineItem3 = new Apttus__AgreementLineItem__c();
        AgreeLineItem3.Apttus__AgreementId__c = agreement.Id;
        AgreeLineItem3.Apttus_CMConfig__DerivedFromId__c = lineItem2.Id;
        AgreeLineItem3.Apttus__Quantity__c = 2;
        AgreeLineItem3.Apttus_CMConfig__BasePrice__c=200;
        AgreeLineItem3.APTS_Discount_Type__c = 'Net Price Discount';              
        AgreeLineItem3.APTS_Discount_Percentage__c = 10;        
        agrLineItemList.add(AgreeLineItem3);
        
        insert agrLineItemList;
    }
    public static testMethod void SAPConnectorForMSPACreation() 
    {
        User usr = APTS_LP_TestUtility.getUser();
        System.runAs(usr) {
            Test.startTest();
            createTestData();
            ApexPages.StandardController stdController = new ApexPages.StandardController(agreement);
            APTS_SAPConnectorForMSPACreation obj = new APTS_SAPConnectorForMSPACreation(stdController);
            Test.setMock(HttpCalloutMock.class, new APTPS_CalloutMockTest());
            PageReference ref = obj.CreateMSPAviaButton();
            Test.stopTest();
        }
    }
    
    public static testMethod void testCreateMSPA() 
    {
        User usr = APTS_LP_TestUtility.getUser();
        System.runAs(usr) {
            Test.startTest();
                createTestData();
            	Set<Id> agrIds = new Set<Id>();
            	agrIds.add(agreement.Id);
				APTS_SAPConnectorForMSPACreation.CreateMSPA(agrIds,'True');
            Test.stopTest();
        }
    }
}