src/objects/APTS_LP_Local_Customer_Reference_Data__c.object
<CustomObject>
    <description>Object to hold the reference data related to customer (account). (ABB-LP)</description>
    <fields>
        <fullName>APTS_LP_Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <picklist>
            <picklistValues>
                <fullName>BT</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>DT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>APTS_LP_Incoterms__c</fullName>
        <label>Incoterms</label>
        <picklist>
            <picklistValues>
                <fullName>CFR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DDP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DAF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DDU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DEQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FOB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZFE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EXW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZVR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>APTS_LP_Local_Channel__c</fullName>
        <label>Local Channel</label>
        <picklist>
            <picklistValues>
                <fullName>P1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P6</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>APTS_Payment_Terms__c</fullName>
        <description>Field to capture payment terms associated with Apttus LSO object record.</description>
        <label>Payment Terms</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Local Operational Data</label>
    <nameField>
        <displayFormat>LCRD-{00000}</displayFormat>
        <label>Local Operational Data Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Local Operational Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/APTS_Master_Picklist_Table__c.object
<CustomObject>
    <description>Object to hold locale wise description for codes (used for incoterm, payment term etc.) used in SAP</description>
    <fields>
        <fullName>APTS_Code_Description__c</fullName>
        <description>Field to hold the description value for code.</description>
        <label>Code Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Master Picklist Table</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Picklist Table</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/APTS_WrapperLOD.cls
/*
    @Description: This is a Wrapper Class used for displaying LOD records on the LOD selection page.
    @Owner: Jignesh Shekhaliya(Apttus)
    @Created Date: 12-Dec-2015
*/
public class APTS_WrapperLOD{
    public integer iRecordId{get;set;}
    public APTS_LP_Local_Customer_Reference_Data__c LSOData  {get; set;}
    public String descDistributionChannel {get; set;}
    public String descIncoterm {get; set;}
    public String descPaymentTerm {get; set;}
    public String descLocalChannel {get; set;}
    public String salesOffice {get;set;}
    public String lbu {get;set;}
    public boolean bIsSelected {get; set;}
    public String sDistributionChannelId {get; set;}
    public String sPaymentTermId {get; set;}
    public String sLocalChannelId {get; set;}
    public String sIncotermId {get; set;}
    
    // Default constructor
    public APTS_WrapperLOD(){
        
    }
    
    public APTS_WrapperLOD(APTS_LP_Local_Customer_Reference_Data__c LSOData, string descIncoterm,string descPaymentTerm,string descLocalChannel, string sSalesOffice, string lbu){
        
        this.LSOData = LSOData;
        this.descIncoterm = descIncoterm;
        this.descPaymentTerm = descPaymentTerm;
        this.descLocalChannel = descLocalChannel;
        this.salesOffice = sSalesOffice;
        this.lbu = lbu;
        this.bIsSelected = false;
        
    }
    
    public APTS_WrapperLOD(APTS_LP_Local_Customer_Reference_Data__c oLODRecord, Map<Id, APTS_Master_Picklist_Table__c> mapMPLData, string sSalesOffice, string lbu){
        
        APTS_Master_Picklist_Table__c oMPLRecord;
        oMPLRecord = APTS_LP_CommonUtil.getMPLRecord(mapMPLData, oLODRecord.APTS_LP_Incoterms__c, APTS_CaptureInputForLSODataConstants.INCOTERM);
        if(oMPLRecord != null){        
            String descIncoterm  = oMPLRecord.APTS_Code_Description__c; 
            this.descIncoterm = descIncoterm;
            this.sIncotermId = oMPLRecord.id;
        }
        
        oMPLRecord = APTS_LP_CommonUtil.getMPLRecord(mapMPLData, oLODRecord.APTS_Payment_Terms__c, APTS_CaptureInputForLSODataConstants.PAYMENT_TERM);
        if(oMPLRecord != null){
            String descPaymentTerm  = oMPLRecord.APTS_Code_Description__c;
            this.descPaymentTerm = descPaymentTerm;
            this.sPaymentTermId = oMPLRecord.id;
        }
        
        oMPLRecord = APTS_LP_CommonUtil.getMPLRecord(mapMPLData, oLODRecord.APTS_LP_Local_Channel__c, APTS_CaptureInputForLSODataConstants.LOCAL_CHANNEL);
        if(oMPLRecord != null){
            String descLocalChannel  = oMPLRecord.APTS_Code_Description__c;
            this.descLocalChannel = descLocalChannel;
            this.sLocalChannelId = oMPLRecord.id;
        }
        
        oMPLRecord = APTS_LP_CommonUtil.getMPLRecord(mapMPLData, oLODRecord.APTS_LP_Distribution_Channel__c, APTS_CaptureInputForLSODataConstants.DISTRIBUTION_CHANNEL);
        if(oMPLRecord != null){
            system.debug('@@ : oLODRecord.APTS_LP_Distribution_Channel__c :' + oLODRecord.APTS_LP_Distribution_Channel__c);
            String descDistributionChannel  = oMPLRecord.APTS_Code_Description__c;
            this.descDistributionChannel = descDistributionChannel;
            this.sDistributionChannelId = oMPLRecord.id;
            system.debug('@@ : sDistributionChannelId :' + sDistributionChannelId);
        }
        
        
                        
        this.LSOData = oLODRecord;
        this.salesOffice = sSalesOffice;
        this.lbu = lbu;
        this.bIsSelected = false;
        
    }
}