src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>APTS_LP_Blocked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Blocked</description>
        <inlineHelpText>Set MSPA to Blocked</inlineHelpText>
        <label>Blocked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_LP_Deactivated__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Set MSPA to Deactivated</inlineHelpText>
        <label>Deactivated</label>
        <type>Checkbox</type>
    </fields>
    
    <fields>
        <fullName>Apttus__Status__c</fullName>
        <description>The sub stage of an agreement – the status underneath a given status category.  These are generally modifiable by the customer except for the following values which are Apttus reserved to manage agreement lifecycles:

Request, Submitted Request,
Cancelled Request, In Amendment, Being Amended, Superseded, Activated, Expired, Internal Signatures, Author Contract, Expired, Terminated,  Ready for Signatures, Fully Signed, Signature Declined</description>
        <label>Status</label>
        <picklist>
            <controllingField>Apttus__Status_Category__c</controllingField>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approval In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturated Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved but failed to load on SAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved but Action Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deactivated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Signatures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queued to create in SAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recalled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Generated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Presented</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/APTS_AgreementStatusController.cls
/*************************************************************
@Name: APTS_AgreementStatusController
@Author: Hardik Shah
@CreateDate: 07 Sep 2015
@Description: This class updates the status of Agreement based on Request Parameter Received
@UsedBy: VF-Page : APTS_AgreementStatus
******************************************************************
@ModifiedBy: NA
@ModifiedDate: NA
@ChangeDescription: A brief description of what was modified.
**** PS: @ModifiedBy and @ChangeDescription can be repeated multiple time, based on number of changes made to the original process.
******************************************************************/

public class APTS_AgreementStatusController {
	// Agreement Id
	public Id agreementId {
		get;
		set;
	}
	// Request Parameter from URL - This Parameter is used to determine whether agreement
	// needs to be blocked or DeActivated.
	private string requestParameter;
	// boolean variable to show error message on  VF page
	public Boolean hasErrors {
		get;
		set;
	}
	// Instance of PageReference
	private Pagereference pagereference;
	// Agreement Object
	public Apttus__APTS_Agreement__c agreement {
		get;
		set;
	}


	// Constructor to iniatialize Agreement-Id,Request-Parameter
	public APTS_AgreementStatusController(ApexPages.StandardController controller) {
		agreement = (Apttus__APTS_Agreement__c) controller.getrecord();
		requestParameter = ApexPages.currentPage().getParameters().get('requestParameter');
		hasErrors = false;
	}

	public pagereference onload() {
		try {
			// Check for Agreement-Id
			if (agreement != null && String.isNotBlank(agreement.Id)) {
				// Fetch the Agreement Status. 
				system.debug('status***' + agreement.Apttus__Status__c);
				if (APTS_Constants.AGREEMENT_STATUS.equalsIgnoreCase(agreement.Apttus__Status__c)) {
					Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.INFO, Label.APTS_CANCEL_APPROVAL));
					hasErrors = true;
					return null;
				}
			} else {
				Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, Label.APTS_AGREEMENT_NOT_FOUND));
				hasErrors = true;
				return null;
			}

			// Check for Request-Parameter
			if (requestParameter != null && String.isNotBlank(requestParameter)) {
				// If Request Parameter is De-Activated	
				if (APTS_Constants.MSPA_DEACTIVATED.equalsIgnoreCase(requestParameter)) {

					Apttus__APTS_Agreement__c agr = new Apttus__APTS_Agreement__c(Id = agreement.Id);
					agr.Apttus__Status__c = APTS_Constants.MSPA_DEACTIVATED;
					agr.APTS_LP_Deactivated__c = true;
					update agr;

				}
				// If Request Parameter is Blocked
				else if (APTS_Constants.MSPA_BLOCKED.equalsIgnoreCase(requestParameter)) {
					Apttus__APTS_Agreement__c agr = new Apttus__APTS_Agreement__c(Id = agreement.Id);
					agr.Apttus__Status__c = APTS_Constants.MSPA_BLOCKED;
					agr.APTS_LP_Blocked__c = true;
					update agr;
				}

				pagereference = New Pagereference('/' + agreement.Id);
				pagereference.setRedirect(true);

			} else {
				Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, Label.APTS_AGREEMENT_REQUEST_PARAMETER_NOTFOUND));
				hasErrors = true;
			}


		} catch (Exception ex) {
			Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, ex.getMessage()));
			hasErrors = true;
		}
		return pagereference;
	}

}