src/objects/Apttus__AgreementLineItem__c.object
<CustomObject>
    <description>Represents a product or service line item associated with an agreement</description>
    <fields>
        <fullName>APTS_Is_Critical_Discount__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Critical Discount</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_Product_Name__c</fullName>
        <formula>IF( Apttus__ProductId__r.APTS_LP_Is_Hierarchy__c , Apttus_CMConfig__DerivedFromId__r.Apttus_Config2__ProductId__r.Name, Apttus_CMConfig__DerivedFromId__r.APTS_LP_Product_Description__c)</formula>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Standard_Discount_Format__c</fullName>
        <formula>IF(APTS_LP_Standard_Discount__c &lt; 0.1, LEFT(SUBSTITUTE(TEXT(APTS_LP_Standard_Discount__c * 100), &quot;.&quot;, &quot;,&quot;), 4), LEFT(SUBSTITUTE(TEXT(APTS_LP_Standard_Discount__c * 100), &quot;.&quot;, &quot;,&quot;), 5))</formula>
        <label>Standard Discount Format</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Discount_Percentage__c</fullName>
        <description>Field to hold the value of percentage of discount applied to the line item when selected discount type is either &quot;Substitute Discount&quot; or &quot;Additional Discount&quot;.</description>
        <label>Discount %</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>APTS_Discount_Type__c</fullName>
        <description>Field used by user to select appropriate type of discount in line item.</description>
        <label>Discount Type</label>
        <picklist>
            <picklistValues>
                <fullName>--None--</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net Price Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Additional Discount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Substitute Discount</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
<fields>
        <fullName>APTS_Product_Hierarchy_Information__c</fullName>
        <formula>If( APTS_Product_Is_Hierarchy__c= True, APTS_LP_Hierarchy_Name__c &amp; BR() &amp; &apos;Hierarchy Code:&apos; &amp; CASE(  Apttus__ProductId__r.APTS_Hierarchy_Level__c,2, Apttus__ProductId__r.APTS_LP_Product_Hierarchy__c,3,Apttus__ProductId__r.APTS_Hierarchy_Level_3_Code__c,4, Apttus__ProductId__r.APTS_Hierarchy_Level_4_Code__c,NULL), APTS_Product_Description__c &amp; BR() &amp; &apos;Hierarchy Code:&apos;&amp; Apttus__ProductId__r.APTS_Hierarchy_Level_3_Code__c &amp; BR() &amp; &apos;Local Code:&apos; &amp; APTS_Product_Code__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product/Hierarchy Information</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_LP_Total_Standard_Price__c</fullName>
        <label>Total Standard Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>APTS_LP_Hierarchy_Name__c</fullName>
        <formula>IF( Apttus__ProductId__r.APTS_LP_Is_Hierarchy__c, Apttus__ProductId__r.Name , &quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Hierarchy Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_LP_Product_Hierarchy_Code__c</fullName>
        <formula>Apttus__ProductId__r.APTS_Hierarchy_Level_3_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Hierarchy Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_LP_Standard_Discount__c</fullName>
        <label>Standard Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>APTS_LP_Standard_Net__c</fullName>
        <label>Standard Net</label>
        <precision>15</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>    
    <fields>
        <fullName>APTS_LP_Unit_Of_Measure__c</fullName>
        <label>Unit Of Measure</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_LP_Unit_Of_Price__c</fullName>
        <label>Unit Of Price</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Net_Adjustment_Percentage__c</fullName>
        <formula>IF( ISPICKVAL( APTS_Discount_Type__c , &apos;Substitute Discount&apos;) , 
APTS_Discount_Percentage__c 
,IF(ISPICKVAL( APTS_Discount_Type__c , &apos;Additional Discount&apos;), 
APTS_Discount_Percentage__c + APTS_LP_Standard_Discount__c , 
IF(ISPICKVAL( APTS_Discount_Type__c , &apos;Net Price Discount&apos;), 
Apttus_CMConfig__NetAdjustmentPercent__c * -1, NULL) 
))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Net Adj. (%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>APTS_Net_Price_Override__c</fullName>
        <description>Field to hold the new price value (to override existing price value) for the line item when selected discount type is &quot;Net Price Discount&quot; in line item.</description>
        <label>Net Price Override</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>APTS_Product_Code__c</fullName>
        <formula>IF( Apttus_CMConfig__DerivedFromId__r.Apttus_Config2__ProductId__r.APTS_LP_Is_Hierarchy__c, &apos;&apos;, Apttus_CMConfig__DerivedFromId__r.Apttus_Config2__ProductId__r.APTS_Product_ID__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Product_Description__c</fullName>
        <formula>IF(Apttus_CMConfig__DerivedFromId__r.Apttus_Config2__ProductId__r.APTS_LP_Is_Hierarchy__c, &apos;&apos;,  Apttus_CMConfig__DerivedFromId__r.Apttus_Config2__ProductId__r.Name )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Quantity__c</fullName>
        <formula>Apttus__Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quantity*</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>APTS_Total_Quote_Price__c</fullName>
        <label>Total Quote Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
   <fields>
        <fullName>APTS_new_product_code__c</fullName>
        <inlineHelpText>Summary of the Product and Hierarchy information , for a given line item.</inlineHelpText>
        <label>Product/Hierarchy Information</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__BasePrice__c</fullName>
        <description>The base price is List price + Automatic Adjustments for individual products and options</description>
        <label>Base Price</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__LineNumber__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The line number</description>
        <label>Line Number</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__NetAdjustmentPercent__c</fullName>
        <description>The net adjustment percent</description>
        <label>Net Adjustment (%)</label>
        <precision>14</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Apttus__AgreementId__c</fullName>
        <description>ID of the associated agreement</description>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Agreement Line Items</relationshipLabel>
        <relationshipName>AgreementLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Apttus__NetPrice__c</fullName>
        <description>The net price for the product or service is the Adjusted Price after applying the Group Adjustment %</description>
        <label>Net Price</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <label>Agreement Line Item</label>
    <nameField>
        <displayFormat>AL-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreement Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/APTS_MaxCriticalDiscountController.cls
/*************************************************************
@Name: APTS_MaxCriticalDiscountController
@Author: Rushabh Acharya
@CreateDate: 27th Nov 2015
@Description: This class is to get Agreement Line Item with maximum critical discount 
@UsedBy: Used by a VF component 'APTS_MaxCriticalDiscountComponent'
******************************************************************/



public with sharing class APTS_MaxCriticalDiscountController{

    public Apttus__APTS_Agreement__c agrmntSO {get;set;}
    
    public APTS_MaxCriticalDiscountController(){
        
    }
    
    public String getAgreementUrl() {
        String pageURL = '';
        Apttus_Proposal__ProposalSystemProperties__c proposalSystemProperties = Apttus_Proposal__ProposalSystemProperties__c.getValues('System Properties');
        if(proposalSystemProperties != null && proposalSystemProperties.Apttus_Proposal__InstanceUrl__c != null) {
            pageURL = proposalSystemProperties.Apttus_Proposal__InstanceUrl__c + '/' + agrmntSO.Id;
        }
        PageReference pageRef = new PageReference(pageURL);
        
        return pageRef.getUrl();
    }
    
    public Apttus__AgreementLineItem__c getAgreementLI(){
    
       List<Apttus__AgreementLineItem__c> listOfAgrLI = [SELECT Apttus_CMConfig__LineNumber__c,
                                                 APTS_LP_Product_Hierarchy_Code__c,
                                                 APTS_Product_Hierarchy_Information__c,
                                                 APTS_new_product_code__c,
                                                 APTS_Product_Name__c,
                                                 APTS_LP_Hierarchy_Name__c,
                                                 APTS_Product_Code__c,
                                                 APTS_Product_Description__c,
                                                 APTS_Standard_Discount_Format__c,
                                                 APTS_Quantity__c,
                                                 Apttus_CMConfig__BasePrice__c,
                                                 APTS_LP_Standard_Discount__c,
                                                 APTS_LP_Standard_Net__c,
                                                 APTS_Net_Adjustment_Percentage__c,
                                                 APTS_Discount_Type__c,
                                                 APTS_Net_Price_Override__c,
                                                 Apttus__NetPrice__c,
                                                 APTS_LP_Total_Standard_Price__c,
                                                 APTS_LP_Unit_Of_Measure__c,
                                                 APTS_LP_Unit_Of_Price__c,
                                                 APTS_Discount_Percentage__c,
                                                 Apttus_CMConfig__NetAdjustmentPercent__c,
                                                 APTS_Total_Quote_Price__c
                                                 FROM Apttus__AgreementLineItem__c
                                                 WHERE Apttus__AgreementId__c = :agrmntSO.Id 
                                                 AND 
                                                 APTS_Is_Critical_Discount__c = True];
           
           if(listOfAgrLI.size()>0){
               return listOfAgrLI.get(0);
           }
           else{
               return null;
           } 
       /*    if(null != agrLI){
               displayTable = true;
           }
           else{
               displayTable = false;
           }      */
            
                                               
    }

}