src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>APTS_LP_Account_End_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indirect customer to which the MSPA is related.</description>
        <inlineHelpText>Indirect customer to which the MSPA is related. Auto populated if MSPA created from Opportunity.</inlineHelpText>
        <label>Primary Partner Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notEqual</operation>
                <value>GIS Approved</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MSPAs (Primary Partner Customer)</relationshipLabel>
        <relationshipName>MSPAs1</relationshipName>
        <type>Lookup</type>
    </fields>
    
 <fields>
        <fullName>Apttus_Approval__Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Submitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved but Action Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deactivated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Approval__Approval_Request__c.object
<CustomObject>
    <description>Designates an approval request created from an approval process</description>
	<label>Approval Request</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Approval__ApprovalsSystemProperties__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Approvals System properties</description>
    <fields>
        <fullName>APTS_Comments_Mandatory_On_Rejection__c</fullName>
        <description>Field to display message about mandatory comments when approval is rejected.</description>
        <label>Comments Mandatory On Rejection Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Approvals System Properties</label>
</CustomObject>

src/objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
</CustomObject>

src/classes/APTS_ApprovalRequestTriggerHandlerTest.cls
/**
 * @Name : APTS_ApprovalRequestTriggerHandlerTest
 * @Author : Shalin Shah (sshah@apttus.com)
 * @CreateDate: 16th Sept 2015
 * @Description: Test class for handler class
 * @BaseClass : APTS_ApprovalRequestTriggerHandler
 */

@isTest (seealldata=false)
public with sharing class APTS_ApprovalRequestTriggerHandlerTest {
    
    static testMethod void testMethod1() {
 System.runAs(APTS_LP_TestUtility.getUser()) {
        Account acc=APTS_LP_TestUtility.getNewAccount('Apttus Inc','Spain');
        insert acc;
        
        APTS_LP_TestUtility.getDiscountConfig();
		APTS_LP_TestUtility.getCustomSetting_QuoteNProposal();
        Apttus_Proposal__Proposal__c quote=APTS_LP_TestUtility.getProposal('Apttus quote');
        quote.APTS_LP_Account_End_User__c=acc.Id;
        insert quote;

        Apttus_Approval__ApprovalsSystemProperties__c approvalSystemProperties = new Apttus_Approval__ApprovalsSystemProperties__c( name = 'System Properties');
        approvalSystemProperties.APTS_Comments_Mandatory_On_Rejection__c = 'Comments Mandatory on Rejection';
        insert approvalSystemProperties;

        Apttus_Approval__Approval_Request__c objApproval1 = new Apttus_Approval__Approval_Request__c(
                                                  Apttus_Approval__Assigned_To_Name__c = 'Test Test1',
                                                  Apttus_Approval__Assigned_To_Type__c = 'User');
        objApproval1.Apttus_Approval__Object_Type__c = 'Apttus_Proposal__Proposal__c';
        objApproval1.Apttus_Approval__Object_Id__c = quote.Id;
        insert objApproval1;
        
        objApproval1.Apttus_Approval__Approval_Status__c = 'Rejected';
        update objApproval1;

        objApproval1.Apttus_Approval__Approval_Status__c = 'Rejected';
        objApproval1.Apttus_Approval__Approver_Comments__c = 'Rejected due to high discount';
        try{
          update objApproval1;
             
      }Catch(exception ex){}
 }
    }

    static testMethod void testMethod2() {
         System.runAs(APTS_LP_TestUtility.getUser()) {
      APTS_LP_TestUtility.getDiscountConfig();
	APTS_LP_TestUtility.getCommonConfigSetting();
      Apttus__APTS_Agreement__c agreement = APTS_LP_TestUtility.getAgreement('TestAgreement');
      insert agreement;        
      
      Apttus_Approval__ApprovalsSystemProperties__c approvalSystemProperties = new Apttus_Approval__ApprovalsSystemProperties__c( name = 'System Properties');
        approvalSystemProperties.APTS_Comments_Mandatory_On_Rejection__c = 'Comments Mandatory on Rejection';
        insert approvalSystemProperties;

        Apttus_Approval__Approval_Request__c objApproval1 = new Apttus_Approval__Approval_Request__c(
                                                  Apttus_Approval__Assigned_To_Name__c = 'Test Test1',
                                                  Apttus_Approval__Assigned_To_Type__c = 'User');
        objApproval1.Apttus_Approval__Object_Type__c = 'Apttus__APTS_Agreement__c';
        objApproval1.Apttus_Approval__Object_Id__c = agreement.Id;
        insert objApproval1;
        
        objApproval1.Apttus_Approval__Approval_Status__c = 'Approved';
        update objApproval1;
         }

    }
}