src/objects/Attends_Hidden_for_Review__c.object
<CustomObject>
    <fields>
        <fullName>Visit_Report_Meeting_Minutes__c</fullName>
        <label>Visit Report Meeting Minutes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Channel_Partner_Business_Review__c</fullName>
        <label>Channel Partner Business Review</label>
        <referenceTo>Channel_Business_Review__c</referenceTo>
        <relationshipLabel>Attends Hidden for Review</relationshipLabel>
        <relationshipName>Attends_Hidden_for_Review</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Visit_Attendee_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Visit Attendee Acccount</label>
        <referenceTo>Visit_Attendee__c</referenceTo>
        <relationshipLabel>Attends Hidden for Review</relationshipLabel>
        <relationshipName>Attends_Hidden_for_Review</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Attends Hidden for Review</label>
    <nameField>
        <label>Attends Hidden for Review Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attends Hidden for Review</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Visit_Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Channel_Partner_Business_Review_ID__c</fullName>
        <formula>CASESAFEID(Visit_Report__r.Channel_Review__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Channel Partner Business Review ID</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Visit_Report__c.object
<CustomObject>
    <description>This object holds the Visit Reports which will be attached to Accounts and can be linked to Opportunities &amp; Attendees</description>
    <fields>
        <fullName>Meeting_Minutes__c</fullName>
        <label>Meeting Minutes</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Visit Report</label>
    <nameField>
        <label>Visit Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visit Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ClsTriggerVisitReportAttendeeHandler.cls
/**   
* TriggerClass on the Visit Report Attendee object
*       
* Release - R5 
 *  
 * @author  - Vasanthi (Accenture)
 * @created - 2016-03-28
 * @version - 1.0
*/
public without sharing class ClsTriggerVisitReportAttendeeHandler extends ClsTriggerVirtual {
     
    /**   
    * Constructor       
    * Release - R5 
     *  
    */    
    public ClsTriggerVisitReportAttendeeHandler  () {
    
    }

    /**   
    * bulkBefore 
    * Release - R5 
     *  
    */       
    public override void afterTrigger(ClsWrappers.TriggerContext trgCtx) {   
        
        if (trgCtx.isInsert) {                       
            copyInfo(trgCtx);
        }
        
        if (trgCtx.IsDelete) {
            deleteInfo(trgCtx);
        }
    }
   
    
    public void copyInfo(ClsWrappers.TriggerContext trgCtx) {
        
        List<Attends_Hidden_for_Review__c> tobeInsertedList = new List<Attends_Hidden_for_Review__c>();
        Map<Id, Visit_Report__c> visitReportMap = new Map<Id, Visit_Report__c>();
        Set<Id> visitReportIdSet = new Set<Id>();
        
        for (Visit_Attendee__c attendee: (List<Visit_Attendee__c>)trgCtx.newList) {
            
            if (attendee.Visit_Report__c != NULL) {
                visitReportIdSet.add(attendee.Visit_Report__c);
            }
            
        }      
        
        if (visitReportIdSet.size() > 0) {
            visitReportMap = new Map<Id, Visit_Report__c> ([SELECT Id, Meeting_Minutes__c FROM Visit_Report__c WHERE Id IN :visitReportIdSet]);
        }
        
        for (Visit_Attendee__c attendee: (List<Visit_Attendee__c>)trgCtx.newList) {            
           
            if (attendee.Channel_Partner_Business_Review_ID__c != '' && attendee.Channel_Partner_Business_Review_ID__c != NULL) {
                
                Attends_Hidden_for_Review__c rev = new Attends_Hidden_for_Review__c(Channel_Partner_Business_Review__c = attendee.Channel_Partner_Business_Review_ID__c, 
                Visit_Attendee_Account__c = attendee.Id);
                
                if (attendee.Visit_Report__c != NULL) {
                    rev.Visit_Report_Meeting_Minutes__c = visitReportMap.get(attendee.Visit_Report__c).Meeting_Minutes__c ;
                }
                
                tobeInsertedList.add (rev);
            }
        }       
         
        if (tobeInsertedList.size() > 0) insert tobeInsertedList;
    }
    
    public void deleteInfo(ClsWrappers.TriggerContext trgCtx) {
        
        Set<Id> attendeeIdSet = new Set<Id>();
        
        for (Visit_Attendee__c attendee: (List<Visit_Attendee__c>) trgCtx.oldList) {
            
            attendeeIdSet.add (attendee.Id);
        }       
        if (attendeeIdSet.size() > 0) {
            List<Attends_Hidden_for_Review__c> infoList = [ SELECT ID FROM Attends_Hidden_for_Review__c WHERE Visit_Attendee_Account__c IN :attendeeIdSet ];
            if (infoList.size() > 0) delete infoList;
        }
    }
}