src/objects/Budget__c.object
<CustomObject>
    <description>R5 - New Custom Object -Financial Target and Expectation Budgets</description>
    <fields>
        <fullName>Division__c</fullName>
        <description>R5 - Division</description>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>DM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PG</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Targets and Results</label>
    <nameField>
        <displayFormat>SalesTargets-Results{0000}</displayFormat>
        <label>Budget Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Targets and Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
<fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Record Type for Active Contact (Default)</description>
        <label>Active</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Budget__c</fullName>
        <description>Lead Qualification Field (Sales &amp; Marketing)</description>
        <inlineHelpText>Is this project officially funded? Will the opportunity be realised by the end user?</inlineHelpText>
        <label>Budget</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>This field captures the description for the inquiry</description>
        <inlineHelpText>This field captures the description for the inquiry</inlineHelpText>
        <label>Description</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>DM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PG</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Fit__c</fullName>
        <description>Lead Qualification Field (Sales &amp; Marketing)</description>
        <inlineHelpText>Is this opportunity/business attractive for ABB? Does it FIT with the strategy?</inlineHelpText>
        <label>Fit</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Interest_need__c</fullName>
        <description>Lead Qualification Field (Sales &amp; Marketing)</description>
        <inlineHelpText>What problem is the contact/organization trying to solve? Is this an official project or are they purely information gatherers?</inlineHelpText>
        <label>Interest/need</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Lead_Engagement__c</fullName>
        <description>(only for Sales &amp; Marketing)</description>
        <label>Lead Engagement</label>
        <picklist>
            <picklistValues>
                <fullName>Low</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Positioning__c</fullName>
        <description>Lead Qualification Field (Sales &amp; Marketing)</description>
        <inlineHelpText>Are we well positioned to GET (win) the opportunity or make business with the contact/organization?</inlineHelpText>
        <label>Positioning</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Purchasing_power__c</fullName>
        <description>Lead Qualification Field (Sales &amp; Marketing)</description>
        <inlineHelpText>Can the contact/organization make a purchase decision?</inlineHelpText>
        <label>Purchasing power</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>(only for Contact Centre)</description>
        <label>Subject</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Timeframe__c</fullName>
        <label>Timeframe</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>

 
 

	
   
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <formula>Product_Group__r.Division__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Division</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LeadConverCustomCon_Test.cls
@isTest
private class LeadConverCustomCon_Test {

    static testMethod void myUnitTest() {
           Profile p = [select id from profile where name='Standard User'];

         User u = new User(alias = 'standt', email='standarduser@testorg.com',

            emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',

            localesidkey='en_US', profileid = p.Id,

            timezonesidkey='America/Los_Angeles', 
            username='testUser@testleadconvert.com');
        
        DateTime d=system.now();
        Lead newLead = new Lead(
                        Company = 'Test Account', LastName= 'Test Lead',email='ishita4@abc.com',
                        LeadSource = 'Web',  
                        Status = 'Contacted',Interest_need__c='int',Lead_Engagement__c='High',
                         Purchasing_power__c='yes',Budget__c='yes',Positioning__c='yes',Fit__c='yes',
                         Timeframe__c=d.date(),Description__c='desc',subject__c='sub',division__c='PP');
     
        newLead.street='Teststr. 1';
          newLead.state='Tibet';
          newLead.country='China';
          newLead.city='Musterstadt';
      
        Insert newLead;
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(newLead);
        LeadConvertCustomCon leadController = new LeadConvertCustomCon(stdController);
        
        leadcontroller.leadReference = newLead;
        
       leadcontroller.leadReference.status='Qualified';
      leadController.taskID.Subject = 'TEST TASK';
          leadController.taskID.ActivityDate = system.today();
          leadController.taskID.isReminderSet=true;
         leadController.taskID.Subject = 'Other';
        leadController.taskID.Priority = 'High';
        leadController.taskID.Status = 'In Progress';
      leadController.selectedAccount = 'NEW';
      

        Contact contactID = leadController.contactID;
        leadController.cancelOpp = true;
        List<SelectOption> leadStatuses = leadController.LeadStatusOption;
        
        Opportunity opportunityID = leadController.opp;
        leadController.reminder = true;
        String reminderTime = leadController.reminderTime;
        List<SelectOption> timeOptions = leadController.ReminderTimeOption;
        leadController.emailChecked = true;
       List<SelectOption> priorityOptions = leadController.TaskPriorityOption;
        List<SelectOption> statusOptions = leadController.TaskStatusOption;
        System.runAs(u) {
           List<SelectOption> timeOptions2= leadController.ReminderTimeOption;
            LeadController.convertToDatetime(d.date(),'8:00 a');
         }
        leadController.convertLead();   
        leadController.PrintErrors(new List<Database.Error>());
       Account [] checkAccount = [SELECT Id FROM Account WHERE Name ='Test Account' ];
        system.debug(checkAccount);
        system.assertEquals(1, checkAccount.size(), 'There was a problem converting lead to an account');
       Contact [] checkContact = [SELECT Id FROM Contact WHERE Name ='Test Lead' ];
        system.debug(checkContact);
        system.assertEquals(1, checkContact.size(), 'There was a problem converting lead to a contact');
        
       string reminderDate = leadController.disabledActivityDate;
     
       
        // test the reminder time as a French user to test the 24 hour clock
       
        
         System.runAs(u) {
            timeOptions = leadController.ReminderTimeOption;
             LeadController.convertToDatetime(d.date(),'8:00 a');
         }
         
         leadController.selectedAccount = 'None';
         leadController.emailChecked= false;
         
         //test the situation where there is a due date but no subject
         leadController.taskID.ActivityDate = system.today();
          leadController.taskID.isReminderSet=true;
         leadController.taskID.Subject = 'Other';
         leadController.leadReference.Status = 'Qualified';
         
         //convert the lead
        System.assertequals( leadController.convertLead(),null);
         
         leadController.accountLookedUp();
         leadController.DueDateChanged();
         leadController.accountChanged();
     
    } 


}