src/objects/Capture_Team__c.object
<CustomObject>
    <description>R4V1-This object refers to data.</description>
    <fields>
        <fullName>EndUserProject_Manager__c</fullName>
        <description>R4 - End user project Manager</description>
        <formula>End_User_Project__r.Account_Manager__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>EndUserProject Manager</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndUserProject_Owner__c</fullName>
        <description>R4 - End user Project Owner field</description>
        <formula>End_User_Project__r.OwnerId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>EndUserProject Owner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_User_Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>End User Project</label>
        <referenceTo>End_User_Project__c</referenceTo>
        <relationshipLabel>Capture Teams</relationshipLabel>
        <relationshipName>Capture_Teams</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Capture Team</label>
    <nameField>
        <label>Capture Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capture Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/End_User_Project__c.object
<CustomObject>
    <description>Only the Project Owner and Account Manager should be able to change the status of the project (Not the opportunity owner)</description>
    <fields>
        <fullName>Capture_Team_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Capture Team Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Capture_Team_Status__c</fullName>
        <defaultValue>&quot;No CT Required&quot;</defaultValue>
        <label>Capture Team Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>End User Project</label>
    <nameField>
        <label>End User Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>End User Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>

 
 

	
    <fields>
        <fullName>Capture_Team_Indicator_Status__c</fullName>
        <formula>IF(OR(End_User_Project__c = NULL,Technical_Amount_USD__c &lt;= 5000000,Target__c = FALSE), &quot;No CT Required&quot;,  IF(AND( Technical_Amount_USD__c &gt; 5000000, Technical_Amount_USD__c &lt;=15000000, Target__c = TRUE , End_User_Project__r.Capture_Team_Count__c &gt; 0), &quot;CT Lite Available&quot;, IF(AND( Technical_Amount_USD__c &gt; 5000000, Technical_Amount_USD__c &lt;=15000000, Target__c = TRUE ,  End_User_Project__r.Capture_Team_Count__c = 0), &quot;CT Lite Required&quot;, IF(AND( Technical_Amount_USD__c &gt; 15000000, Target__c = TRUE ,  End_User_Project__r.Capture_Team_Count__c &gt; 0), &quot;CT Full Available&quot; ,IF(AND( Technical_Amount_USD__c &gt; 15000000, Target__c = TRUE ,  End_User_Project__r.Capture_Team_Count__c = 0), &quot;CT Full Required&quot; ,&apos;&apos;)))  ) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Capture Team Indicator Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Capture_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created as part of R5-2507. To associate the opportunity directly to the Capture Team.</description>
        <label>Capture Team</label>
        <referenceTo>Capture_Team__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
   
    <fields>
        <fullName>End_User_Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to active End User Projects only</description>
        <inlineHelpText>Please select a End User Project (mandatory for Regular Opportunities, optional for Fast Track Opportunities).
Make sure that you set the Project Site Country first as this will be a filter for the End User Projects.</inlineHelpText>
        <label>End User Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>End_User_Project__c.End_User_Project_Status__c</field>
                <operation>notEqual</operation>
                <value>Closed, Cancelled</value>
            </filterItems>
            <filterItems>
                <field>$Source.Account_End_User__c</field>
                <operation>equals</operation>
                <valueField>End_User_Project__c.Account_End_User__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.End_User_Project_Site_Country__c</field>
                <operation>equals</operation>
                <valueField>End_User_Project__c.End_User_Project_Site_Country__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>End_User_Project__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to determine whether a target has been set.</description>
        <label>Target</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Technical_Amount_USD__c</fullName>
        <description>This technical field holds the oppy amount in USD. The field is hidden for the end user.</description>
        <label>Opportunity Value USD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ClsTriggerCaptureTeamHandler.cls
/**
    @Author Rajesh K
    @name ClsTriggerCaptureTeamHandler
    @CreateDate 9/21/2015
    @Description To display Capture team count in End user project object
    @Version 1.0
    **/
public with sharing class ClsTriggerCaptureTeamHandler extends ClsTriggerVirtual {
        Set<Id> setEUPId = new Set<Id>();
        Set<Id> setEndUserProjId = new Set<Id>();
        List<Capture_Team__c> lstCT = new List<Capture_Team__c>();
        List<End_User_Project__c > lstEUP = new List<End_User_Project__c >();
        List<End_User_Project__c > lstUpdateEUP = new List<End_User_Project__c >();
        Map<Id,List<Opportunity>> mapEUPIdAndOpportunity = new Map<Id,List<Opportunity>>();
        Map<Id,List<Capture_Team__c>> mapEUPIdAndCapturTeam = new Map<Id,List<Capture_Team__c>>();
    /**
     * @see IntHelper.afterTrigger
    */
    public override void afterTrigger(ClsWrappers.TriggerContext trgCtx) {
        captureTeamCreation(trgCtx);
        captureTeamDeletion(trgCtx);
        captureTeamSharingCreation(trgCtx);
    } 
    /*  Description of the purpose of the method. 
    *  @name captureTeamSharingCreation
    *  @Description - Provide the Capture Team sharing for account manager or End user project owner .
    *  @return Nothing - 
    */
    private void captureTeamSharingCreation(ClsWrappers.TriggerContext trgCtx) {
        if(Trigger.isInsert && Trigger.isAfter){            
            List<Capture_Team__Share> lstshare = new List<Capture_Team__Share>();
            Set<String> setEmail = new Set<String>();
            Set<ID> capTeamids = new Set<ID>();
            Map<String,Id> mapUserEmail = new Map<String,Id>();
            for (sobject so : trgCtx.newList) {
                Capture_Team__c ct = (Capture_Team__c)so;
                setEmail.add(ct.EndUserProject_Manager__c);
                capTeamids.add(ct.id);
            }
            for(User objuser : [Select id,Email from User where Email IN:setEmail and isActive = true LIMIT 50000]){
                mapUserEmail.put(objuser.Email,objuser.id);
            }
            List<Capture_Team__Share> sharesCaptureTeam = [SELECT Id,UserOrGroupId,ParentId,Accesslevel,RowCause FROM Capture_Team__Share WHERE ParentId IN :capTeamids AND (RowCause =: System.label.System_CL00028 OR RowCause =: System.label.System_CL00030) LIMIT 50000];    
                        
            
            for (sobject so : trgCtx.newList) {
                Capture_Team__c capteam = (Capture_Team__c)so;
                Map<String, Schema.SObjectType> tokens = Schema.getGlobalDescribe();
                if(!tokens.containsKey(System.label.System_CL00029)){   //System_CL00029 => Capture_Team__Share
                    capteam.adderror(System.label.CL00039); //CL00039 => End User Project is not enabled as private.
                }
                Boolean checkManager = false;
                Boolean checkOwner = false;
                for(Capture_Team__Share objCTShare : sharesCaptureTeam){                            
                    if(mapUserEmail.containsKey(capteam.EndUserProject_Manager__c) && mapUserEmail.get(capteam.EndUserProject_Manager__c) == objCTShare.UserOrGroupId && capteam.id == objCTShare.ParentId){
                        checkManager = true;                                       
                    }
                    if(capteam.EndUserProject_Owner__c == objCTShare.UserOrGroupId && capteam.id == objCTShare.ParentId){
                        checkOwner = true;                                       
                    }
                }               
                if(tokens.containsKey(System.label.System_CL00038) && mapUserEmail.containsKey(capteam.EndUserProject_Manager__c) && checkManager == false) {  
                    Capture_Team__Share objCTS = new Capture_Team__Share();
                    objCTS.ParentId = capteam.Id; //System_CL00023 => ParentId  
                    objCTS.UserOrGroupId = mapUserEmail.get(capteam.EndUserProject_Manager__c);//System_CL00024 => UserOrGroupId
                    objCTS.AccessLevel = System.label.System_CL00026;//System_CL00025 => AccessLevel , System_CL00026 => 'Edit'
                    objCTS.RowCause = System.label.System_CL00028;//System_CL00027 => RowCause , System_CL00028 => 'Manual'
                    lstshare.add(objCTS);
                } 
                if(tokens.containsKey(System.label.System_CL00038) && checkOwner == false) {  
                    Capture_Team__Share objCTS = new Capture_Team__Share();
                    objCTS.ParentId = capteam.Id; //System_CL00023 => ParentId  
                    objCTS.UserOrGroupId = capteam.EndUserProject_Owner__c;//System_CL00024 => UserOrGroupId
                    objCTS.AccessLevel = System.label.System_CL00026;//System_CL00025 => AccessLevel , System_CL00026 => 'Edit'
                    objCTS.RowCause = System.label.System_CL00028;//System_CL00027 => RowCause , System_CL00028 => 'Manual'
                    lstshare.add(objCTS);
                }
            }
            if(lstshare.size()>0){
                Database.insert(lstshare);
            }  
        }
    }
   
    /*  Description of the purpose of the method. 
    *  @name captureTeamCreation
    *  @Description - Provide the Capture Team Count while create a new capture team .
    *  @return Nothing - 
    */
    @TestVisible 
    private void captureTeamCreation(ClsWrappers.TriggerContext trgCtx) {
        if(Trigger.isInsert && Trigger.isAfter){
             for(sobject objCapTeam : trgCtx.newList){
             Capture_Team__c ct = (Capture_Team__c)objCapTeam ;
             setEUPId.add(ct.End_User_Project__c);
            }
            if(setEUPId !=NUll){
                lstEUP = [SELECT Id FROM End_User_Project__c WHERE Id in: setEUPId LIMIT 10000];
                //lstCT = [SELECT Id,End_User_Project__c FROM Capture_Team__c WHERE End_User_Project__c in: setEUPId LIMIT 10000];
                for(Opportunity op : [SELECT Id,Capture_Team_Indicator_Status__c,End_User_Project__c,Target__c,Technical_Amount_USD__c FROM Opportunity  where End_User_Project__c in: setEUPId LIMIT 10000] )
                {
                    List<Opportunity> lstop = new List<Opportunity>();
                    lstop.add(op);                
                    if (mapEUPIdAndOpportunity.containsKey(op.End_User_Project__c))
                    {                    
                        mapEUPIdAndOpportunity.get(op.End_User_Project__c).add(op);
                    }
                    else
                    {
                        mapEUPIdAndOpportunity.put(op.End_User_Project__c, lstop);
                    }
                }
                
                for(Capture_Team__c cpt : [SELECT Id,End_User_Project__c FROM Capture_Team__c WHERE End_User_Project__c in: setEUPId LIMIT 10000] )
                {
                    List<Capture_Team__c> lstcpt = new List<Capture_Team__c>();
                    lstcpt.add(cpt);                
                    if (mapEUPIdAndCapturTeam.containsKey(cpt.End_User_Project__c))
                    {                    
                        mapEUPIdAndCapturTeam.get(cpt.End_User_Project__c).add(cpt);
                    }
                    else
                    {
                        mapEUPIdAndCapturTeam.put(cpt.End_User_Project__c, lstcpt);
                    }
                }
                   
            }
            if(lstEUP.size() > 0){
                     for(String endusrid : setEUPId){
                        End_User_Project__c  EUPupddate= new End_User_Project__c();
                        EUPupddate.Id=endusrid;
                        List<Capture_Team__c> lstcp = mapEUPIdAndCapturTeam.get(endusrid);
                        integer cp_count;
                        if(lstcp!=null && lstcp.size()>0)
                        { cp_count = lstcp.size(); }
                        else{ cp_count = 0;}
                        EUPupddate.Capture_Team_Count__c= cp_count;
                        String EndUsrStatus = ''; 
                        Boolean isFullRequired = False;
                        Boolean isFullAvailable = False;
                        Boolean isLiteRequired = False;
                        Boolean isLiteAvailable = False;
                        Boolean isNotRequired = False;        
                        List<Opportunity> lstopty = mapEUPIdAndOpportunity.get(endusrid);
                        if(lstopty !=null)
                        for(Opportunity opp : lstopty){
                          if(opp.Technical_Amount_USD__c <= 5000000 || opp.Target__c == FALSE)
                          { isNotRequired = True;}
                          if(opp.Technical_Amount_USD__c > 15000000 && opp.Target__c == TRUE && cp_count > 0)
                          { isFullAvailable = True;}
                          if(opp.Technical_Amount_USD__c > 15000000 && opp.Target__c == TRUE && cp_count == 0)
                          { isFullRequired = True;}
                          if(opp.Technical_Amount_USD__c <= 15000000 && opp.Target__c == TRUE && cp_count > 0 && opp.Technical_Amount_USD__c > 5000000)
                          { isLiteAvailable = True;}
                          if(opp.Technical_Amount_USD__c <= 15000000 && opp.Target__c == TRUE && cp_count == 0 && opp.Technical_Amount_USD__c > 5000000)
                          { isLiteRequired = True;}
                        }
                
                        if(isFullAvailable){
                            EndUsrStatus = 'CT Full Available';
                        }
                        else if (isFullRequired){
                            EndUsrStatus = 'CT Full Required';
                        }
                        else if (isLiteAvailable){
                            EndUsrStatus = 'CT Lite Available';
                        }
                        else if (isLiteRequired){
                            EndUsrStatus = 'CT Lite Required';
                        }
                        else if(isNotRequired){
                            EndUsrStatus = 'No CT Required';
                        }
                        else{
                            EndUsrStatus = 'No CT Required';
                        }
                                          
                        EUPupddate.Capture_Team_Status__c= EndUsrStatus;
                        lstUpdateEUP.add(EUPupddate);
                    }
            }
            if(lstUpdateEUP.size() >0){
                try {
                    Database.SaveResult[] results =  database.update(lstUpdateEUP);
                    if (results != null){
                        for (Database.SaveResult result : results) {
                            if (!result.isSuccess()) {
                                Database.Error[] errs = result.getErrors();
                                for(Database.Error err : errs)
                                    System.debug(err.getStatusCode() + ' - ' + err.getMessage());
                
                            }
                        }
                    }

                } catch (Exception e) {
                        System.debug(e.getTypeName() + ' - ' + e.getCause() + ': ' + e.getMessage());
                } 
            }
        }
    }
      
      
/*  Description of the purpose of the method. 
    *  @name captureTeamDeletion
    *  @Description - Provide the Capture Team Count while deleting capture team .
    *  @return Nothing - 
    */
    @TestVisible 
    private void captureTeamDeletion(ClsWrappers.TriggerContext trgCtx) {
        if(Trigger.isDelete && Trigger.isAfter){  
            for(sobject objCapTeam : trgCtx.oldList){
                Capture_Team__c ct = (Capture_Team__c)objCapTeam ;
                setEUPId.add(ct.End_User_Project__c);
            }
            if(setEUPId !=NUll){
                lstEUP = [SELECT Id FROM End_User_Project__c WHERE Id in: setEUPId LIMIT 10000];
                //lstCT = [SELECT Id,End_User_Project__c FROM Capture_Team__c WHERE End_User_Project__c in: setEUPId LIMIT 10000];
                System.debug('------------lstCT'+lstCT.size()+'---------------lstEUP '+lstEUP.size() );
                for(Opportunity op : [SELECT Id,Capture_Team_Indicator_Status__c,End_User_Project__c,Target__c,Technical_Amount_USD__c FROM Opportunity  where End_User_Project__c in: setEUPId LIMIT 10000] )
                {
                    List<Opportunity> lstop = new List<Opportunity>();
                    lstop.add(op);
                    
                    if (mapEUPIdAndOpportunity.containsKey(op.End_User_Project__c))
                    {                    
                        mapEUPIdAndOpportunity.get(op.End_User_Project__c).add(op);
                    }
                    else
                    {
                        mapEUPIdAndOpportunity.put(op.End_User_Project__c, lstop);
                    }
                
                }
                
                for(Capture_Team__c cpt : [SELECT Id,End_User_Project__c FROM Capture_Team__c WHERE End_User_Project__c in: setEUPId LIMIT 10000] )
                {
                    List<Capture_Team__c> lstcpt = new List<Capture_Team__c>();
                    lstcpt.add(cpt);                
                    if (mapEUPIdAndCapturTeam.containsKey(cpt.End_User_Project__c))
                    {                    
                        mapEUPIdAndCapturTeam.get(cpt.End_User_Project__c).add(cpt);
                    }
                    else
                    {
                        mapEUPIdAndCapturTeam.put(cpt.End_User_Project__c, lstcpt);
                    }
                }
                
            }
            
            if(lstEUP.size() > 0){
                for(String endusrid : setEUPId){
                    List<Capture_Team__c> lstcp = mapEUPIdAndCapturTeam.get(endusrid);
                    End_User_Project__c  EUPupddate= new End_User_Project__c();
                    EUPupddate.Id=endusrid;
                    
                    integer cp_count;
                    if(lstcp!=null && lstcp.size()>0){ 
                        cp_count = lstcp.size(); 
                    }
                    else{ 
                        cp_count = 0;
                    }
                    EUPupddate.Capture_Team_Count__c=cp_count;
                    
                    String EndUsrStatus = ''; 
                    Boolean isFullRequired = False;
                    Boolean isFullAvailable = False;
                    Boolean isLiteRequired = False;
                    Boolean isLiteAvailable = False;
                    Boolean isNotRequired = False;        
                    List<Opportunity> lstopty = mapEUPIdAndOpportunity.get(endusrid);
                if(lstopty !=null)
                for(Opportunity opp : lstopty)
                {
                      System.debug('&&&&&&&&&&&&&&'+opp.Capture_Team_Indicator_Status__c);
                      if(opp.Technical_Amount_USD__c <= 5000000 || opp.Target__c == FALSE)
                      { isNotRequired = True;}
                      if(opp.Technical_Amount_USD__c > 15000000 && opp.Target__c == TRUE && cp_count  > 0)
                      { isFullAvailable = True;}
                      if(opp.Technical_Amount_USD__c > 15000000 && opp.Target__c == TRUE && cp_count  == 0)
                      { isFullRequired = True;}
                      if(opp.Technical_Amount_USD__c <= 15000000 && opp.Target__c == TRUE && cp_count  > 0 && opp.Technical_Amount_USD__c > 5000000)
                      { isLiteAvailable = True;}
                      if(opp.Technical_Amount_USD__c <= 15000000 && opp.Target__c == TRUE && cp_count  == 0 && opp.Technical_Amount_USD__c > 5000000)
                      { isLiteRequired = True;}
                }
                
                if(isFullAvailable){
                    EndUsrStatus = 'CT Full Available';
                }
                else if (isFullRequired){
                    EndUsrStatus = 'CT Full Required';
                }
                else if (isLiteAvailable){
                    EndUsrStatus = 'CT Lite Available';
                }
                else if (isLiteRequired){
                    EndUsrStatus = 'CT Lite Required';
                }
                else if(isNotRequired){
                    EndUsrStatus = 'No CT Required';
                }
                else{
                    EndUsrStatus = 'No CT Required';
                }
                    
                    EUPupddate.Capture_Team_Status__c=EndUsrStatus;
                    lstUpdateEUP.add(EUPupddate);
                    }
                 } 
            if(lstUpdateEUP.size() >0){
                try {
                    Database.SaveResult[] results =  database.update(lstUpdateEUP);
                    if (results != null){
                        for (Database.SaveResult result : results) {
                            if (!result.isSuccess()) {
                                Database.Error[] errs = result.getErrors();
                                for(Database.Error err : errs)
                                    System.debug(err.getStatusCode() + ' - ' + err.getMessage());
                
                            }
                        }
                    }

                } catch (Exception e) {
                        System.debug(e.getTypeName() + ' - ' + e.getCause() + ': ' + e.getMessage());
                }
               
            }
            
        }
    }
}