src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <description>From Master Data Management Hierarchy</description>
        <inlineHelpText>Select the Business Unit that is responsible for resolving the case</inlineHelpText>
        <label>Business Unit</label>
        <picklist>
            <controllingField>Division__c</controllingField>
            <picklistValues>
                <fullName>DMDR - Drives and Controls</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>DMMG - Motors &amp; Generators</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>DMPC - Power Conversion</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>DMRO - Robotics</fullName>
                <color>#A845DC</color>
            </picklistValues>
            <picklistValues>
                <fullName>EPBP - Building Products</fullName>
                <color>#B6E32E</color>
            </picklistValues>
            <picklistValues>
                <fullName>EPBS - Breakers &amp; Switches</fullName>
                <color>#A53711</color>
            </picklistValues>
            <picklistValues>
                <fullName>EPCP - Control Products</fullName>
                <color>#66E9BD</color>
            </picklistValues>
            <picklistValues>
                <fullName>EPCW - Installation Products</fullName>
                <color>#641CCF</color>
            </picklistValues>
            <picklistValues>
                <fullName>EPLS - Electrification Solutions</fullName>
                <color>#419249</color>
            </picklistValues>
            <picklistValues>
                <fullName>EPMV - Medium Voltage Products</fullName>
                <color>#A845DC</color>
            </picklistValues>
            <picklistValues>
                <fullName>PACT - Control Technologies</fullName>
                <color>#2F5D85</color>
            </picklistValues>
            <picklistValues>
                <fullName>PAMA - Marine &amp; Ports</fullName>
                <color>#8F6429</color>
            </picklistValues>
            <picklistValues>
                <fullName>PAMP - Measurement &amp; Analytics</fullName>
                <color>#EFAE73</color>
            </picklistValues>
            <picklistValues>
                <fullName>PAOG - Oil, Gas &amp; Chemicals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAPG - Power Generation</fullName>
                <color>#B6E32E</color>
            </picklistValues>
            <picklistValues>
                <fullName>PAPI - Process Industries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PATU - Turbocharging</fullName>
                <color>#57F17C</color>
            </picklistValues>
            <picklistValues>
                <fullName>PGGA - Grid Automation</fullName>
                <color>#0B24BE</color>
            </picklistValues>
            <picklistValues>
                <fullName>PGGI - Grid Integration</fullName>
                <color>#641CCF</color>
            </picklistValues>
            <picklistValues>
                <fullName>PGGS - Grid Systems</fullName>
                <color>#66E9BD</color>
            </picklistValues>
            <picklistValues>
                <fullName>PGHV - High Voltage Products</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>PGTR - Transformers</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>ZCCO - Corporate</fullName>
                <color>#2F5D85</color>
            </picklistValues>
            <picklistValues>
                <fullName>ZCRE - Real Estate</fullName>
                <color>#AFCADF</color>
            </picklistValues>
            <picklistValues>
                <fullName>ZCVA - Various</fullName>
                <color>#8F6429</color>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <inlineHelpText>The city or nearest city where this site is located.</inlineHelpText>
        <label>Site City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commissioning_Date__c</fullName>
        <inlineHelpText>The date when the installation was commissioned.</inlineHelpText>
        <label>Commissioning Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>TBD 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TBD 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TBD 3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer_Warranty_enddate__c</fullName>
        <inlineHelpText>The date when the customer warranty for the Installation ends.</inlineHelpText>
        <label>Customer Warranty end date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Customer_Warranty_startdate__c</fullName>
        <inlineHelpText>The date when the customer warranty for the Installation starts.</inlineHelpText>
        <label>Customer Warranty start date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>DM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PG</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Installation_ID__c</fullName>
        <inlineHelpText>Unique identifier of the installation within ServIS. Generated automatically by ServIS.</inlineHelpText>
        <label>Installation ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Installation_status__c</fullName>
        <inlineHelpText>Installation Status (e.g. Planned, Delivered, Running).</inlineHelpText>
        <label>Installation status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Link_to_Site_Registration__c</fullName>
        <formula>HYPERLINK(&apos;https://abb.sharepoint.com/sites/ServiceMarketTransparencyPortal/_layouts/15/start.aspx#/Lists/Contacts/AllItems.aspx#InplviewHash17eb2232-e163-4e60-8bf6-081f94cb5263=FolderCTID%3D0x012001-FilterFields1%3DJobTitle-FilterValues1%3DCountry%2520Installed%2520Base%2520Manager%253B%2523Regional%2520Installed%2520Base%2520Manager-FilterOp1%3DIn&apos;, &apos;Link&apos;)</formula>
        <label>Link to Site Registration</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manufacturer__c</fullName>
        <inlineHelpText>Legacy brand. Use the naming convention &quot;brand-city country code&quot;. E.g. &quot;Westinghouse - Munice, US&quot;, &quot;ABB - Turgi, CH&quot;.</inlineHelpText>
        <label>Manufacturer</label>
        <length>2500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Manufacturing_Date__c</fullName>
        <inlineHelpText>The date when the installation was produced.</inlineHelpText>
        <label>Manufacturing Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Manufacturing_Order_Number__c</fullName>
        <inlineHelpText>The factory production order reference number for the installation.</inlineHelpText>
        <label>Manufacturing Order Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator_GUID__c</fullName>
        <label>Operator GUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator_Name__c</fullName>
        <inlineHelpText>The company operating the site. This includes name, address and GUID (reference GIS).</inlineHelpText>
        <label>Operator Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner_Type__c</fullName>
        <formula>IF(ISBLANK(Owner:User.Id),&quot;Queue&quot;,&quot;User&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Owner Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_category_ServIS__c</fullName>
        <inlineHelpText>Installation category. The keywords are defined by Div/Pgs.</inlineHelpText>
        <label>Product category ServIS</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Purchase_Order_Number__c</fullName>
        <label>Purchase Order Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Also System ID. For Warranty Claim either Serial Number or ABB Order Number must be filled. Recommended for Technical Inquiry and Product Information</inlineHelpText>
        <label>Serial Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServIS_BU__c</fullName>
        <label>ServIS BU</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServIS_Division__c</fullName>
        <label>ServIS Division</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServIS_ProductGroup__c</fullName>
        <label>ServIS ProductGroup</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Address__c</fullName>
        <inlineHelpText>Address where the site is located. In most cases equals to the postal address.</inlineHelpText>
        <label>Site Address</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Site_Country__c</fullName>
        <inlineHelpText>The name of the country where the site is located. The name represents the current official political status of the country according to ISO 3166-1 standard.</inlineHelpText>
        <label>Site Country</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antarctica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua And Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia, Plurinational State Of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonaire, Sint Eustatius And Saba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia And Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bouvet Island</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Site_Id__c</fullName>
        <description>R5 : R-2222 : To store the value of site id which is populated by ServIS</description>
        <label>Site Id</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Name__c</fullName>
        <inlineHelpText>Name of the plant/site/vessel, the &quot;nickname&quot; this plant is known by. In most cases (but not always) it consists of: (Owner name or abbr. + city + Plant Type)</inlineHelpText>
        <label>Site Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/RequestUpdateToServISClass.cls
/**
@Author Rajesh K
@name RequestUpdateToServISClass
@CreateDate 21-Jan-2015
@Version 1.0
**/
global without sharing class RequestUpdateToServISClass
{
    /*  Description of the method. 
    *  @name requestUpdatetoServis
    *  @Description - Request update to ServIS from SFDC.
    *  @return String
    */
    webservice static String requestUpdatetoServis(Id caseid) 
    {         
        //Send Additional product values into ServeIS here        
        String servisDivision;
        String servisBU;
        String servisProdCategory;
        String servisSitename;
        String servisSiteid;
        String servisInstallationid;
        String servisManufacturer;
        Date servisManufactDate;
        String servisManufactOrderNumber;
        Date servisCommissioningDate;
        String servisInstallationStatus;
        Date servisCustWarrantyStartDate;
        Date servisCustWarrantyEndDate;
        String servisWarrantyStatus;
        String servisSerialnumber;
        String servisPurchaseOrder;
        String servisOperatorGUID;
        String servisOperatorName;      
        String servisAddress;
        String servisCid;
        String servisCity;
        String servisCountry;
        String servisLatitude;
        String servisLongitude;
        String servisPG; 
        String reqPurchaseorder = '';
        String reqSerialnumber = '';       
        
        //String taskMsg = 'The following values were extracted from ServIS, but as the case has already some entries, the following values where not updated. \n';
        //Boolean loopcheck = false;
        
        Case objcase = [Select id, Link_to_Site_Registration__c, Owner_Type__c, Product.CID__c, Site_Address__c, Ownerid, City__c, ServIS_ProductGroup__c, Site_Country__c, Country__c, Division__c, Site_Geo_Location__Latitude__s, Site_Geo_Location__Longitude__s, Business_Unit__c, Product_category_ServIS__c, Site_Name__c, Site_Id__c, 
            Installation_ID__c,  Manufacturer__c, Manufacturing_Date__c, Manufacturing_Order_Number__c, Commissioning_Date__c, Installation_status__c, Customer_Warranty_startdate__c,
            Customer_Warranty_enddate__c, Serial_Number__c, Operator_GUID__c, Operator_Name__c, Purchase_Order_Number__c from Case where id =: caseid LIMIT 1];
        if(objcase.Purchase_Order_Number__c != null){
            reqPurchaseorder = objcase.Purchase_Order_Number__c;
        }
        if(objcase.Serial_Number__c != null){
            reqSerialnumber = objcase.Serial_Number__c;
        }
        User u = [select firstname, FederationIdentifier  from user where id=:userinfo.getuserid() LIMIT 1];
        HttpRequest req = new HttpRequest();
        String reqbody = System.label.INTEG_SYS_ServIS_URL1 + System.label.INTEG_SYS_ServIS_URL2 + reqPurchaseorder + System.label.INTEG_SYS_ServIS_URL3 + reqSerialnumber;
        //String reqbody = System.label.INTEG_SYS_ServIS_URL1 + u.FederationIdentifier  + System.label.INTEG_SYS_ServIS_URL2 + reqPurchaseorder + System.label.INTEG_SYS_ServIS_URL3 + reqSerialnumber;
        //String reqbody = 'https://www1008.abb.com/stage/servisws/sfdc/Search.svc/SearchInstallSerialRef?email='+ 'mariusz.stala@pl.abb.com' +'&purchaseorder='+reqPurchaseorder+'&serialNumber='+reqSerialnumber;
        req.setEndpoint(reqbody);
        req.setMethod(System.label.INTEG_SYS_SERVIS_Response_GET);    //'GET'
        String autorithationServIS = System.label.SYS_ServIS_Autorithation;
            //req.setHeader('Authorization', 'Basic ZmFjZTpXZWIkZXJ2I2ZhY2U0');
            req.setHeader('Authorization', autorithationServIS );
        Http http = new Http();
        HTTPResponse res = http.send(req);
        String status = res.getStatus(); 
        if(status.equals(System.label.INTEG_SYS_SERVIS_Response_Bad_Request)){
            return System.label.INTEG_SYS_ServIS_Return1;          //'Bad Request: Pelase check the values of [Purchase Order][Serial Number].'
        }
       System.debug('Result:'+ res.getBody());
        Map<String, Object> m = (Map<String, Object>)JSON.deserializeUntyped(res.getBody());
      // System.debug('Very first list:'+ m); 
        String result = String.valueof(m.get(System.label.INTEG_SYS_SERVIS_Response_Description));
        if(status != System.label.INTEG_SYS_SERVIS_Response_OK){
            return System.label.INTEG_SYS_ServIS_Return2 + res.getbody();  //Request error
        }else{
            if(result != System.label.INTEG_SYS_SERVIS_Response_OK){
                return System.label.INTEG_SYS_ServIS_Return2 + result;
            }else{
                List<Object> reslist = (List<Object>) m.get(System.label.INTEG_SYS_SERVIS_Response_Items);
                if(reslist.size() != 1){                    
                    if(objcase.Owner_Type__c.equals(System.label.INTEG_SYS_ServIS_User)){      //User
                        if(reslist.size() == 0){
                            Task newTask= new Task();         
                            newTask.OwnerId = objcase.Ownerid;          
                            newTask.Subject = System.label.INTEG_SYS_ServIS_Task_Subject;   //'Error while retrieving information from ServIS';      
                            newTask.Priority = System.label.INTEG_SYS_ServIS_Task_Priority;//'Normal';           
                            newTask.Status = System.label.INTEG_SYS_ServIS_Task_Status;  //'Open';          
                            newTask.Type = System.label.INTEG_SYS_ServIS_Task_Type;   //'Action';
                            newTask.Description = System.label.INTEG_SYS_ServIS_Task_Decription1 + ' ' + System.label.SYS_ServIS_SiteReg;    //'Request Error: Please correct the data and request again.\n\n ';
                            newTask.whatid = objcase.id;          
                            Database.Insert(newTask,False);                         
                            return System.label.INTEG_SYS_ServIS_Task_Return1;      //'Please correct the data and request again.'
                        }
                        if(reslist.size() > 1){
                            Task newTask= new Task();         
                            newTask.OwnerId = objcase.Ownerid;          
                            newTask.Subject = System.label.INTEG_SYS_ServIS_Task_Subject;       //'Error while retrieving information from ServIS'
                            newTask.Priority = System.label.INTEG_SYS_ServIS_Task_Priority;      //Normal      
                            newTask.Status = System.label.INTEG_SYS_ServIS_Task_Status;        //Open   
                            newTask.Type = System.label.INTEG_SYS_ServIS_Task_Type;    //Action
                            newTask.Description = System.label.INTEG_SYS_ServIS_Task_Decription2 + System.label.SYS_ServIS_SiteReg;    //'Request Error: Found Multiple entries for current Serial Number/Purchase Order.\n\n'
                            newTask.whatid = objcase.id;           
                            Database.Insert(newTask,False);                         
                            return System.label.INTEG_SYS_ServIS_Task_Return2;
                        }                        
                    }
                }
                try{
                    Map<String, Object> finalresult = new Map<String, Object>();
                    for (Object o : reslist) {
                        finalresult = (Map<String, Object>) o;
                    } 
                    servisAddress = String.valueof(finalresult.get(System.label.INTEG_SYS_SERVIS_Response_Adress));
                    servisCid = String.valueof(finalresult.get(System.label.INTEG_SYS_SERVIS_Response_Cid));
                    servisCity = String.valueof(finalresult.get(System.label.INTEG_SYS_SERVIS_Response_City));
                    servisCountry = String.valueof(finalresult.get(System.label.INTEG_SYS_SERVIS_Response_Country));
                    if(servisCountry != NULL){
                        if(servisCountry.contains('00') || servisCountry.contains('99') || servisCountry.contains('unkno')){
                            return 'No results found';
                        }
                    }
                    servisLatitude = String.valueof(finalresult.get(System.label.INTEG_SYS_SERVIS_Response_Latitude));
                    servisLongitude = String.valueof(finalresult.get(System.label.INTEG_SYS_SERVIS_Response_Longitude));
                    
                    servisPG = String.valueof(finalresult.get(System.label.INTEG_SYS_SERVIS_Response_PG));
                    servisDivision = String.valueof(finalresult.get(System.label.INTEG_SYS_SERVIS_Response_Division));
                    servisBU = String.valueof(finalresult.get(System.label.INTEG_SYS_SERVIS_Response_BU));
                    
                    servisProdCategory = String.valueof(finalresult.get(System.label.INTEG_SYS_SERVIS_Response_Category));
                    servisSitename = String.valueof(finalresult.get(System.label.INTEG_SYS_SERVIS_Response_SiteName));
                    servisSiteid = String.valueof(finalresult.get(System.label.INTEG_SYS_SERVIS_Response_SiteId));
                    servisInstallationid = String.valueof(finalresult.get(System.label.INTEG_SYS_SERVIS_Response_InstallationId));
                    servisManufacturer = String.valueof(finalresult.get(System.label.INTEG_SYS_SERVIS_Response_Manufacturer));
                    
                    String manuDate = String.valueOf(finalresult.get(System.label.INTEG_SYS_SERVIS_Response_ManufacturingDate));
                    System.debug('Test'+ manuDate);
                    if(manuDate!= 'null'){
                        servisManufactDate = dateparsing(manuDate);
                    }
                    
                    //servisManufactDate = dateparsing(String.valueof(finalresult.get(System.label.INTEG_SYS_SERVIS_Response_ManufacturingDate)));
                    servisManufactOrderNumber = String.valueof(finalresult.get(System.label.INTEG_SYS_SERVIS_Response_ManufacturingOrder));
                    
                    String comDate = String.valueOf(finalresult.get(System.label.INTEG_SYS_SERVIS_Response_ManufacturingOrder));
                    System.debug('Test'+ comDate );
                    if(comDate != 'null'){
                        servisCustWarrantyStartDate = dateparsing(comDate );
                    }
                    //servisCommissioningDate = dateparsing(String.Valueof(finalresult.get(System.label.INTEG_SYS_SERVIS_Response_CommissioningDate)));
                    servisInstallationStatus = String.valueof(finalresult.get(System.label.INTEG_SYS_SERVIS_Response_InstallationStatus));
                    
                    String warStar = String.valueOf(finalresult.get(System.label.INTEG_SYS_SERVIS_Response_WarrantyStart));
                    System.debug('Test'+ warStar );
                    if(warStar != 'null'){
                        servisCustWarrantyStartDate = dateparsing(warStar );
                    }
                    
                    String warClose = String.valueOf(finalresult.get(System.label.INTEG_SYS_SERVIS_Response_WarrantyEnd));
                    System.debug('Test'+ warClose );
                    if(warClose != 'null'){
                        servisCustWarrantyEndDate = dateparsing(warClose);
                    }
                    
                    //servisWarrantyStatus = finalresult.get('Division');
                    servisSerialnumber = String.valueof(finalresult.get(System.label.INTEG_SYS_SERVIS_Response_SerialNumber));
                    servisPurchaseOrder = String.valueof(finalresult.get(System.label.INTEG_SYS_SERVIS_Response_PurchaseOrderNumber));
                    servisOperatorGUID = String.valueof(finalresult.get(System.label.INTEG_SYS_SERVIS_Response_OperatorGuid));
                    servisOperatorName = String.valueof(finalresult.get(System.label.INTEG_SYS_SERVIS_Response_Operator));
                    Integer remLimit =  limits.getLimitQueryRows() - limits.getQueryRows();     
                    List<Product2> servISproduct = [Select id from Product2 where CID__C =:servisCid LIMIT :remLimit];
                    /*
                    Product2 updproduct = new Product2();
                    updproduct.id = objcase.Productid;
                    updproduct.CID__c = servisCid;
                    */
                    
                    Case updCase = new Case();
                    updCase.id = objcase.id;
                    updCase.Site_Address__c = servisAddress;
                    updCase.City__c = servisCity;
                    updCase.Site_Country__c = servisCountry.tolowercase().capitalize();
                    if(servisLatitude != null)
                        updCase.Site_Geo_Location__Latitude__s = Decimal.valueof(servisLatitude);
                    if(servisLongitude != null)
                        updCase.Site_Geo_Location__Longitude__s = Decimal.valueof(servisLongitude);
                    updCase.ServIS_ProductGroup__c = servisPG;
                    updCase.ServIS_Division__c= servisDivision;
                    updCase.ServIS_BU__c= servisBU;
                    updCase.Product_category_ServIS__c = servisProdCategory;
                    updCase.Site_Name__c = servisSitename;
                    updCase.Site_Id__c = servisSiteid;
                    updCase.Installation_ID__c = servisInstallationid;
                    updCase.Manufacturer__c = servisManufacturer;
                    updCase.Manufacturing_Date__c = servisManufactDate;
                    updCase.Manufacturing_Order_Number__c = servisManufactOrderNumber;
                    updCase.Commissioning_Date__c = servisCommissioningDate;
                    updCase.Installation_status__c = servisInstallationStatus;
                    updCase.Customer_Warranty_startdate__c = servisCustWarrantyStartDate;
                    updCase.Customer_Warranty_enddate__c = servisCustWarrantyEndDate;
                    updCase.Serial_Number__c = servisSerialnumber;
                    updCase.Purchase_Order_Number__c = servisPurchaseOrder;
                    updCase.Operator_GUID__c = servisOperatorGUID;
                    updCase.Operator_Name__c = servisOperatorName;
                    if(!servISproduct.isEmpty()){
                        updCase.productID = servISproduct[0].id;    
                    }
                   // System.debug('Case : '+ updCase);
                    Database.update(updCase, False);  
                    
                }Catch(Exception ex){
                    return System.label.INTEG_SYS_ServIS_Return3 + ex.getMessage() + System.label.INTEG_SYS_ServIS_Return4 + ex.getLineNumber();    //'Server Exception :'   >>> 'Line Number: '
                }
                return System.label.INTEG_SYS_ServIS_Return5;     //'Requested update has been completed successfully from ServIS.'
            }
        }
    }
    /*  Description of the method. 
    *  @name dateparsing
    *  @Description - get the value for parseddate.
    */       
    private static Date dateparsing(string strdate){
        if(strdate != null){
            List<String> dateParts = strdate.toLowerCase().replace(',','').split('-');
            System.debug('SplitDate'+ dateParts ) ;
            if(dateParts.size()>2){
                Integer month = Integer.valueof(dateParts[1]);
                Integer day = Integer.valueOf(dateParts[2]);
                Integer year = Integer.valueOf(dateParts[0]);
                Date parsedDate = Date.newInstance(year,month,day);
                return parseddate;
            }else
                return null;
        }else{
            return null;
        }
    }
}