src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <description>From Master Data Management Hierarchy</description>
        <inlineHelpText>Select the Business Unit that is responsible for resolving the case</inlineHelpText>
        <label>Business Unit</label>
        <picklist>
            <controllingField>Division__c</controllingField>
            <picklistValues>
                <fullName>DMDR - Drives and Controls</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>DMMG - Motors &amp; Generators</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>DMPC - Power Conversion</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>DMRO - Robotics</fullName>
                <color>#A845DC</color>
            </picklistValues>
            <picklistValues>
                <fullName>EPBP - Building Products</fullName>
                <color>#B6E32E</color>
            </picklistValues>
            <picklistValues>
                <fullName>EPBS - Breakers &amp; Switches</fullName>
                <color>#A53711</color>
            </picklistValues>
            <picklistValues>
                <fullName>EPCP - Control Products</fullName>
                <color>#66E9BD</color>
            </picklistValues>
            <picklistValues>
                <fullName>EPCW - Installation Products</fullName>
                <color>#641CCF</color>
            </picklistValues>
            <picklistValues>
                <fullName>EPLS - Electrification Solutions</fullName>
                <color>#419249</color>
            </picklistValues>
            <picklistValues>
                <fullName>EPMV - Medium Voltage Products</fullName>
                <color>#A845DC</color>
            </picklistValues>
            <picklistValues>
                <fullName>PACT - Control Technologies</fullName>
                <color>#2F5D85</color>
            </picklistValues>
            <picklistValues>
                <fullName>PAMA - Marine &amp; Ports</fullName>
                <color>#8F6429</color>
            </picklistValues>
            <picklistValues>
                <fullName>PAMP - Measurement &amp; Analytics</fullName>
                <color>#EFAE73</color>
            </picklistValues>
            <picklistValues>
                <fullName>PAOG - Oil, Gas &amp; Chemicals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAPG - Power Generation</fullName>
                <color>#B6E32E</color>
            </picklistValues>
            <picklistValues>
                <fullName>PAPI - Process Industries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PATU - Turbocharging</fullName>
                <color>#57F17C</color>
            </picklistValues>
            <picklistValues>
                <fullName>PGGA - Grid Automation</fullName>
                <color>#0B24BE</color>
            </picklistValues>
            <picklistValues>
                <fullName>PGGI - Grid Integration</fullName>
                <color>#641CCF</color>
            </picklistValues>
            <picklistValues>
                <fullName>PGGS - Grid Systems</fullName>
                <color>#66E9BD</color>
            </picklistValues>
            <picklistValues>
                <fullName>PGHV - High Voltage Products</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>PGTR - Transformers</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>ZCCO - Corporate</fullName>
                <color>#2F5D85</color>
            </picklistValues>
            <picklistValues>
                <fullName>ZCRE - Real Estate</fullName>
                <color>#AFCADF</color>
            </picklistValues>
            <picklistValues>
                <fullName>ZCVA - Various</fullName>
                <color>#8F6429</color>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>TBD 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TBD 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TBD 3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>DM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PG</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Email_To_Case_Recipient__c</fullName>
        <description>Integration Workstream : R5 : R-2661</description>
        <label>Email To Case Recipient</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Originating_Country__c</fullName>
        <description>Use the related Account Country, if not sure.</description>
        <inlineHelpText>Select the country where the case was raised</inlineHelpText>
        <label>Originating Country</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aland Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antarctica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua And Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia, Plurinational State Of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonaire, Sint Eustatius And Saba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia And Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Routing_Email__c.object
<CustomObject>
    <description>Integration Workstream : R5: R-2678</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antarctica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua And Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia, Plurinational State Of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonaire, Sint Eustatius And Saba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia And Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bouvet Island</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <description>Integration Workstream : R5 : R-2678</description>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>PG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Routing Email</label>
    <nameField>
        <displayFormat>RE-{00}</displayFormat>
        <label>Routing Email Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Routing Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ClsTriggerEmailMessageHandler.cls
/**
 * Trigger handler class for Case which does following actions
 * - 1. TBD
 * - 2. insert, undelete, update TargetGroupShare.
 *
 * @author Nikhil Pimpale
 * @created 16 Dec 2015
 * @version 1.0
 * @since 35.0
 *   
 * @changelog
 * 
 */
 public class ClsTriggerEmailMessageHandler  extends ClsTriggerVirtual {
 private Map<String,List<Case>> toAddressMap = new Map<String,List<Case>>();
 private Map<String,List<Case>> multipleToAddressMap = new Map<String,List<Case>>();
 private Set<Id> caseSet = new Set<Id>();
 private Map<Id,EmailMessage> emailMessageMap = new Map<Id,EmailMessage>();
 private Map<Id,Case> detailCaseMap = new Map<Id,Case>();
 private Map<Id,Case> caseUpdateMap = new Map<Id,Case>();
 private Map<Id,Case> singleMatchMap = new Map<Id,Case>();
 private Map<Id,Task> taskUpdateMap = new Map<Id,Task>();
 public Map<Id,EmailMessage> activityMap = new Map<Id,EmailMessage>();
 private Map<Id,Routing_Email__c> detailRoutingEmailMap = new Map<Id,Routing_Email__c> ();
 private Map<Id,Task> detailTaskMap = new Map<Id,Task>();
 
     public override void beforeTrigger(ClsWrappers.TriggerContext trgCtx) {
         lookupRoutingEmail(trgCtx);
     }
     public override void afterTrigger(ClsWrappers.TriggerContext trgCtx) {
         closeRelatedTask(trgCtx);
     }
     @TestVisible
     private void lookupRoutingEmail(ClsWrappers.TriggerContext trgCtx){
        try
        {   
            if (trgCtx.isBefore && trgCtx.isInsert)
            {
                 for(sobject so : trgCtx.newList)
                 {
                     EmailMessage eMessage = (EmailMessage)so;
                     if(eMessage.ParentId!= null && eMessage.ToAddress != null && eMessage.Incoming)
                     {
                         emailMessageMap.put(eMessage.Id,eMessage);
                         caseSet.add(eMessage.ParentId);
                     }
                 }
                 if(caseSet.size() > 0)
                 {
                     detailCaseMap = new Map<Id,Case>([Select Id,Status,SuppliedEmail,Origin,Email_To_Case_Recipient__c,Originating_Country__c,
                                                                    Division__c,Business_Unit__c,Product_Group__c,OwnerId From Case Where Id IN:caseSet limit 10000]);
                                      
                 }
                 if(!emailMessageMap.isEmpty() && !detailCaseMap.isEmpty())
                 {
                     for(EmailMessage eMessage : emailMessageMap.values()) 
                     {
                        if(detailCaseMap.containskey(eMessage.ParentId) && detailCaseMap.get(eMessage.ParentId).Status == System.label.Trigger_Email_Message_Status_New
                           && detailCaseMap.get(eMessage.ParentId).SuppliedEmail != null && detailCaseMap.get(eMessage.ParentId).Origin== System.label.Trigger_Email_Origin_Email
                           && detailCaseMap.get(eMessage.ParentId).Email_To_Case_Recipient__c == null)
                        {
                            
                            if(eMessage.ToAddress.contains(System.label.System_CL00046))//System_CL00046 --> ';'
                            {
                                String[] temp = eMessage.ToAddress.split('\\;');   
                                for(String t:temp)
                                {
                                    t = t.trim();
                                    System.debug('Email'+t);
                                    if(multipleToAddressMap.containskey(t))
                                    {
                                        multipleToAddressMap.get(t).add(detailCaseMap.get(eMessage.ParentId));
                                    }
                                    else
                                    {
                                       multipleToAddressMap.put(t, new List<Case> { detailCaseMap.get(eMessage.ParentId) });
                                    }
                                }
                                
                            }
                            else
                            {
                                detailCaseMap.get(eMessage.ParentId).Email_To_Case_Recipient__c = eMessage.ToAddress;
                                detailCaseMap.get(eMessage.ParentId).Originating_Country__c = null;
                                caseUpdateMap.put(eMessage.ParentId,detailCaseMap.get(eMessage.ParentId));
                                if(toAddressMap.containskey(eMessage.ToAddress))
                                {
                                    toAddressMap.get(eMessage.ToAddress).add(detailCaseMap.get(eMessage.ParentId));
                                }
                                else
                                {
                                   toAddressMap.put(eMessage.ToAddress, new List<Case> { detailCaseMap.get(eMessage.ParentId) });
                                }
                            }
                        }
                    
                     }
                 }
                 if(!toAddressMap.isEmpty() || !multipleToAddressMap.isEmpty())
                 {
                     System.debug('multipleToAddressMap.keyset()'+multipleToAddressMap.keyset());
                     detailRoutingEmailMap = new Map<Id,Routing_Email__c>([Select Id,Business_Unit__c,Division__c,Product_Group__c,Routing_Email_Address__c,Country__c From Routing_Email__c Where Routing_Email_Address__c IN :toAddressMap.keyset()
                                                                           OR Routing_Email_Address__c IN :multipleToAddressMap.keyset() ORDER BY Routing_Email_Address__c ASC limit 10000]);
                 }
                 if(!detailRoutingEmailMap.isEmpty())
                 {
                     for(Routing_Email__c emailAddress: detailRoutingEmailMap.values())
                     {
                         if(multipleToAddressMap.containskey(emailAddress.Routing_Email_Address__c))
                         {
                             list<Case> tempCase = multipleToAddressMap.get(emailAddress.Routing_Email_Address__c);
                             for(Case caseVar:tempCase)
                             {
                                 if(singleMatchMap.containskey(caseVar.Id))
                                 {
                                     break;
                                 }
                                 else
                                 {
                                     if(emailAddress.Division__c != null)
                                     {
                                     caseVar.Division__c = emailAddress.Division__c;
                                     caseVar.Business_Unit__c = emailAddress.Business_Unit__c;
                                     caseVar.Product_Group__c = emailAddress.Product_Group__c;
                                     }
                                     caseVar.Email_To_Case_Recipient__c = emailAddress.Routing_Email_Address__c;
                                     if(emailAddress.Country__c != null)
                                     {
                                         caseVar.Originating_Country__c = emailAddress.Country__c;
                                     }
                                     
                                     singleMatchMap.put(caseVar.Id,caseVar);
                                 }
                             }
                         }
                         if(toAddressMap.containskey(emailAddress.Routing_Email_Address__c))
                         {
                             list<Case> tempCase = toAddressMap.get(emailAddress.Routing_Email_Address__c);
                             for(Case caseVar:tempCase)
                             {
                                     if(emailAddress.Division__c != null)
                                     {
                                     caseVar.Division__c = emailAddress.Division__c;
                                     caseVar.Business_Unit__c = emailAddress.Business_Unit__c;
                                     caseVar.Product_Group__c = emailAddress.Product_Group__c;
                                     }
                                     caseVar.Email_To_Case_Recipient__c = emailAddress.Routing_Email_Address__c;
                                     if(emailAddress.Country__c != null)
                                     {
                                         caseVar.Originating_Country__c = emailAddress.Country__c;
                                     }
                                     caseUpdateMap.put(caseVar.Id,caseVar);
                             }
                         }
                     }
                 }
                 if(!singleMatchMap.isEmpty())
                 {
                     caseUpdateMap.putAll(singleMatchMap);
                 }
                 if(!caseUpdateMap.isEmpty())
                 {
                     Database.update(caseUpdateMap.values());
                 }    
            }
        }
        catch(ClsTriggerException cte)
        {
            System.debug('Message: ' + cte.getMessage()); 
        }
        
    }
    @TestVisible
     private void closeRelatedTask(ClsWrappers.TriggerContext trgCtx){
        try
        {
            if (trgCtx.isAfter && trgCtx.isInsert)
            {
                for(sobject so : trgCtx.newList)
                {
                        EmailMessage eMessage = (EmailMessage)so;
                        if(eMessage.ParentId!= null && eMessage.ToAddress != null && eMessage.Incoming && eMessage.ActivityId != null)
                        {
                            caseSet.add(eMessage.ParentId);
                             activityMap.put(eMessage.ActivityId,eMessage);
                        }
                }
                if(caseSet.size() > 0)
                {
                     detailCaseMap = new Map<Id,Case>([Select Id,Status,SuppliedEmail,Origin,Email_To_Case_Recipient__c,
                                                                    Division__c,Business_Unit__c,Product_Group__c,OwnerId From Case Where Id IN:caseSet limit 10000]);
                                      
                } 
                if(!activityMap.isEmpty() && !detailCaseMap.isEmpty())
                {
                    detailTaskMap = new Map<Id,Task>([select Status,Id From Task where Id IN :activityMap.keyset() limit 10000]);
                }
                if(!detailTaskMap.isEmpty())
                {
                    for(Task tsk :detailTaskMap.values())
                    {
                        String tempOwner = detailCaseMap.get(activityMap.get(tsk.Id).ParentId).OwnerId;
                        if(tempOwner.startsWith(System.label.System_Task_Owner_Prefix))
                        {
                            tsk.Status = System.label.Actions_Status_Completed; //Actions_Status_Completed --> 'Completed'
                            taskUpdateMap.put(tsk.Id,tsk);
                        }
                        else
                        {
                            continue;
                        }
                    }
                    if(!taskUpdateMap.isEmpty())
                    {
                        Database.update(taskUpdateMap.values());
                    }
                }
            }
            
        }
        catch(ClsTriggerException cte)
        {
            System.debug('Message: ' + cte.getMessage()); 
        }  
     }
 }