src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <description>From Master Data Management Hierarchy</description>
        <inlineHelpText>Select the Business Unit that is responsible for resolving the case</inlineHelpText>
        <label>Business Unit</label>
        <picklist>
            <controllingField>Division__c</controllingField>
            <picklistValues>
                <fullName>DMDR - Drives and Controls</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>DMMG - Motors &amp; Generators</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>DMPC - Power Conversion</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>DMRO - Robotics</fullName>
                <color>#A845DC</color>
            </picklistValues>
            <picklistValues>
                <fullName>EPBP - Building Products</fullName>
                <color>#B6E32E</color>
            </picklistValues>
            <picklistValues>
                <fullName>EPBS - Breakers &amp; Switches</fullName>
                <color>#A53711</color>
            </picklistValues>
            <picklistValues>
                <fullName>EPCP - Control Products</fullName>
                <color>#66E9BD</color>
            </picklistValues>
            <picklistValues>
                <fullName>EPCW - Installation Products</fullName>
                <color>#641CCF</color>
            </picklistValues>
            <picklistValues>
                <fullName>EPLS - Electrification Solutions</fullName>
                <color>#419249</color>
            </picklistValues>
            <picklistValues>
                <fullName>EPMV - Medium Voltage Products</fullName>
                <color>#A845DC</color>
            </picklistValues>
            <picklistValues>
                <fullName>PACT - Control Technologies</fullName>
                <color>#2F5D85</color>
            </picklistValues>
            <picklistValues>
                <fullName>PAMA - Marine &amp; Ports</fullName>
                <color>#8F6429</color>
            </picklistValues>
            <picklistValues>
                <fullName>PAMP - Measurement &amp; Analytics</fullName>
                <color>#EFAE73</color>
            </picklistValues>
            <picklistValues>
                <fullName>PAOG - Oil, Gas &amp; Chemicals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAPG - Power Generation</fullName>
                <color>#B6E32E</color>
            </picklistValues>
            <picklistValues>
                <fullName>PAPI - Process Industries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PATU - Turbocharging</fullName>
                <color>#57F17C</color>
            </picklistValues>
            <picklistValues>
                <fullName>PGGA - Grid Automation</fullName>
                <color>#0B24BE</color>
            </picklistValues>
            <picklistValues>
                <fullName>PGGI - Grid Integration</fullName>
                <color>#641CCF</color>
            </picklistValues>
            <picklistValues>
                <fullName>PGGS - Grid Systems</fullName>
                <color>#66E9BD</color>
            </picklistValues>
            <picklistValues>
                <fullName>PGHV - High Voltage Products</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>PGTR - Transformers</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>ZCCO - Corporate</fullName>
                <color>#2F5D85</color>
            </picklistValues>
            <picklistValues>
                <fullName>ZCRE - Real Estate</fullName>
                <color>#AFCADF</color>
            </picklistValues>
            <picklistValues>
                <fullName>ZCVA - Various</fullName>
                <color>#8F6429</color>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_BU__c.object
<CustomObject>
    <description>R5 - User who has read and edit access to a case will be able to create a Case Business Unit Detail record related to that Case using the related list &quot;Case Business Unit Details&quot; on the Case page. User will be able to create multiple Case Business Unit detail record per case only if all those records are created for a unique BU Specific recordtype. If a user tries to create a Case Business Unit detail record for the same recordtype the system will display an error message.</description>
    <fields>
        <fullName>Case__c</fullName>
        <description>Master-Detail Relationship to case object</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Case</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Case Business Unit Specifics</label>
    <nameField>
        <displayFormat>CBU-{0000}</displayFormat>
        <label>Case BU Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Business Unit Specifics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CheckCaseBusinessUnitDetailClass.cls
/*  Description of the method. 
    *  @name CheckCaseBusinessUnitDetailClass
    *  @Author  Rajesh Kaliyaperumal
    *  @Description - validate when create new case Business Unit detail.
    *  @return nothing
    */
global without sharing class CheckCaseBusinessUnitDetailClass{

/*  Description of the method. 
*  @name checkCaseBU
*  @Description - validate when create new case Business Unit detail.
*  @return String
*/
webservice static String checkCaseBU(Id caseid){ 
         String caseBusinessUnit;   
        Case objcase = [Select id,Business_Unit__c from Case where id=:caseid LIMIT 1];
        if(objcase.Business_Unit__c.equals(System.label.INTEG_SYS_Case_BU_EPBP_Full)){
            caseBusinessUnit = System.label.INTEG_SYS_Case_BU_EPBP;
        }else if(objcase.Business_Unit__c.equals(System.label.INTEG_SYS_Case_BU_EPCP_Full)){
            caseBusinessUnit = System.label.INTEG_SYS_Case_BU_EPCP;
        }else if(objcase.Business_Unit__c.equals(System.label.INTEG_SYS_Case_BU_DMMG_Full)){
            caseBusinessUnit = System.label.INTEG_SYS_Case_BU_DMMG;
        }else if(objcase.Business_Unit__c.equals(System.label.INTEG_SYS_Case_BU_DMDR_Full)){
            caseBusinessUnit = System.label.INTEG_SYS_Case_BU_DMDR;
        }else if(objcase.Business_Unit__c.equals(System.label.INTEG_SYS_Case_BU_DMPC_Full)){
            caseBusinessUnit = System.label.INTEG_SYS_Case_BU_DMPC;
        }else if(objcase.Business_Unit__c.equals(System.label.INTEG_SYS_Case_BU_PACT_Full)){
            caseBusinessUnit = System.label.INTEG_SYS_Case_BU_PACT;
        }else if(objcase.Business_Unit__c.equals(System.label.INTEG_SYS_Case_BU_PAMP_Full)){
            caseBusinessUnit = System.label.INTEG_SYS_Case_BU_PAMP;
        }else if(objcase.Business_Unit__c.equals(System.label.INTEG_SYS_Case_BU_PAOG_Full)){
            caseBusinessUnit = System.label.INTEG_SYS_Case_BU_PAOG;
        }else if(objcase.Business_Unit__c.equals(System.label.INTEG_SYS_Case_BU_PAPI_Full)){
            caseBusinessUnit = System.label.INTEG_SYS_Case_BU_PAPI;
        }else if(objcase.Business_Unit__c.equals(System.label.INTEG_SYS_Case_BU_EPMV_Full)){
            caseBusinessUnit = System.label.INTEG_SYS_Case_BU_EPMV;
        }else if(objcase.Business_Unit__c.equals(System.label.INTEG_SYS_Case_BU_PGGS_Full)){
            caseBusinessUnit = System.label.INTEG_SYS_Case_BU_PGGS;
        }else if(objcase.Business_Unit__c.equals(System.label.INTEG_SYS_Case_BU_PGGI_Full)){
            caseBusinessUnit = System.label.INTEG_SYS_Case_BU_PGGI; 
        }else if(objcase.Business_Unit__c.equals(System.label.INTEG_SYS_Case_BU_PGGA_Full)){
            caseBusinessUnit = System.label.INTEG_SYS_Case_BU_PGGA;
        }
        else{
            return System.label.INTEG_SYS_Case_BU_Return_NoBusinessUnit;
        }
        Boolean ischeck = false;
        for(Case_BU__c objcaseBU : [Select Recordtype.name from Case_BU__c where case__c =: caseid LIMIT 10000]){
            if(caseBusinessUnit == objcaseBU.recordtype.Name){
                ischeck = true;
                break;
            }
            else
            {
                continue;
            }
        }
        if(ischeck==true){
            return System.label.INTEG_SYS_Case_BU_Return_BUisThere;
        }
        return System.label.INTEG_SYS_Case_BU_Return_Yes;
    }    
}