src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <description>From Master Data Management Hierarchy</description>
        <inlineHelpText>Select the Business Unit that is responsible for resolving the case</inlineHelpText>
        <label>Business Unit</label>
        <picklist>
            <controllingField>Division__c</controllingField>
            <picklistValues>
                <fullName>DMDR - Drives and Controls</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>DMMG - Motors &amp; Generators</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>DMPC - Power Conversion</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>DMRO - Robotics</fullName>
                <color>#A845DC</color>
            </picklistValues>
            <picklistValues>
                <fullName>EPBP - Building Products</fullName>
                <color>#B6E32E</color>
            </picklistValues>
            <picklistValues>
                <fullName>EPBS - Breakers &amp; Switches</fullName>
                <color>#A53711</color>
            </picklistValues>
            <picklistValues>
                <fullName>EPCP - Control Products</fullName>
                <color>#66E9BD</color>
            </picklistValues>
            <picklistValues>
                <fullName>EPCW - Installation Products</fullName>
                <color>#641CCF</color>
            </picklistValues>
            <picklistValues>
                <fullName>EPLS - Electrification Solutions</fullName>
                <color>#419249</color>
            </picklistValues>
            <picklistValues>
                <fullName>EPMV - Medium Voltage Products</fullName>
                <color>#A845DC</color>
            </picklistValues>
            <picklistValues>
                <fullName>PACT - Control Technologies</fullName>
                <color>#2F5D85</color>
            </picklistValues>
            <picklistValues>
                <fullName>PAMA - Marine &amp; Ports</fullName>
                <color>#8F6429</color>
            </picklistValues>
            <picklistValues>
                <fullName>PAMP - Measurement &amp; Analytics</fullName>
                <color>#EFAE73</color>
            </picklistValues>
            <picklistValues>
                <fullName>PAOG - Oil, Gas &amp; Chemicals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAPG - Power Generation</fullName>
                <color>#B6E32E</color>
            </picklistValues>
            <picklistValues>
                <fullName>PAPI - Process Industries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PATU - Turbocharging</fullName>
                <color>#57F17C</color>
            </picklistValues>
            <picklistValues>
                <fullName>PGGA - Grid Automation</fullName>
                <color>#0B24BE</color>
            </picklistValues>
            <picklistValues>
                <fullName>PGGI - Grid Integration</fullName>
                <color>#641CCF</color>
            </picklistValues>
            <picklistValues>
                <fullName>PGGS - Grid Systems</fullName>
                <color>#66E9BD</color>
            </picklistValues>
            <picklistValues>
                <fullName>PGHV - High Voltage Products</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>PGTR - Transformers</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>ZCCO - Corporate</fullName>
                <color>#2F5D85</color>
            </picklistValues>
            <picklistValues>
                <fullName>ZCRE - Real Estate</fullName>
                <color>#AFCADF</color>
            </picklistValues>
            <picklistValues>
                <fullName>ZCVA - Various</fullName>
                <color>#8F6429</color>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CCRP_Status__c</fullName>
        <description>Integration Workstream : R5 : R-2190</description>
        <label>CCRP Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_2__c</fullName>
        <label>Case Type</label>
        <picklist>
            <controllingField>Category__c</controllingField>
            <picklistValues>
                <fullName>Homologation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Requirement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Factory Acceptance Test</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HelpDesk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complaints</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Details</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Originating_Country__c</fullName>
        <description>Use the related Account Country, if not sure.</description>
        <inlineHelpText>Select the country where the case was raised</inlineHelpText>
        <label>Originating Country</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aland Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antarctica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua And Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia, Plurinational State Of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonaire, Sint Eustatius And Saba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia And Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Costa Rica</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Email_Opt_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Updated for User Story R-2314 in ABB DOC:
https://abb--doc.cs18.my.salesforce.com/a0E1100000HuT09</description>
        <inlineHelpText>Do not send e-mail to this contact.</inlineHelpText>
        <label>Email Opt Out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Preferred_Contact_Method__c</fullName>
        <label>Preferred Contact Method</label>
        <picklist>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fax</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Do Not Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Validation_Override__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This setting allows user to be excluded from validation rules and triggers</description>
    <fields>
        <fullName>Exclude__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If this field is set to true, the validation will not be applicable for the user</description>
        <inlineHelpText>If this field is set to true, the validation will not be applicable for the user</inlineHelpText>
        <label>Exclude</label>
        <type>Checkbox</type>
    </fields>
    <label>Validation Override</label>
</CustomObject>

src/classes/ClsTriggerCaseHandler_Test.cls
/**
*  This test class used to test class ClsTriggerCaseHandler.
*
@author Jinbo Shan
@created 2015-03-12
@version 1.0   
@since 30.0
*
@changelog
* coverage 88% 
* 
* 
2015-03-12 Jinbo Shan <jinbo.shan@itbconsult.com>
* - Created
*/
@isTest
private class ClsTriggerCaseHandler_Test {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        
        RecordType rt = [select Id from RecordType where SObjectType = 'Case' limit 1];
        User u = [select Id from User where Id = : UserInfo.getUserId()];
        Validation_Override__c valiOver;
        for(Validation_Override__c vo : [select SetupOwnerId, Exclude__c from Validation_Override__c where SetupOwnerId = : u.Id and Name = 'Validation Override (User)']) {
            valiOver = vo;
        }
        if(valiOver == null) {
            valiOver = new Validation_Override__c();
            valiOver.SetupOwnerId = u.Id;
            valiOver.Exclude__c = true;
            valiOver.Name = 'Validation Override (User)';
            insert valiOver;
        }
        
        system.runAs(u){
            Account acc = ClsTestHelp.createTestAccounts();
            acc.Name = 'sdosetsss';
            insert acc;
            
            AccountTeamMember am = new AccountTeamMember();
            am.UserId = UserInfo.getUserId();
            am.AccountId = acc.Id;
            am.TeamMemberRole = 'Account Manager';
            insert am;
            

            
            Contact con = ClsTestHelp.createTestContacts();
            con.LastName = 'ddsssdd';
            con.AccountId = acc.Id;
            con.Email_Opt_Out__c = false;
            con.Preferred_Contact_Method__c = 'Email';
            insert con;
            
          /* Case c = new Case();
            c.RecordTypeId = rt.Id;
            c.ContactId = con.Id;
            c.AccountId = acc.Id;
            insert c;*/
            
            
            Case c = new Case();
            C.subject = 'TestCase 1';
            C.status ='Open';
            C.type='Mechanical';
            C.reason='Installation';
            C.Business_unit__c ='EPCP - Control Products';
            C.contactid=con.id;
            C.RecordTypeId = rt.ID;
            C.Originating_Country__c = 'Bangladesh';
            c.Category_2__c ='Complaints';
            c.CCRP_Status__c =null;
            c.Description = 'sai213';
            C.SuppliedEmail='abc@abc.com';    
            C.accountid=acc.id;
            c.OwnerID =  u.id;
            Insert c;
            
          /*  Case c1 = new Case();
            c1.RecordTypeId = rt.Id;
            c1.ParentId = c.Id;
            c1.Status = 'Closed';   
            c1.ContactId = con.Id;
            insert c1;
            
            Case c2 = new Case();
            c2.RecordTypeId = rt.Id;
            c2.ParentId = c.Id;
            c2.Status = 'Closed';
            c2.ContactId = con.Id;
            c2.Originating_Country__c = 'Costa Rica';
            insert c2;*/

            Date sDate = Date.today();
            Date eDate = sDate.addDays(2);
            Entitlement e = new Entitlement();
            e.Name = 'Entitlement: P&G';
            e.StartDate = sDate;
            e.EndDate = eDate;
            e.AccountId = acc.Id;
            insert e;
            
           /* Case c3 = new Case();
            c3.RecordTypeId = rt.Id;
            c3.ParentId = c.Id;
            c3.Status = 'Closed';
            c3.ContactId = con.Id;
            c3.AccountId = acc.Id;
            insert c3;*/
            Case c3 = new Case();
            C3.subject = 'TestCase 1';
            C3.status ='Open';
            C3.type='Mechanical';
            C3.reason='Installation';
            C3.Business_unit__c ='EPCP - Control Products';
            C3.contactid=con.id;
            C3.RecordTypeId = rt.ID;
            C3.Originating_Country__c = 'Bangladesh';
            c3.Category_2__c ='Complaints';
            c3.CCRP_Status__c =null;
            c3.Description = 'sai213';
            C3.SuppliedEmail='abc@abc.com';    
            C3.accountid=acc.id;
            c3.OwnerID =  u.id;
            Insert c3;
        Test.startTest();    
            Account accc = ClsTestHelp.createTestAccounts();
            accc.Name = 'sxsxsssdosetsssss';
            insert accc;
            
            Contact conn = ClsTestHelp.createTestContacts();
            conn.LastName = 'xsssxddsssdd';
            conn.AccountId = accc.Id;
            conn.Email_Opt_Out__c = false;
            conn.Preferred_Contact_Method__c = 'Email';
            insert conn;
            
            Entitlement ee = new Entitlement();
            ee.Name = 'xEntitlement: P&Gx';
            ee.StartDate = sDate;
            ee.EndDate = eDate;
            ee.AccountId = accc.Id;
            insert ee;
            
            EntitlementContact ecc = new EntitlementContact();
            ecc.ContactId = conn.Id;
            ecc.EntitlementId = ee.Id;
            insert ecc;
            
            
            /*Case c4 = new Case();
            c4.RecordTypeId = rt.Id;
            c4.ParentId = c.Id;
            c4.Status = 'Closed';
            c4.ContactId = conn.Id;
            c4.AccountId = accc.Id;
            insert c4;*/
            
            Case c4 = new Case();
            C4.subject = 'TestCase 1';
            C4.status ='Open';
            C4.type='Mechanical';
            C4.reason='Installation';
            C4.Business_unit__c ='EPCP - Control Products';
            C4.contactid=con.id;
            C4.RecordTypeId = rt.ID;
            C4.Originating_Country__c = 'Bangladesh';
            c4.Category_2__c ='Complaints';
            c4.CCRP_Status__c =null;
            c4.Description = 'sai213';
            C4.SuppliedEmail='abc@abc.com';    
            C4.accountid=acc.id;
            c4.OwnerID =  u.id;
            Insert c4;
            
            //c.Status = 'Closed';
           // update c;
            Test.stopTest();
        }
    }
    
    static testMethod void myUnitTest1() {
        // TO DO: implement unit test
        
        RecordType rt = [select Id from RecordType where SObjectType = 'Case' limit 1];
        Id EXtNonBuyingID = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get('External Non-Buying Account').getRecordTypeId();
    Test.startTest();    
        Account acc = ClsTestHelp.createTestAccounts();
        acc.Name = 'jintestssssdds';
        acc.RecordTypeId = EXtNonBuyingID;
        insert acc;
        
        Contact con = ClsTestHelp.createTestContacts();
        con.LastName = 'ddsssdd';
        con.AccountId = acc.Id;
        con.Email_Opt_Out__c = false;
        con.Preferred_Contact_Method__c = 'Email';
        insert con;
        
        User u = ClsTestHelp.createTestUsers();
        u.Username = 'jinbo.shan@itbconsultds.comssdftest';
        insert u;
        
        AccountTeamMember atm = new AccountTeamMember();
        atm.AccountId = acc.Id;
        atm.UserId = u.Id;
        insert atm;
        
        Account acc1 = ClsTestHelp.createTestAccounts();
        acc1.Name = 'jinbotestsdds';
        insert acc1;
        
        AccountTeamMember atm1 = new AccountTeamMember();
        atm1.AccountId = acc1.Id;
        atm1.UserId = u.Id;
        insert atm1;
        
            Case c = new Case();
            C.subject = 'TestCase 1';
            C.status ='Open';
            C.type='Mechanical';
            C.reason='Installation';
            C.Business_unit__c ='EPCP - Control Products';
            C.contactid=con.id;
            C.RecordTypeId = rt.ID;
            C.Originating_Country__c = 'Bangladesh';
            c.Category_2__c ='Complaints';
            c.CCRP_Status__c =null;
            c.Description = 'sai213';
            C.SuppliedEmail='abc@abc.com';    
            C.accountid=acc.id;
            c.OwnerID =  u.id;
            Insert c;            
            
            Case c3 = new Case();
            c3.parentId = c.Id;
            C3.subject = 'TestCase 1';
            C3.status ='Open';
            C3.type='Mechanical';
            C3.reason='Installation';
            C3.Business_unit__c ='EPCP - Control Products';
            C3.contactid=con.id;
            C3.RecordTypeId = rt.ID;
            C3.Originating_Country__c = 'Bangladesh';
            c3.Category_2__c ='Complaints';
            c3.CCRP_Status__c =null;
            c3.Description = 'sai213';
            C3.SuppliedEmail='abc@abc.com';    
            C3.accountid=acc.id;
            //c3.OwnerID =  u.id;
            Insert c3;
            
        Test.stopTest();
    }
 
}