src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>HYPERLINK(AccountId,Account_Name_Formula__c)</formula>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Support Type</label>
        <picklist>
            <picklistValues>
                <fullName>Pre Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Sales</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>TBD 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TBD 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TBD 3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>DM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PG</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Originating_Country__c</fullName>
        <description>Use the related Account Country, if not sure.</description>
        <inlineHelpText>Select the country where the case was raised</inlineHelpText>
        <label>Originating Country</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aland Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antarctica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua And Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia, Plurinational State Of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonaire, Sint Eustatius And Saba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia And Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Italy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spain</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Preferred_Language__c</fullName>
        <label>Preferred Language</label>
        <picklist>
            <picklistValues>
                <fullName>(Afan) Oromo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abkhazian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Afar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Afrikaans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Akan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albanian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amharic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arabic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aragonese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assamese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avaric</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avestan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aymara</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijani</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bambara</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bashkir</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Basque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarusian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bengali; Bangla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bihari</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bislama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bokmål, Norwegian; Norwegian Bokmål</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazilian Portuguese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Breton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulgarian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burmese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cambodian (Central Khmer)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Catalan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>English</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>This field is used to define if the contact is external or internal (ie. ABB). Contacts are generally external. However, there could be valid reasons to add an internal contact.</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Internal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Record Type for Active Contact (Default)</description>
        <label>Active</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ERP_Reference_Data__c.object
<CustomObject>
    <description>R3v1 - This custom object holds LSO Reference Data for Accounts.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R3v1 - Custom Lookup field to Account object to display the account reference in LSO Reference Data.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>LSO_Reference_Datas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aland Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antarctica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia, Plurinational State of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia and Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Italy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spain</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LBU__c</fullName>
        <description>R3 -LBU</description>
        <label>LBU</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LSO_ERP_Mapping_Value__c</fullName>
        <description>R3 - Text field to hold the value of LSO from ERP Mapping table</description>
        <label>LSO</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LSO__c</fullName>
        <description>R3 - LSO</description>
        <label>LSO</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Local Reference Data</label>
    <nameField>
        <displayFormat>ERP-REF-DATA-{0000}</displayFormat>
        <label>LSO Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Local Reference Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
<fields>
        <fullName>Default_BU__c</fullName>
        <description>R4 - Default BU</description>
        <label>Default LBU</label>
        <length>100</length>
        <type>Text</type>
    </fields>
<fields>
        <fullName>Default_LSO__c</fullName>
        <description>R4 - Default LSO</description>
        <label>Default LSO</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/ClsBatch_LSOUpdateOnCase_Test.cls
/**
*  This test class used to test the batch class 
*  ClsBatch_LSOUpdateOnCase 
*
@author Shankar Anand
@created 2015-10-16
@version 1.0   

* coverage 90% 
*/


@istest(SeeAllData = False)
public class ClsBatch_LSOUpdateOnCase_Test{

static testMethod void  methodTest(){
 
    RecordType enb = [SELECT Id, DeveloperName, SobjectType FROM RecordType WHERE SobjectType = 'Account' and DeveloperName = 'External_Non_Buying_Account'];  
    RecordType ga = [SELECT Id, DeveloperName, SobjectType FROM RecordType WHERE SobjectType = 'Account' and DeveloperName = 'GIS_Approved'];
 
       
    Account eu = new Account();
    eu.Name = '2168 AccountCase1';
    eu.BillingCountry = 'India';
    eu.BillingStreet = 'TestStreet123';
    eu.BillingCity = 'Chennai';
    //eu.RecordtypeId = enb.id;
    insert eu;
    
    Contact con = new Contact();
    con.firstname = 'John';
    con.lastname = 'Doe';
    con.email = 'abcd@xyz.com';
    con.accountId = eu.Id;
    con.Type__c = 'External';
    con.Preferred_Language__c = 'English';
    insert con;
    
   
    ERP_Reference_Data__c LSOeu1 = new ERP_Reference_Data__c();        
    LSOeu1.Account__c = eu.id;
    LSOeu1.Country__c = 'Italy';                       
    LSOeu1.LSO_ERP_Mapping_Value__c = 'LSO-LSO Description';
    LSOeu1.LSO__c = 'LSOac1'; 
    LSOeu1.LBU__c = 'LBUac1';
    insert LSOeu1;
    
    ERP_Reference_Data__c LSOeu2 = new ERP_Reference_Data__c();        
    LSOeu2.Account__c = eu.id;
    LSOeu2.Country__c = 'Spain';                       
    LSOeu2.LSO_ERP_Mapping_Value__c = 'LSO-LSO Description';
    LSOeu2.LSO__c = 'LSOeu2'; 
    LSOeu2.LBU__c = 'LBUeu2';
    insert LSOeu2;
    
    
  
    Profile up = [Select Id, Name from Profile where profile.name = 'ABB Sales Standard Profile' Limit 1];
    User u = new User();
    u.firstname = '2168';
    u.lastname = 'Test user2168';
    u.Username ='test@xyzdg.com';
    u.Alias = 'tester';
    u.CommunityNickname = 'tester';
    u.TimeZoneSidKey ='Europe/London';
    u.LocaleSidKey ='en_US';
    u.EmailEncodingKey ='ISO-8859-1';
    u.LanguageLocaleKey ='en_US';
    u.email = 'abc@xyz.com';
    u.profileid = up.id;
    u.isActive = true;
    u.Default_BU__c = 'LBUac1';
    u.Default_LSO__c ='LSOac1';
    insert u;
    
    Case o1 = new Case();
    o1.ownerid = u.id;
    o1.AccountId = eu.id;
    o1.Subject = 'TESTLSOAutomation';
    o1.Originating_Country__c = 'Albania';
    o1.Division__c = 'PS';
    o1.Description = 'Testing';
    o1.Category__c = 'Pre Sales';
    o1.Status= 'New';
    o1.contactId = con.id;
    insert o1;
    
    Test.startTest();
        ClsBatch_LSOUpdateOnCase b = new ClsBatch_LSOUpdateOnCase();
        database.executeBatch(b);
    Test.stopTest();
    
    Case cs = [Select Id,Account_LSO_Case__c from Case where Subject = 'TESTLSOAutomation' Limit 1];
    System.assertEquals(LSOeu1.Id,cs.Account_LSO_Case__c);
    
}

static testMethod void  methodTest1(){
 
    RecordType enb = [SELECT Id, DeveloperName, SobjectType FROM RecordType WHERE SobjectType = 'Account' and DeveloperName = 'External_Non_Buying_Account'];  
    RecordType ga = [SELECT Id, DeveloperName, SobjectType FROM RecordType WHERE SobjectType = 'Account' and DeveloperName = 'GIS_Approved'];
    
    Account eu2 = new Account();
    eu2.Name = '2168 AccountCase2';
    eu2.BillingCountry = 'India';
    eu2.BillingStreet = 'Street1234';
    eu2.BillingCity = 'Kolkata';
    //eu2.RecordtypeId = enb.id;
    insert eu2;
    
    Contact con = new Contact();
    con.firstname = 'John';
    con.lastname = 'Doe';
    con.email = 'abcd@xyz.com';
    con.accountId = eu2.Id;
    con.Type__c = 'External';
    con.Preferred_Language__c = 'English';
    insert con;
    
    ERP_Reference_Data__c LSOeu3 = new ERP_Reference_Data__c();        
    LSOeu3.Account__c = eu2.id;
    LSOeu3.Country__c = 'Spain';                       
    LSOeu3.LSO_ERP_Mapping_Value__c = 'LSO-LSO Description';
    LSOeu3.LSO__c = 'LSOac1'; 
    insert LSOeu3;
  
    Profile up = [Select Id, Name from Profile where profile.name = 'ABB Sales Standard Profile' Limit 1];
    User u = new User();
    u.firstname = '2168';
    u.lastname = 'Test user2168';
    u.Username ='test@xyzdg.com';
    u.Alias = 'tester';
    u.CommunityNickname = 'tester';
    u.TimeZoneSidKey ='Europe/London';
    u.LocaleSidKey ='en_US';
    u.EmailEncodingKey ='ISO-8859-1';
    u.LanguageLocaleKey ='en_US';
    u.email = 'abc@xyz.com';
    u.profileid = up.id;
    u.isActive = true;
    u.Default_LSO__c ='LSOac1';
    insert u;
    
    Case o1 = new Case();
    o1.ownerid = u.id;
    o1.AccountId = eu2.id;
    o1.Subject = 'TESTLSOAutomation';
    o1.Originating_Country__c = 'Albania';
    o1.Division__c = 'PS';
    o1.Description = 'Testing';
    o1.Category__c = 'Pre Sales';
    o1.Status= 'New';
    o1.contactId = con.id;
    insert o1;
    
    
    
    Test.startTest();
        ClsBatch_LSOUpdateOnCase b2 = new ClsBatch_LSOUpdateOnCase();
        database.executeBatch(b2);
    Test.stopTest();
    
    Case cs2 = [Select Id,Account_LSO_Case__c from Case where Subject = 'TESTLSOAutomation' Limit 1];
    System.assertEquals(LSOeu3.Id,cs2.Account_LSO_Case__c); 
}
}