src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <inlineHelpText>The city or nearest city where this site is located.</inlineHelpText>
        <label>Site City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Reference__c</fullName>
        <inlineHelpText>Reference or case number / identifier from customer’s system.</inlineHelpText>
        <label>Customer Reference</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Request_site__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Request site</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_category_ServIS__c</fullName>
        <inlineHelpText>Installation category. The keywords are defined by Div/Pgs.</inlineHelpText>
        <label>Product category ServIS</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Also System ID. For Warranty Claim either Serial Number or ABB Order Number must be filled. Recommended for Technical Inquiry and Product Information</inlineHelpText>
        <label>Serial Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Address__c</fullName>
        <inlineHelpText>Address where the site is located. In most cases equals to the postal address.</inlineHelpText>
        <label>Site Address</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Site_Country__c</fullName>
        <inlineHelpText>The name of the country where the site is located. The name represents the current official political status of the country according to ISO 3166-1 standard.</inlineHelpText>
        <label>Site Country</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antarctica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua And Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia, Plurinational State Of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonaire, Sint Eustatius And Saba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia And Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bouvet Island</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Site_Id__c</fullName>
        <description>R5 : R-2222 : To store the value of site id which is populated by ServIS</description>
        <label>Site Id</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Name__c</fullName>
        <inlineHelpText>Name of the plant/site/vessel, the &quot;nickname&quot; this plant is known by. In most cases (but not always) it consists of: (Owner name or abbr. + city + Plant Type)</inlineHelpText>
        <label>Site Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/RequestSiteCreationServISClass.cls
/**
@Author Rajesh K
@name RequestSiteCreationServISClass
@CreateDate 17-Feb-2015
@Version 1.0
**/
global without sharing class RequestSiteCreationServISClass
{
    /*  Description of the method. 
    *  @name requestSiteCreate
    *  @Description - Request site creation in ServIS from SFDC.
    *  @return String
    */
    webservice static String requestSiteCreate(Id caseid) 
    { 
        Case objcase = [Select id, City__c, Site_Address__c, Site_Country__c, Site_Geo_Location__Latitude__s, Site_Geo_Location__Longitude__s, Serial_Number__c, Product_category_ServIS__c, Product.CID__c, Site_Id__c, Site_Name__c, Customer_Reference__c from Case where id =: caseid LIMIT 1];
        if(objcase.Product_category_ServIS__c !=NULL){
            HttpRequest req = new HttpRequest();
            req.setEndpoint(System.label.INTEG_SYS_ReqSiteCreation_Endpoint);   //'https://www1008.abb.com/stage/servisws/mcp/ProductRegistration.svc/RegisterAsUnathorized'
            req.setMethod(System.label.INTEG_SYS_ReqSiteCreation_Method);    //'POST'
            String autorithationServIS = System.label.SYS_ServIS_Autorithation;
            //req.setHeader('Authorization', 'Basic ZmFjZTpXZWIkZXJ2I2ZhY2U0');
            req.setHeader('Authorization', autorithationServIS );
            //String strbody = 'email='+ UserInfo.getUserEmail() +'&serialNumber='+objcase.Serial_Number__c+'&category='+objcase.Product_category_ServIS__c;
            User u = [select firstname, FederationIdentifier  from user where id=:userinfo.getuserid() LIMIT 1];
            String strbody = System.label.INTEG_SYS_ReqSiteCreation_Body1 + u.FederationIdentifier  + System.label.INTEG_SYS_ReqSiteCreation_Body2 + objcase.Serial_Number__c + System.label.INTEG_SYS_ReqSiteCreation_Body3 + objcase.Product_category_ServIS__c;    //INTEG_SYS_ReqSiteCreation_Body1 => 'email=' => '&serialNumber=' => '&category='
            strbody = strbody + System.label.INTEG_SYS_ReqSiteCreation_Body4 + objcase.Product.CID__c;      // =>'&cid='
            strbody = strbody + System.label.INTEG_SYS_ReqSiteCreation_Body5 + objcase.City__c + System.label.INTEG_SYS_ReqSiteCreation_Body6;  //>'&siteComment=&siteCity=' >'&siteZipCode='
            strbody = strbody + System.label.INTEG_SYS_ReqSiteCreation_Body9 + objcase.Site_Address__c + System.label.INTEG_SYS_ReqSiteCreation_Body10 + objcase.Site_Country__c;    //>>>'&siteRegion=&siteAddress='  >>'&siteCountry='
            strbody = strbody + System.label.INTEG_SYS_ReqSiteCreation_Body11+ objcase.Site_Name__c + System.label.INTEG_SYS_ReqSiteCreation_Body12;    //>>'&siteName='    >>'&siteType=&format=JSON&lang=EN'
            req.setBody(strbody);  
            Http http = new Http();
            HTTPResponse res = http.send(req);
            Map<String, object> m = (Map<String, object>)JSON.deserializeUntyped(res.getBody());
            String status = res.getStatus();
            String result = String.valueof(m.get(System.label.INTEG_SYS_ReqSiteCreation_Description));    //'Description'
            if(result != System.label.INTEG_SYS_ReqSiteCreation_OK){                //'OK'
                return result;    //'ServIS response: '
            }else{      
                Case updcase = new Case(id = caseid,Is_Request_site__c = true);
                Database.update(updcase, false);
                return System.label.INTEG_SYS_ReqSiteCreation_Return2;    //'Request Site Creation to ServIS has been completed.';   
            }
        return res.getStatus();
        }else{
            return System.label.INTEG_SYS_ReqSiteCreation_Return3;  //'Product Category ServIS is required, please provide it';
        }
        
    }    
}