src/objects/Channel_Business_Review__c.object
<CustomObject>
    <description>R5 Channel Business Review is a custom object to review the Channels, Partner, ABB Authorized value provider &amp; Strategic / Key Partner  who will be partnering with ABB to do business.</description>
    <label>Channel Partner Business Review</label>
    <nameField>
        <label>Business Review Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partner Business Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <!--validationRules>
        <fullName>CBR_Validate_Required_Fields</fullName>
        <active>false</active>
        <description>R5 - Validation rule to check all the checkbox fields need to be filled out</description>
        <errorConditionFormula>OR(Sales_Answer_1__c = FALSE, Actions_Answer_1__c= FALSE, Partner_Answer_1__c=FALSE,ISBLANK(Sales_Answer_2__c),ISBLANK(Actions_Answer_2__c))</errorConditionFormula>
        <errorMessage>Cannot save the changes. Please fill the required fields.</errorMessage>
    </validationRules-->
</CustomObject>

src/objects/Channel_Business_Review_Market_Trend__c.object
<CustomObject>
    <description>R5-Custom object to define Channel Business Review Market Trend</description>
    <fields>
        <fullName>Channel_Business_Review__c</fullName>
        <description>R5 Master relation ship Channel Business Review</description>
        <label>Channel Business Review</label>
        <referenceTo>Channel_Business_Review__c</referenceTo>
        <relationshipName>Channel_Business_Review_Market_Trends</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Feedback__c</fullName>
        <description>R5-Picklist contains Feedback values</description>
        <label>Feedback</label>
        <picklist>
            <picklistValues>
                <fullName>Negative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Slightly Negative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stable/ OK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Slightly Positive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Positive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Known</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Focussed_Industry__c</fullName>
        <description>R5 - Picklist contains Focussed Industry Values</description>
        <label>Focused Industry</label>
        <picklist>
            <picklistValues>
                <fullName>Building - Residential Buildings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building - Commercial &amp; institutional Buildings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building - Industrial Buildings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Automotive - Automotive (Vehicles - OEM)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Automotive - Automotives (Parts - Tier1)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Chemical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Petrochemicals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Food and Beverage - Ingredients</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Food and Beverage - Sugar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Food and Beverage - Bakery &amp; Confectionery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Food and Beverage - Fruit &amp; Vegetables</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Food and Beverage - Dairy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Food and Beverage - Meat, Poultry, Seafood</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Food and Beverage - Beverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Food and Beverage - Other Food &amp; Beverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Printing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Textile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Metals - Aluminium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Metals - Steel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Metals - Other Metals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Electronics and Semiconductors (3C)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Mining and Minerals - Underground Mining including Hoisting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Mining and Minerals - Open Pit Mining</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Mining and Minerals - Grinding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Mining and Minerals - Mineral Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Cement and Glass - Cement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Cement and Glass - Glass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Oil and Gas Industry -Oil and Gas - Offshore Upstream</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Oil and Gas Industry -Oil and Gas - Onshore Upstream</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry - Oil and Gas Industry - Refining</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>R5 - Notes</description>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Market trend detail</label>
    <nameField>
        <displayFormat>MARKET TREND - {0000}</displayFormat>
        <label>Market Trend Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market trend details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ClsMarketTrendList.cls
/**   
* Apex Class : ClsMarketTrendList
* VF Page    : MarketTrendList
* Controller for MarketTrendList - Enable Inline Editing
* Release R5
*
*/
public with sharing class ClsMarketTrendList{

    public List<Channel_Business_Review_Market_Trend__c> CMSProdLineItems {get;set;}
    public String parentId;
/**   
* Constructor : ClsMarketTrendList
*
*/    
    public ClsMarketTrendList(ApexPages.StandardController controller) {
        
        //Channel_Business_Review_Market_Trend__c ChanMarktScope = (Channel_Business_Review_Market_Trend__c)controller.getRecord();         
        parentId = apexpages.currentpage().getparameters().get(Label.ApexClass_id);           
        
        CMSProdLineItems =[SELECT Id, Name, Channel_Business_Review__c, Feedback__c, Focussed_Industry__c, Notes__c
                           FROM Channel_Business_Review_Market_Trend__c 
                           WHERE Channel_Business_Review__c = :parentId limit 1000];
            
    }
/**   
* Method Save
*
*/     
    public PageReference save() {
        
        try {
            Database.update(CMSProdLineItems);
        } Catch(DMLEXception e) {           
            string error = '';
            for (Integer i = 0; i < e.getNumDML(); i++) {
                error += e.getDMLMessage(i)+Label.Line_Break;
            }
            apexPages.addMessage(new ApexPages.message(ApexPages.severity.Error,error));
            return null;
        }
        
        PageReference pageRef = new PageReference(Label.System_CL00020+parentId);
        return pageRef;        
    }
/**   
* Method Save.
* returns to the previous page
*/     
    public PageReference cancel() {
        PageReference pageRef = new PageReference(Label.System_CL00020+parentId);
        return pageRef;  
    }

}