src/objects/Channel_Market_Coverage__c.object
<CustomObject>
    <description>R5 - Custom Object to define Channel Market Coverage</description>
    <!--fields>
        <fullName>Focussed_Industry1__c</fullName>
        <description>R5 - New Focussed Industry value -Combination of Industry usage level1, level2 and level3</description>
        <inlineHelpText>Pick all the industries currently served and targeted in the upcoming 3 years. Pick only industries with sales focus, not the ones that are served reactively.</inlineHelpText>
        <label>Focussed Industry</label>
        <picklist>
            <picklistValues>
                <fullName>BLD - BLD.8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BLD - BLD.9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BLD - BLD.10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.1 - IND.1.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.1 - IND.1.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.7 - IND.7.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.7 - IND.7.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.7 - IND.7.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.10 - IND.10.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.10 - IND.10.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.10 - IND.10.4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.10 - IND.10.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.11 - IND.11.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.11 - IND.11.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.12 - IND.12.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.12 - IND.12.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.12 - IND.12.3</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields-->
    <fields>
        <fullName>Primary_Channel_Class__c</fullName>
        <description>R5-Picklist contains Primary Channel Class values</description>
        <inlineHelpText>Select the primary channel class for this market scope</inlineHelpText>
        <label>Channel Class</label>
        <picklist>
            <picklistValues>
                <fullName>Engineering, Procurement and Construction (EPC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distributor (DIS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installer (INST)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Original Equipment Manufacturer (OEM)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panel Builder (PBL)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Provider (SPRO)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System Integrator (SYIN)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Distributor (TDIS)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Targeted_AVP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>R5-Checkbox for Targeted AVP</description>
        <inlineHelpText>Mark if the partner is planned to become an AVP in the upcoming 0-2 years. Affects the templates and functionalities.</inlineHelpText>
        <label>Targeted AVP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Targeted_Key_Strategic__c</fullName>
        <defaultValue>false</defaultValue>
        <description>R5-Checkbox for Targeted Key Strategic</description>
        <inlineHelpText>Mark if the partner is targeting to become key or strategic partner in the upcoming 0-2 years. Affects the templates and functionalities.</inlineHelpText>
        <label>Targeted Strategic / Key Partner</label>
        <type>Checkbox</type>
    </fields>
    <label>Channel Partner Market Scope</label>
    <nameField>
        <label>Market Scope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partner Market Scope</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <!--webLinks>
        <fullName>Change_Product_Line</fullName>
        <availability>online</availability>
        <description>R5 - Change the Product through PIS Tree</description>
        <displayType>button</displayType>
        <height>600</height>
        <linkType>page</linkType>
        <masterLabel>Change Product Line</masterLabel>
        <openType>sidebar</openType>
        <page>EditChannelMarketPIS</page>
        <protected>false</protected>
    </webLinks-->
</CustomObject>

src/objects/Joint_Business_Plan__c.object
<CustomObject>
    <description>R5 Joint Business Plan</description>
    <fields>
        <fullName>Channel_Market_Coverage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R5 - Lookup to Channel Market Coverage</description>
        <inlineHelpText>Channel &quot;Market scope&quot; this business plan is related to</inlineHelpText>
        <label>Market Scope</label>
        <referenceTo>Channel_Market_Coverage__c</referenceTo>
        <relationshipLabel>Channel Partner Business Plans</relationshipLabel>
        <relationshipName>Joint_Business_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Channel_Class__c</fullName>
        <description>R5 - Primary Channel Class</description>
        <formula>TEXT(Channel_Market_Coverage__r.Primary_Channel_Class__c )</formula>
        <inlineHelpText>Presents the channel class defined in &quot;Market scope&quot; where possible update must be done.</inlineHelpText>
        <label>Channel Class</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Targeted_AVP__c</fullName>
        <description>R5 - Targeted AVP</description>
        <formula>Channel_Market_Coverage__r.Targeted_AVP__c</formula>
        <inlineHelpText>Checked if indicated as such in &quot;Market Scope&quot;. Update only from &quot;Market Scope&quot; view.</inlineHelpText>
        <label>Targeted AVP</label>
        <type>Checkbox</type>
    </fields>
    <label>Channel Partner Business Plan</label>
    <nameField>
        <label>Business Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partner Business Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/JointBusinessPlanRecordTypeController.cls
/**
 * TriggerClass -  Based on the answers provided on the Channel Market Coverage, user will be automatically directed to the corresponding record type. 
 * Controller for Vf pgae - JBPRecordTypePage
 *  Release R5
 * @author  Ayiravalli Arasu (Accenture)
 * @created 2016-1-04
 * @version 1.0
 * Created
 */
public with sharing class JointBusinessPlanRecordTypeController
{
    
    public Id abbBasicAdminProfileId = NULL;
/**
 * redirect method 
 * Based on the answers provided on the Channel Market Coverage, user will be automatically directed to the corresponding record type. 
 * 
 */     
    public PageReference redirect(){
         Integer remLimit =  limits.getLimitQueryRows() - limits.getQueryRows();
         Channel_Market_Coverage__c ChanMarkCov=[select id, Primary_Channel_Class__c, Targeted_AVP__c, Targeted_Key_Strategic__c from Channel_Market_Coverage__c 
                  where id=:ApexPages.currentPage().getParameters().get(Label.ApexClass_id) LIMIT :remLimit];
         Map<String, Schema.RecordTypeInfo> JBP_RECORD_TYPES = Schema.SObjectType.Joint_Business_Plan__c.getRecordTypeInfosByName();
         Profile[] basicProf = [ SELECT ID, Name FROM Profile WHERE Name = :system.label.ABB_Basic_Admin_Profile_Name LIMIT :remLimit];
         abbBasicAdminProfileId = (basicProf != NULL && basicProf.size() > 0) ? basicProf[0].Id : NULL; 
          
         //System.debug('-----------------'+JBP_RECORD_TYPES);
       /*  
        1  Distributor as partner 
        2   Distributor as strategic/key partner 
        3   Distributor as AVP 
        4   Technical channel as partner 
        5   Technical channel as key/strategic partner or AVP 
      */   
                 
         String JBP_DistAsPartner_RECORD_TYPE_ID = JBP_RECORD_TYPES.get(Label.JBP_RecordType_Name1).getRecordTypeId(); // JBP_RecordType_Name1 => 1. Distributor as Partner
         String JBP_DistAsStraKeyPartner_RECORD_TYPE_ID = JBP_RECORD_TYPES.get(Label.JBP_RecordType_Name2).getRecordTypeId(); // JBP_RecordType_Name2 => 2. Distributor as Strategic/Key Partner
         String JBP_DistAsAVP_RECORD_TYPE_ID = JBP_RECORD_TYPES.get(Label.JBP_RecordType_Name3).getRecordTypeId(); // JBP_RecordType_Name3 => 3. Distributor as AVP
         String JBP_TechAsPartner_RECORD_TYPE_ID = JBP_RECORD_TYPES.get(Label.JBP_RecordType_Name4).getRecordTypeId(); // JBP_RecordType_Name4 => 4. Technical Channel as Partner
         String JBP_TechKeyStraPartner_RECORD_TYPE_ID = JBP_RECORD_TYPES.get(Label.JBP_RecordType_Name5).getRecordTypeId(); // JBP_RecordType_Name5 => 5. Technical Channel as Key/Strategic Partner or AVP

         
         String strAccountId = System.currentPageReference().getParameters().get(Label.System_ID_Account);       
         Id userProfileId = Userinfo.getProfileid();
         Id currUser = UserInfo.getUserId();
         Set<ID> setAccTeamUserIds = new Set<ID>(); 
         
         if (strAccountId != NULL) { 
                
                Id accOwnerID;
                Id accID = ID.valueOf(strAccountId.trim());           
                
                Account[] accList = [ SELECT Id, OwnerID FROM Account WHERE Id =: accID LIMIT :remLimit];
                
                if (accList != NULL && accList.size() > 0) accOwnerID = accList[0].OwnerId;
                   
                for(AccountTeamMember atm : [SELECT id, UserId, AccountId, Account.OwnerID FROM AccountTeamMember where AccountId =: accID LIMIT :remLimit]){
                    setAccTeamUserIds.add(atm.userId);
                } 
                        
              
                if(accID != NULL && (setAccTeamUserIds == NULL || (setAccTeamUserIds != NULL && !setAccTeamUserIds.contains(currUser))) && currUser != accOwnerID && abbBasicAdminProfileId != userProfileId ){
                   apexPages.addMessage(new ApexPages.message(ApexPages.severity.Error,System.label.System_CL00102));
                   return null;
                }  
         } 
         
             PageReference pReference = null;
             String strObject = System.currentPageReference().getParameters().get(Label.System_Object); // Label.System_Object => Object
             Schema.Sobjecttype oGenericObj = Schema.getGlobalDescribe().get(strObject); 
             pReference = new PageReference(Label.System_CL00020 + oGenericObj.getDescribe().getKeyPrefix() + Label.System_CL00112); 
             
             Map<String, String> m = pReference.getParameters();      
                if(oGenericObj != null){                
                    PageReference pEditReference = new PageReference(Label.System_CL00020 +  oGenericObj.getDescribe().getKeyPrefix() + Label.System_CL00112);  // Label.System_CL00112 =>  /e         
                    m.putAll(StaticFunctions.createLabelParameters(pEditReference, oGenericObj.newSObject()));
                    m.put(Label.System_Nooverride, Label.System_CL00114);           
                    m.put(Label.System_CL00045, ApexPages.currentPage().getParameters().get(Label.System_CL00045));         
                }
                           
                if(ChanMarkCov.Targeted_AVP__c== TRUE ){
                    if(ChanMarkCov.Primary_Channel_Class__c == Label.CMS_Primary_Channel_Class_Value){    // CMS_Primary_Channel_Class_Value => Distributor (DIS)
                        m.put(Label.Business_RecordType, JBP_DistAsAVP_RECORD_TYPE_ID);
                        pReference.setRedirect(false);
                        return pReference;
                    }else if(ChanMarkCov.Primary_Channel_Class__c != Label.CMS_Primary_Channel_Class_Value){
                        m.put(Label.Business_RecordType, JBP_TechKeyStraPartner_RECORD_TYPE_ID);
                        pReference.setRedirect(false);
                        return pReference; 
                    }else{}
                }else if(ChanMarkCov.Targeted_AVP__c== FALSE ){
                    if(ChanMarkCov.Primary_Channel_Class__c == Label.CMS_Primary_Channel_Class_Value && ChanMarkCov.Targeted_Key_Strategic__c== TRUE){
                        m.put(Label.Business_RecordType, JBP_DistAsStraKeyPartner_RECORD_TYPE_ID);
                        pReference.setRedirect(false);
                        return pReference; 
                    }else if(ChanMarkCov.Primary_Channel_Class__c == Label.CMS_Primary_Channel_Class_Value && ChanMarkCov.Targeted_Key_Strategic__c== FALSE){
                        //System.debug('---------- distributor as partner-----------');
                        m.put(Label.Business_RecordType, JBP_DistAsPartner_RECORD_TYPE_ID);  //System.debug('test');
                        pReference.setRedirect(false);
                        return pReference; 
                    }else if(ChanMarkCov.Primary_Channel_Class__c != Label.CMS_Primary_Channel_Class_Value){
                        if(ChanMarkCov.Targeted_Key_Strategic__c==TRUE){
                            m.put(Label.Business_RecordType, JBP_TechKeyStraPartner_RECORD_TYPE_ID);
                            pReference.setRedirect(false);
                            return pReference;
                        }else{
                            m.put(Label.Business_RecordType, JBP_TechAsPartner_RECORD_TYPE_ID); //Label.Business_RecordType => RecordType
                            pReference.setRedirect(false);
                            return pReference;
                        }
                    }else{}
                }else{
                    return null;
                }
            
            return null;
    }
}