src/objects/Channel_Business_Review__c.object
<CustomObject>
    <description>R5 Channel Business Review is a custom object to review the Channels, Partner, ABB Authorized value provider &amp; Strategic / Key Partner  who will be partnering with ABB to do business.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R5 - Channel review to have a look-up relationship with the Account Object.</description>
        <inlineHelpText>The partner and business plan this review covers. If the scope is several branch offices, that need to be indicated in general comments below.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Channel_Business_Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Actual_Sales_Year_to_Date__c</fullName>
        <description>R5- Copy the value from the Channel Business Plan</description>
        <formula>Joint_Business_Plan__r.Actual_Sales_Year_to_Date_Formula__c</formula>
        <label>Actual Sales Year to Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Budget_Current_Year__c</fullName>
        <description>R5 - Budget Current Year copy from the channel business plan</description>
        <formula>Joint_Business_Plan__r.Budget_Current_Year_formula__c</formula>
        <label>Budget Current Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Joint_Business_Plan__c</fullName>
        <description>R5-Channel review to have a look-up relationship with the Joint Business Plan Object.</description>
        <inlineHelpText>The partner business plan this review covers. If the scope is several branch offices, that need to be indicated in general comments below.</inlineHelpText>
        <label>Business Plan</label>
        <referenceTo>Joint_Business_Plan__c</referenceTo>
        <relationshipLabel>Channel Partner Business Reviews</relationshipLabel>
        <relationshipName>Channel_Reviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Previous_Year__c</fullName>
        <description>R5 - Sales Previous Year formula field to copy from CBP</description>
        <formula>Joint_Business_Plan__r.Sales_previous_year_formula__c</formula>
        <label>Sales Previous Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Channel Partner Business Review</label>
    <nameField>
        <label>Business Review Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partner Business Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <!--validationRules>
        <fullName>CBR_Validate_Required_Fields</fullName>
        <active>false</active>
        <description>R5 - Validation rule to check all the checkbox fields need to be filled out</description>
        <errorConditionFormula>OR(Sales_Answer_1__c = FALSE, Actions_Answer_1__c= FALSE, Partner_Answer_1__c=FALSE,ISBLANK(Sales_Answer_2__c),ISBLANK(Actions_Answer_2__c))</errorConditionFormula>
        <errorMessage>Cannot save the changes. Please fill the required fields.</errorMessage>
    </validationRules-->
</CustomObject>

src/objects/Joint_Business_Plan__c.object
<CustomObject>
    <description>R5 Joint Business Plan</description>
    <fields>
        <fullName>Actual_Sales_Year_to_Date__c</fullName>
        <description>R5 - Actual Sales Year to Date</description>
        <label>Actual Sales Year to Date</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Budget_Current_Year__c</fullName>
        <description>R5 - Budget Current Year</description>
        <label>Budget Current Year</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Channel_Market_Coverage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R5 - Lookup to Channel Market Coverage</description>
        <inlineHelpText>Channel &quot;Market scope&quot; this business plan is related to</inlineHelpText>
        <label>Market Scope</label>
        <referenceTo>Channel_Market_Coverage__c</referenceTo>
        <relationshipLabel>Channel Partner Business Plans</relationshipLabel>
        <relationshipName>Joint_Business_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Forecast_ongoing_year__c</fullName>
        <description>R5 - Forecast current year</description>
        <label>Forecast current year</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rund_Rate_Ongoing_year__c</fullName>
        <description>R5 - Run Rate Current year</description>
        <label>Run Rate Current year</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sales_previous_year__c</fullName>
        <description>R5 - Sales previous year</description>
        <label>Sales previous year</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Start Date Field</description>
        <inlineHelpText>The date the plan starts to be effective, typically Jan1st of the year</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Target_2nd_Year__c</fullName>
        <description>R5 - Target 2nd Year</description>
        <label>Target 2nd Year</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Target_3rd_Year__c</fullName>
        <description>R5 - Target 3rd Year</description>
        <label>Target 3rd Year</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Channel Partner Business Plan</label>
    <nameField>
        <label>Business Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partner Business Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Joint_Business_Plan_Market_Coverage__c.object
<CustomObject>
    <description>R5 - New Custom Object Joint Business Plan Market Coverage</description>
    <!--fields>
        <fullName>Focussed_Industry1__c</fullName>
        <description>R5 - Focussed industry - combination of Industry usage level 1, level2 and level3</description>
        <inlineHelpText>Pick all the industries currently served and targeted in the upcoming 3 years.  Want to add/ remove a focused industry? Do it on &quot;Channel Market Scope&quot; -view and clone the list on Business Plan header -view.</inlineHelpText>
        <label>Focussed Industry</label>
        <picklist>
            <picklistValues>
                <fullName>BLD - BLD.8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BLD - BLD.9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BLD - BLD.10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.1 - IND.1.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.1 - IND.1.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.7 - IND.7.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.7 - IND.7.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.7 - IND.7.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.10 - IND.10.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.10 - IND.10.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.10 - IND.10.4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.10 - IND.10.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.11 - IND.11.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.11 - IND.11.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.12 - IND.12.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.12 - IND.12.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.12 - IND.12.3</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields-->
    <fields>
        <fullName>Joint_Business_Plan__c</fullName>
        <description>R5 - Joint Business Plan</description>
        <inlineHelpText>Business plan  this market scope is connected to</inlineHelpText>
        <label>Business Plan</label>
        <referenceTo>Joint_Business_Plan__c</referenceTo>
        <relationshipLabel>Market coverages</relationshipLabel>
        <relationshipName>Joint_Business_Plan_Market_Coverages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Market Coverage</label>
    <nameField>
        <displayFormat>Market-{000000}</displayFormat>
        <label>Market Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market Coverages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Joint_Business_Plan_Product_Lines__c.object
<CustomObject>
    <description>R5 - Joint Business Plan Product Lines</description>
    <fields>
        <fullName>Current_Ongoing_Year__c</fullName>
        <description>R5 Current_Ongoing_Year</description>
        <inlineHelpText>Update the actual sales @ every business review. Indicate also date of the report to get run rate calculation correct</inlineHelpText>
        <label>Actual Sales Year to Date</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Year_Currency__c</fullName>
        <description>R5 Current_Year_Currency field</description>
        <inlineHelpText>Budget for this product line, this year</inlineHelpText>
        <label>Budget Current Year</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Forecast_Ongoing_Year__c</fullName>
        <description>R5 Forecast_Ongoing_Year field</description>
        <inlineHelpText>Update the whole year&apos;s forecast @ every business review</inlineHelpText>
        <label>Forecast Current Year</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Joint_Business_Plan__c</fullName>
        <description>R5 - Master-Detail Relationship to Joint Business Plan</description>
        <inlineHelpText>Business plan this sales plan is connected to</inlineHelpText>
        <label>Business Plan</label>
        <referenceTo>Joint_Business_Plan__c</referenceTo>
        <relationshipLabel>Sales Targets and Results</relationshipLabel>
        <relationshipName>Joint_Business_Plan_Product_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Previous_Year_Currency__c</fullName>
        <description>R5 Previous_Year_Currency field</description>
        <inlineHelpText>Sales of this product, previous year</inlineHelpText>
        <label>Sales previous year</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Run_Rate_On__c</fullName>
        <description>R5 - Run Rate Calculation Formula</description>
        <formula>IF (ISNULL(Actual_Year_to_Date_Changed_on__c) , 0, (365  / (  Actual_Year_to_Date_Changed_on__c - DATEVALUE( TEXT(YEAR( Actual_Year_to_Date_Changed_on__c  )) &amp; &quot;-01-01&quot; )))  * Current_Ongoing_Year__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Calculated; linear trend based on Year to Date sales and date</inlineHelpText>
        <label>Run Rate Current Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Second_Year_Currency__c</fullName>
        <description>R5 Second_Year_Currency field</description>
        <inlineHelpText>Budget/ target for this product line, 2nd year</inlineHelpText>
        <label>Target 2nd Year</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Starting_Year__c</fullName>
        <description>R5 Starting_Year</description>
        <label>Current Year</label>
        <picklist>
            <picklistValues>
                <fullName>1991</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1992</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1993</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1994</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1995</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1996</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1997</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1998</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2001</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2002</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2003</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2004</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2005</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2006</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2007</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2008</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2009</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2011</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Third_Year_Currency__c</fullName>
        <description>R5 Third_Year_Currency field</description>
        <inlineHelpText>Budget/ target for this product line, 3rd year</inlineHelpText>
        <label>Target 3rd Year</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Sales Targets and Results</label>
    <nameField>
        <displayFormat>MIX-{0000000}</displayFormat>
        <label>Product Mix</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Targets and Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ClsTriggerJointBusinessPlanHandler.cls
/**   
* TriggerClass on the Joint_Business_Plan__c object to
    1. To update the Record Type based on Status 
    2. Uncheck the Mutual Agreed if start date is changed
*       
* Release - R5 
 *  
 * @author  - Vasanthi (Accenture)
 * @created - 2016-1-25
 * @version - 1.0
 * @Description - Update the Record Type to Open if the status changed from 'Cloded' to anything = as per Req#2450
 Whenever the JBP Start date changes then mutually agreed will be unchecked as per Req #2746 (KAD-00895)
   
* - Created
*/
public without sharing class ClsTriggerJointBusinessPlanHandler extends ClsTriggerVirtual {
  
    
    public Static Set<Id> processedIdSet = new Set<Id>();
    public Set<Id> rtIdSet = new Set<Id>();

/**    
    *constructor
*/
    public ClsTriggerJointBusinessPlanHandler() {
    
        for (Schema.RecordTypeInfo rt: Schema.SObjectType.Joint_Business_Plan__c.getRecordTypeInfosByName().values()) {
            rtIdSet.add(rt.getRecordTypeId());
        }
    }
    
/**    
    *Req #1960 Criteria Based Rollup summary field on the object Joint_Business_Plan__c
*/       
    public void rollupJointBusinessProductLinesValue(ClsWrappers.TriggerContext trgCtx) {
        
        Map<ID, AggregateResult> aggregateMAp = new MAp<Id, AggregateResult>();
        List<Joint_Business_Plan__c> recordList = new List<Joint_Business_Plan__c>();
        Set<Id> parentIdSet = new Set<Id>();
        Set<String> yearSet = new Set<String>();
        List<String> expList = new List<String>();
        expList.addAll(Label.System_Aggregate_Query_Expr.split(Label.CL00069));   //Label.CL00069 = comma(,) 
        //System_Aggregate_Query_Expr => sales,budget,actualSales,runRate,target2nd,target3rd,forecast
        
        if (trgCtx.isUpdate) {
            for (Joint_Business_Plan__c jbp : (List<Joint_Business_Plan__c >) trgCtx.newList) {
                
                Joint_Business_Plan__c oldJbp = (trgCtx.isInsert) ? NULL : (Joint_Business_Plan__c ) trgCtx.oldMap.get(jbp.Id);
                
                if (jbp.Start_Date__c != oldJbp.Start_Date__c) {
                    
                    recordList.add(jbp);
                    
                    if (jbp.Start_Date__c != NULL) {
                        parentIdSet.add(jbp.Id);                    
                        yearSet.add(String.valueOf(jbp.Start_Date__c.YEar()));
                    }
                }
            }
            
            if (parentIdSet.size() > 0) {
                
                Integer limitRows = Limits.getLimitQueryRows() - Limits.getQueryRows();
                
                List<AggregateResult> ag = [ SELECT SUM(Previous_Year_Currency__c) sales, SUM(Current_Year_Currency__c) budget, 
                        SUM(Current_Ongoing_Year__c) actualSales, SUM(Run_Rate_On__c) runRate, SUM(Second_Year_Currency__c) target2nd, 
                        SUM(Third_Year_Currency__c ) target3rd, SUM(Forecast_Ongoing_Year__c) forecast, Joint_Business_Plan__c 
                    FROM Joint_Business_Plan_Product_Lines__c 
                    WHERE Joint_Business_Plan__c IN :parentIdSet AND Starting_Year__c IN :yearSet AND (
                        Previous_Year_Currency__c > 0 OR Current_Year_Currency__c > 0 OR Current_Ongoing_Year__c > 0 OR Run_Rate_On__c > 0 OR 
                        Second_Year_Currency__c > 0 OR Third_Year_Currency__c > 0 OR Forecast_Ongoing_Year__c > 0)
                        GROUP BY Joint_Business_Plan__c LIMIT :limitRows ];
                        
               
               for (AggregateResult res: ag) {
                   aggregateMap.put(String.valueOf(res.get(Label.System_Joint_Business_Plan_object_API)), res);
               }     
            }
            
            
            for (Joint_Business_Plan__c jbp: recordList) {
                //exp sales,budget,actualSales,runRate,target2nd,target3rd,forecast
                jbp.Sales_previous_year__c = aggregateMap.get(jbp.Id) != NULL ? ((aggregateMap.get(jbp.Id).get(expList[0]) != NULL) ? Double.valueOf(aggregateMap.get(jbp.Id).get(expList[0])) : 0): 0;
                jbp.Budget_Current_Year__c = (aggregateMap.get(jbp.Id) != NULL) ? ((aggregateMap.get(jbp.Id).get(expList[1]) != NULL) ? Double.valueOf(aggregateMap.get(jbp.Id).get(expList[1])) : 0): 0;
                jbp.Actual_Sales_Year_to_Date__c = aggregateMap.get(jbp.Id) != NULL ?((aggregateMap.get(jbp.Id).get(expList[2]) != NULL) ? Double.valueOf(aggregateMap.get(jbp.Id).get(expList[2])) : 0): 0;
                jbp.Rund_Rate_Ongoing_year__c = aggregateMap.get(jbp.Id) != NULL ? ((aggregateMap.get(jbp.Id).get(expList[3]) != NULL) ? Double.valueOf(aggregateMap.get(jbp.Id).get(expList[3])) : 0): 0;
                jbp.Target_2nd_Year__c = aggregateMap.get(jbp.Id) != NULL ? ((aggregateMap.get(jbp.Id).get(expList[4]) != NULL) ? Double.valueOf(aggregateMap.get(jbp.Id).get(expList[4])) : 0): 0;          
                jbp.Target_3rd_Year__c = aggregateMap.get(jbp.Id) != NULL ? ((aggregateMap.get(jbp.Id).get(expList[5]) != NULL) ? Double.valueOf(aggregateMap.get(jbp.Id).get(expList[5])) : 0): 0;                            
                jbp.Forecast_ongoing_year__c = aggregateMap.get(jbp.Id) != NULL ? ((aggregateMap.get(jbp.Id).get(expList[6]) != NULL) ? Double.valueOf(aggregateMap.get(jbp.Id).get(expList[6])) : 0): 0;
            }
        }
    }
/**    
    * Bulk After override method
*/      
    public override void bulkAfter(ClsWrappers.TriggerContext trgCtx) {
        if (trgCtx.isUpdate) {
            assingnCurrency(trgCtx);
        }
    }
/**    
    * Copy Channel common data and Channel market coverage informations  
 */ 
    public void copyAccAndChannelMarketCoverage(ClsWrappers.TriggerContext trgCtx) {
        
        Set<Id> accIdSet = new Set<Id>();
        Set<Id> cmcIdSet = new Set<Id>();
        Map<Id, Account> accMap = new MAp<Id, Account>();
        Map<Id, Channel_Market_Coverage__c> cmcMap = new MAp<Id, Channel_Market_Coverage__c>();
        Integer limitRows = Limits.getLimitQueryRows() - Limits.getQueryRows();
        
        if (trgCtx.isInsert || trgCtx.isUpdate) {
            for (Joint_Business_Plan__c jbp : (List<Joint_Business_Plan__c >) trgCtx.newList) {
                
                if (jbp.Channel_Market_Coverage__c != NULL) {
                    cmcIdSet.add(jbp.Channel_Market_Coverage__c);
                }
                
                if (jbp.Account__c != NULL) {
                    accIdSet.add(jbp.Account__c );
                }                
            }
        }
        
        if (cmcIdSet.size() > 0) {
            cmcMap = new Map<ID, Channel_Market_Coverage__c>( [ SELECT Id, Secondary_Channel_Class_2__c, Suppliers_with_complementary_products__c,
                    Suppliers_with_possible_ABB_offering__c, Division__c, Existing_ABB_offering__c
                FROM Channel_Market_Coverage__c
                WHERE Id IN :cmcIdSet LIMIT :limitRows] );
        }
        
        if (accIdSet.size() > 0) {
            
            limitRows = Limits.getLimitQueryRows() - Limits.getQueryRows();
            accMap = new Map<ID, Account>( [ SELECT Id, Company_Description__c
                FROM Account
                WHERE Id IN :accIdSet LIMIT :limitRows] );
        }
        
         if (accIdSet.size() > 0 || cmcIdSet.size() > 0) {
            for (Joint_Business_Plan__c jbp : (List<Joint_Business_Plan__c >) trgCtx.newList) {
                
                jbp.Company_Description__c = (jbp.Account__c != NULL) ? accMap.get(jbp.Account__c).Company_Description__c : '';
                
                if (jbp.Company_Description__c != null) {
                    
                    if (jbp.Company_Description__c.length() < 255) {
                        jbp.Check_Company_Description__c = jbp.Company_Description__c;
                    } else {
                     jbp.Check_Company_Description__c = jbp.Company_Description__c.substring(0, 255);
                    }
                }
                jbp.Secondary_Channel_Class__c = (jbp.Channel_Market_Coverage__c != NULL) ? cmcMap.get(jbp.Channel_Market_Coverage__c).Secondary_Channel_Class_2__c: '';
                jbp.Suppliers_with_complementary_products__c = (jbp.Channel_Market_Coverage__c != NULL) ? cmcMap.get(jbp.Channel_Market_Coverage__c).Suppliers_with_complementary_products__c: '';
                jbp.Division__c = (jbp.Channel_Market_Coverage__c != NULL) ? cmcMap.get(jbp.Channel_Market_Coverage__c).Division__c: '';
                jbp.Existing_ABB_offering__c = (jbp.Channel_Market_Coverage__c != NULL) ? cmcMap.get(jbp.Channel_Market_Coverage__c).Existing_ABB_offering__c: '';
                jbp.Suppliers_with_potential_ABB_offering__c = (jbp.Channel_Market_Coverage__c != NULL) ? cmcMap.get(jbp.Channel_Market_Coverage__c).Suppliers_with_possible_ABB_offering__c: '';
                         
            }
        }
    }
/**    
    * Update the Record Type to Open if the status changed from 'Closed' to anything = as per Req#2450
    * Copy Channel common data and Channel market coverage informations   
*/               
    public override void bulkBefore(ClsWrappers.TriggerContext trgCtx) {
        
        if (trgCtx.isInsert || trgCtx.isUpdate) {
            copyAccAndChannelMarketCoverage(trgCtx);
        }
        
        if (trgCtx.isUpdate) {
            
            rollupJointBusinessProductLinesValue(trgCtx);
            
            for (SObject sobj: trgCtx.newList) {
                
                if (!processedIdSet.contains(sobj.Id)) {
                
                    Joint_Business_Plan__c newJoinBusPlan = (Joint_Business_Plan__c) sobj;
                    Joint_Business_Plan__c oldJoinBusPlan = (Joint_Business_Plan__c) trgCtx.oldMap.get(sobj.Id);
                    
                    //  Update the Record Type to Open if the status changed from 'Cloded' to anything = as per Req#2450                    
                    if (newJoinBusPlan.Status__c !=  oldJoinBusPlan.Status__c && newJoinBusPlan.Status__c == Label.Closed) {
                        
                        newJoinBusPlan.Old_Record_Type_Value__c = newJoinBusPlan.RecordTypeId; // Copy the previous record type
                    
                    } else if (newJoinBusPlan.Status__c !=  oldJoinBusPlan.Status__c && oldJoinBusPlan.Status__c == Label.Closed && 
                        newJoinBusPlan.Old_Record_Type_Value__c != NULL && !(String.IsBlank(newJoinBusPlan.Old_Record_Type_Value__c)) &&
                        rtIdSet.contains(newJoinBusPlan.Old_Record_Type_Value__c)){
                        
                        newJoinBusPlan.RecordTypeId = newJoinBusPlan.Old_Record_Type_Value__c;  // Update the previous record type
                    }else{} 
                    
                   
                    //Whenever the JBP Start date changes then mutually agreed will be unchecked as per Req #2746 (KAD-00895)
                    if (newJoinBusPlan.Start_Date__c !=  oldJoinBusPlan.Start_Date__c && newJoinBusPlan.Mutually_Agreed__c) {                        
                        newJoinBusPlan.Mutually_Agreed__c = FALSE;                 
                    }
                    
                    processedIdSet.add(sobj.Id);
                }               
            }
        }
    }
    
/**     
      * Req #1960 (Update Joint Business Plan currency to Joint Business Plan Product Lines).    
*/       
    public void assingnCurrency(ClsWrappers.TriggerContext trgCtx) {
        
        Set<Id> parentIdSet = new Set<Id>();
        Map<ID, String> JbpIdAndCurrencyMap = new Map<ID, String>();
        
        for (Sobject sobj : trgCtx.newList) {
        
            Joint_Business_Plan__c newJoinBusPlan = (Joint_Business_Plan__c) sobj;
            Joint_Business_Plan__c oldJoinBusPlan = (Joint_Business_Plan__c) trgCtx.oldMap.get(sobj.Id);
            
            if (newJoinBusPlan.CurrencyISOCode != oldJoinBusPlan.CurrencyISOCode) {
                parentIdSet.add(newJoinBusPlan.Id);
                JbpIdAndCurrencyMap.put(newJoinBusPlan.Id, newJoinBusPlan.CurrencyISOCode);
            }
        }
        
        if (parentIdSet.size() > 0) {
            
            Integer limitRows = Limits.getLimitQueryRows() - Limits.getQueryRows(); 
           
            List<Joint_Business_Plan_Product_Lines__c> updateList = new List<Joint_Business_Plan_Product_Lines__c>();
            List<Channel_Business_Review__c> reviewList = new List<Channel_Business_Review__c>();
            List<Joint_Business_Plan_Market_Coverage__c> marketCoverageList = new List<Joint_Business_Plan_Market_Coverage__c>();
            
            for (Joint_Business_Plan_Product_Lines__c productLine : [ SELECT Id,CurrencyISOCode,
                  Previous_Year_Currency__c, Current_Year_Currency__c, Current_Ongoing_Year__c, Second_Year_Currency__c, Third_Year_Currency__c, Forecast_Ongoing_Year__c,Joint_Business_Plan__c  
                  FROM Joint_Business_Plan_Product_Lines__c WHERE Joint_Business_Plan__c IN :parentIdSet  LIMIT :limitRows]) {
               
                productLine.currencyISOCode = JbpIdAndCurrencyMap.get(productLine.Joint_Business_Plan__c);
                updateList.add(productLine);
            }
            
            limitRows = Limits.getLimitQueryRows() - Limits.getQueryRows(); 
            
            for (Channel_Business_Review__c rev : [ SELECT Id, Joint_Business_Plan__c, CurrencyISOCode FROM Channel_Business_Review__c 
                    WHERE Joint_Business_Plan__c IN :parentIdSet LIMIT :limitRows]) {
                rev.currencyISOCode = JbpIdAndCurrencyMap.get(rev.Joint_Business_Plan__c);
                reviewList.add(rev);
            }
            
            limitRows = Limits.getLimitQueryRows() - Limits.getQueryRows(); 
            
            for (Joint_Business_Plan_Market_Coverage__c jbp: [SELECT Id, Joint_Business_Plan__c, CurrencyISOCode FROM Joint_Business_Plan_Market_Coverage__c
                    WHERE Joint_Business_Plan__c IN :parentIdSet LIMIT :limitRows]) {
                jbp.currencyISOCode = JbpIdAndCurrencyMap.get(jbp.Joint_Business_Plan__c);
                marketCoverageList.add(jbp);            
            }
            
            limitRows = Limits.getLimitQueryRows() - Limits.getQueryRows();
            
            List<Sales_and_Target_channel_business_review__c> updateSalesList = new List<Sales_and_Target_channel_business_review__c> ();
            
            for (Sales_and_Target_channel_business_review__c jbp: [SELECT Id, Channel_Partner_Business_Review__r.Joint_Business_Plan__c, CurrencyISOCode FROM Sales_and_Target_channel_business_review__c
                    WHERE Channel_Partner_Business_Review__r.Joint_Business_Plan__c IN :parentIdSet LIMIT :limitRows]) {
                jbp.currencyISOCode = JbpIdAndCurrencyMap.get(jbp.Channel_Partner_Business_Review__r.Joint_Business_Plan__c);
                updateSalesList.add(jbp);     
            }
            try {
        
                if (updateList.size() > 0) {
                    
                    Database.Update(updateList);
                }
                
                if (reviewList.size() > 0) Database.Update(reviewList);
                if (marketCoverageList.size() > 0) Database.Update(marketCoverageList);
                if (updateSalesList.size() > 0) Database.Update(updateSalesList);
                
            } Catch(DMLException e) {
                
                String err = '';
                for (Integer i = 0; i < e.getNumDML(); i++) {
                    err += e.getDMLMessage(i) +Label.Line_Break;
                }
                
                for (Id tmp: parentIdSet) {
                    trgCtx.newMap.get(tmp).addError(err, false);
                }
            }
        }       
    }
    
   
}