src/objects/Channel_Market_Coverage__c.object
<CustomObject>
    <description>R5 - Custom Object to define Channel Market Coverage</description>
    <fields>
        <fullName>Division__c</fullName>
        <description>R5 Division</description>
        <inlineHelpText>Pick division(s) focused in this market scope (and connected business plan/review)</inlineHelpText>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>DM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PG</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <!--fields>
        <fullName>Focussed_Industry1__c</fullName>
        <description>R5 - New Focussed Industry value -Combination of Industry usage level1, level2 and level3</description>
        <inlineHelpText>Pick all the industries currently served and targeted in the upcoming 3 years. Pick only industries with sales focus, not the ones that are served reactively.</inlineHelpText>
        <label>Focussed Industry</label>
        <picklist>
            <picklistValues>
                <fullName>BLD - BLD.8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BLD - BLD.9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BLD - BLD.10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.1 - IND.1.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.1 - IND.1.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.7 - IND.7.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.7 - IND.7.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.7 - IND.7.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.10 - IND.10.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.10 - IND.10.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.10 - IND.10.4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.10 - IND.10.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.11 - IND.11.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.11 - IND.11.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.12 - IND.12.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.12 - IND.12.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.12 - IND.12.3</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields-->
    <label>Channel Partner Market Scope</label>
    <nameField>
        <label>Market Scope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partner Market Scope</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <!--webLinks>
        <fullName>Change_Product_Line</fullName>
        <availability>online</availability>
        <description>R5 - Change the Product through PIS Tree</description>
        <displayType>button</displayType>
        <height>600</height>
        <linkType>page</linkType>
        <masterLabel>Change Product Line</masterLabel>
        <openType>sidebar</openType>
        <page>EditChannelMarketPIS</page>
        <protected>false</protected>
    </webLinks-->
</CustomObject>

src/objects/Channel_Market_Coverage_Product_Lines__c.object
<CustomObject>
    <description>R5 - Channel Market Coverage Product Lines</description>
    <fields>
        <fullName>Actual_Stock__c</fullName>
        <description>R5 - Actual Stock</description>
        <inlineHelpText>Indicate the current stock level for the product, either in # products or in value (indicate which). Used to search possible stocking partners when urgent needs from customers.</inlineHelpText>
        <label>Actual Stock</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Unit_Name__c</fullName>
        <description>R5 - Business Unit Name</description>
        <label>Business Unit Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <description>R5 - Business Unit</description>
        <inlineHelpText>DIv, BU and PG are only editable if there are no pre-filled values. (Default values from Master Data)</inlineHelpText>
        <label>Business Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Channel_Market_Coverage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R5 - Lookup Relationship to Channel Market Coverage</description>
        <inlineHelpText>Channel Market Scope this product is connected to</inlineHelpText>
        <label>Channel Market Scope</label>
        <referenceTo>Channel_Market_Coverage__c</referenceTo>
        <relationshipName>Channel_Market_Coverage_Product_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Division_Name__c</fullName>
        <description>R5 - Division Name</description>
        <label>Division Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <description>R5 - Division</description>
        <inlineHelpText>DIv, BU and PG are only editable if there are no pre-filled values. (Default values from Master Data)</inlineHelpText>
        <label>Division</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Other_Information__c</fullName>
        <description>R5 - Other Information</description>
        <inlineHelpText>Additional logistics and stock information about this product</inlineHelpText>
        <label>Other Information</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Planned_Stock__c</fullName>
        <description>R5 - Planned Stock</description>
        <inlineHelpText>Stock level planned to meet the targeted lead time, either in # products or in value (indicate which).</inlineHelpText>
        <label>Planned Stock</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <description>R5 - Product Group</description>
        <inlineHelpText>DIv, BU and PG are only editable if there are no pre-filled values. (Default values from Master Data)</inlineHelpText>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R5 - Lookup to Product</description>
        <inlineHelpText>Pick from the product tree. Use level practical for defining sales plans and targeted stock levels.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Channel Partner Product Mix</relationshipLabel>
        <relationshipName>Channel_Market_Coverage_Product_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Lead_Times__c</fullName>
        <description>R5 - Target Lead Times</description>
        <inlineHelpText>Indicate how fast customers tend to require the product indicated. E.g. &quot;Out of stock&quot; ;  &quot;in 2 days&quot; or  &quot;in 2 weeks&quot;</inlineHelpText>
        <label>Target Lead Times</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Targeted_Stock__c</fullName>
        <description>R5 - Targeted Stock</description>
        <label>Targeted Stock</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Channel Partner Product Mix</label>
    <nameField>
        <displayFormat>CHAN-PROD-LINE-{0000}</displayFormat>
        <label>Product Mix</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channel Partner Product Mix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Joint_Business_Plan__c.object
<CustomObject>
    <description>R5 Joint Business Plan</description>
    <fields>
        <fullName>Channel_Market_Coverage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R5 - Lookup to Channel Market Coverage</description>
        <inlineHelpText>Channel &quot;Market scope&quot; this business plan is related to</inlineHelpText>
        <label>Market Scope</label>
        <referenceTo>Channel_Market_Coverage__c</referenceTo>
        <relationshipLabel>Channel Partner Business Plans</relationshipLabel>
        <relationshipName>Joint_Business_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Start Date Field</description>
        <inlineHelpText>The date the plan starts to be effective, typically Jan1st of the year</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Channel Partner Business Plan</label>
    <nameField>
        <label>Business Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partner Business Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Joint_Business_Plan_Product_Lines__c.object
<CustomObject>
    <description>R5 - Joint Business Plan Product Lines</description>
    <fields>
        <fullName>Actual_Stock__c</fullName>
        <description>R5 - Actual Stock</description>
        <label>Actual Stock</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Unit_Name__c</fullName>
        <description>R5 - Business Unit Name</description>
        <label>Business Unit Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <description>R5 - Business Unit</description>
        <label>Business Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division_Name__c</fullName>
        <description>R5 - Division Name</description>
        <label>Division Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <description>R5 - Division</description>
        <label>Division</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Joint_Business_Plan__c</fullName>
        <description>R5 - Master-Detail Relationship to Joint Business Plan</description>
        <inlineHelpText>Business plan this sales plan is connected to</inlineHelpText>
        <label>Business Plan</label>
        <referenceTo>Joint_Business_Plan__c</referenceTo>
        <relationshipLabel>Sales Targets and Results</relationshipLabel>
        <relationshipName>Joint_Business_Plan_Product_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Other_Information__c</fullName>
        <description>R5 - Other Information</description>
        <label>Other Information</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Planned_Stock__c</fullName>
        <description>R5 - Planned Stock</description>
        <label>Planned Stock</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <description>R5 - Product Group</description>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Mix__c</fullName>
        <description>R5 - Product Mix</description>
        <label>Product Mix</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R5 - Product</description>
        <inlineHelpText>Product as chosen in the market scope. Want to add/remove products? Update Market scope product list and copy content on Business Plan template.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Sales Targets and Results</relationshipLabel>
        <relationshipName>Joint_Business_Plan_Product_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Starting_Year__c</fullName>
        <description>R5 Starting_Year</description>
        <label>Current Year</label>
        <picklist>
            <picklistValues>
                <fullName>1991</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1992</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1993</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1994</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1995</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1996</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1997</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1998</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2001</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2002</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2003</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2004</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2005</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2006</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2007</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2008</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2009</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2011</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target_Lead_Times__c</fullName>
        <description>R5 - Target Lead Times</description>
        <label>Target Lead Times</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Targeted_Stock__c</fullName>
        <description>R5 - Targeted Stock</description>
        <label>Targeted Stock</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sales Targets and Results</label>
    <nameField>
        <displayFormat>MIX-{0000000}</displayFormat>
        <label>Product Mix</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Targets and Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product_Group__c.object
<CustomObject>
</CustomObject>

src/classes/ClsJBPProductLineCopy.cls
/**
 * TriggerClass -  Copy all the Product Lines from Channel Market Coverage in to Joint Business Plan Product Line.
 * Don't copy the duplicate product lines. 
 * Controller for Vf pgae - JBPProductLineCopy
 * 
 * Release R5
 * @author  Indhu Selvi Rmalingam (Accenture)
 * @created 2015-12-31
 * @version 1.0
 * Created
 */ 
public with sharing class ClsJBPProductLineCopy {
/**
 * Constructor ClsJBPProductLineCopy
 */     
    public ClsJBPProductLineCopy(ApexPages.StandardController controller){}
/**
 * Constructor ClsJBPProductLineCopy
 */     
    public ClsJBPProductLineCopy(){}
    public String JBPId=Apexpages.currentPage().getParameters().get(Label.ApexClass_id);
    public Boolean isSubApproval{get;set;}
    public Boolean showErrmsg{get;set;} 
/**
 * Method copyChanMarCovProductLine
 * Copy the Joint Business Plan Product Lines 
 */     
    public pagereference copyChanMarCovProductLine(){
        Integer limitRow = Limits.getLimitQueryRows() - Limits.getQueryRows();
        List<Joint_Business_Plan_Product_Lines__c> listJBPProds = new List<Joint_Business_Plan_Product_Lines__c>(); //list to insert
        
        List<Joint_Business_Plan__c> lstJBPRecs=[select id,Start_Date__c,Channel_Market_Coverage__c from Joint_Business_Plan__c where id =:JBPId LIMIT :limitRow];
        
        List<Channel_Market_Coverage_Product_Lines__c> listChanMarkCovProds = new List<Channel_Market_Coverage_Product_Lines__c>();
        
        
        
        if(lstJBPRecs != NULL && lstJBPRecs.size()>0 &&  lstJBPRecs[0].Channel_Market_Coverage__c != NULL){
            
            listChanMarkCovProds = [SELECT Id, Name, Product__c, Target_Lead_Times__c, Product_Group__c, Planned_Stock__c, Business_Unit__c, Business_Unit_Name__c, Division__c, Division_Name__c,
                                        Actual_Stock__c, Other_Information__c, Channel_Market_Coverage__c FROM Channel_Market_Coverage_Product_Lines__c 
                                    WHERE Channel_Market_Coverage__c =: lstJBPRecs[0].Channel_Market_Coverage__c LIMIT :limitRow];            
            
            
            //system.debug('::::listChanMarkCovProds:::'+listChanMarkCovProds );
        }
        
        
        
        List<ProcessInstance> lstProcessInstance = [Select Id, Status, TargetObject.Name , TargetObjectId from ProcessInstance where
                     TargetObjectId  =: JBPId and Status =:Label.ProcessInstance_Status_Pending  LIMIT :limitRow];
                     
        if(lstProcessInstance != null && lstProcessInstance.size() >0)
        {isSubApproval = true;}
        else        
        {isSubApproval = False;}
            
        //system.debug('JBPId----'+JBPId);
     
            Set<Id> mapJBP = new Set<Id>(); 
            
            List<Joint_Business_Plan_Product_Lines__c> lstDuplicateCheck = [Select id,Product__c from Joint_Business_Plan_Product_Lines__c 
                                where Joint_Business_Plan__c  =: JBPId LIMIT :limitRow];
          
            if(lstDuplicateCheck.size()>0){
                for(Joint_Business_Plan_Product_Lines__c dupCheck : lstDuplicateCheck){
                    mapJBP.add(dupCheck.Product__c);           
                }  
                
            }   
        
        
        if(lstJBPRecs != NULL && lstJBPRecs.size() > 0){
            for(Channel_Market_Coverage_Product_Lines__c MarkCoverProds : listChanMarkCovProds){
            
                if(!mapJBP.contains(MarkCoverProds.Product__c)){
                
                    String yearVal = (lstJBPRecs[0].Start_Date__c != NULL ) ? String.ValueOf(lstJBPRecs[0].Start_Date__c.Year()) : '';
                    Joint_Business_Plan_Product_Lines__c newJBPProds = new Joint_Business_Plan_Product_Lines__c();
                    newJBPProds.Joint_Business_Plan__c = lstJBPRecs[0].id;
                    newJBPProds.Product__c = MarkCoverProds.Product__c; 
                    newJBPProds.Product_Mix__c = MarkCoverProds.Product__c;                    
                    newJBPProds.Product_Group__c = MarkCoverProds.Product_Group__c;
                    newJBPProds.Target_Lead_Times__c = MarkCoverProds.Target_Lead_Times__c;
                    //newJBPProds.Targeted_Stock__c = MarkCoverProds.Targeted_Stock__c;
                    newJBPProds.Business_Unit__c = MarkCoverProds.Business_Unit__c;
                    newJBPProds.Division__c = MarkCoverProds.Division__c;
                    newJBPProds.Business_Unit_Name__c = MarkCoverProds.Business_Unit_Name__c;
                    newJBPProds.Division_Name__c = MarkCoverProds.Division_Name__c;
                    newJBPProds.Planned_Stock__c = MarkCoverProds.Planned_Stock__c;
                    newJBPProds.Actual_Stock__c = MarkCoverProds.Actual_Stock__c;
                    newJBPProds.Other_Information__c = MarkCoverProds.Other_Information__c;
                    newJBPProds.Starting_Year__c = yearVal;
                    listJBPProds.add(newJBPProds);              
                }
            }
        }
        
          if(isSubApproval )
            {   
                showErrmsg = True;                  
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, Label.System_CL00096));
                return null;                
            }else if(listJBPProds.size()>0){
                 try {
                 //system.debug(':::listJBPProds:::'+listJBPProds);
                
                 Database.insert(listJBPProds);
                 }    Catch(DMLException e) {
                     showErrmsg = TRUE;
                     string error = '';
                     for (Integer i = 0; i < e.getNumDml(); i++) {
                        // Process exception here
                       error += (e.getDmlMessage(i)) +Label.Line_Break; 
                    }
                    ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, error));
                    return null;   
                }
            }else{}
        
        PageReference pageRef = new PageReference(Label.System_CL00020+JBPId); 
        return pageRef;
       }
/**
 * Method GoBack
 * GoBack to the previous page
 */        
         public Pagereference GoBack(){
            try
            {
                PageReference pageRef = new PageReference(Label.System_CL00020+JBPId);
                return pageRef;
            }
            catch(DMLException e){ return null; } 
        }  
        
    
    
}