src/objects/Channel_Market_Coverage__c.object
<CustomObject>
    <description>R5 - Custom Object to define Channel Market Coverage</description>
    <fields>
        <fullName>Division__c</fullName>
        <description>R5 Division</description>
        <inlineHelpText>Pick division(s) focused in this market scope (and connected business plan/review)</inlineHelpText>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>DM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PG</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <!--fields>
        <fullName>Focussed_Industry1__c</fullName>
        <description>R5 - New Focussed Industry value -Combination of Industry usage level1, level2 and level3</description>
        <inlineHelpText>Pick all the industries currently served and targeted in the upcoming 3 years. Pick only industries with sales focus, not the ones that are served reactively.</inlineHelpText>
        <label>Focussed Industry</label>
        <picklist>
            <picklistValues>
                <fullName>BLD - BLD.8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BLD - BLD.9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BLD - BLD.10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.1 - IND.1.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.1 - IND.1.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.7 - IND.7.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.7 - IND.7.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.7 - IND.7.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.10 - IND.10.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.10 - IND.10.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.10 - IND.10.4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.10 - IND.10.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.11 - IND.11.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.11 - IND.11.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.12 - IND.12.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.12 - IND.12.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.12 - IND.12.3</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields-->
    <label>Channel Partner Market Scope</label>
    <nameField>
        <label>Market Scope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partner Market Scope</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <!--webLinks>
        <fullName>Change_Product_Line</fullName>
        <availability>online</availability>
        <description>R5 - Change the Product through PIS Tree</description>
        <displayType>button</displayType>
        <height>600</height>
        <linkType>page</linkType>
        <masterLabel>Change Product Line</masterLabel>
        <openType>sidebar</openType>
        <page>EditChannelMarketPIS</page>
        <protected>false</protected>
    </webLinks-->
</CustomObject>

src/objects/Channel_Market_Coverage_Product_Lines__c.object
<CustomObject>
    <description>R5 - Channel Market Coverage Product Lines</description>
    <fields>
        <fullName>Actual_Stock__c</fullName>
        <description>R5 - Actual Stock</description>
        <inlineHelpText>Indicate the current stock level for the product, either in # products or in value (indicate which). Used to search possible stocking partners when urgent needs from customers.</inlineHelpText>
        <label>Actual Stock</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <description>R5 - Business Unit</description>
        <inlineHelpText>DIv, BU and PG are only editable if there are no pre-filled values. (Default values from Master Data)</inlineHelpText>
        <label>Business Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Channel_Market_Coverage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R5 - Lookup Relationship to Channel Market Coverage</description>
        <inlineHelpText>Channel Market Scope this product is connected to</inlineHelpText>
        <label>Channel Market Scope</label>
        <referenceTo>Channel_Market_Coverage__c</referenceTo>
        <relationshipName>Channel_Market_Coverage_Product_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <description>R5 - Division</description>
        <inlineHelpText>DIv, BU and PG are only editable if there are no pre-filled values. (Default values from Master Data)</inlineHelpText>
        <label>Division</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Other_Information__c</fullName>
        <description>R5 - Other Information</description>
        <inlineHelpText>Additional logistics and stock information about this product</inlineHelpText>
        <label>Other Information</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Planned_Stock__c</fullName>
        <description>R5 - Planned Stock</description>
        <inlineHelpText>Stock level planned to meet the targeted lead time, either in # products or in value (indicate which).</inlineHelpText>
        <label>Planned Stock</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <description>R5 - Product Group</description>
        <inlineHelpText>DIv, BU and PG are only editable if there are no pre-filled values. (Default values from Master Data)</inlineHelpText>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R5 - Lookup to Product</description>
        <inlineHelpText>Pick from the product tree. Use level practical for defining sales plans and targeted stock levels.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Channel Partner Product Mix</relationshipLabel>
        <relationshipName>Channel_Market_Coverage_Product_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Lead_Times__c</fullName>
        <description>R5 - Target Lead Times</description>
        <inlineHelpText>Indicate how fast customers tend to require the product indicated. E.g. &quot;Out of stock&quot; ;  &quot;in 2 days&quot; or  &quot;in 2 weeks&quot;</inlineHelpText>
        <label>Target Lead Times</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Channel Partner Product Mix</label>
    <nameField>
        <displayFormat>CHAN-PROD-LINE-{0000}</displayFormat>
        <label>Product Mix</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channel Partner Product Mix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Group__c.object
<CustomObject>
</CustomObject>

src/classes/ClsCMSProductLinesList.cls
/**   
* Apex Class : ClsCMSProductLinesList
* VF Page    : CMSProductLinesList
* Controller for CMSProductLinesList- Enable Inline Editing for Channel Market Scope Product Lines in Channel Market Scope
* Release R5
*
*/
public with sharing class ClsCMSProductLinesList
{
    public String returnURL {get;set;}
    public String parentId {get;set;}
    Map<Id,Set<Id>> mapJBP= new Map<Id,Set<Id>>(); 
    public List<Channel_Market_Coverage_Product_Lines__c> lstDuplicateCheck {get;set;}
  //  public string productlkp {get;set;}
    public List<Channel_Market_Coverage_Product_Lines__c> CMSProdLineItems {get;set;}

/**   
* Constructor ClsCMSProductLinesList
* Release R5
*
*/    
    public ClsCMSProductLinesList(ApexPages.StandardController controller) {
        Channel_Market_Coverage__c chanMarktScope=(Channel_Market_Coverage__c)controller.getRecord();         
        returnURL = apexpages.currentpage().getparameters().get(System.label.System_CL00018);                   
        parentId = returnURL.replace(Label.System_CL00020 , '');  // System_CL00020 => /           
        parentId = parentId.substring(0,15);
        
        CMSProdLineItems =[SELECT Id, Name, Channel_Market_Coverage__c, Actual_Stock__c, Business_Unit__c, Division__c, Other_Information__c, Planned_Stock__c,Product__r.Name,
                           Product_Group__c, Product__c,  Target_Lead_Times__c FROM Channel_Market_Coverage_Product_Lines__c WHERE Channel_Market_Coverage__c =:parentId limit 10000];
            
    }
/**   
* Save method 
* Update the record Channel_Market_Coverage_Product_Lines__c 
*
*/     
     public PageReference save() {
           
        Set<Id> productIdSet = new Set<Id>();    
        String dupPrd = '';  
        
        for(Channel_Market_Coverage_Product_Lines__c dupCheck : CMSProdLineItems){
            productIdSet.add(dupCheck.Product__c);
        }
        Integer remLimit =  limits.getLimitQueryRows() - limits.getQueryRows();
        Map<Id, Product2> productMap = new Map<Id, Product2> ([SELECT Id, Name FROM Product2 WHERE IsActive = TRUE AND Id IN: productIdSet LIMIT :remLimit]);
        
        productIdSet.clear();
        
        for(Channel_Market_Coverage_Product_Lines__c dupCheck : CMSProdLineItems){            
            if (!productIdSet.contains(dupCheck.Product__c)) {
                productIdSet.add(dupCheck.Product__c); 
            } else {
                dupPrd += (productMap.containsKey(dupCheck.Product__c)) ? productMap.get(dupCheck.Product__c).Name + System.label.CL00069 : dupCheck.Product__c + System.label.CL00069 ;
                 //system.debug('::::::'+dupCheck.Product__r.Name+':dupCheck.Product__c:::'+dupCheck.Product__c);  
            }          
        }           
           
       if (dupPrd != '') {           
           dupPrd = dupPrd.substring(0, dupPrd.length()-2);
           apexPages.addMessage(new ApexPages.message(ApexPages.severity.Error,System.label.ChannelMarkScope_Error_Message+dupPrd));
           return null;
       } else {
       
       Database.update(CMSProdLineItems);
       }
        PageReference pageRef = new PageReference(System.label.System_CL00020+returnURL);
        return pageRef;        
    }
 
/**   
* cancel method 
* returns to the previous page
*
*/     
    public PageReference cancel() {
         PageReference pageRef = new PageReference(System.label.System_CL00020+returnURL);
        return pageRef;  
    }

}