src/objects/Channel_Pre_Qualification_Team__c.object
<CustomObject>
    <description>R5 - New Custom object - Channel Pre-Qualification Team</description>
    <fields>
        <fullName>Access__c</fullName>
        <description>R5 -Access</description>
        <label>Access</label>
        <picklist>
            <picklistValues>
                <fullName>Read/Write</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel_Pre_Qualification__c</fullName>
        <label>Channel Pre-Qualification</label>
        <referenceTo>Channel_Qualifications__c</referenceTo>
        <relationshipName>Channel_Pre_Qualification_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team_Role__c</fullName>
        <description>R5 - Team Role</description>
        <label>Team Role</label>
        <picklist>
            <picklistValues>
                <fullName>Account Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GAM/SAM Account Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Engineer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Channel Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Service Responsible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive Sponsor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Qualifier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Sales Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Rep</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R5 - User</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Channel_Pre_Qualification_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Channel Partner Pre-Qualification Team</label>
    <nameField>
        <displayFormat>Team Member - {0000}</displayFormat>
        <label>Channel Pre-Qualification Team</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channel Partner Pre-Qualification Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Channel_Qualifications__c.object
<CustomObject>
    <description>R5-New custom object created for Release 5 to track to rate the Potential partner based on the criteria.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R5 - Lookup Relationship between Account and Channel Qualification</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Channel_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Channel Partner Pre-Qualification</label>
    <nameField>
        <label>Pre-Qualification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partner Pre-Qualifications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ClsChannelPreQualTeamMembersCopy.cls
/**
 * TriggerClass - ClsChannelPreQualTeamMembersCopy 
 * Controller for Vf pgae - ChannelPreQualTeamMembersCopy
 * 
 * Copy Account Team Members from the Account Team along with their roles in to the Channel Pre-Qualification Team
      and provide "Read/Write" Access. don't copy the duplicate user names. don't copy the inactive user.
 * Release R5
 * @author  Abiramasundari Radha (Accenture)
 * @created 2015-12-29
 * @version 1.0
 * Created
 */
public with sharing class ClsChannelPreQualTeamMembersCopy{
 /**
 * Constructor
 */ 
    public ClsChannelPreQualTeamMembersCopy(ApexPages.StandardController controller) {    
    }
 /**
 * Constructor
 */    
    public ClsChannelPreQualTeamMembersCopy(){}
    
    public String stringChannelPreQualId = Apexpages.currentPage().getParameters().get(Label.System_CL00018);   
    public Boolean isSubApproval{get;set;}
    public Boolean showErrmsg{get;set;} 
 /**
 * @name copyAccountTeamMember
 * Copy Account Team Members from the Account Team along with their roles in to the Channel Pre-Qualification Team
 */       
    public pagereference copyAccountTeamMember(){
        String accountId;
         showErrmsg = false;
        Integer remLimit =  limits.getLimitQueryRows() - limits.getQueryRows();
        Set<Id> channelPreQualId = new Set<Id>();        
        List<Channel_Pre_Qualification_Team__c> addteamMembersList = new List<Channel_Pre_Qualification_Team__c>();
        Set<Id> ChannelPreQualSet = new Set<Id>();
             
        List<Channel_Qualifications__c> lstChannelPreQual = [SELECT Id,Name,Account__c, OwnerID
            FROM Channel_Qualifications__c WHERE Id =: stringChannelPreQualId LIMIT :remLimit];         
        if(lstChannelPreQual.size()>0){
            accountId = lstChannelPreQual[0].Account__c;
        }
        
        
        If(lstChannelPreQual.size()>0){         
            for(Channel_Qualifications__c oldrecords : lstChannelPreQual){
                channelPreQualId.add(oldrecords.Id);
            }
        }
                
        List<AccountTeamMember> listAccountTeamMember = [SELECT UserId, AccountAccessLevel, TeamMemberRole, Id, AccountId From AccountTeamMember 
                        where AccountID =: accountId AND User.IsActive = TRUE AND User.Profile.Name != :Label.Sys_Admin_Profile_Name LIMIT :remLimit];
                        
        List<ProcessInstance> lstProcessInstance = [Select Id, Status, TargetObject.Name , TargetObjectId from ProcessInstance where
                     TargetObjectId  =: stringChannelPreQualId and Status =: Label.ProcessInstance_Status_Pending LIMIT :remLimit];   // ProcessInstance_Status_Pending -> 'Pending'
        if(lstProcessInstance != null && lstProcessInstance.size() >0)
        {isSubApproval = true;}
        else        
        {isSubApproval = False;}
        
       
        for(Channel_Pre_Qualification_Team__c dupCheck : [SELECT Id,Channel_Pre_Qualification__c,User__c,Team_Role__c FROM 
                Channel_Pre_Qualification_Team__c WHERE Channel_Pre_Qualification__c IN: channelPreQualId LIMIT :remLimit]){
           
            ChannelPreQualSet.add(dupCheck.User__c);           
        }           
                
        
        If(lstChannelPreQual.size()>0){
            for(Channel_Qualifications__c ChannelPreQual : lstChannelPreQual){  
                If(listAccountTeamMember.size()>0){      
                    for(AccountTeamMember accTeamMember : listAccountTeamMember){
                        if(ChannelPreQual.OwnerID != accTeamMember.UserId && !ChannelPreQualSet.contains(accTeamMember.UserId)) {
                            Channel_Pre_Qualification_Team__c channelTeamMember = new Channel_Pre_Qualification_Team__c();
                            channelTeamMember.Channel_Pre_Qualification__c = ChannelPreQual.Id;
                            channelTeamMember.User__c = accTeamMember.UserId;
                            channelTeamMember.Access__c = Label.System_CL00037;              //  System_CL00037 -> 'Read/Write'
                            channelTeamMember.Team_Role__c = accTeamMember.TeamMemberRole;
                            addteamMembersList.add(channelTeamMember);   
                        }
                    }                                         
                } 
            } 
  
        }    
        
        try {
         if(isSubApproval )
            {   
            showErrmsg = True;                  
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, Label.System_CL00096));
            return null;               
            }else  if(addteamMembersList.size()>0){
               // system.debug(addteamMembersList);
            Database.insert(addteamMembersList); 
          }else{}
            
        } Catch(DMLException e) {
            showErrmsg = True;
            
            String error = e.getDMLMEssage(0);
            
            if (System.label.cross_reference_error != '' && error.contains(System.label.cross_reference_error)){
                error = system.label.cross_reference_alt_message;
            } 

            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, error));
            return null;   
        }
                          
        PageReference pageRef = new PageReference(Label.System_CL00020+ stringChannelPreQualId); 
        return pageRef;
    } 
/**
 * @name GoBack
 * returns to the previous page
 */ 
    public Pagereference GoBack(){
            try
          {
                PageReference pageRef = new PageReference(Label.System_CL00020+stringChannelPreQualId);
                return pageRef;
            }
            catch(DMLException e){ return null; } 
        }   
}