src/objects/Channel_Business_Review__c.object
<CustomObject>
    <description>R5 Channel Business Review is a custom object to review the Channels, Partner, ABB Authorized value provider &amp; Strategic / Key Partner  who will be partnering with ABB to do business.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R5 - Channel review to have a look-up relationship with the Account Object.</description>
        <inlineHelpText>The partner and business plan this review covers. If the scope is several branch offices, that need to be indicated in general comments below.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Channel_Business_Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Channel Partner Business Review</label>
    <nameField>
        <label>Business Review Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partner Business Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <!--validationRules>
        <fullName>CBR_Validate_Required_Fields</fullName>
        <active>false</active>
        <description>R5 - Validation rule to check all the checkbox fields need to be filled out</description>
        <errorConditionFormula>OR(Sales_Answer_1__c = FALSE, Actions_Answer_1__c= FALSE, Partner_Answer_1__c=FALSE,ISBLANK(Sales_Answer_2__c),ISBLANK(Actions_Answer_2__c))</errorConditionFormula>
        <errorMessage>Cannot save the changes. Please fill the required fields.</errorMessage>
    </validationRules-->
</CustomObject>

src/objects/Opportunity_Info_Channel_Business_Review__c.object
<CustomObject>
    <description>R5 - Technical Object to establish many to many between Opportunity Information &amp; Channel Bussiness Review</description>
    <fields>
        <fullName>Channel_Partner_Business_Review__c</fullName>
        <description>R5 - master Detail</description>
        <label>Channel Partner Business Review</label>
        <referenceTo>Channel_Business_Review__c</referenceTo>
        <relationshipLabel>Opportunity Info Channel Business Review</relationshipLabel>
        <relationshipName>Opportunity_Info_Channel_Business_Review</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Opportunity_Information__c</fullName>
        <description>R5 _ Master Detail</description>
        <label>Opportunity Information</label>
        <referenceTo>Opportunity_Information__c</referenceTo>
        <relationshipLabel>Opportunity Info Channel Business Review</relationshipLabel>
        <relationshipName>Opportunity_Info_Channel_Business_Review</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Opportunity Info Channel Business Review</label>
    <nameField>
        <displayFormat>OPPCBR-{00000}</displayFormat>
        <label>Opportunity Info Channel Business Review</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Info Channel Business Review</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity_Information__c.object
<CustomObject>
    <description>According to the main authorisation principles, access to opportunity is set to private. Only the owner and the team members will have access to the opportunities.
To enable transparency, collaboration and cross selling options, this object contains public information of the opportunity.
The Object is set to public read only and gets all fields updated from the belonging opportunity. 
The relationship between opportunity and opportunity information is 1:1</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup field to ensure a relation to the correct Account</description>
        <label>Account Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Information</relationshipLabel>
        <relationshipName>Opportunity_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Information</label>
    <nameField>
        <displayFormat>OI-{0000000}</displayFormat>
        <label>Opportunity Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Information</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ClsTriggerOpportunityInformation.cls
/**   
* TriggerClass :  ClsTriggerOpportunityInformation
* 
* To create Opportunity_Info_Channel_Business_Review__c
* Release R5
*  
* @author  Vasanthi (Accenture)
* @created 2016-3-09
* @version 1.0
*
* - Created
*/
public without sharing class ClsTriggerOpportunityInformation extends ClsTriggerVirtual {
        
   
    Integer remLimit;     
    
    
    /**
    * @see IntHelper.AfterTrigger
    *To copy the opportunity information
    */  
    public override void bulkAfter(ClsWrappers.TriggerContext trgCtx) {
        if (trgCtx.isInsert) {
            copytheOpportuntiyInfos(trgCtx);
        }
    }            

    /**    
    *To copy the opportunity information
    */ 
    public void copytheOpportuntiyInfos(ClsWrappers.TriggerContext trgCtx){
        
        List<Opportunity_Info_Channel_Business_Review__c> toBeCreatedOppReviewList = new List<Opportunity_Info_Channel_Business_Review__c>();
        Map<Id, List<Opportunity_Information__c >> accIDOppInfoListMap  = new Map<Id, List<Opportunity_Information__c >>();
        
        for (Sobject sobj : trgCtx.newList) {
        
            Opportunity_Information__c info = (Opportunity_Information__c)sObj;            
            if (info.Account__c != NULL) {
                if (!accIDOppInfoListMap.containsKey(info.Account__c)) {
                    accIDOppInfoListMap.put(info.Account__c, new List<Opportunity_Information__c>());
                }
                accIDOppInfoListMap.get(info.Account__c).add(info);
            }
        }
        
        if (!accIDOppInfoListMap.isEmpty()) {
            
            remLimit =  limits.getLimitQueryRows() - limits.getQueryRows(); 
            
            for (Channel_Business_Review__c channel : [SELECT Id, Account__c FROM Channel_Business_Review__c WHERE Account__c IN : accIDOppInfoListMap.KeySet() LIMIT :remLimit ] ) {
                
                for (Opportunity_Information__c oppInfo: accIDOppInfoListMap.get(channel.Account__c)) {
                    
                    toBeCreatedOppReviewList.add( new Opportunity_Info_Channel_Business_Review__c(Channel_Partner_Business_Review__c = channel.Id, Opportunity_Information__c = oppInfo.Id));
                }
            }
        }
        
        try {
            if (toBeCreatedOppReviewList.size() > 0) {
                insert toBeCreatedOppReviewList;
            }
        } Catch(DMLException e) {
            String err = '';
            for (Integer i = 0; i < e.getNumDML(); i++) {
                err += e.getDMLMessage(i) +Label.Line_Break;
            }
            
            for (Sobject sobj : trgCtx.newList) {
                sobj.addError(err, false);
            }
        }
    }
}