src/objects/Customer_Segmentation__c.object
<CustomObject>
    <description>R5 - Custom Object to define Customer Segmentation</description>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <description>R5 Business Unit</description>
        <label>Application BU</label>
        <picklist>
            <controllingField>DIV__c</controllingField>
            <picklistValues>
                <fullName>DMDR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMPC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMRO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PATU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGGA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGGI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGGS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Other BU&apos;s</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R5 - Lookup to Product Group</description>
        <inlineHelpText>The enter PG will automatically update both the assigned Division &amp; BU in the above fields for this particular PG.</inlineHelpText>
        <label>Product Group</label>
        <referenceTo>Product_Group__c</referenceTo>
        <relationshipLabel>Account Segmentations</relationshipLabel>
        <relationshipName>Customer_Segmentations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R5 Product</description>
        <inlineHelpText>The enter Product Line will automatically update the assigned Division,  BU and PG in the above fields for this particular Product Line</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Account Segmentations</relationshipLabel>
        <relationshipName>Customer_Segmentations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Segment_Level__c</fullName>
        <inlineHelpText>Segmentation Level must always match to the values entered on the fields DIV,BU,Product Group,Product. For Example;Choose &quot;Division&quot; on segmentation level and populate up to DIV drop down list.</inlineHelpText>
        <label>Segment Level</label>
        <picklist>
            <picklistValues>
                <fullName>Division</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Line</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Segmentation</label>
    <nameField>
        <displayFormat>CS - {0000}</displayFormat>
        <label>Account Segmentation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Segmentations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product_Group__c.object
<CustomObject>
</CustomObject>

src/classes/ClsRemoveProductCustSeg.cls
/**   
* Class - ClsRemoveProductCustSeg
* Controller for VF Page - RemoveProductBudgetPIS 
* Remove only the product from record. 
* Release R5
*  
* @author  Indhu Selvi Ramalingam (Accenture)
* @created 2016-01-11
* @version 1.0
*
* - Created
*/
public with sharing class ClsRemoveProductCustSeg{

    public Boolean IsError {get;set;}
/**
* Constructor
*/  
    public ClsRemoveProductCustSeg(ApexPages.StandardController controller) { 
        IsError = FALSE;   
    }
/**
* Construtor
*/   
    public ClsRemoveProductCustSeg(){}
    
    public String stringCustSegId = Apexpages.currentPage().getParameters().get(Label.ApexClass_id);   
/**
* Method removeProduct
* Remove only the product from record. 
*/        
    public pagereference removeProduct(){
        
       IsError = FALSE;
       Customer_Segmentation__c lstCustSeg = [Select id, Product__c, Product_Group__c, Segment_Level__c, Business_Unit__c from Customer_Segmentation__c where Customer_Segmentation__c.Id =: stringCustSegId limit 50000 ];
         

       List<Customer_Segmentation__c> lstNewCustSeg = new List<Customer_Segmentation__c>();   
     
        if(stringCustSegId != '' &&  stringCustSegId  != null )
        {
            if(lstCustSeg.Product__c != NULL)
            {
                Customer_Segmentation__c custSegProduct = new Customer_Segmentation__c();
                custSegProduct.id = stringCustSegId ;
                custSegProduct.Product__c = Null;
                custSegProduct.Segment_Level__c = lstCustSeg.Segment_Level__c;
                custSegProduct.Segment_Level__c = (lstCustSeg.Product_Group__c != NULL) ? 'Product Group' : custSegProduct.Segment_Level__c;
                custSegProduct.Segment_Level__c = (lstCustSeg.Product_Group__c == NULL && lstCustSeg.Business_Unit__c != NULL) ? 'Business Unit' : custSegProduct.Segment_Level__c;
                custSegProduct.Segment_Level__c = (lstCustSeg.Product_Group__c == NULL && lstCustSeg.Business_Unit__c == NULL) ? 'Division' : custSegProduct.Segment_Level__c;
                
                lstNewCustSeg.add(custSegProduct);                                                                   
            } 
            try{
            Database.update(lstNewCustSeg);
            }Catch(DMLexception e){
                IsError = TRUE;
                ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR,e.getDMLMessage(0)));
                return null;
            }
        } 
                     
        PageReference pageRef = new PageReference(Label.System_CL00020 + stringCustSegId ); 
        return pageRef;
    } 
  
}