src/objects/Customer_Segmentation__c.object
<CustomObject>
    <description>R5 - Custom Object to define Customer Segmentation</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R5 - Lookup to Account Standard Object</description>
        <inlineHelpText>Account means Customer</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Customer_Segmentations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Line_BU__c</fullName>
        <description>R5-Picklist for Business line Bu.</description>
        <label>BU</label>
        <picklist>
            <controllingField>DIV__c</controllingField>
            <picklistValues>
                <fullName>DMDR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMPC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMRO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMSU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPBP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPCP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPCW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPLS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPMV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPSU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PACT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAMP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAOG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAPG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAPI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PASU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PATU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGGA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGGI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGGS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGHV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGSU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGTR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZCCO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZCRE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZCVA</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <description>R5 Business Unit</description>
        <label>Application BU</label>
        <picklist>
            <controllingField>DIV__c</controllingField>
            <picklistValues>
                <fullName>DMDR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMPC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMRO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PATU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGGA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGGI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGGS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Other BU&apos;s</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DIV__c</fullName>
        <description>R5 Division</description>
        <label>DIV</label>
        <picklist>
            <picklistValues>
                <fullName>DM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PG</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Marketing_Segmentation_Year__c</fullName>
        <description>R5 Marketing Segmentation Year</description>
        <inlineHelpText>The year which refers to the segmentation</inlineHelpText>
        <label>Heat Map Segmentation Year</label>
        <picklist>
            <picklistValues>
                <fullName>1991</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1992</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1993</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1994</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1995</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1996</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1997</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1998</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2001</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2002</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2003</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2004</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2005</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2006</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2007</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2008</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2009</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2011</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R5 - Lookup to Product Group</description>
        <inlineHelpText>The enter PG will automatically update both the assigned Division &amp; BU in the above fields for this particular PG.</inlineHelpText>
        <label>Product Group</label>
        <referenceTo>Product_Group__c</referenceTo>
        <relationshipLabel>Account Segmentations</relationshipLabel>
        <relationshipName>Customer_Segmentations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R5 Product</description>
        <inlineHelpText>The enter Product Line will automatically update the assigned Division,  BU and PG in the above fields for this particular Product Line</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Account Segmentations</relationshipLabel>
        <relationshipName>Customer_Segmentations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Segment_Level__c</fullName>
        <inlineHelpText>Segmentation Level must always match to the values entered on the fields DIV,BU,Product Group,Product. For Example;Choose &quot;Division&quot; on segmentation level and populate up to DIV drop down list.</inlineHelpText>
        <label>Segment Level</label>
        <picklist>
            <picklistValues>
                <fullName>Division</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Line</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unique_Check__c</fullName>
        <description>R5 Unique Check</description>
        <label>Unique Check</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Account Segmentation</label>
    <nameField>
        <displayFormat>CS - {0000}</displayFormat>
        <label>Account Segmentation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Segmentations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product_Group__c.object
<CustomObject>
</CustomObject>

src/classes/ClsTriggerCustomerSegmentation.cls
/**   
* TriggerClass :  ClsTriggerCustomerSegmentation
* 
* Update the values of Division & Business Unit based on selected Product group      
* Release R5
*  
* @author  Abiramasundari Radha (Accenture)
* @created 2015-11-21
* @version 1.0
*
* - Created
*/
public without sharing class ClsTriggerCustomerSegmentation extends ClsTriggerVirtual {
    
     public Id abbBasicAdminProfileId = NULL;
     
     public ClsTriggerCustomerSegmentation(){
         
         Profile[] basicProf = [ SELECT ID, Name FROM Profile WHERE Name =: system.label.ABB_Basic_Admin_Profile_Name];
         abbBasicAdminProfileId = (basicProf != NULL && basicProf.size() > 0) ? basicProf[0].Id : NULL;
     }
   /**
* @see IntHelper.beforeTrigger
*/  
    public override void beforeTrigger(ClsWrappers.TriggerContext trgCtx) { 
        customerSegmentationRecordSharing(trgCtx);                       
        assignProductGroupValues(trgCtx); 
    } 
    
@TestVisible 
    private void assignProductGroupValues(ClsWrappers.TriggerContext trgCtx) {  
      
        Set<String> setProductGroupId = new Set<String>();  
        Set<String> setProductId = new Set<String>(); 
        Set<String> setProductName = new Set<String>();
        Map<Id, String> mapProductGroup = new Map<Id, String>(); 
        Map <ID, Product2> productMap = new Map<Id, Product2> ();
        Map <ID, Product_Group__c> productGroupMap = new Map<Id, Product_Group__c> ();
        Map <String, Product_Group__c> productGroupNameAndPGMap = new Map<String, Product_Group__c> ();
        Map<ID,Schema.RecordTypeInfo> MapCS = Customer_Segmentation__c.sObjectType.getDescribe().getRecordTypeInfosById();
        
        if (trgCtx.isInsert || trgCtx.isUpdate) {

            for (sobject sObj : trgCtx.newList) {                   
                // Add the Record to the List - budget     && custSeg.Product__r.Product_Group__c != NULL 
                Customer_Segmentation__c custSeg = (Customer_Segmentation__c) sObj;   
                Customer_Segmentation__c oldSeg  = (trgCtx.isUpdate) ? (Customer_Segmentation__c)trgCtx.oldMap.get(sObj.ID) : NULL; 
                
                if (trgCtx.isUpdate) {
                
                    if (custSeg.Business_Line_BU__c != oldSeg.Business_Line_BU__c && custSeg.Business_Line_BU__c == NULL) {
                        custSeg.Segment_Level__c = 'Division';
                    }
                    
                    if (custSeg.Product_Group__c  != oldSeg.Product_Group__c && custSeg.Product_Group__c == NULL ) {
                    
                        custSeg.Segment_Level__c = (custSeg.Business_Line_BU__c != NULL) ? 'Business Unit' : 'Division';
                    }
                }
                
                if ((custSeg.Product__c != NULL || custSeg.Product_Group__c != Null) && (trgCtx.isInsert || ( trgCtx.isUpdate && (custSeg.Product__c != oldSeg.Product__c || custSeg.Product_Group__c != oldSeg.Product_Group__c ||
                    custSeg.Business_Line_BU__c != oldSeg.Business_Line_BU__c || custSeg.DIV__c != oldSeg.DIV__c)))){                                    
                    if (custSeg.Product__c != NULL) setProductId.add(custSeg.Product__c); 
                    if (custSeg.Product_Group__c != NULL) setProductGroupId.add(custSeg.Product_Group__c);
                }
            }
            
            if (setProductId.size() > 0) {
                productMap = new Map<Id, Product2> ([SELECT Id, Name,Product_Group__c FROM Product2 WHERE ID IN: setProductId AND Product_Group__c != NULL]);
                for (Product2 prod: productMap.Values()) {
                    setProductName.add(String.ValueOf(prod.Product_Group__c));
                }
            }
            
            if (setProductGroupId.size() > 0 || setProductName.size() > 0) {
                productGroupMap = new Map<Id, Product_Group__c > ([ SELECT ID, Name, Business_Unit__c, Business_Unit_Name__c,Division__c
                            FROM Product_Group__c WHERE ID IN :setProductGroupId OR Name IN :setProductName]); 
                for (Product_Group__c prod: productGroupMap.Values()) {
                    productGroupNameAndPGMap.put(prod.Name, prod);
                }
                
            }
            
            for (sobject sObj : trgCtx.newList) {    
                
                Customer_Segmentation__c custSeg = (Customer_Segmentation__c) sObj;
                String Year = '';
                
                if (custSeg.Product__c != NULL && productMap.containskey(custSeg.Product__c) && 
                            productGroupNameAndPGMap.containsKey(String.valueOf(productMap.get(custSeg.Product__c).Product_Group__c))) {
                    
                    Product_Group__c pg = productGroupNameAndPGMap.get(String.valueOf(productMap.get(custSeg.Product__c).Product_Group__c));               
                    custSeg.Business_Line_BU__c = pg.Business_Unit__c;
                    custSeg.DIV__c = pg.Division__c;
                    custSeg.Product_Group__c = pg.Id;
                    
                } else if (custSeg.Product_Group__c != NULL && productGroupMap.containskey(custSeg.Product_Group__c)) {
                    custSeg.Business_Line_BU__c = productGroupMap.get(custSeg.Product_Group__c).Business_Unit__c;
                    custSeg.DIV__c = productGroupMap.get(custSeg.Product_Group__c).Division__c;
                }else{}
                
                String segment = '';
                if(MapCS.get(custSeg.RecordTypeId).getName().containsIgnoreCase(label.Customer_Segmentation_Record_Type_Name_1) && custSeg.Marketing_Segmentation_Year__c != NULL){
                    Year= custSeg.Marketing_Segmentation_Year__c;
                } else {
                    segment = custSeg.Segment_Level__c;
                }
                   
               
                custSeg.Unique_Check__c = (custSeg.DIV__c != NULL) ? custSeg.DIV__c: '';
                if (custSeg.Business_Line_BU__c != NULL) {
                custSeg.Unique_Check__c += custSeg.Business_Line_BU__c;
                }
                
                if (custSeg.Product_Group__c != NULL) {
                    custSeg.Unique_Check__c += custSeg.Product_Group__c ;
                }
                if (custSeg.Product__c != NULL) {
                    custSeg.Unique_Check__c += custSeg.Product__c;
                }
                
                if (custSeg.Account__c != NULL) {
                    custSeg.Unique_Check__c += custSeg.Account__c;
                }
                custSeg.Unique_Check__c += custSeg.RecordTypeId + Year+segment;
            }
        
        }
    }
    

/**     
Method : customerSegmentationRecordSharing - Method to create/view the customer segmentation record only by Account team member
@author  Ayiravalli Arasu(Accenture)
*/
@TestVisible   
    private void customerSegmentationRecordSharing(ClsWrappers.TriggerContext trgCtx) {
      if(trgCtx.isInsert && trgCtx.isBefore){
            Set<ID> setAccTeamUserIds = new Set<ID>(); //capture the Account team users ids
            Set<ID> setAccIds = new Set<ID>(); //capture the Account Ids
            Map<ID, Set<Id>> mapUsersId = new Map<ID, Set<Id>>();
            Id labelId = Label.CL00075;
            Id userProfileId = Userinfo.getProfileid();
            Id currUser = UserInfo.getUserId();
            
            for(sobject so :trgCtx.newList){
                Customer_Segmentation__c CS = (Customer_Segmentation__c)so;
                setAccIds.add(CS.Account__c);
            }
            for(AccountTeamMember atm : [SELECT id, UserId, AccountId FROM AccountTeamMember where AccountId IN:setAccIds ]){
                if(!mapUsersId.containsKey(atm.AccountId)){
                    mapUsersId.put(atm.AccountId, new Set<ID>());
                }
                mapUsersId.get(atm.AccountId).add(atm.UserId);
            } 
            
            Map<ID, Account> accMap = new Map <Id, Account> ([SELECT ID, OwnerID FROM Account WHERE ID IN :setAccIds]);
             
            for(sobject so : trgCtx.newList){
                Customer_Segmentation__c CS = (Customer_Segmentation__c)so;
                if(CS.Account__c != NULL && mapUsersId.containsKey(CS.Account__c)){
                    setAccTeamUserIds = mapUsersId.get(CS.Account__c);                  
                }
                if(CS.Account__c != NULL && !setAccTeamUserIds.contains(currUser) && currUser != accMap.get(CS.Account__c).OwnerId && abbBasicAdminProfileId != userProfileId)
                {
                so.addError(System.label.Customer_Segmentation_Error_Message);
                }
            }
           
        } 
     }  
 }