src/objects/Customer_Segmentation__c.object
<CustomObject>
    <description>R5 - Custom Object to define Customer Segmentation</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R5 - Lookup to Account Standard Object</description>
        <inlineHelpText>Account means Customer</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Customer_Segmentations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Line_BU__c</fullName>
        <description>R5-Picklist for Business line Bu.</description>
        <label>BU</label>
        <picklist>
            <controllingField>DIV__c</controllingField>
            <picklistValues>
                <fullName>DMDR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMMG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMPC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMRO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMSU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPBP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPCP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPCW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPLS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPMV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPSU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PACT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAMP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAOG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAPG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAPI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PASU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PATU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGGA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGGI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGGS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGHV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGSU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGTR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZCCO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZCRE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZCVA</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Marketing_Segmentation_Year__c</fullName>
        <description>R5 Marketing Segmentation Year</description>
        <inlineHelpText>The year which refers to the segmentation</inlineHelpText>
        <label>Heat Map Segmentation Year</label>
        <picklist>
            <picklistValues>
                <fullName>1991</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1992</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1993</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1994</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1995</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1996</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1997</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1998</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2001</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2002</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2003</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2004</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2005</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2006</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2007</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2008</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2009</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2011</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PIE_Customer_Marketing_Segmentation__c</fullName>
        <description>R5 - PIE Customer Marketing Segmentation</description>
        <inlineHelpText>ABB position at the Account</inlineHelpText>
        <label>Heat Map</label>
        <picklist>
            <picklistValues>
                <fullName>Preferred Supplier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supplier amongst others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weak or not approved supplier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not applicable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Segmentation</label>
    <nameField>
        <displayFormat>CS - {0000}</displayFormat>
        <label>Account Segmentation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Segmentations</pluralLabel>
    <recordTypes>
        <fullName>Customer_Marketing_Segmentation</fullName>
        <active>true</active>
        <description>Segmentation of the account from a  product marketing perspective, to monitor the ABB ranking as a supplier for each Division/BU (Heat Maps)</description>
        <label>Heat Maps</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ClsCustSegmChart.cls
/**   
* Controller : ClsCustSegmChart
* Release R5
*  
* @author  MohanRaj Kasinathan (Accenture)
* @created  2015-12-01* @version 1.0
*
*/ 
public class ClsCustSegmChart {
    
    private Map<String,Integer> ChartMap = new Map<String,Integer>();
    public List<chartClass> data{get;set;}
    
    private Map<String, Integer>  segmentWithScoreMap = new Map<String, Integer>();
    public Item[] data1 {get;set;}
    public String stackFieldStr;
/**    
  * constructor
*/  
    public ClsCustSegmChart(ApexPages.StandardController controller) {
        
        String accID = ApexPages.CurrentPage().getPArameters().get(Label.System_CL00018); // Label.System_CL00018 => id
        Account acc = (Account)controller.getRecord();
        data = new List<chartClass>();
        data1 = new List<Item>();
        String st = Label.data_Stack_Fields; //data1,data2,data3,data4,data5,data6
        stackFieldStr = st.substring(0, st.LastIndexOf(Label.CL00069));
        Integer remLimit =  limits.getLimitQueryRows() - limits.getQueryRows();
        String pickVal = Label.Sys_Customer_Segmentation_PIE_Customer_Marketing_Segmentation;
        String[] valueArr = pickVal.split(Label.CL00069);
        segmentWithScoreMap = new Map<String, Integer>{valueArr[0]=>1, valueArr[1]=>2, valueArr[2]=>3, valueArr[3]=>4, valueArr[4]=>5};
        if (accID != NULL) {
              
            List<AggregateResult> lstcustseg = [SELECT Business_Line_BU__c, Marketing_Segmentation_Year__c, PIE_Customer_Marketing_Segmentation__c
                  FROM Customer_Segmentation__c WHERE Business_Line_BU__c != NULL AND Account__c = :accID and Marketing_Segmentation_Year__c != NULL AND 
                      RecordType.DeveloperName = 'Customer_Marketing_Segmentation' 
                      GROUP BY Marketing_Segmentation_Year__c, Business_Line_BU__c, PIE_Customer_Marketing_Segmentation__c LIMIT :remLimit]; 
            
            for (AggregateResult seg: lstcustseg ) {
                
                chartClass chart = new chartClass();
                chart.BUandSegmentYear =  String.valueOf(seg.get(Label.Sys_Business_Line_BU)) + Label.System_hyphen + String.valueOf(seg.get(Label.Sys_Marketing_Segmentation_Year))  ;
                chart.score = segmentWithScoreMap.containsKey(String.valueOf(seg.get(Label.Sys_PIE_Customer_Marketing_Segmentation))) ? segmentWithScoreMap.get(String.valueOf(seg.get(Label.Sys_PIE_Customer_Marketing_Segmentation))): 0;
                //data.add(chart);
                data1.add(new Item(chart.BUandSegmentYear,chart.score));
                   
            }
          
       }
         
    }
/**    
   * wrapper
 */  
    public class chartClass{  
        public Integer score {get;set;}
        public String BUandSegmentYear {get;set;}
    } 
/**    
  * Data fields
*/    
    public String fields {
        get {
            return stackFieldStr; //data1,data2,data3,data4,data5
        }
    }
 /**    
  * Titles
 */ 
    public String titles {
        get {
           return Label.Sys_Customer_Segmentation_PIE_Customer_Marketing_Segmentation;    //Not applicable, Others, Weak or not approved supplier,Supplier amongst others,Preferred Supplier       
        }
    }
    
/**
* Inner class used to display value in chart
*/
    public with sharing class Item {

        private String name;
        private Decimal per;
        private Integer data1;
        private Integer data2;
        private Integer data3;
        private Integer data4;
        private Integer data5;
        private String data;
        private String lbl;
/**
* Item values for chart
*/     
        Item(String name, Decimal per) {
            this.name = name;
            integer perval =  Math.round(per);
            
            if(perval == 1 )
            {
                data1 = perval;
                data2 = 0;
                data3 = 0; 
                data4 = 0;
                data5 = 0;
            }
            else if(perval == 2)
            {
                data1 = 0;
                data2 = perval;
                data3 = 0; 
                data4 = 0;
                data5 = 0; 
            }
            else if(perval == 3)
            {
                data1 = 0;
                data2 = 0;
                data3 = perval; 
                data4 = 0;
                data5 = 0; 
            }       
            else if(perval == 4)
            {
                data1 = 0;
                data2 = 0;
                data3 = 0; 
                data4 = perval;
                data5 = 0; 
            }
            else if(perval == 5)
            {
                data1 = 0;
                data2 = 0;
                data3 = 0; 
                data4 = 0;
                data5 = perval; 
            }           
            else
            {
                data1 = 0;
                data2 = 0;
                data3 = 0; 
                data4 = 0;
                data5 = 0;
            }
            
            lbl = name;
            data = string.valueof(perval);
                 
        }
        
    }
  
}