src/objects/End_User_Project__c.object
<CustomObject>
    <description>Only the Project Owner and Account Manager should be able to change the status of the project (Not the opportunity owner)</description>
    <fields>
        <fullName>Account_End_User__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>- Account - End User (should be selected from account)</description>
        <label>Account - End User</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notEqual</operation>
                <value>&quot;ABB ICV&quot;, &quot;External non-buying Account&quot;</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>End User Projects</relationshipLabel>
        <relationshipName>End_User_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>End User Project</label>
    <nameField>
        <label>End User Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>End User Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>

 
 

    <fields>
        <fullName>Account_End_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Account</description>
        <inlineHelpText>This Account lookup is used for End User Accounts.</inlineHelpText>
        <label>Account - End User</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities - End User</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
	
    <fields>
        <fullName>Confidence_Level__c</fullName>
        <description>Sets the level of confidence that Expected Award Date is still achievable</description>
        <inlineHelpText>Sets the level of confidence that Expected Award Date is still achievable</inlineHelpText>
        <label>Confidence Level</label>
        <picklist>
            <picklistValues>
                <fullName>No Delay Expected</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Slight Delay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Substantial Delay Expected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
   
    <fields>
        <fullName>End_User_Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to active End User Projects only</description>
        <inlineHelpText>Please select a End User Project (mandatory for Regular Opportunities, optional for Fast Track Opportunities).
Make sure that you set the Project Site Country first as this will be a filter for the End User Projects.</inlineHelpText>
        <label>End User Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>End_User_Project__c.End_User_Project_Status__c</field>
                <operation>notEqual</operation>
                <value>Closed, Cancelled</value>
            </filterItems>
            <filterItems>
                <field>$Source.Account_End_User__c</field>
                <operation>equals</operation>
                <valueField>End_User_Project__c.Account_End_User__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.End_User_Project_Site_Country__c</field>
                <operation>equals</operation>
                <valueField>End_User_Project__c.End_User_Project_Site_Country__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>End_User_Project__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
<fields>
        <fullName>ABB_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Refers to the Sales, Project Execution or Manufacturing unit (Business Activity Location – BAL) that will lead the project in terms of final bid preparation towards the customer and that will book the order if we are awarded.</inlineHelpText>
        <label>ABB Location – Bidding unit</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND 3 AND 4 AND 5 AND 6</booleanFilter>
            <filterItems>
                <field>ABB_Location__c.Deleted__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>ABB_Location__c.Data_Load_Year__c</field>
                <operation>notEqual</operation>
                <value>2015</value>
            </filterItems>
            <filterItems>
                <field>ABB_Location__c.BU__c</field>
                <operation>notEqual</operation>
                <value>ZCCO, ZCRE, ZCVA</value>
            </filterItems>
            <filterItems>
                <field>ABB_Location__c.DIV__c</field>
                <operation>notEqual</operation>
                <value>ZC</value>
            </filterItems>
            <filterItems>
                <field>ABB_Location__c.Activity__c</field>
                <operation>notEqual</operation>
                <value>Admin/Corporate, Other, R&amp;D, Warehouse or Logistics, Training</value>
            </filterItems>
            <filterItems>
                <field>ABB_Location__c.Activity__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <infoMessage>Please use the filters to reduce the number of fields in the lookup window.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>ABB_Location__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Value__c</fullName>
        <description>Holds the overall Opportunity Value of an opportunity</description>
        <label>Opportunity Value</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Probability_Verification__c</fullName>
        <description>Shows how Probability compares to the selected Sales Pursuit Progress value.</description>
        <formula>IF( Probability  =  Stage_Detail_Percent__c ,
  IMAGE(&quot;/img/samples/rating3.gif&quot;,&quot;Rating Does Matching&quot;),

  IF( Probability  &lt;  Stage_Detail_Percent__c, 
   IMAGE(&quot;/img/samples/rating1.gif&quot;, &quot;Probability Too Low&quot;) &amp; &quot; Probability Seems Low&quot;,

    IF( Probability  &gt;  Stage_Detail_Percent__c, 
     IMAGE(&quot;/img/samples/rating5.gif&quot;, &quot;Probability Too High&quot;) &amp; &quot; Probability Seems High&quot;,
     &quot;&quot;
    )
  )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Probability Verification</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Pursuit_Progress__c</fullName>
        <description>Dependent picklist for Sales Pursuit Progress</description>
        <inlineHelpText>Please choose the Stage detail from picklist</inlineHelpText>
        <label>Sales Pursuit Progress</label>
        <picklist>
            <controllingField>StageName</controllingField>
            <picklistValues>
                <fullName>Opportunity Is Captured</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity Pursuit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold (Pursuit)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Budget Proposal Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFQ Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bidding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Preference To Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold (Bidding)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solution Presented To Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Budget Proposal Submitted (Bidding)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bid Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Is Neutral To Supplier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Preference To ABB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold (Negotiation)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LOI To Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Buying Preference To Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Position Is Neutral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clear Buying Signal To ABB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ABB Preferred &amp; Shows Clear Signals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LOI To ABB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSED Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSED Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSED Lost Without ABB Bid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSED Won</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Specific_Opportunity_Info__c</fullName>
        <description>Text field for additional, specific infos about the opportunity (will be added automatically to Opportunity name in the format of [Country Code]-[Account Name]-[Specific Opportunity Info].</description>
        <inlineHelpText>Text field for additional, specific infos about the opportunity (will be added automatically to Opportunity name in the format of [Country Code]-[Account Name]-[Specific Opportunity Info].</inlineHelpText>
        <label>Opportunity Name (free text)</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ClsTriggerOpptyCompetitorHandlerTest.cls
/**
*  This test class used to test class ClsTriggerOpptyCompetitorHandler.
*
@author Aswini Arasu
@created 2015-12-21
@version 1.0  
*/
@istest(SeeAllData = False)
public class ClsTriggerOpptyCompetitorHandlerTest{
   static testMethod void  enforceSingleWinnerOnInsertTest(){
     Profile p = [SELECT id FROM profile WHERE name = 'System Administrator'];
     User u1 = new User(alias = 'chfree01',
                           email = 'chatterfreeuser101@testorg.com',
                           emailencodingkey = 'UTF-8',
                           lastname = 'Testing',
                           companyname = 'testorg',
                           languagelocalekey = 'en_US',
                           localesidkey = 'en_US',
                           profileId = p.Id,
                           timezonesidkey = 'America/Los_Angeles',
                           username = 'chatterfreeuser101@testorg.com');
    insert u1;
    System.runAs(u1){
    Test.StartTest();
    Account a = new Account();
    a.Name = 'test';
    a.BillingStreet = 'dajie';
    a.BillingCity = 'berlin';
    a.BillingState = 'Berlin';
    a.BillingPostalCode = '20012';
    a.BillingCountry = 'Germany';
    
    Account a1 = new Account();
    a1.Name = 'test1';
    //a.RecordtypeId = ga.id;
    a1.BillingStreet = 'dajie';
    a1.BillingCity = 'berlin';
    a1.BillingState = 'Berlin';
    a1.BillingPostalCode = '20012';
    a1.BillingCountry = 'Germany';
    
    List<Account> acc = new List<Account>();
    acc.add(a);
    acc.add(a1);
    insert acc;
      
    Opportunity o = new Opportunity();
    o.AccountId = a.id;
    //o.RecordtypeId = rg.id;
    //o.Account_End_User__c =a.id;
    //o.End_User_Project__c = 'Testct';
    o.Name = 'ES-Acciona, S.A-Test';
    o.StageName = 'Prospecting';
    o.Sales_Pursuit_Progress__c = 'Opportunity Is Captured';
    o.Specific_Opportunity_Info__c ='Test';
    o.Confidence_Level__c ='No Delay Expected';
    //o.Probability_Verification__c = '';
    //o.ABB_Location__c ='Test';
    o.CloseDate = date.today();
    //o.Opportunity_Value__c = '10';
    //o.Technical_Amount_USD = ''
    o.Industry_Usage__c = 'BLD.10.1';
    //o.Channel_Class__c = 'Direct Sales to End Customer / End User';
    o.Customer_Buying_Path__c = 'Awareness';
    o.Opportunity_Winner__c = a.id;
    insert o;
    
   Competitor__c c = new Competitor__c();
   c.Competitor__c = a.id;
   c.Opportunity__c = o.id;
   c.Winning_Company__c = True;
   insert c;
    
   Competitor__c c1 = new Competitor__c();
   c1.Competitor__c = a1.id;
   c1.Opportunity__c = o.id;
   c1.Customer_Relationship__c = 'Strong';
   c1.Winning_Company__c = True;
   insert c1;
   
   /*List<Competitor__c> comp = new List<Competitor__c>();
   comp.add(c);
   comp.add(c1);
   insert comp;*/
   
   //Test.StartTest();
   Competitor__c com = [Select Id,Winning_Company__c from Competitor__c where id=:c1.id];
   Test.StopTest();
     System.assertEquals(com.Winning_Company__c ,True);
   }
   }  
   
   static testMethod void  enforceSingleWinnerOnUpdateTest(){
    Profile p = [SELECT id FROM profile WHERE name = 'System Administrator'];
    User u1 = new User(alias = 'chfree01',
                           email = 'chatterfreeuser101@testorg.com',
                           emailencodingkey = 'UTF-8',
                           lastname = 'Testing',
                           companyname = 'testorg',
                           languagelocalekey = 'en_US',
                           localesidkey = 'en_US',
                           profileId = p.Id,
                           timezonesidkey = 'America/Los_Angeles',
                           username = 'chatterfreeuser101@testorg.com');
    insert u1;
    System.runAs(u1){
    Test.StartTest();
    Account a = new Account();
    a.Name = 'test';
    a.BillingStreet = 'dajie';
    a.BillingCity = 'berlin';
    a.BillingState = 'Berlin';
    a.BillingPostalCode = '20012';
    a.BillingCountry = 'Germany';
    
    Account a1 = new Account();
    a1.Name = 'test1';
    //a.RecordtypeId = ga.id;
    a1.BillingStreet = 'dajie';
    a1.BillingCity = 'berlin';
    a1.BillingState = 'Berlin';
    a1.BillingPostalCode = '20012';
    a1.BillingCountry = 'Germany';
    
    List<Account> acc = new List<Account>();
    acc.add(a);
    acc.add(a1);
    insert acc;
    
    Opportunity o = new Opportunity();
    o.AccountId = a.id;
    //o.Account_End_User__c =a.id;
    //o.End_User_Project__c = 'Testct';
    o.Name = 'ES-Acciona, S.A-Test';
    o.StageName = 'Prospecting';
    o.Sales_Pursuit_Progress__c = 'Opportunity Is Captured';
    o.Specific_Opportunity_Info__c ='Test';
    o.Confidence_Level__c ='No Delay Expected';
    //o.Probability_Verification__c = '';
    //o.ABB_Location__c ='Test';
    o.CloseDate = date.today();
    //o.Opportunity_Value__c = '10';
    //o.Technical_Amount_USD = ''
    o.Industry_Usage__c = 'BLD.10.1';
   // o.Channel_Class__c = 'Direct Sales to End Customer / End User';
    o.Customer_Buying_Path__c = 'Awareness';
    o.Opportunity_Winner__c = a.id;
    insert o;
    
   Competitor__c c = new Competitor__c();
   c.Competitor__c = a.id;
   c.Opportunity__c = o.id;
   c.Winning_Company__c = True;
   insert c;
  
   Competitor__c c1 = new Competitor__c();
   c1.Competitor__c = a1.id;
   c1.Opportunity__c = o.id;
   c1.Customer_Relationship__c = 'Strong';
   c1.Winning_Company__c = True;
   insert c1;
   
   /*List<Competitor__c> comp = new List<Competitor__c>();
   comp.add(c);
   comp.add(c1);
   insert comp;*/
 
   //Test.StartTest();  
   c.Winning_Company__c = True;
   update c;
   Test.stopTest();
   Competitor__c com = [Select Id,Winning_Company__c from Competitor__c where id=:c.id];
   System.assertEquals(com.Winning_Company__c ,True);
   
   }}
   
    static testMethod void  enforceSingleWinnerOnDelete(){
     Profile p = [SELECT id FROM profile WHERE name = 'System Administrator'];
     User u1 = new User(alias = 'chfree01',
                           email = 'chatterfreeuser101@testorg.com',
                           emailencodingkey = 'UTF-8',
                           lastname = 'Testing',
                           companyname = 'testorg',
                           languagelocalekey = 'en_US',
                           localesidkey = 'en_US',
                           profileId = p.Id,
                           timezonesidkey = 'America/Los_Angeles',
                           username = 'chatterfreeuser101@testorg.com');
    insert u1;
    System.runAs(u1){
    Test.StartTest();
    Account a = new Account();
    a.Name = 'test';
    a.BillingStreet = 'dajie';
    a.BillingCity = 'berlin';
    a.BillingState = 'Berlin';
    a.BillingPostalCode = '20012';
    a.BillingCountry = 'Germany';
  
    Account a1 = new Account();
    a1.Name = 'test1';
    //a.RecordtypeId = ga.id;
    a1.BillingStreet = 'dajie';
    a1.BillingCity = 'berlin';
    a1.BillingState = 'Berlin';
    a1.BillingPostalCode = '20012';
    a1.BillingCountry = 'Germany';
    
    List<Account> acc = new List<Account>();
    acc.add(a);
    acc.add(a1);
    insert acc;
    
    Opportunity o = new Opportunity();
    o.AccountId = a.id;
    //o.Account_End_User__c =a.id;
    //o.End_User_Project__c = 'Testct';
    o.Name = 'ES-Acciona, S.A-Test';
    o.StageName = 'Prospecting';
    o.Sales_Pursuit_Progress__c = 'Opportunity Is Captured';
    o.Specific_Opportunity_Info__c ='Test';
    o.Confidence_Level__c ='No Delay Expected';
    //o.Probability_Verification__c = '';
    //o.ABB_Location__c ='Test';
    o.CloseDate = date.today();
    //o.Opportunity_Value__c = '10';
    //o.Technical_Amount_USD = ''
    o.Industry_Usage__c = 'BLD.10.1';
    o.Channel_Class__c = 'Direct Sales to End Customer / End User';
    o.Customer_Buying_Path__c = 'Awareness';
    o.Opportunity_Winner__c = a.id;
    insert o;
    
   Competitor__c c = new Competitor__c();
   c.Competitor__c = a.id;
   c.Opportunity__c = o.id;
   c.Winning_Company__c = True;
   insert c;
    
   Competitor__c c1 = new Competitor__c();
   c1.Competitor__c = a1.id;
   c1.Opportunity__c = o.id;
   c1.Customer_Relationship__c = 'Strong';
   c1.Winning_Company__c = True;
   insert c1;

   /*List<Competitor__c> comp = new List<Competitor__c>();
   comp.add(c);
   comp.add(c1);
   insert comp;*/
    
 
   //Test.StartTest();  
   Delete c1;
   Test.stopTest();
   Opportunity Opp = [Select id ,Opportunity_Winner__c from Opportunity where id =:o.id];
   System.assertEquals(opp.Opportunity_Winner__c,NULL);
   }
   }
   
   }