src/objects/End_User_Project__c.object
<CustomObject>
    <description>Only the Project Owner and Account Manager should be able to change the status of the project (Not the opportunity owner)</description>
    <fields>
        <fullName>End_User_Project_Status__c</fullName>
        <description>End User Project Status</description>
        <label>End User Project Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>End User Project</label>
    <nameField>
        <label>End User Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>End User Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>

 
 

	
   
    <fields>
        <fullName>End_User_Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to active End User Projects only</description>
        <inlineHelpText>Please select a End User Project (mandatory for Regular Opportunities, optional for Fast Track Opportunities).
Make sure that you set the Project Site Country first as this will be a filter for the End User Projects.</inlineHelpText>
        <label>End User Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>End_User_Project__c.End_User_Project_Status__c</field>
                <operation>notEqual</operation>
                <value>Closed, Cancelled</value>
            </filterItems>
            <filterItems>
                <field>$Source.Account_End_User__c</field>
                <operation>equals</operation>
                <valueField>End_User_Project__c.Account_End_User__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.End_User_Project_Site_Country__c</field>
                <operation>equals</operation>
                <valueField>End_User_Project__c.End_User_Project_Site_Country__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>End_User_Project__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
   <fields>
        <fullName>Product_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to PG / BU / Div, filtered on RecType &quot;Product Group&quot;</description>
        <inlineHelpText>This field will be auto populated by the offering flagged as Primary Product Group. If you haven’t selected an offering yet, please add it. If you don’t know which product/service will be offered, but you know the Product Group, you can enter it directly.</inlineHelpText>
        <label>Product Group</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product_Group__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Product Group</value>
            </filterItems>
            <filterItems>
                <field>Product_Group__c.Data_Load_Year__c</field>
                <operation>notEqual</operation>
                <value>2015</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product_Group__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Specific_Opportunity_Info__c</fullName>
        <description>Text field for additional, specific infos about the opportunity (will be added automatically to Opportunity name in the format of [Country Code]-[Account Name]-[Specific Opportunity Info].</description>
        <inlineHelpText>Text field for additional, specific infos about the opportunity (will be added automatically to Opportunity name in the format of [Country Code]-[Account Name]-[Specific Opportunity Info].</inlineHelpText>
        <label>Opportunity Name (free text)</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product_Group__c.object
<CustomObject>
</CustomObject>

src/classes/ClsTriggerEndUserProjectHandler_Test.cls
/**
*	Test class is for ClsTriggerEndUserProjectHandler.
*
@author Sherlock Feng
@created 2015-03-24
@version 1.0
@since 29.0 (Force.com ApiVersion)
*
@changelog
* 2015-03-24 Sherlock Feng <sherlock.feng@itbconsult.com>
* - Created
*/
@isTest
private class ClsTriggerEndUserProjectHandler_Test {

    static testMethod void myTest() {
        Test.startTest();
        
        End_User_Project__c eup = new End_User_Project__c();
        eup.End_User_Project_Status__c = 'Open';
        eup.Name = 'test';
        insert eup;
        
        Opportunity opp = new Opportunity();
        for(Opportunity o : [SELECT AccountId, Name, CurrencyIsoCode, Product_Group__c, StageName, Specific_Opportunity_Info__c, End_User_Project__c, CloseDate FROM Opportunity limit 1]){
        	o.End_User_Project__c = eup.Id;
        	o.CloseDate = Date.valueOf('2015-05-25');
        	update o;
        	opp = o;
        }
        
        eup.End_User_Project_Status__c = 'Closed';
        update eup;
        
        system.assert(true);
        Test.stopTest();
    }
    
}