src/objects/ERP_Reference_Data__c.object
<CustomObject>
    <description>R3v1 - This custom object holds LSO Reference Data for Accounts.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R3v1 - Custom Lookup field to Account object to display the account reference in LSO Reference Data.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>LSO_Reference_Datas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LBU__c</fullName>
        <description>R3 -LBU</description>
        <label>LBU</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LSO_ERP_Mapping_Value__c</fullName>
        <description>R3 - Text field to hold the value of LSO from ERP Mapping table</description>
        <label>LSO</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LSO__c</fullName>
        <description>R3 - LSO</description>
        <label>LSO</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Local Reference Data</label>
    <nameField>
        <displayFormat>ERP-REF-DATA-{0000}</displayFormat>
        <label>LSO Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Local Reference Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>

	    <fields>
        <fullName>Account_Customer_LSO_Reference_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R3V1 - Lookup to LSO Reference Data</description>
        <label>Account Customer LSO Reference Data</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>ERP_Reference_Data__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>ERP_Reference_Data__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
 
 

    <fields>
        <fullName>Account_End_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Account</description>
        <inlineHelpText>This Account lookup is used for End User Accounts.</inlineHelpText>
        <label>Account - End User</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities - End User</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
	
   
    <fields>
        <fullName>End_User_LSO_Reference_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R3V1 - Lookup to LSO Reference Data</description>
        <label>End User LSO Reference Data</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ERP_Reference_Data__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account_End_User__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>ERP_Reference_Data__c</referenceTo>
        <relationshipLabel>Opportunities (End User LSO Reference Data)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Partner_LSO_Reference_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R3V1 - Lookup to LSO Reference Data</description>
        <label>Primary Partner LSO Reference Data</label>
        <referenceTo>ERP_Reference_Data__c</referenceTo>
        <relationshipLabel>Opportunities (Primary Partner LSO Reference Data)</relationshipLabel>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
<fields>
        <fullName>Default_BU__c</fullName>
        <description>R4 - Default BU</description>
        <label>Default LBU</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Country_ISO_Code__c</fullName>
        <description>R4 - Default Country ISO Code</description>
        <label>Default Country ISO Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
<fields>
        <fullName>Default_LSO__c</fullName>
        <description>R4 - Default LSO</description>
        <label>Default LSO</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/ClsBatch_LSOUpdateOnOppty.cls
/**
 *  batch job to auto-populate LSO reference data info on Opportunity record 
 *  from associated 
 *  Account Customer, Account End User and Primary Partner Account
 *
 @  author Shankar Anand
 @  created 2015-110-07
 @  version 1.0
 */
 
global class ClsBatch_LSOUpdateOnOppty implements Database.Batchable<sObject>, Database.stateful{
    global String query;
    global Set<Id> sucsIds = new Set<Id>();
    global Set<String> errIds = new Set<String>();
    global Set<Opportunity> totalProcesd = new Set<Opportunity>();
           
    global Database.QueryLocator start(Database.BatchableContext BC) {
        
        if(!Test.isRunningTest()){
        query = 'Select Id,Name,OwnerId,AccountId,Account_End_User__c,Account_Customer_LSO_Reference_Data__c,End_User_LSO_Reference_Data__c,Primary_Partner_LSO_Reference_Data__c From Opportunity';
            }
        else{
            query = 'Select Id,Name,OwnerId,AccountId,Account_End_User__c,Account_Customer_LSO_Reference_Data__c,End_User_LSO_Reference_Data__c,Primary_Partner_LSO_Reference_Data__c From Opportunity LIMIT 1';
            }
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, list<Sobject> list_sobjects){ 
      Map<Id,Opportunity> opptyMap = new Map<Id,Opportunity>();
      for(Sobject sobj : list_sobjects) {
          Opportunity oppty = (Opportunity)sobj;
          opptyMap.put(oppty.Id,oppty);
      }
      
      String userLSO;
      String userLSO1;
      String accLSO;
      String primPartnerLSO;
      List<Opportunity> updatedOpptyList = new List<Opportunity>();
            
      Map<Id,OpportunityPartner> partnerMap = new Map<Id,OpportunityPartner>();     
      Map<Id,Opportunity> oldOpptyMap = new map<Id,Opportunity>();
      Map<Id,Account> accountCustMap = new map<Id,Account>([Select Id, Name, (Select Id, name,LBU__c,LSO__c,LSO_ERP_Mapping_Value__c from LSO_Reference_Datas__r) from Account where id in (Select accountId from Opportunity where id in :opptyMap.keySet())]);
      Map<Id,Account> accountEndUserMap = new map<Id,Account>([Select Id, Name, (Select Id, name,LBU__c,LSO__c,LSO_ERP_Mapping_Value__c from LSO_Reference_Datas__r) from Account where id in (Select Account_End_User__c from Opportunity where id in :opptyMap.keySet())]);
      Map<Id,User> userMap = new map<Id,User>([Select Id, Name,Default_BU__c,Default_LSO__c,Default_Country_ISO_Code__c from User where Id in (Select ownerId from Opportunity where id in :opptyMap.keySet())]);          
      Map<Id,OpportunityPartner> primPartners= new map<Id,OpportunityPartner>([Select Id,role,isPrimary,OpportunityId,accountToId from OpportunityPartner where isPrimary = true and OpportunityId in :opptyMap.keySet() LIMIT 50000]);
      Map<Id,Account> primPartnerAccnts = new map<Id,Account>([Select Id, Name, (Select Id, name,LBU__c,LSO__c,LSO_ERP_Mapping_Value__c from LSO_Reference_Datas__r) from Account where id in (Select accountToId from OpportunityPartner where id in :primPartners.keySet()) LIMIT 50000]);
     
        for(Opportunity oppty : opptyMap.values()) { 
            Opportunity oppy = new Opportunity(Id = oppty.Id);
            Account act = accountCustMap.get(oppty.accountId);
            Account eua = accountEndUserMap.get(oppty.Account_End_User__c);
               
            for(OpportunityPartner prtnr:primPartners.values()){
               if(prtnr.opportunityId == oppty.id){
                  partnerMap.put(oppty.Id,prtnr);
                  }
              }
                
            User usr = userMap.get(oppty.ownerid);
            if(usr!=null && usr.Default_BU__c!=null){
              userLSO = usr.Default_LSO__c+usr.Default_BU__c;
            }
            else{
              if(usr!=null)
              userLSO1 = usr.Default_LSO__c;
            }
                
            if(act!=null){  
              List<ERP_Reference_Data__c> acLsoRefList = new List<ERP_Reference_Data__c>();
              acLsoRefList.addall(act.LSO_Reference_Datas__r);
                
              if(acLsoRefList.size()>0){
                for(ERP_Reference_Data__c lrd:act.LSO_Reference_Datas__r){
                    accLSO = String.valueof(lrd.LSO__c)+String.valueof(lrd.LBU__c);
                    if(usr!= null && usr.Default_BU__c!=null && lrd.LBU__c!= null && userLSO!=null && userLSO.equalsIgnoreCase(accLSO)){
                        oppy.Account_Customer_LSO_Reference_Data__c = lrd.id;
                        break;
                    }
                    else if(usr!= null && usr.Default_BU__c == null && lrd.LBU__c == null && userLSO1!=null && userLSO1.equalsIgnoreCase(String.valueof(lrd.LSO__c))){
                        oppy.Account_Customer_LSO_Reference_Data__c = lrd.id;
                        break;
                    }
                    else{
                    oppy.Account_Customer_LSO_Reference_Data__c = null;
                    }
                }
               }
              else{
                oppy.Account_Customer_LSO_Reference_Data__c = null;
              }
            }
                
                
            if(eua!=null){
                List<ERP_Reference_Data__c> aeuLsoRefList = new List<ERP_Reference_Data__c>();
                aeuLsoRefList.addall(eua.LSO_Reference_Datas__r);
           
              if(aeuLsoRefList.size()>0){
                for(ERP_Reference_Data__c lrd:eua.LSO_Reference_Datas__r){
                    accLSO = String.valueof(lrd.LSO__c)+String.valueof(lrd.LBU__c);
                    if(usr!= null && usr.Default_BU__c!=null &&  lrd.LBU__c!= null && userLSO!=null && userLSO.equalsIgnoreCase(accLSO)){
                        oppy.End_User_LSO_Reference_Data__c = lrd.id;
                        break;
                    }
                    else if(usr!= null && usr.Default_BU__c==null &&  lrd.LBU__c == null && userLSO1!=null && userLSO1.equalsIgnoreCase(String.valueof(lrd.LSO__c))){
                        oppy.End_User_LSO_Reference_Data__c = lrd.id;
                        break;
                    }
                    else{
                    oppy.End_User_LSO_Reference_Data__c  = null;
                    }
                }
               }
              else{
                oppy.End_User_LSO_Reference_Data__c  = null;
              }
            }
        
            
            if(partnerMap!=null){
                OpportunityPartner op = partnerMap.get(oppy.id);
                List<ERP_Reference_Data__c> partnerLsoRefList = new List<ERP_Reference_Data__c>();
                if(primPartnerAccnts!=null && op!=null && primPartnerAccnts.get(op.accountToId)!=null)
                    partnerLsoRefList.addall(primPartnerAccnts.get(op.accountToId).LSO_Reference_Datas__r);
                    if(partnerLsoRefList.size()>0){  
                            for(ERP_Reference_Data__c lrd:primPartnerAccnts.get(op.accountToId).LSO_Reference_Datas__r){
                                primPartnerLSO = String.valueof(lrd.LSO__c)+String.valueof(lrd.LBU__c);
                                if(usr!= null && usr.Default_BU__c!=null &&  lrd.LBU__c!= null && userLSO!=null && userLSO.equalsIgnorecase(primPartnerLSO) &&  op.isPrimary == true){
                                   oppy.Primary_Partner_LSO_Reference_Data__c  = lrd.id;
                                   break;
                                }
                                else if(usr!= null && usr.Default_BU__c ==null &&  lrd.LBU__c == null && userLSO1!=null && userLSO1.equalsIgnorecase(String.valueof(lrd.LSO__c))  &&  op.isPrimary == true){
                                   oppy.Primary_Partner_LSO_Reference_Data__c = lrd.id;
                                   break;
                                }
                                else{
                                   oppy.Primary_Partner_LSO_Reference_Data__c = null;
                                }
                            }
                    }
                    else{
                        oppy.Primary_Partner_LSO_Reference_Data__c = null;
                    }           
            }
            updatedOpptyList.add(oppy);         
        }   
      totalProcesd.addAll(updatedOpptyList);  
      Database.SaveResult[] saveRes = database.update(updatedOpptyList, false);
      for(Integer i=0;i<saveRes.size();i++){
          String errDet;
          if(saveRes.get(i).isSuccess()){
            sucsIds.add(saveRes.get(i).getId()); 
          }
          else{
            Database.Error err = saveRes.get(i).getErrors().get(0);
            errDet = updatedOpptyList.get(i).Id+'-'+err.getMessage()+'/n';
            errIds.add(errDet);
          }
       }
    }      
    
    global void finish(Database.BatchableContext BC){
        System.Debug('@@@@@@@@@ Opportunity Batch Processed List Size @@@@@@@@@  '+totalProcesd.size());
        System.Debug('$$$$$$$$$ Opportunity Batch Update List Size $$$$$$$$$  '+sucsIds.size());    
        System.Debug('######### Opportunity Batch Update Errors #########  '+errIds.size()+'--'+errIds);
    }
}