src/objects/ERP_Reference_Data__c.object
<CustomObject>
    <description>R3v1 - This custom object holds LSO Reference Data for Accounts.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R3v1 - Custom Lookup field to Account object to display the account reference in LSO Reference Data.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>LSO_Reference_Datas</relationshipName>
        <type>Lookup</type>
    </fields>
     <fields>
        <fullName>ManualUniqueKey__c</fullName>
        <formula>Account__r.Id &amp; Text(Country__c) &amp; LBU__c &amp; LSO__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ManualUniqueKey</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aland Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antarctica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia, Plurinational State of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia and Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LBU__c</fullName>
        <description>R3 -LBU</description>
        <label>LBU</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LSO__c</fullName>
        <description>R3 - LSO</description>
        <label>LSO</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Local Reference Data</label>
    <nameField>
        <displayFormat>ERP-REF-DATA-{0000}</displayFormat>
        <label>LSO Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Local Reference Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ClsTriggerLSODupeHandler.cls
/**
*  @Name: ClsTriggerLSODupeHandler
*  @Release - R3 CR
*  @Description - This class helps to allow the duplicate on ERP Picklist data
*  @Author : Mohan Raj (Accenture)
*/
public without sharing class ClsTriggerLSODupeHandler extends ClsTriggerVirtual  {
    
     /**
         * @see IntHelper.beforeTrigger
    */
    public override void beforeTrigger(ClsWrappers.TriggerContext trgCtx) {
        CheckLSODupeEntries(trgCtx);    
    }
    
    /**
    *  Method - CheckLSODupeEntries
    *  Description - Check the Description of ERP Mapping  
    */            
    @TestVisible 
    private void CheckLSODupeEntries(ClsWrappers.TriggerContext trgCtx) { 
        
        if ( (trgCtx.isBefore && trgCtx.isInsert) )
        {          
            Set<String> lsos = new Set<String>(); 
                         
            for (sobject so : trgCtx.newList) {
                ERP_Reference_Data__c erp = (ERP_Reference_Data__c)so;    
                
                //if( (erp.Account__c != null) && (erp.Country__c != null) && (erp.LBU__c != null) && (erp.LSO__c != null) && (erp.recordtypeid == '01220000000jYpuAAE'))
                if( (erp.Account__c != null) && (erp.Country__c != null) && (erp.LSO__c != null) && (erp.recordtypeid == '01220000000jYpuAAE'))
                {
                    string accid = erp.Account__c;
                    string strLBU = '';
                    if(erp.LBU__c != null){strLBU = erp.LBU__c;}
                    lsos.add(accid.substring(0,15)+erp.Country__c+strLBU+erp.LSO__c );                                  
                }
            } 
        
            set<String> Manualkeys = new set<String>();
            
            for(ERP_Reference_Data__c e : [select Id, ManualUniqueKey__c from ERP_Reference_Data__c where ManualUniqueKey__c in :lsos LIMIT 50000])
            {
                Manualkeys.add(e.ManualUniqueKey__c);
            }
            
            system.debug('MJ::'+Manualkeys.size());
                         
            for (sobject so : trgCtx.newList) {
                ERP_Reference_Data__c erp = (ERP_Reference_Data__c)so; 
                string accid1 = erp.Account__c; 
                //system.debug('MJ::'+accid1.substring(0,15)+erp.Country__c+erp.LBU__c+erp.LSO__c);      
                //system.debug('MJ::'+erp.recordtypeid);
                //system.debug('MJ::'+Manualkeys.Contains(accid1.substring(0,15)+erp.Country__c+erp.LBU__c+erp.LSO__c));
                if( (erp.Account__c != null) && (erp.Country__c != null) && (erp.LSO__c != null)  && (erp.recordtypeid == '01220000000jYpuAAE'))
                {   
                    string accid = erp.Account__c;
                    string strLBU = '';
                    if(erp.LBU__c != null){strLBU = erp.LBU__c;}                    
                    if(Manualkeys.Contains(accid.substring(0,15)+erp.Country__c+strLBU+erp.LSO__c) == True  )
                    {   system.debug('MJ::IS Error');                  
                        so.addError('An Account with this Country, LSO and LBU combination already exists. Cannot create duplicate records!');
                    }
                        
                }
            }            
        }  
        
        
        
        if ( trgCtx.isBefore && trgCtx.isUpdate )
        {               
        
            Set<String> lsos = new Set<String>(); 
            Set<Id> lsoids = new Set<Id>();
            
            for (sobject so : trgCtx.newList) {
                ERP_Reference_Data__c erp = (ERP_Reference_Data__c)so;    
                
                if( (erp.Account__c != null) && (erp.Country__c != null) && (erp.LSO__c != null) && (erp.recordtypeid == '01220000000jYpuAAE'))
                {
                    string accid = erp.Account__c;
                    string strLBU = '';
                    if(erp.LBU__c != null){strLBU = erp.LBU__c;}
                    lsos.add(accid.substring(0,15)+erp.Country__c+strLBU+erp.LSO__c );  
                    lsoids.add(erp.Id);                                
                }
            } 
        
            set<String> Manualkeys = new set<String>();
            
            for(ERP_Reference_Data__c e : [select Id, ManualUniqueKey__c from ERP_Reference_Data__c where ManualUniqueKey__c in :lsos and  Id not in : lsoids  LIMIT 50000])
            {
                Manualkeys.add(e.ManualUniqueKey__c);
            }
            
            system.debug('MJ::'+Manualkeys.size());
                         
            for (sobject so : trgCtx.newList) {
                ERP_Reference_Data__c erp = (ERP_Reference_Data__c)so; 
                string accid1 = erp.Account__c; 
                //system.debug('MJ::'+accid1.substring(0,15)+erp.Country__c+erp.LBU__c+erp.LSO__c);      
                //system.debug('MJ::'+erp.recordtypeid);
                //system.debug('MJ::'+Manualkeys.Contains(accid1.substring(0,15)+erp.Country__c+erp.LBU__c+erp.LSO__c));
                if( (erp.Account__c != null) && (erp.Country__c != null) && (erp.LSO__c != null)  && (erp.recordtypeid == '01220000000jYpuAAE'))
                {   
                    string accid = erp.Account__c;
                    string strLBU = '';
                    if(erp.LBU__c != null){strLBU = erp.LBU__c;}
                    if(Manualkeys.Contains(accid.substring(0,15)+erp.Country__c+strLBU+erp.LSO__c) )
                    {   system.debug('MJ::IS Error');                  
                        so.addError('An Account with this Country, LSO and LBU combination already exists. Cannot create duplicate records!');
                    }
                        
                }
            }            
        }  
        
                           
    }           
}