src/objects/Exchange_Rate_Loader__c.object
<CustomObject>
	<fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Daily</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Budget</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Exchange Rate Loader</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Exchange Rate Loader  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exchange Rate Loaders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ClsTriggerExchangeRateLoaderHandler.cls
/**
*  @Name: ClsTriggerExchangeRateLoaderHandler
*  @return - void
*  @Description - This class helps to load data in to Exchange rate currency object
*  @Author : Rajesh Kaliyaperumal (Accenture)
*/
public class ClsTriggerExchangeRateLoaderHandler extends ClsTriggerVirtual {
    /**
     * @see IntHelper.beforeTrigger
    */    
    public override void beforeTrigger(ClsWrappers.TriggerContext trgCtx) {
       
    }    
    /**
     * @see IntHelper.afterTrigger
    */
    public override void afterTrigger(ClsWrappers.TriggerContext trgCtx) {      
        loadDataExchangeRate(trgCtx);
    }
    
    /**
    *  @Name: loadDataExchangeRate
    *  @return - void
    */
    @TestVisible 
    private void loadDataExchangeRate(ClsWrappers.TriggerContext trgCtx) { 
        if(trgCtx.isAfter && trgCtx.isInsert)
        {
            List<DatedConversionRate> lstDatedConvRate = new List<DatedConversionRate>();
            for (sobject so : trgCtx.newList) {             
                Exchange_Rate_Loader__c erl = (Exchange_Rate_Loader__c)so;
                if(erl.Type__c == 'Budget'){
                    DatedConversionRate objDCR = new DatedConversionRate();
                    objDCR.StartDate = System.today();
                    //objDCR.NextStartDate = System.today()+1;
                    objDCR.ISOCODE = erl.CurrencyIsoCode;
                    objDCR.ConversionRate = Decimal.valueof(erl.Value__c);
                    lstDatedConvRate.add(objDCR);
                }
            }
            if(lstDatedConvRate.size()>0){
                //Database.insert(lstDatedConvRate, false);
            }
        }
    }
}