src/objects/Joint_Business_Plan__c.object
<CustomObject>
    <description>R5 Joint Business Plan</description>
    <label>Channel Partner Business Plan</label>
    <nameField>
        <label>Business Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partner Business Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Joint_Business_Plan_Market_Coverage__c.object
<CustomObject>
    <description>R5 - New Custom Object Joint Business Plan Market Coverage</description>
    <fields>
        <fullName>ABB_Product_Lines__c</fullName>
        <description>R5 - ABB Product Lines</description>
        <inlineHelpText>Product mix - content under Market Scope is used as default value. Please edit as needed.</inlineHelpText>
        <label>ABB Product Lines</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Annual_Growth_Potential__c</fullName>
        <description>R5 - Annual Growth Potential</description>
        <inlineHelpText>in % for the partners’ whole business in this segment</inlineHelpText>
        <label>% Annual Growth Potential</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Current_Business__c</fullName>
        <description>R5 - % Current Business</description>
        <inlineHelpText>What % this segment represents of the partners total business</inlineHelpText>
        <label>% Current Business</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <!--fields>
        <fullName>Focussed_Industry1__c</fullName>
        <description>R5 - Focussed industry - combination of Industry usage level 1, level2 and level3</description>
        <inlineHelpText>Pick all the industries currently served and targeted in the upcoming 3 years.  Want to add/ remove a focused industry? Do it on &quot;Channel Market Scope&quot; -view and clone the list on Business Plan header -view.</inlineHelpText>
        <label>Focussed Industry</label>
        <picklist>
            <picklistValues>
                <fullName>BLD - BLD.8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BLD - BLD.9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BLD - BLD.10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.1 - IND.1.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.1 - IND.1.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.7 - IND.7.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.7 - IND.7.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.7 - IND.7.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.10 - IND.10.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.10 - IND.10.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.10 - IND.10.4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.10 - IND.10.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.11 - IND.11.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.11 - IND.11.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.12 - IND.12.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.12 - IND.12.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.12 - IND.12.3</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields-->
    <fields>
        <fullName>Joint_Business_Plan__c</fullName>
        <description>R5 - Joint Business Plan</description>
        <inlineHelpText>Business plan  this market scope is connected to</inlineHelpText>
        <label>Business Plan</label>
        <referenceTo>Joint_Business_Plan__c</referenceTo>
        <relationshipLabel>Market coverages</relationshipLabel>
        <relationshipName>Joint_Business_Plan_Market_Coverages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Market_Position__c</fullName>
        <description>R5 - Market Position</description>
        <inlineHelpText>Partner’s position on this market segment today. Do not enter if possible compliance issues.</inlineHelpText>
        <label>Market Position</label>
        <picklist>
            <picklistValues>
                <fullName>Top 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Top 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Top 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Top 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Top 5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Top 6 or more</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Other_Details__c</fullName>
        <description>R5 - Other Details</description>
        <inlineHelpText>..concerning ABB business potential in this segment</inlineHelpText>
        <label>Other Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sales_Today__c</fullName>
        <description>R5 - Sales Today</description>
        <inlineHelpText>.. to this segment for the products indicated above</inlineHelpText>
        <label>ABB sales last year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Special_Focus__c</fullName>
        <description>R5 - Special Focus</description>
        <inlineHelpText>e.g. application, sub-segment</inlineHelpText>
        <label>Special Focus</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Strength__c</fullName>
        <description>R5 - Strength</description>
        <inlineHelpText>What are the partners competitive advantages in this segment</inlineHelpText>
        <label>Strengths</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Targeted_ABB_this_year_sales__c</fullName>
        <description>R5 - Targeted ABB this year sales</description>
        <inlineHelpText>.. to this segment for the products indicated above</inlineHelpText>
        <label>Targeted ABB sales this year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Targeted_Sales_this_year__c</fullName>
        <description>R5 - Targeted Sales This year</description>
        <inlineHelpText>Main products and services sold today to this segment</inlineHelpText>
        <label>Offering today</label>
        <type>TextArea</type>
    </fields>
    <label>Market Coverage</label>
    <nameField>
        <displayFormat>Market-{000000}</displayFormat>
        <label>Market Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market Coverages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ClsJBPMarketCoverageList.cls
/**   
* Apex Class : ClsJBPMarketCoverageList
* VF Page    : JBPMarketCoverageList
* Controller for JBPMarketCoverageList - Enable Inline Editing for Joint Business Plan Market Coverage in Joint Business Plan
* Release R5
*
*/
public with sharing class ClsJBPMarketCoverageList
{
    public String returnURL {get;set;}
    public String parentId {get;set;}
    Map<Id,Set<Id>> mapJBP= new Map<Id,Set<Id>>(); 
    public List<Joint_Business_Plan_Market_Coverage__c> lstDuplicateCheck {get;set;}   
    public List<Joint_Business_Plan_Market_Coverage__c> JBPMarketCoverage {get;set;}
/**   
* Constructor ClsJBPMarketCoverageList
*/    
    public ClsJBPMarketCoverageList(ApexPages.StandardController controller) {
        Joint_Business_Plan__c jointBussPlan=(Joint_Business_Plan__c)controller.getRecord();         
        returnURL = apexpages.currentpage().getparameters().get(Label.ApexClass_id);                   
        parentId = returnURL.replace(Label.System_CL00020 , '');  // System_CL00020 => /           
        parentId = parentId.substring(0,15);    
                      
        JBPMarketCoverage = [SELECT Id, Name,Joint_Business_Plan__c, Market_Position__c,
                    Focussed_Industry1__c, Special_Focus__c, Strength__c, 
                    Targeted_ABB_this_year_sales__c, Other_Details__c, Targeted_Sales_this_year__c, 
                    Sales_Today__c, Annual_Growth_Potential__c, Current_Business__c, ABB_Product_Lines__c
                      from Joint_Business_Plan_Market_Coverage__c WHERE Joint_Business_Plan__c =: parentid limit 10000];                  
    } 
/**   
* Save method for Joint_Business_Plan_Market_Coverage__c
*/    
    public PageReference save() {
       Map<Id, Joint_Business_Plan_Market_Coverage__c> industryMap = new Map<Id, Joint_Business_Plan_Market_Coverage__c> ([SELECT Focussed_Industry1__c FROM Joint_Business_Plan_Market_Coverage__c WHERE Joint_Business_Plan__c =: parentid LIMIT 50000]);      
        Set<String> productIdSet = new Set<String>();    
        String dupPrd = '';  
          
       for(Joint_Business_Plan_Market_Coverage__c dupCheck : JBPMarketCoverage ){  
                      
            if (dupCheck.Focussed_Industry1__c != NULL) {
            
                List<String> str = dupCheck.Focussed_Industry1__c.split(Label.System_CL00046);
                
                for (String st: str) {
                    if (!productIdSet.contains(st)) {
                    
                        productIdSet.add(st); 
                    } else {
                        dupPrd += st +Label.CL00069; // comma
                    }
                }              
            }            
        }
                  
       if (!String.isBlank(dupPrd)) {           
           dupPrd = dupPrd.substring(0, dupPrd.length()-2);
           apexPages.addMessage(new ApexPages.message(ApexPages.severity.Error, Label.Focussed_Industry_Error_Msg + dupPrd));
           return null;
       } else {      
           Database.update(JBPMarketCoverage);
       }
        PageReference pageRef = new PageReference(Label.System_CL00020+returnURL);
        return pageRef;        
    }
/**   
* cancel Method 
* redirect to the parent detail page
*/      
    public PageReference cancel() {
        PageReference pageRef = new PageReference(Label.System_CL00020+returnURL);
        return pageRef;  
    }
}