src/objects/Joint_Business_Plan__c.object
<CustomObject>
    <description>R5 Joint Business Plan</description>
    <label>Channel Partner Business Plan</label>
    <nameField>
        <label>Business Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partner Business Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Joint_Business_Plan_Market_Coverage__c.object
<CustomObject>
    <description>R5 - New Custom Object Joint Business Plan Market Coverage</description>
    <fields>
        <fullName>Channel_Partner_Business_Plan_Status__c</fullName>
        <formula>IF ( (TEXT(Joint_Business_Plan__r.Status__c) == &apos;Closed&apos; || TEXT(Joint_Business_Plan__r.Status__c) == &apos;Obsolete&apos;), &apos;Closed&apos;, TEXT(Joint_Business_Plan__r.Status__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Channel Partner Business Plan Status</label>
        <type>Text</type>
    </fields>
    <!--fields>
        <fullName>Focussed_Industry1__c</fullName>
        <description>R5 - Focussed industry - combination of Industry usage level 1, level2 and level3</description>
        <inlineHelpText>Pick all the industries currently served and targeted in the upcoming 3 years.  Want to add/ remove a focused industry? Do it on &quot;Channel Market Scope&quot; -view and clone the list on Business Plan header -view.</inlineHelpText>
        <label>Focussed Industry</label>
        <picklist>
            <picklistValues>
                <fullName>BLD - BLD.8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BLD - BLD.9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BLD - BLD.10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.1 - IND.1.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.1 - IND.1.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.4 - IND.4.8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.7 - IND.7.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.7 - IND.7.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.7 - IND.7.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.10 - IND.10.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.10 - IND.10.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.10 - IND.10.4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.10 - IND.10.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.11 - IND.11.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.11 - IND.11.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.12 - IND.12.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.12 - IND.12.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND - IND.12 - IND.12.3</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields-->
    <fields>
        <fullName>Joint_Business_Plan__c</fullName>
        <description>R5 - Joint Business Plan</description>
        <inlineHelpText>Business plan  this market scope is connected to</inlineHelpText>
        <label>Business Plan</label>
        <referenceTo>Joint_Business_Plan__c</referenceTo>
        <relationshipLabel>Market coverages</relationshipLabel>
        <relationshipName>Joint_Business_Plan_Market_Coverages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Market Coverage</label>
    <nameField>
        <displayFormat>Market-{000000}</displayFormat>
        <label>Market Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market Coverages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ClsTriggerMarketCoverageHandler.cls
/**   
* TriggerClass on the Joint_Business_Plan__c object to
    1. To populate the Joint Business Plan currency
*       
* Release - R5 
 *  
 * @author  - Vasanthi (Accenture)
 * @created - 2016-3-7
 * @version - 1.0
 * @Description -To populate the Joint Business Plan currency
   
* - Created
*/
public without sharing class ClsTriggerMarketCoverageHandler extends ClsTriggerVirtual {
  
   
/**
* @see bulkBefore
*/   
    public override void bulkBefore(ClsWrappers.TriggerContext trgCtx) {
        if (trgCtx.isInsert) {
            assingnCurrency (trgCtx);           
        }
        
        if (trgCtx.IsDelete) {
            deleteValidation(trgCtx);
        } 
    }
    
    
     
        /**
    To prevent deletion when the account plan status is closed
    */
     Public void deleteValidation(ClsWrappers.TriggerContext trgCtx){
         ID sysAdminProfileId = Label.CL00075;
         for (Joint_Business_Plan_Market_Coverage__c con : (List<Joint_Business_Plan_Market_Coverage__c>) trgCtx.oldList) {             
             if (sysAdminProfileId != Userinfo.getProfileid() && con.Channel_Partner_Business_Plan_Status__c== Label.Closed ) {
                 con.addError(Label.Business_Visit_Report_Business_Plan_Error); //You cannot save the changes - Channel Partner Business Plan is Closed/Obsolete.
             }
         }        
     }
     
/**    
  * Req #1960 (Update Joint Business Plan currency to Market Coverage).     
*/  
    public void assingnCurrency(ClsWrappers.TriggerContext trgCtx) {
        
        Set<Id> parentIdSet = new Set<Id>();
        
        for (Sobject sobj : trgCtx.newList) {
            Joint_Business_Plan_Market_Coverage__c sobjJBP = (Joint_Business_Plan_Market_Coverage__c)sObj;
            parentIdSet.add(sobjJBP.Joint_Business_Plan__c);
        }
        
        if (parentIdSet.size() > 0) {
            
            Integer limitRows = Limits.getLimitQueryRows() - Limits.getQueryRows();
            Map<Id, Joint_Business_Plan__c> jointBusPlanMap = new Map<Id, Joint_Business_Plan__c> ([ SELECT Id, CurrencyISOCode FROM Joint_Business_Plan__c WHERE Id IN :parentIdSet LIMIT :limitRows ] );
            
            for (Sobject sobj : trgCtx.newList) {
                Joint_Business_Plan_Market_Coverage__c sobjJBP = (Joint_Business_Plan_Market_Coverage__c )sObj;
                sobjJBP.CurrencyISOCode = jointBusPlanMap.get(sobjJBP.Joint_Business_Plan__c).CurrencyISOCode;
            }
        }
    }
}