src/objects/Local_ERP_Loader__c.object
<CustomObject>
    <description>R3 - Object to hold the data which is used to do comparison with SAP data - (SAP data is compared with mapping table)</description>
    <label>Local ERP Loader</label>
    <nameField>
        <displayFormat>ERP Data # - {0000000000}</displayFormat>
        <label>ERP Data Hold Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Local ERP Loader</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Log__c.object
<CustomObject>
    <description>R3 - Log object for exception tracking purpose.</description>
    <fields>
        <fullName>Class_Name__c</fullName>
        <description>R3 - Class_Name</description>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Line__c</fullName>
        <description>R3 - Error Line</description>
        <label>Error Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Full_Error__c</fullName>
        <description>R3 - Full_Error</description>
        <label>Full Error</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>Log # - {0000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchDeleteLocalErpLoader.cls
/**
 * BatchClass - Delete the records from Local ERP Loader 
 *       
 * Release R3
 *  
 * @author  Vinodh Kumar (Accenture)
 * @created 2015-07-22
 * @version 1.0
 *
 * - Created
 */
global class BatchDeleteLocalErpLoader implements Database.Batchable<sObject>{

    Public Datetime todayDate = system.now();
    Public DateTime lastThreeMonthDateTime = todayDate.addMonths(-3);       
    Public String query = 'SELECT Id, Name FROM Local_ERP_Loader__c WHERE CreatedDate <= :lastThreeMonthDateTime';
/**
 *  Method - start
 *  get the record to process      
 *  
 */    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }

/**
 *  Method - execute
 *  delete the records      
 *  
 */   
    global void execute(Database.BatchableContext BC, List<Local_ERP_Loader__c> erpLoadList){
                 
        try {             
            Database.Delete(erpLoadList);   
        }catch(Exception e) {        
            Log__c log = new Log__c(Class_Name__c = System.Label.System_BatchDeleteLocalErpLoader, Error_Line__c = String.valueof(e.getLineNumber()), Full_Error__c = String.valueof(e));
            Database.insert(log);
        }  
    }   
/**
 *  Method - finish      
 *  
 */    
    global void finish(Database.BatchableContext BC){
    }
}