src/objects/LSO_Field_Entries__c.object
<CustomObject>
    <description>R3 -  LSO Field Entries</description>
    <fields>
        <fullName>Country__c</fullName>
        <description>R3 Country</description>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Spain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Italy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LSO_Pick_List_Value_Name__c</fullName>
        <description>R3 LSO Pick List Value Name</description>
        <label>LSO Pick List Value Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PickList_Code__c</fullName>
        <description>R3 PickList Code</description>
        <label>PickList Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PickList_Description_Code__c</fullName>
        <description>R4 Formula field to Concatenate Picklist code and Picklist Description</description>
        <formula>PickList_Code__c&amp;&apos; :: &apos;&amp;  PickList_Description__c</formula>
        <label>PickList Description Code</label>
        <type>Text</type>
    </fields>
    <label>LSO Field Entries</label>
    <nameField>
        <displayFormat>LSO Field Entry - {0000}</displayFormat>
        <label>LSO Field Entry</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LSO Field Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/APTS_LSOFieldEntriesTriggerHandler.cls
/*
@Name: APTS_LSOFieldEntriesTriggerHandler
@Author: Jignesh Shekhaliya
@CreateDate: 28-Nov-2015
@Description: Handler Class to invoke appropriate methods from Helper Class
@UsedBy: APTS_LSOFieldEntriesTrigger
******************************************************************
*/
public with sharing class APTS_LSOFieldEntriesTriggerHandler {

    list<LSO_Field_Entries__c> listLSOEntries = new list<LSO_Field_Entries__c>();
    String recordTypeId='';
    
    public APTS_LSOFieldEntriesTriggerHandler(){
        
        recordTypeId = APTS_LSOFieldEntriesTriggerHelper.getRecordTypeId();
        
    }
    
    
    public void OnAfterInsert(list<LSO_Field_Entries__c> listNewLSOFieldEntries) {
    
        for( LSO_Field_Entries__c oLSOFieldEntry : listNewLSOFieldEntries ){
        
            if( oLSOFieldEntry.PickList_Code__c != null && oLSOFieldEntry.PickList_Description_Code__c != null && 
                oLSOFieldEntry.Country__c != null && oLSOFieldEntry.LSO_Pick_List_Value_Name__c.Contains(APTS_Constants.LSO_FIELD_ENTRY_IDENTIFIER) &&
                oLSOFieldEntry.RecordTypeId ==recordTypeId){
            
                listLSOEntries.add(oLSOFieldEntry);
            }                        
        }
    
        if( !listLSOEntries.isEmpty() ){
        
            APTS_LSOFieldEntriesTriggerHelper.syncMasterPicklistTable(listLSOEntries);
        }
    }
    
    public void OnAfterUpdate(Map<Id, LSO_Field_Entries__c> mapNewLSOFieldEntries, Map<Id, LSO_Field_Entries__c> mapOldLSOFieldEntries) {
    
        for( LSO_Field_Entries__c oLSOFieldEntry : mapNewLSOFieldEntries.Values() ){
        
            if( oLSOFieldEntry.PickList_Code__c != null && oLSOFieldEntry.PickList_Description_Code__c != null && 
                oLSOFieldEntry.Country__c != null && oLSOFieldEntry.LSO_Pick_List_Value_Name__c.Contains(APTS_Constants.LSO_FIELD_ENTRY_IDENTIFIER) &&
                oLSOFieldEntry.RecordTypeId ==recordTypeId){
            
                listLSOEntries.add(oLSOFieldEntry);
            } 
/*            
            if( oLSOFieldEntry.LSO_Pick_List_Value_Name__c.Contains('LSO Reference Data. Sales Office') &&
                ((oLSOFieldEntry.PickList_Code__c != null && oLSOFieldEntry.PickList_Code__c != mapOldLSOFieldEntries.get(oLSOFieldEntry.Id).PickList_Code__c) ||
                 (oLSOFieldEntry.PickList_Description_Code__c != null && oLSOFieldEntry.PickList_Description_Code__c != mapOldLSOFieldEntries.get(oLSOFieldEntry.Id).PickList_Code__c) ||
                 (oLSOFieldEntry.Country__c != null && oLSOFieldEntry.Country__c != mapOldLSOFieldEntries.get(oLSOFieldEntry.Id).PickList_Code__c)) ){
            
                listLSOEntries.add(oLSOFieldEntry);
            }                      */  
        }
    
        if( !listLSOEntries.isEmpty() ){
        
            APTS_LSOFieldEntriesTriggerHelper.syncMasterPicklistTable(listLSOEntries);
        }
    
    }

    public void OnAfterDelete(Map<Id, LSO_Field_Entries__c> mapOldLSOFieldEntries) {
    
        Set<String> setLSOFieldEntriesId = new Set<String>();
    
        for( LSO_Field_Entries__c oLSOFieldEntry : mapOldLSOFieldEntries.Values() ){
        
            if( oLSOFieldEntry.LSO_Pick_List_Value_Name__c.Contains(APTS_Constants.LSO_FIELD_ENTRY_IDENTIFIER) &&
                oLSOFieldEntry.RecordTypeId ==recordTypeId){
            
                setLSOFieldEntriesId.add(oLSOFieldEntry.Id);
            }
        }
        
        if( !setLSOFieldEntriesId.isEmpty() ){
        
            APTS_LSOFieldEntriesTriggerHelper.syncDeleteMasterPicklist(setLSOFieldEntriesId);
        }        
    }
    
    
}