src/objects/LSO_Field_Entries__c.object
<CustomObject>
    <description>R3 -  LSO Field Entries</description>
    <fields>
        <fullName>Country__c</fullName>
        <description>R3 Country</description>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Spain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Italy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LSO_Pick_List_Value_Name__c</fullName>
        <description>R3 LSO Pick List Value Name</description>
        <label>LSO Pick List Value Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PickList_Code__c</fullName>
        <description>R3 PickList Code</description>
        <label>PickList Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PickList_Description__c</fullName>
        <description>R3 PickList Description</description>
        <label>PickList Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>LSO Field Entries</label>
    <nameField>
        <displayFormat>LSO Field Entry - {0000}</displayFormat>
        <label>LSO Field Entry</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LSO Field Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/APTS_LSOFieldEntriesTriggerTest.cls
@isTest
public class APTS_LSOFieldEntriesTriggerTest {

    // Test Sync Master Picklist Table data when LSO Field Entry is created / modified / deleted
    public static testMethod void syncLSOFieldEntryWithMasterPicklist(){

        System.runAs(APTS_LP_TestUtility.getUser()){
            Test.startTest();
            APTS_LP_TestUtility.getCommonConfigSetting();
            LSO_Field_Entries__c oLSOFieldEntry = new LSO_Field_Entries__c();
            oLSOFieldEntry.PickList_Description__c = 'Test/Code Description';
            oLSOFieldEntry.PickList_Code__c = 'Test/Code Description';
            oLSOFieldEntry.Country__c = 'Spain';
            oLSOFieldEntry.LSO_Pick_List_Value_Name__c = 'LSO Reference Data. Sales Office';
            insert oLSOFieldEntry;
            
            oLSOFieldEntry.Country__c = 'Austria';
            Update oLSOFieldEntry;
            
            delete oLSOFieldEntry;
            
            Test.stopTest(); 
    	}
    }
}