src/objects/Opportunity.object
<CustomObject>

 
 

    <fields>
        <fullName>Actual_Bid_Submission_Date_Comm__c</fullName>
        <description>Contains the date when the Commercial bid was submitted.</description>
        <label>Actual Bid Submission Date (Comm.)</label>
        <type>Date</type>
    </fields>
	
   
    <fields>
        <fullName>Requested_Bid_Submission_Date_Comm__c</fullName>
        <description>Requested date when a commercial bid should be submitted by.</description>
        <label>Requested Bid Submission Date (Comm.)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Requested_Bid_Submission_Date_Tech__c</fullName>
        <description>Requested date when a technical bid should be submitted by.</description>
        <label>Requested Bid Submission Date (Tech.)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_Pursuit_Progress__c</fullName>
        <description>Dependent picklist for Sales Pursuit Progress</description>
        <inlineHelpText>Please choose the Stage detail from picklist</inlineHelpText>
        <label>Sales Pursuit Progress</label>
        <picklist>
            <controllingField>StageName</controllingField>
            <picklistValues>
                <fullName>Opportunity Is Captured</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity Pursuit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold (Pursuit)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Budget Proposal Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFQ Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bidding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Preference To Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold (Bidding)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solution Presented To Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Budget Proposal Submitted (Bidding)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bid Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Is Neutral To Supplier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Preference To ABB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold (Negotiation)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LOI To Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Buying Preference To Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Position Is Neutral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clear Buying Signal To ABB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ABB Preferred &amp; Shows Clear Signals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LOI To ABB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSED Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSED Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSED Lost Without ABB Bid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSED Won</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/cancelOpptyChanges.cls
/**
 *      @description    Class for reverting opportunity record type and stage changes.  
 */
public with sharing class cancelOpptyChanges{
 /*  Description of the purpose of the method. 
    *  @name revertOpptyRecrdType
 */   
     public PageReference revertOpptyRecrdType(){
     try{
      List<Opportunity> opptyList = new List<Opportunity>();
      Id id = ApexPages.currentPage().getParameters().get(System.label.ApexClass_id);
      List <Opportunity> oppty = [Select Id, Name, StageName from Opportunity where id =:id LIMIT 1];
      //String recordtypeId = ApexPages.currentPage().getParameters().get('recordTypeId');
      String stageName = ApexPages.currentPage().getParameters().get(System.label.StageName);
      String salesProgress = ApexPages.currentPage().getParameters().get('Sales_Pursuit_Progress__c');
      //Date oldActualBidComm= Date.valueOf(ApexPages.currentPage().getParameters().get('oldActualBidComm'));
      //Date oldReqBidTech= Date.valueOf(ApexPages.currentPage().getParameters().get('oldReqBidTech'));
      //Date oldReqBidComm= Date.valueOf(ApexPages.currentPage().getParameters().get('oldReqBidComm'));
      Date oldCloseDate = Date.valueOf(ApexPages.currentPage().getParameters().get('CloseDate'));
      
      //Opportunity opp = new Opportunity(id= id,StageName=stageName,Sales_Pursuit_Progress__c=salesProgress,Actual_Bid_Submission_Date_Comm__c=oldActualBidComm,Requested_Bid_Submission_Date_Tech__c=oldReqBidTech,Requested_Bid_Submission_Date_Comm__c =oldReqBidComm,CloseDate=CloseDate);
      Opportunity opp = new Opportunity(id= id,StageName=stageName,Sales_Pursuit_Progress__c=salesProgress,CloseDate=oldCloseDate);
      opptyList.add(opp);
      Database.Update(opptyList);
      
      Pagereference prf = new Pagereference(System.label.CL0001+id);
      return prf;
      }
      catch(DMLException exc){
       String e=exc.getDMLMessage(0);
       ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,+e,''));
       return null;
      }
      
  }
  /*  Description of the purpose of the method. 
    *  @name back
 */
  public PageReference back(){
  try{
      Id id = ApexPages.currentPage().getParameters().get(System.label.ApexClass_id);
      //String recordtypeId = ApexPages.currentPage().getParameters().get('recordTypeId');
      String stageName = ApexPages.currentPage().getParameters().get(System.label.StageName);
      String oldProgress = ApexPages.currentPage().getParameters().get('Sales_Pursuit_Progress__c');
      Date oldCloseDate = Date.valueOf(ApexPages.currentPage().getParameters().get('CloseDate'));
      
      //Pagereference prf = new Pagereference('/'+id+'/e?cancelURL=/apex/Cancel_Oppty_Record_Type_change?stageName='+stageName+'%26id='+id+'&saveURL=/'+id);
      Pagereference prf = new Pagereference(System.label.CL0001+id+System.label.CL00203+System.label.CL00204+stageName+'%26CloseDate='+oldCloseDate+System.Label.CL002108+oldProgress+System.label.CL00205+id+System.label.CL00206+id);
      return prf;
      }catch(Exception e){String err=e.getMessage();}
         return null; 
  }
      
}