src/objects/Opportunity_Screening__c.object
<CustomObject>
    <description>R4 v1 - Opportunity Screening custom object to capture the Opportunity Qualification status</description>
    <fields>
        <fullName>GATE1_Completeness__c</fullName>
        <formula>(IF(OR(TEXT(Gate1_Will_EndUser_A__c) = &quot;&quot;, TEXT(Gate1_Will_EndUser_A__c) =&quot;Unknown&quot;),0,1)+
IF(OR(TEXT(Gate1_Will_Project_Development_A__c) = &quot;&quot;, TEXT(Gate1_Will_Project_Development_A__c) =&quot;Unknown&quot;),0,1)+
IF(OR(TEXT(Gate1_Will_Business_value_A__c) = &quot;&quot;, TEXT(Gate1_Will_Business_value_A__c) =&quot;Unknown&quot;),0,1)+
IF(OR(TEXT(Gate1_Fit_Strategy1_A__c) = &quot;&quot;, TEXT(Gate1_Fit_Strategy1_A__c) =&quot;Unknown&quot;),0,1)+
IF(OR(TEXT(Gate1_Fit_Strategy2_A__c) = &quot;&quot;, TEXT(Gate1_Fit_Strategy2_A__c) =&quot;Unknown&quot;),0,1)+
IF(OR(TEXT(Gate1_Fit_Resources_A__c) = &quot;&quot;, TEXT(Gate1_Fit_Resources_A__c) =&quot;Unknown&quot;),0,1)+
IF(OR(TEXT(Gate1_Fit_Safe_Island_A__c) = &quot;&quot;, TEXT(Gate1_Fit_Safe_Island_A__c) =&quot;Unknown&quot;),0,1)+
IF(Safe_Island_Classification__c = &quot;Please fill out required in formation in Opportunity Screening sheet&quot;,0,1)+
IF(OR(TEXT(Gate1_Get_Customer_Relation1_A__c) = &quot;&quot;, TEXT(Gate1_Get_Customer_Relation1_A__c) =&quot;Unknown&quot;),0,1)+
IF(OR(TEXT(Gate1_Get_Customer_Relation2_A__c) = &quot;&quot;, TEXT(Gate1_Get_Customer_Relation2_A__c) =&quot;Unknown&quot;),0,1)+
IF(OR(TEXT(Gate1_Get_Competition1_A__c) = &quot;&quot;, TEXT(Gate1_Get_Competition1_A__c) =&quot;Unknown&quot;),0,1)+
IF(OR(TEXT(Gate1_Get_Competition2_A__c) = &quot;&quot;, TEXT(Gate1_Get_Competition2_A__c) =&quot;Unknown&quot;),0,1))/12</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GATE1_Completeness</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>GATE1_FIT_CategoryScore__c</fullName>
        <formula>(((IF(TEXT(Gate1_Fit_Strategy1_A__c) = &quot;Strongly agree&quot;,100,IF(TEXT(Gate1_Fit_Strategy1_A__c) =&quot;Agree&quot;,75,IF(TEXT(Gate1_Fit_Strategy1_A__c) = &quot;Neutral&quot;,50,IF(TEXT(Gate1_Fit_Strategy1_A__c) = &quot;Disagree&quot;,25,0))))*(70/100))+ 
(IF(TEXT(Gate1_Fit_Strategy2_A__c) = &quot;Strongly agree&quot;,100,IF(TEXT(Gate1_Fit_Strategy2_A__c) =&quot;Agree&quot;,75,IF(TEXT(Gate1_Fit_Strategy2_A__c) = &quot;Neutral&quot;,50,IF(TEXT(Gate1_Fit_Strategy2_A__c) = &quot;Disagree&quot;,25,0))))*(30/100)))*(40/100))+ 
((IF(OR(TEXT(Gate1_Fit_Resources_A__c)=&quot;&quot;,TEXT(Gate1_Fit_Resources_A__c)=&quot;Unknown&quot;,TEXT(Gate1_Fit_Resources_A__c)=&quot;No&quot;),0,100)*1)*(20/100))+ 
(((IF(TEXT(Gate1_Fit_Safe_Island_A__c)=&quot;Yes:Safe Island Classification in Place&quot;,100,IF(TEXT(Gate1_Fit_Safe_Island_A__c)=&quot;No:Safe Island Classification not in Place&quot;,25,0))*(50/100))+ 
(IF(Safe_Island_Classification__c=&quot;High-focus Customer&quot;,100,IF(Safe_Island_Classification__c =&quot;Focus customer with required response&quot;,50,0))*(50/100)))*(40/100))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GATE1_FIT_CategoryScore</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GATE1_GET_CategoryScore__c</fullName>
        <formula>(((IF(TEXT(Gate1_Get_Customer_Relation1_A__c)=&quot;Very Good&quot;,100,IF(TEXT(Gate1_Get_Customer_Relation1_A__c)=&quot;Good&quot;,75, IF(TEXT(Gate1_Get_Customer_Relation1_A__c)=&quot;Difficult&quot;,25, 0)))*(50/100))+
(IF(TEXT(Gate1_Get_Customer_Relation2_A__c) = &quot;Strongly agree&quot;,100,IF(TEXT(Gate1_Get_Customer_Relation2_A__c) =&quot;Agree&quot;,75,IF(TEXT(Gate1_Get_Customer_Relation2_A__c) = &quot;Neutral&quot;,50,IF(TEXT(Gate1_Get_Customer_Relation2_A__c) = &quot;Disagree&quot;,25,0))))*(50/100)))*(30/100))+
(((IF(TEXT(Gate1_Get_Competition1_A__c) = &quot;Strongly agree&quot;,100,IF(TEXT(Gate1_Get_Competition1_A__c) =&quot;Agree&quot;,75,IF(TEXT(Gate1_Get_Competition1_A__c) = &quot;Neutral&quot;,50,IF(TEXT(Gate1_Get_Competition1_A__c) = &quot;Disagree&quot;,25,0))))*(90/100))+
(IF(TEXT(Gate1_Get_Competition2_A__c) = &quot;Strongly agree&quot;,100,IF(TEXT(Gate1_Get_Competition2_A__c) =&quot;Agree&quot;,75,IF(TEXT(Gate1_Get_Competition2_A__c) = &quot;Neutral&quot;,50,IF(TEXT(Gate1_Get_Competition2_A__c) = &quot;Disagree&quot;,25,0))))*(10/100)))*(70/100))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GATE1_GET_CategoryScore</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GATE1_WILL_CategoryScore__c</fullName>
        <formula>((IF(TEXT(Gate1_Will_EndUser_A__c) = &quot;Strongly agree&quot;,100,IF(TEXT(Gate1_Will_EndUser_A__c) =&quot;Agree&quot;,75,IF(TEXT(Gate1_Will_EndUser_A__c) = &quot;Neutral&quot;,50,IF(TEXT(Gate1_Will_EndUser_A__c) = &quot;Disagree&quot;,25,0))))*1)*(40/100))+
((IF(TEXT(Gate1_Will_Project_Development_A__c) = &quot;Strongly agree&quot;,100,IF(TEXT(Gate1_Will_Project_Development_A__c) =&quot;Agree&quot;,75,IF(TEXT(Gate1_Will_Project_Development_A__c) = &quot;Neutral&quot;,50,IF(TEXT(Gate1_Will_Project_Development_A__c) = &quot;Disagree&quot;,25,0))))*1)*(50/100))+
((IF(TEXT(Gate1_Will_Business_value_A__c) = &quot;Strongly agree&quot;,100,IF(TEXT(Gate1_Will_Business_value_A__c) =&quot;Agree&quot;,75,IF(TEXT(Gate1_Will_Business_value_A__c) = &quot;Neutral&quot;,50,IF(TEXT(Gate1_Will_Business_value_A__c) = &quot;Disagree&quot;,25,0))))*1)*(10/100))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GATE1_WILL_CategoryScore</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GATE2_Completeness__c</fullName>
        <formula>(IF(OR(TEXT(Gate2_Will_EndUser1_A__c) = &quot;&quot;, TEXT(Gate2_Will_EndUser1_A__c) =&quot;Unknown&quot;),0,1)+
IF(OR(TEXT(Gate2_Will_EndUser2_A__c) = &quot;&quot;, TEXT(Gate2_Will_EndUser2_A__c) =&quot;Unknown&quot;),0,1)+
IF(OR(TEXT(Gate2_Will_Project_Development1_A__c) = &quot;&quot;, TEXT(Gate2_Will_Project_Development1_A__c) =&quot;Unknown&quot;),0,1)+
IF(OR(TEXT(Gate2_Will_Project_Development2_A__c) = &quot;&quot;, TEXT(Gate2_Will_Project_Development2_A__c) =&quot;Unknown&quot;),0,1)+
IF(OR(TEXT(Gate2_Will_Business_value_and_bank1_A__c) = &quot;&quot;, TEXT(Gate2_Will_Business_value_and_bank1_A__c) =&quot;Unknown&quot;),0,1)+
IF(OR(TEXT(Gate2_Will_Business_value_and_bank2_A__c) = &quot;&quot;, TEXT(Gate2_Will_Business_value_and_bank2_A__c) =&quot;Unknown&quot;),0,1)+
IF(OR(TEXT(Gate2_Will_Business_value_and_bank3_A__c) = &quot;&quot;, TEXT(Gate2_Will_Business_value_and_bank3_A__c) =&quot;Unknown&quot;),0,1)+
IF(OR(TEXT(Gate2_Fit_Strategy1_A__c) = &quot;&quot;, TEXT(Gate2_Fit_Strategy1_A__c) =&quot;Unknown&quot;),0,1)+
IF(OR(TEXT(Gate2_Fit_Strategy2_A__c) = &quot;&quot;, TEXT(Gate2_Fit_Strategy2_A__c) =&quot;Unknown&quot;),0,1)+
IF(OR(TEXT(Gate2_Fit_Commercial1_A__c) = &quot;&quot;, TEXT(Gate2_Fit_Commercial1_A__c) =&quot;Unknown&quot;),0,1)+
IF(OR(TEXT(Gate2_Fit_Commercial2_A__c) = &quot;&quot;, TEXT(Gate2_Fit_Commercial2_A__c) =&quot;Unknown&quot;),0,1)+
IF(OR(TEXT(Gate2_Fit_Commercial3_A__c) = &quot;&quot;, TEXT(Gate2_Fit_Commercial3_A__c) =&quot;Unknown&quot;),0,1)+
IF(OR(TEXT(Gate2_Fit_Commercial4_A__c) = &quot;&quot;, TEXT(Gate2_Fit_Commercial4_A__c) =&quot;Unknown&quot;),0,1)+
IF(OR(TEXT(Gate2_Fit_Resources1_A__c) = &quot;&quot;, TEXT(Gate2_Fit_Resources1_A__c) =&quot;Unknown&quot;),0,1)+
IF(OR(TEXT(Gate2_Fit_Resources2_A__c) = &quot;&quot;, TEXT(Gate2_Fit_Resources2_A__c) =&quot;Unknown&quot;),0,1)+
IF(OR(TEXT(Gate2_Fit_Resources3_A__c) = &quot;&quot;, TEXT(Gate2_Fit_Resources3_A__c) =&quot;Unknown&quot;),0,1)+
IF(OR(TEXT(Gate2_Fit_Resources4_A__c) = &quot;&quot;, TEXT(Gate2_Fit_Resources4_A__c) =&quot;Unknown&quot;),0,1)+
IF(OR(TEXT(Gate2_Fit_Resources5_A__c) = &quot;&quot;, TEXT(Gate2_Fit_Resources5_A__c) =&quot;Unknown&quot;),0,1)+
IF(OR(TEXT(Gate2_FIT_Safe_Island_A__c) = &quot;&quot;, TEXT(Gate2_FIT_Safe_Island_A__c) =&quot;Unknown&quot;),0,1)+
IF(Gate2_Fit_Safe_Island_Classification_A__c = &quot;Please fill out required in formation in Opportunity Screening sheet&quot;,0,1)+
IF(OR(TEXT(Gate2_Fit_Risk1_A__c) = &quot;&quot;, TEXT(Gate2_Fit_Risk1_A__c) =&quot;Unknown&quot;),0,1)+
IF(OR(TEXT(Gate2_Fit_Risk2_A__c) = &quot;&quot;, TEXT(Gate2_Fit_Risk2_A__c) =&quot;Unknown&quot;),0,1)+
IF(OR(TEXT(Gate2_Fit_Risk3_A__c) = &quot;&quot;, TEXT(Gate2_Fit_Risk3_A__c) =&quot;Unknown&quot;),0,1)+
IF(OR(TEXT(Gate2_Get_Customer_relation1_A__c) = &quot;&quot;, TEXT(Gate2_Get_Customer_relation1_A__c) =&quot;Unknown&quot;),0,1)+
IF(OR(TEXT(Gate2_Get_Customer_relation2_A__c) = &quot;&quot;, TEXT(Gate2_Get_Customer_relation2_A__c) =&quot;Unknown&quot;),0,1)+
IF(OR(TEXT(Gate2_Get_Competition1_A__c) = &quot;&quot;, TEXT(Gate2_Get_Competition1_A__c) =&quot;Unknown&quot;),0,1)+
IF(OR(TEXT(Gate2_Get_Competition2_A__c) = &quot;&quot;, TEXT(Gate2_Get_Competition2_A__c) =&quot;Unknown&quot;),0,1)+
IF(OR(TEXT(Gate2_Get_Competition3_A__c) = &quot;&quot;, TEXT(Gate2_Get_Competition3_A__c) =&quot;Unknown&quot;),0,1)+
IF(OR(TEXT(Gate2_Get_Competition4_A__c) = &quot;&quot;, TEXT(Gate2_Get_Competition4_A__c) =&quot;Unknown&quot;),0,1)+
IF(OR(TEXT(Gate2_Get_Competitive_edge1_A__c) = &quot;&quot;, TEXT(Gate2_Get_Competitive_edge1_A__c) =&quot;Unknown&quot;),0,1)+
IF(OR(TEXT(Gate2_Get_Competitive_edge2_A__c) = &quot;&quot;, TEXT(Gate2_Get_Competitive_edge2_A__c) =&quot;Unknown&quot;),0,1)+
IF(OR(TEXT(Gate2_Get_Competitive_edge3_A__c) = &quot;&quot;, TEXT(Gate2_Get_Competitive_edge3_A__c) =&quot;Unknown&quot;),0,1))/32</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GATE2_Completeness</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>GATE2_FIT_CategoryScore__c</fullName>
        <formula>IF(OR(Gate2_Fit_Safe_Island_Classification_A__c=&quot;Non-focus Customer&quot;,IF(TEXT(Gate2_Fit_Commercial1_A__c)=&quot;Exceeded&quot;,100,IF(TEXT(Gate2_Fit_Commercial1_A__c)=&quot;Fulfilled&quot;,100,0))=0,IF(TEXT(Gate2_Fit_Commercial2_A__c)=&quot;Exceeded&quot;,100,IF(TEXT(Gate2_Fit_Commercial2_A__c)=&quot;Fulfilled&quot;,100,0))=0,IF(TEXT(Gate2_Fit_Commercial3_A__c)=&quot;Exceeded&quot;,100,IF(TEXT(Gate2_Fit_Commercial3_A__c)=&quot;Fulfilled&quot;,100,0))=0),0,(GATE2_FIT_StrategyGS__c*(10/100) + GATE2_FIT_CommercialGroupScore__c*(30/100) + GATE2_FIT_ResourcesGroupScore__c*(10/100) + GATE2_FIT_SafeIslandGS__c*(20/100) + GATE2_FIT_RiskGroupScore__c*(30/100)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GATE2_FIT_CategoryScore</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GATE2_GET_CategoryScore__c</fullName>
        <formula>(GATE2_GET_CustomerRelationGS__c * (20/100))+(GATE2_GET_CompetitionGS__c * (60/100))+(GATE2_GET_CompetitiveEdgeGroupScore__c * (20/100))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GATE2_GET_CategoryScore</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GATE2_WILL_BusinessValueGroupScore__c</fullName>
        <formula>((IF(TEXT(Gate2_Will_Business_value_and_bank1_A__c) = &quot;Strongly agree&quot;,100,IF(TEXT(Gate2_Will_Business_value_and_bank1_A__c) =&quot;Agree&quot;,75,IF(TEXT(Gate2_Will_Business_value_and_bank1_A__c) = &quot;Neutral&quot;,50,IF(TEXT(Gate2_Will_Business_value_and_bank1_A__c) = &quot;Disagree&quot;,25,0))))*(10/100))+ 
(IF(TEXT(Gate2_Will_Business_value_and_bank2_A__c) = &quot;Strongly agree&quot;,100,IF(TEXT(Gate2_Will_Business_value_and_bank2_A__c) =&quot;Agree&quot;,75,IF(TEXT(Gate2_Will_Business_value_and_bank2_A__c) = &quot;Neutral&quot;,50,IF(TEXT(Gate2_Will_Business_value_and_bank2_A__c) = &quot;Disagree&quot;,25,0))))*(80/100))+ 
(IF(TEXT(Gate2_Will_Business_value_and_bank3_A__c) = &quot;Strongly agree&quot;,100,IF(TEXT(Gate2_Will_Business_value_and_bank3_A__c) =&quot;Agree&quot;,75,IF(TEXT(Gate2_Will_Business_value_and_bank3_A__c) = &quot;Neutral&quot;,50,IF(TEXT(Gate2_Will_Business_value_and_bank3_A__c) = &quot;Disagree&quot;,25,0))))*(10/100)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GATE2_WILL_BusinessValueGroupScore</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GATE2_WILL_CategoryScore__c</fullName>
        <formula>(((IF(TEXT(Gate2_Will_EndUser1_A__c) = &quot;Strongly agree&quot;,100,IF(TEXT(Gate2_Will_EndUser1_A__c) =&quot;Agree&quot;,75,IF(TEXT(Gate2_Will_EndUser1_A__c) = &quot;Neutral&quot;,50,IF(TEXT(Gate2_Will_EndUser1_A__c) = &quot;Disagree&quot;,25,0))))*(50/100))+ 
(IF(TEXT(Gate2_Will_EndUser2_A__c) = &quot;Strongly agree&quot;,100,IF(TEXT(Gate2_Will_EndUser2_A__c) =&quot;Agree&quot;,75,IF(TEXT(Gate2_Will_EndUser2_A__c) = &quot;Neutral&quot;,50,IF(TEXT(Gate2_Will_EndUser2_A__c) = &quot;Disagree&quot;,25,0))))*(50/100)))*(10/100))+ 
(((IF(TEXT(Gate2_Will_Project_Development1_A__c) = &quot;Strongly agree&quot;,100,IF(TEXT(Gate2_Will_Project_Development1_A__c) =&quot;Agree&quot;,75,IF(TEXT(Gate2_Will_Project_Development1_A__c) = &quot;Neutral&quot;,50,IF(TEXT(Gate2_Will_Project_Development1_A__c) = &quot;Disagree&quot;,25,0))))*(90/100))+ 
(IF(TEXT(Gate2_Will_Project_Development2_A__c) = &quot;Strongly agree&quot;,100,IF(TEXT(Gate2_Will_Project_Development2_A__c) =&quot;Agree&quot;,75,IF(TEXT(Gate2_Will_Project_Development2_A__c) = &quot;Neutral&quot;,50,IF(TEXT(Gate2_Will_Project_Development2_A__c) = &quot;Disagree&quot;,25,0))))*(10/100)))*(50/100))+
(((IF(TEXT(Gate2_Will_Business_value_and_bank1_A__c) = &quot;Strongly agree&quot;,100,IF(TEXT(Gate2_Will_Business_value_and_bank1_A__c) =&quot;Agree&quot;,75,IF(TEXT(Gate2_Will_Business_value_and_bank1_A__c) = &quot;Neutral&quot;,50,IF(TEXT(Gate2_Will_Business_value_and_bank1_A__c) = &quot;Disagree&quot;,25,0))))*(10/100))+ 
(IF(TEXT(Gate2_Will_Business_value_and_bank2_A__c) = &quot;Strongly agree&quot;,100,IF(TEXT(Gate2_Will_Business_value_and_bank2_A__c) =&quot;Agree&quot;,75,IF(TEXT(Gate2_Will_Business_value_and_bank2_A__c) = &quot;Neutral&quot;,50,IF(TEXT(Gate2_Will_Business_value_and_bank2_A__c) = &quot;Disagree&quot;,25,0))))*(80/100))+
(IF(TEXT(Gate2_Will_Business_value_and_bank3_A__c) = &quot;Strongly agree&quot;,100,IF(TEXT(Gate2_Will_Business_value_and_bank3_A__c) =&quot;Agree&quot;,75,IF(TEXT(Gate2_Will_Business_value_and_bank3_A__c) = &quot;Neutral&quot;,50,IF(TEXT(Gate2_Will_Business_value_and_bank3_A__c) = &quot;Disagree&quot;,25,0))))*(10/100)))*(40/100))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GATE2_WILL_CategoryScore</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Opportunity Screening</label>
    <nameField>
        <displayFormat>OPS-{0000000}</displayFormat>
        <label>Opportunity Screening Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Screenings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ClsOpportunityScreeningChartG2.cls
/**   
    * Controller : Gate2  
    * Release R4
    *  
    * @author  MohanRaj Kasinathan (Accenture)
    * @created  2015-09-08* @version 1.0
    *
    */ 
    public with sharing class ClsOpportunityScreeningChartG2{

    Public String gate1Per{get;set;}
    Public String gate2Per{get;set;}
    Public String willGate1{get;set;}
    Public String willGate2{get;set;}
    Public String fitGate1{get;set;}
    Public String fitGate2{get;set;}
    Public String getGate1{get;set;}
    Public String getGate2{get;set;}
    private final Opportunity_Screening__c oPSrec;
    /**   
    * Constructor : Gate2
    * Release R4
    *  
    * @author  MohanRaj Kasinathan (Accenture)
    * @created  2015-09-08* @version 1.0
    *
    */ 
    public clsOpportunityScreeningChartG2(ApexPages.StandardController controller) {
    
     this.oPSrec= (Opportunity_Screening__c)controller.getRecord();
   
  
    Opportunity_Screening__c[] oPS_G1 = [Select Id,GATE1_WILL_CategoryScore__c,GATE1_FIT_CategoryScore__c,GATE1_GET_CategoryScore__c,GATE2_WILL_CategoryScore__c,GATE2_FIT_CategoryScore__c,GATE2_GET_CategoryScore__c, GATE1_Completeness__c,GATE2_Completeness__c from Opportunity_Screening__c where Id = : OPSrec.Id LIMIT 1];
    
    gate1Per= string.valueof(Math.round(oPS_G1[0].GATE1_Completeness__c))+Label.CL00056;
    gate2Per= string.valueof(Math.round(oPS_G1[0].GATE2_Completeness__c))+Label.CL00056;
    willGate1= string.valueof(Math.round(oPS_G1[0].GATE1_WILL_CategoryScore__c));
    willGate2= string.valueof(Math.round(oPS_G1[0].GATE2_WILL_CategoryScore__c));
    fitGate1= string.valueof(Math.round(oPS_G1[0].GATE1_FIT_CategoryScore__c));
    fitGate2= string.valueof(Math.round(oPS_G1[0].GATE2_FIT_CategoryScore__c));
    getGate1= string.valueof(Math.round(oPS_G1[0].GATE1_GET_CategoryScore__c));
    getGate2= string.valueof(Math.round(oPS_G1[0].GATE2_GET_CategoryScore__c));

    }
    
    /**   
    *  Barchart : getPieData() Method
    * Release R4
    *  
    * @author  MohanRaj Kasinathan (Accenture)
    * @created  2015-09-08* @version 1.0
    *
    */   
    public List<PieWedgeData> getPieData() {
    
    try
    {
    Integer compedge = 0;
    Integer comptn = 0;
    Integer custRelatn = 0;
    Integer safeIsland = 0;
    Integer resce = 0;
    Integer commercial = 0;
    Integer strategy = 0;
    Integer business = 0;
    Integer project = 0;
    Integer endUser = 0;
    
     Opportunity_Screening__c[] oPS_G2 = [Select Id,GATE2_WILL_BusinessValueGroupScore__c,GATE2_WILL_EndUserGroupScore__c,GATE2_WILL_ProjDevelopGroupScore__c,
                                                GATE2_FIT_CommercialGroupScore__c,GATE2_FIT_ResourcesGroupScore__c,GATE2_FIT_RiskGroupScore__c,
                                                GATE2_FIT_SafeIslandGroupScore__c,GATE2_FIT_StrategyGroupScore__c,
                                                GATE2_GET_CompetitionGroupScore__c,GATE2_GET_CompetitiveEdgeGroupScore__c,GATE2_GET_CustomerRelationGroupScore__c 
                                                from Opportunity_Screening__c where Id = : OPSrec.Id  LIMIT 1];
                                                 
    
    
     
     
     if(oPS_G2 != null && oPS_G2.size() >0)
     {
        compedge = integer.valueof(oPS_G2[0].GATE2_GET_CompetitiveEdgeGroupScore__c);
        comptn = integer.valueof(oPS_G2[0].GATE2_GET_CompetitionGroupScore__c);
        custRelatn = integer.valueof(oPS_G2[0].GATE2_GET_CustomerRelationGroupScore__c);
        safeIsland = integer.valueof(oPS_G2[0].GATE2_FIT_SafeIslandGroupScore__c);
        resce = integer.valueof(oPS_G2[0].GATE2_FIT_ResourcesGroupScore__c);
        commercial = integer.valueof(oPS_G2[0].GATE2_FIT_CommercialGroupScore__c);
        strategy = integer.valueof(oPS_G2[0].GATE2_FIT_StrategyGroupScore__c);
        business = integer.valueof(oPS_G2[0].GATE2_WILL_BusinessValueGroupScore__c);
        project = integer.valueof(oPS_G2[0].GATE2_WILL_ProjDevelopGroupScore__c);
        endUser = integer.valueof(oPS_G2[0].GATE2_WILL_EndUserGroupScore__c);
     }
       
    
     List<PieWedgeData> data = new List<PieWedgeData>();
        data.add(new PieWedgeData(Label.CL00044,compedge));
        data.add(new PieWedgeData(Label.CL00045,comptn));
        data.add(new PieWedgeData(Label.CL00046,custRelatn ));   
        data.add(new PieWedgeData(Label.CL00047,safeIsland));  
        data.add(new PieWedgeData(Label.CL00048,resce));    
        data.add(new PieWedgeData(Label.CL00049,commercial));    
        data.add(new PieWedgeData(Label.CL00050,strategy));  
        data.add(new PieWedgeData(Label.CL00051,business));      
        data.add(new PieWedgeData(Label.CL00052,project));      
        data.add(new PieWedgeData(Label.CL00053,endUser));  
          
     return data;
     }
     catch(DMLException e){  return null; } 
     
    }

    /**   
    *  Barchart : PieWedgeData Wrapper Class
    * Release R4
    *  
    * @author  MohanRaj Kasinathan (Accenture)
    * @created  2015-09-08* @version 1.0
    *
    */ 
    public with sharing class PieWedgeData {
    
    public String name { get; set; }
    public Integer data { get; set; }
    public String tip{ get; set; }
    /**   
    *  Barchart : PieWedgeData Wrapper Class Constructor
    * Release R4
    *  
    * @author  MohanRaj Kasinathan (Accenture)
    * @created  2015-09-08* @version 1.0
    *
    */ 
    public PieWedgeData(String name, Integer data) {
        this.name = name;
        this.data = data;            
        this.tip = string.valueof(data)+Label.CL00056;
    }
    }


}