src/objects/Opportunity.object
<CustomObject>

 
 

	
    <fields>
        <fullName>Confidence_Level__c</fullName>
        <description>Sets the level of confidence that Expected Award Date is still achievable</description>
        <inlineHelpText>Sets the level of confidence that Expected Award Date is still achievable</inlineHelpText>
        <label>Confidence Level</label>
        <picklist>
            <picklistValues>
                <fullName>No Delay Expected</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Slight Delay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Substantial Delay Expected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
   
    <fields>
        <fullName>Industry_Usage__c</fullName>
        <description>Picklist containing the Industry Usage Values</description>
        <label>Industry Usage</label>
        <picklist>
            <picklistValues>
                <fullName>BLD.10.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BLD.10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BLD.8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BLD.9.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BLD.9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND.1.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND.1.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND.10.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND.10.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND.10.4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND.10.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND.10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND.11.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND.11.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND.11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND.12.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND.12.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND.12.3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND.12.4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND.12.7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND.12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND.13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND.14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND.15.10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND.15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND.16.1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND.16.2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND.16.3.4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IND.16.3</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sales_Pursuit_Progress__c</fullName>
        <description>Dependent picklist for Sales Pursuit Progress</description>
        <inlineHelpText>Please choose the Stage detail from picklist</inlineHelpText>
        <label>Sales Pursuit Progress</label>
        <picklist>
            <controllingField>StageName</controllingField>
            <picklistValues>
                <fullName>Opportunity Is Captured</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity Pursuit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold (Pursuit)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Budget Proposal Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFQ Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bidding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Preference To Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold (Bidding)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solution Presented To Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Budget Proposal Submitted (Bidding)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bid Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Is Neutral To Supplier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Preference To ABB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold (Negotiation)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LOI To Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Buying Preference To Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Position Is Neutral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clear Buying Signal To ABB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ABB Preferred &amp; Shows Clear Signals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LOI To ABB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSED Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSED Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSED Lost Without ABB Bid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSED Won</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Specific_Opportunity_Info__c</fullName>
        <description>Text field for additional, specific infos about the opportunity (will be added automatically to Opportunity name in the format of [Country Code]-[Account Name]-[Specific Opportunity Info].</description>
        <inlineHelpText>Text field for additional, specific infos about the opportunity (will be added automatically to Opportunity name in the format of [Country Code]-[Account Name]-[Specific Opportunity Info].</inlineHelpText>
        <label>Opportunity Name (free text)</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/RFP__c.object
<CustomObject>
    <description>R5 - Request For Proposal</description>
    <fields>
        <fullName>Rfp_A4__c</fullName>
        <description>R5 - Created as part of Req 2461</description>
        <label>Project Budgetary Or Funded ?</label>
        <picklist>
            <picklistValues>
                <fullName>Budgetary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funded</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Rfp_Account_Manager_Country__c</fullName>
        <description>R5 - Created as part of req 2461</description>
        <label>Opportunity Owner Country</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aland Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antarctica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia, Plurinational State of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia and Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Germany</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Rfp_Account_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>R5 - Created as part of req 2461</description>
        <label>Opportunity Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RFP</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rfp_Due_Date__c</fullName>
        <description>R5 - Created as part of req 2461</description>
        <label>Due Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Rfp_Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>R5 - 2461</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>RFQ</relationshipLabel>
        <relationshipName>RFP</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>RFQ</label>
    <nameField>
        <label>RFQ Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RFQ</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/RFP_Team__c.object
<CustomObject>
    <description>R5 - Custom object to capture RFP Team members</description>
    <fields>
        <fullName>RFP__c</fullName>
        <description>R5 - RFP Team</description>
        <label>RFQ</label>
        <referenceTo>RFP__c</referenceTo>
        <relationshipLabel>RFQ Team</relationshipLabel>
        <relationshipName>RFP_Team</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>RFQ Team</label>
    <nameField>
        <displayFormat>RFQTM-{0000}</displayFormat>
        <label>RFQ Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFQ Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
<fields>
        <fullName>Default_BU__c</fullName>
        <description>R4 - Default BU</description>
        <label>Default LBU</label>
        <length>100</length>
        <type>Text</type>
    </fields>
<fields>
        <fullName>Default_LSO__c</fullName>
        <description>R4 - Default LSO</description>
        <label>Default LSO</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division_DIV__c</fullName>
        <description>The field Division is added to increase the ability to identify the area the user is related to / working in.</description>
        <label>Division (DIV)</label>
        <picklist>
            <picklistValues>
                <fullName>DM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PG</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/ClsAddOpportunityTeamToRfqTeamTest.cls
/*
*  This test class used to test class ClsAddOpportunityTeamToRfqTeam. 
*
@author Aswini Arasu
@created 2016-03-18
@version 1.0  
*/
@istest(SeeAllData = False)
private class ClsAddOpportunityTeamToRfqTeamTest{
 /*  Description of the purpose of the method. 
    *  @name methodTest
*/ 
  static testMethod void  methodTest(){
  
        Account a = new Account();
        a.Name = 'Acciona, S.A';
        a.BillingStreet = 'dajie';
        a.BillingCity = 'berlin';
        a.BillingState = 'Berlin';
        a.BillingPostalCode = '20012';
        a.BillingCountry = 'Germany';
        insert a;
        
        Profile up = [Select Id, Name from Profile where profile.name = 'System Administrator' Limit 1];
        User u = new User();
        u.firstname = '2503';
        u.lastname = 'TestUser';
        u.Username ='test2503@xyzdqg.com';
        u.Alias = 'tester';
        u.CommunityNickname = 'tester1';
        u.TimeZoneSidKey ='Europe/London';
        u.LocaleSidKey ='en_US';
        u.EmailEncodingKey ='ISO-8859-1';
        u.LanguageLocaleKey ='en_US';
        u.email = 'abc@wxyz.com';
        u.profileid = up.id;
        u.isActive = true;
        u.Division_DIV__c = 'DM';
        u.Default_BU__c = 'LBUac1';
        u.Default_LSO__c ='LSOac1';
        insert u;
        
        Profile up1 = [Select Id, Name from Profile where profile.name = 'ABB Sales Standard Profile' Limit 1];
        User u1 = new User();
        u1.firstname = '2504';
        u1.lastname = 'TestUser1';
        u1.Username ='test25031@xyzuiqg.com';
        u1.Alias = 'tester1';
        u1.CommunityNickname = 'tester2';
        u1.TimeZoneSidKey ='Europe/London';
        u1.LocaleSidKey ='en_US';
        u1.EmailEncodingKey ='ISO-8859-1';
        u1.LanguageLocaleKey ='en_US';
        u1.email = 'abcd@wxyz.com';
        u1.profileid = up1.id;
        u1.isActive = true;
        u1.Division_DIV__c = 'DM';
        u1.Default_BU__c = 'LBUac1';
        u1.Default_LSO__c ='LSOac1';
        insert u1;
        
        Profile up2 = [Select Id, Name from Profile where profile.name = 'ABB Sales Standard Profile' Limit 1];
        User u2 = new User();
        u2.firstname = '2505';
        u2.lastname = 'TestUser2';
        u2.Username ='test25051@xyzuiqg.com';
        u2.Alias = 'tester2';
        u2.CommunityNickname = 'tester3';
        u2.TimeZoneSidKey ='Europe/London';
        u2.LocaleSidKey ='en_US';
        u2.EmailEncodingKey ='ISO-8859-1';
        u2.LanguageLocaleKey ='en_US';
        u2.email = 'abcd@wxyzghe.com';
        u2.profileid = up2.id;
        u2.isActive = true;
        u2.Division_DIV__c = 'DM';
        u2.Default_BU__c = 'LBUac2';
        u2.Default_LSO__c ='LSOac2';
        insert u2;
 
 
       Opportunity o = new Opportunity();
       o.AccountId = a.id;
       o.Name = 'ES-Acciona, S.A-Test';
       o.StageName = 'Prospecting';
       o.Sales_Pursuit_Progress__c = 'Opportunity Is Captured';
       o.Specific_Opportunity_Info__c ='Test';
       o.Confidence_Level__c ='No Delay Expected';
       o.CloseDate = date.today();
       o.Industry_Usage__c = 'BLD.10.1';
       insert o;
       
      OpportunityTeamMember oppTeam = new OpportunityTeamMember ();
      oppTeam.UserId=u2.id;
      oppTeam.TeamMemberRole= 'Sales Rep';
      oppTeam.OpportunityAccessLevel='Read';
      oppTeam.OpportunityId = o.id;
      insert oppTeam;
     
      System.runAs(u) {
      Test.startTest();
      RFP__c rfp = new RFP__c();
      rfp.Name = 'Test';
      rfp.Rfp_Account_Manager__c = u.id;
      rfp.Rfp_Opportunity__c = o.id;
      rfp.Rfp_Account_Manager_Country__c = 'Germany';
      rfp.Rfp_Due_Date__c = System.today();
      rfp.Rfp_A4__c = 'Budgetary';
      rfp.Rfp_Commercial_Terms__c = 'Previously Negotiated Agreement ';
      rfp.CurrencyIsoCode = 'USD';
      insert rfp;
      
      RFP_Team__c rfpTeam = new RFP_Team__c();
      rfpTeam.Access_Level__c = 'Read/Write';
      rfpTeam.User__c = u1.id;
      rfpTeam.Team_Role__c = 'Business Support';
      rfpTeam.RFP__c= rfp.id ;
      insert rfpTeam;
      
      PageReference pageRef = Page.AddOpportunityTeamToRfqTeamPage; 
      pageRef.getParameters().put('id', String.valueOf(rfp.Id));
      Test.setCurrentPage(pageRef);
    
      ApexPages.StandardController stdRfp = new ApexPages.StandardController(rfp);
      ClsAddOpportunityTeamToRfqTeam objController  =  new ClsAddOpportunityTeamToRfqTeam(stdRfp);    
      objController.updateRfqTeam();
      Test.StopTest();
    
    }
    }
    
    }