src/objects/RFP__c.object
<CustomObject>
    <description>R5 - Request For Proposal</description>
    <fields>
        <fullName>Actual_Completion_Date__c</fullName>
        <description>R5 - Created as part of req 2461</description>
        <label>Actual Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Proposal_Number__c</fullName>
        <description>R5 - Created as part of Req 2461</description>
        <label>Quotation Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>RFQ</label>
    <nameField>
        <label>RFQ Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RFQ</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Rfp_Processing__c.object
<CustomObject>
    <description>R5 - RFP Processing</description>
    <fields>
        <fullName>Rfp_Processing__c</fullName>
        <description>R5 - Created as part of req 2461</description>
        <label>RFQ</label>
        <referenceTo>RFP__c</referenceTo>
        <relationshipLabel>Processings</relationshipLabel>
        <relationshipName>Processings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rfp_Proposal_Number__c</fullName>
        <description>Proposal Number - Created as part of R5 Req 2461</description>
        <label>Quotation Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Processing</label>
    <nameField>
        <displayFormat>PRC-{YY}-{0000}</displayFormat>
        <label>Processing Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Processings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ClsTriggerProcessingHandler.cls
/*
 * TriggerClass -  To Populate Proposal Number in RFQ
 * 
 * Release R5
 * @author  Aswini Arasu
 * @created 2016-02-24
 * @version 1.0
 * Created
 */ 
public class ClsTriggerProcessingHandler extends ClsTriggerVirtual {
/**
* @see IntHelper.beforeTrigger

    public override void beforeTrigger(ClsWrappers.TriggerContext trgCtx) {
        setActualCompletionDateFromResults(trgCtx); 
    }

* @see IntHelper.afterTrigger
*/
    public override void afterTrigger(ClsWrappers.TriggerContext trgCtx){
          setProposalNumberFromProcessing(trgCtx); 
        
    }   
/*
 * Method setProposalNumberFromProcessing
 * To Populate Proposal Number in RFQ
 * 
*/    
    private void setProposalNumberFromProcessing(ClsWrappers.TriggerContext trgCtx) { 
     Map <ID, RFP__c> RfpMap = new Map<Id,RFP__c> ();
     Set<ID> RfqIds = new Set<ID>();
     List<RFP__c> updatedRFQs = new List<RFP__c>();
     Integer remLimit =  limits.getLimitQueryRows() - limits.getQueryRows();
     if (trgCtx.isAfter && (trgCtx.isInsert || trgCtx.isUpdate)) {
      for (sobject sObj : trgCtx.newList) {                    
                Rfp_Processing__c proc = (Rfp_Processing__c) sObj; 
                RfqIds.add(proc.Rfp_Processing__c);
        }
        
      RfpMap = new Map<Id,RFP__c > ([ SELECT ID, Name,Actual_Completion_Date__c
                             FROM RFP__c WHERE ID IN :RfqIds LIMIT :remLimit]); 
       
           for (sobject sObj : trgCtx.newList) {  
                Rfp_Processing__c proc = (Rfp_Processing__c) sObj;                 
                RFP__c rfp = RfpMap.get(proc.Rfp_Processing__c);
                if(rfp!=null){
                rfp.Proposal_Number__c =  proc.Rfp_Proposal_Number__c;
                }
                updatedRFQs.add(rfp);
              }
           Database.update(updatedRFQs,false);   
       }
         
     }
     
}